### ISSUE TITLE
Persistent Licenses

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2308] opened 2019-12-18 09:51 UTC
Hi,

We want to use persistent licenses for Widevine on google chrome on mac os. We dont want to download the content, we just want to store the licenses. 

shaka-player is fetching the licenses from server for each play even when the license is allowed to persist from DRM server.

My questions:
--------------
1. Can you please let me know whether shaka-player support persistent-licenses with out downloading the content (For widevine, fairplay, playready)  

2. If shaka-player doesnot support this out-of-the-box, is there any way to implement this?

**Comment by theodab** [comment] 2019-12-18 19:33
Shaka Player, played on Chrome on Mac OS supports offline licenses for Widevine content. You can check for support by calling `shaka.Player.probeSupport()`.

However, we only request persistent licenses as part of storing an asset offline. We have no plans of changing that, at this moment.

If you really want to try to implement this yourself, you could listen to the `shaka.Player.ManifestParsedEvent` event, and use that to fill in the `offlineSessionIds` value of the manifest with pre-loaded offline session Ids. You'd need to have the persistent sessions created in advance, since this is a synchronous event. The persistent sessions will need to be stored but closed beforehand (since the DRM engine will attempt to re-open them, and you can't open a session that's already open). Unfortunately, though, there's a Widevine bug that keeps you from closing and re-opening a session too rapidly, so I'm not sure how well this would work.

**Closed by theodab** 2019-12-18 19:33 UTC
Labels: enhancement, will not implement

**Comment by sridhard** [comment] 2019-12-23 14:53
Hi,

I have implemented the above method. I am setting offlineSessionIds in the manifestParsed event. I am facing the below 2 issues:
1. The offline session IDs which are set in manifestParsed event in the manifest are not used by shaka player. It is always getting new licenses even when offlineSessionIds are set
2. After getting the offline license, we need to close the session. I am trying to close the session using session.close and it is telling InvalidStateError. I am closing session once it becomes 'usable' in keystatus event

Can you please give pointer above how to solve the issues.

Thanks

**Comment by joeyparrish** [comment] 2020-01-02 17:46
Currently, Shaka Player only stores offline licenses when storing offline content.  We don't support your scenario right now, and we don't have any plans to do so in the near future.

You would definitely need to close the sessions before Shaka could re-open and use them, but there seems to be a bug in Chrome's CDM right now that prevents this from working.  There's nothing we can do about this directly, but we continue to work with the Chrome team by reporting issues and helping to reproduce them so the Chrome team can work on fixes.

We apologize for any inconvenience.
