### ISSUE TITLE
Duplicate captions appear often after seeking.

### ISSUE THREAD

**Issue by bcupac** [google/shaka-player#3755] opened 2021-11-15 15:15 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
uncompiled shaka player demo

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
MacBook Pro, Chrome 95.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

played Angel One (multi-codec, multilingual), turned on English subtitles and seeked a few times using the mouse.

**What did you expect to happen?**
regular playback with captions

**What actually happened?**

Double Captions unrelated to current audio appear.

![image](https://user-images.githubusercontent.com/7647317/141806324-816a0d99-b6e1-4189-a699-5979357938e9.png)

**Comment by avelad** [comment] 2021-11-15 16:05
Duplicate of https://github.com/google/shaka-player/issues/3742

**Comment by TheModMaker** [comment] 2021-12-06 18:57
Closing as a duplicate.

**Closed by TheModMaker** 2021-12-06 18:57 UTC
Labels: type: bug
