### ISSUE TITLE
HLS FairPlay encrypted video plays on iOS 14 + safari 14.0, but fails with error code 3016 in macOS Catalina + Safari 14.0

### ISSUE THREAD

**Issue by shashidharc27** [google/shaka-player#3073] opened 2020-12-30 15:28 UTC
Hi,

We have created a HLS FairPlay encrypted video using Shaka-packager. The video plays every time on iOS 14 + Safari 14.0, but playback fails with **error code 3016** on macOS Catalina + Safari 14.0.

**Note**: Playback of the same HLS unencrypted video is successful on  macOS Catalina + Safari 14.0.

- [Error] Error code – 3016 – "object" – {severity: 2, category: 3, code: 3016, …}
{severity: 2, category: 3, code: 3016, data: [3, undefined, undefined], handled: false, …}Object
	onError (player.html:213)
	onErrorEvent (player.html:208)
	(anonymous function) (shaka-player.compiled.debug.js:227:387)
	(anonymous function) (shaka-player.compiled.debug.js:912:250)
	(anonymous function) (shaka-player.compiled.debug.js:914:100)
	(anonymous function) (shaka-player.compiled.debug.js:785:331)

### Link to manifest
[https://github.com/shashidharc27/shaka-player/blob/master/hls.m3u8](url)
[https://github.com/shashidharc27/shaka-player/blob/master/stream_0.m3u8](url)
[https://github.com/shashidharc27/shaka-player/blob/master/stream_1.m3u8](url)

### Log from macOS Catalina + Safari 14.0:
[Log] skdUri is:  – "skd://ZjNjNWUwMzYxZTY2NTRiMjhmODA0OWM3NzhiMjM5NDY=" (player.html, line 169)
[Log] keyid  is: – "ZjNjNWUwMzYxZTY2NTRiMjhmODA0OWM3NzhiMjM5NDY=" (player.html, line 171)
[Log] new keyid:  – "ZjNjNWUwMzYxZTY2NTRiMjhmODA0OWM3NzhiMjM5NDY=" (player.html, line 173)
[Log] Unable to find byte-order-mark, making an educated guess. (shaka-player.compiled.debug.js, line 193)
[Log] PatchedMediaKeysApple.MediaKeySession.generateRequest (shaka-player.compiled.debug.js, line 1613)
[Log] Ignoring duplicate init data. (shaka-player.compiled.debug.js, line 281)
[Log] PatchedMediaKeysApple.onWebkitKeyMessage_ – WebKitMediaKeyMessageEvent {isTrusted: true, message: Uint8Array, destinationURL: "", …} (shaka-player.compiled.debug.js, line 1617)
WebKitMediaKeyMessageEvent {isTrusted: true, message: Uint8Array, destinationURL: "", type: "webkitkeymessage", target: WebKitMediaKeySession, …}WebKitMediaKeyMessageEvent
[Log] cookie val: sduser (player.html, line 133)
[Log] PatchedMediaKeysApple.MediaKeySession.update (shaka-player.compiled.debug.js, line 1615)
[Log] PatchedMediaKeysApple.onWebkitKeyAdded_ – Event {isTrusted: true, type: "webkitkeyadded", target: WebKitMediaKeySession, …} (shaka-player.compiled.debug.js, line 1618)
Event {isTrusted: true, type: "webkitkeyadded", target: WebKitMediaKeySession, currentTarget: WebKitMediaKeySession, eventPhase: 2, …}Event
[Log] DRM Event. getDrmInfo... (player.html, line 196)
[Log] {keySystem: "com.apple.fps.1_0", licenseServerUri: "https://samplelsp:8080/LicenseServerProxy/fps", distinctiveIdentifierRequired: false, persistentStateRequired: false, audioRobustness: "", …} (player.html, line 197)
[Log] session Ids... (player.html, line 198)
[Log] ["135c307b-55dc-4d5c-a4b2-79c813c769e9"] (1) (player.html, line 199)
[Error] Error code – 3016 – "object" – {severity: 2, category: 3, code: 3016, …}
{severity: 2, category: 3, code: 3016, data: [3, undefined, undefined], handled: false, …}Object
	onError (player.html:213)
	onErrorEvent (player.html:208)
	(anonymous function) (shaka-player.compiled.debug.js:227:387)
	(anonymous function) (shaka-player.compiled.debug.js:912:250)
	(anonymous function) (shaka-player.compiled.debug.js:914:100)
	(anonymous function) (shaka-player.compiled.debug.js:785:331)

### Log from iOS 14 + Safari 14.0
[Log] skdUri is:  – "skd://ZjNjNWUwMzYxZTY2NTRiMjhmODA0OWM3NzhiMjM5NDY=" (player.html, line 169)
[Log] keyid  is: – "ZjNjNWUwMzYxZTY2NTRiMjhmODA0OWM3NzhiMjM5NDY=" (player.html, line 171)
[Log] new keyid:  – "ZjNjNWUwMzYxZTY2NTRiMjhmODA0OWM3NzhiMjM5NDY=" (player.html, line 173)
[Log] Unable to find byte-order-mark, making an educated guess. (shaka-player.compiled.debug.js, line 193)
[Log] PatchedMediaKeysApple.MediaKeySession.generateRequest (shaka-player.compiled.debug.js, line 1613)
[Log] Ignoring duplicate init data. (shaka-player.compiled.debug.js, line 281)
[Log] PatchedMediaKeysApple.onWebkitKeyMessage_ – WebKitMediaKeyMessageEvent {isTrusted: true, message: Uint8Array, destinationURL: "", …} (shaka-player.compiled.debug.js, line 1617)
WebKitMediaKeyMessageEvent {isTrusted: true, message: Uint8Array, destinationURL: "", type: "webkitkeymessage", target: WebKitMediaKeySession, …}WebKitMediaKeyMessageEvent
[Log] cookie val: sduser (player.html, line 133)
[Log] PatchedMediaKeysApple.MediaKeySession.update (shaka-player.compiled.debug.js, line 1615)
[Log] PatchedMediaKeysApple.onWebkitKeyAdded_ – Event {isTrusted: true, type: "webkitkeyadded", target: WebKitMediaKeySession, …} (shaka-player.compiled.debug.js, line 1618)
Event {isTrusted: true, type: "webkitkeyadded", target: WebKitMediaKeySession, currentTarget: WebKitMediaKeySession, eventPhase: 2, …}Event
[Log] DRM Event. getDrmInfo... (player.html, line 196)
[Log] {keySystem: "com.apple.fps.1_0", licenseServerUri: "https://samplelsp:8080/LicenseServerProxy/fps", distinctiveIdentifierRequired: false, persistentStateRequired: false, audioRobustness: "", …} (player.html, line 197)
[Log] session Ids... (player.html, line 198)
[Log] ["b073774a-b0a6-4043-bb03-fe2df866e688"] (1) (player.html, line 199)

### For full player logs, Please refer the link below,
[https://github.com/shashidharc27/shaka-player/blob/master/mac_safari.log](url)
[https://github.com/shashidharc27/shaka-player/blob/master/ios_safri.log](url)

What can be the issue? Please let us know.

Thanks

**Comment by avelad** [comment] 2021-01-19 19:58
I see you are using MP4 with Fairplay. As far as I know, you need this to be implemented to work properly: https://github.com/google/shaka-player/issues/2999

**Comment by joeyparrish** [comment] 2021-01-19 22:27
I'm running tests on PR #3021 right now, which should fix this.  In the meantime, I'm closing this as a duplicate of #2999, which will be solved by that PR.  Thanks, @avelad, for your reply!

**Closed** 2021-01-19 22:27 UTC
Labels: duplicate
