### ISSUE TITLE
Player changing frames when paused at extreme negative point of live stream

### ISSUE THREAD

**Issue by sandeep-mirpuri** [google/shaka-player#1034] opened 2017-09-27 04:13 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
V 2.2.1

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
Yes

**Are you using the demo app or your own custom app**:
Tried on both

**If custom app, can you reproduce the issue using our demo app**:
Yes

**What browser and OS are you using**:
Chrome 61 on Mac OS Sierra

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
Cannot share due to Content Protection Policies

**What did you do?**
I am using Shaka to play a live stream. The stream allows me to play around 30mins of previous content. I scrubbed to the -30:00 point and paused the player.

**What did you expect to happen?**
I expected the player to remain paused in a frozen state

**What actually happened?**
As the time elapsed and the content that I paused on was no longer available, rather than remaining frozen on the paused frame, the player fetches the next segments and displays the paused frame at the new -30:00 point. So basically the frames keep changing rather than remaining properly paused. I have attached a screen recording of the same issue on the Shaka demo. Hopefully it will clarify the issue I am having.

[shaka-live-pause-sample.zip](https://github.com/google/shaka-player/files/1335756/shaka-live-pause-sample.zip)

**Comment by TheModMaker** [comment] 2017-09-27 16:35
Duplicate of #982.

**Closed by TheModMaker** 2017-09-27 16:35 UTC
