### ISSUE TITLE
HLS subtitles

### ISSUE THREAD

**Issue by tdrews** [google/shaka-player#146] opened 2015-08-04 21:03 UTC
M3U based subtitles (see #133 for some context) use multiple files for a single subtitles track. `addExternalCaptions()` could be extended to handle these types of subtitles. Work required for this feature may overlap with work required to implement TTML support (#111).

**Comment by joeyparrish** [comment] 2015-08-14 23:48
Unfortunately, we don't have the bandwidth right now to add this.  It basically amounts to subtitle manifest outside of the main content's manifest, and it doesn't fit into our current architecture.

It is trivial to add vtt subtitles to a DASH manifest, and if you can't modify the manifest, you can always use addExternalCaptions() in the mean time.

**Comment by joeyparrish** [comment] 2016-10-04 18:39
Closing as a duplicate of #279, which is more general and covers all HLS support.

**Closed by joeyparrish** 2016-10-04 18:39 UTC
Labels: duplicate, enhancement
