### ISSUE TITLE
Limit video-resolution to current container-size

### ISSUE THREAD

**Issue by Wuschba** [google/shaka-player#2770] opened 2020-08-05 14:49 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.0.2

**Please ask your question**
I have a video rendered in different resolutions (1200x900, 800x600, 400x300, 200x150) and a DASH-manifest. I'm embedding the video on a responsive webpage using the shaka-player. This works so far, but the video displayed is depending more on the bandwidth than the size of the container which is playing in, for example:

Container size: 800x600, low bandwidth -> Playing the video 200x150 -> Ok
Container size: 1200x900, high bandwidth -> Playing the video 1200x900 -> Ok
Container size: 200x150, high bandwidth -> Playing the video 1200x900 -> Not ok, because it's not necessary

I want to prevent the last case because it increases my traffic and on some devices/browsers/setups the downscaling of the video is really horrible (because of the device/browser/setup, not because of shaka).

How can I limit the size of the played video to the size of the container the video-player is in?

**Comment by TheModMaker** [comment] 2020-08-05 16:55
Duplicate of #2333.  For now you can use `abr.restrictions.maxWidth` and `abr.restrictions.maxHeight` configurations to limit the ABR sizes chosen.

**Closed** 2020-08-14 21:28 UTC
Labels: duplicate
