### ISSUE TITLE
is there any required dependency is missing ?

### ISSUE THREAD

**Issue by ayaanmondal** [google/shaka-player#3221] opened 2021-03-14 20:10 UTC
Notebook-PC:~/Desktop/shaka-player$ python3 build/all.py
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Generating Closure dependencies...
[INFO] Linting JavaScript...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Linting CSS...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Linting HTML...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Checking that the build files are complete...
[INFO] Checking for common misspellings...
[INFO] Checking correct usage of eslint-disable...
[INFO] Checking the tests for type errors...
[WARNING] No changes detected, skipping. Use --force to override.
[ERROR] *** A required dependency is missing: java

{Getting this error OS: Ubuntu 20.04}

**Comment by nbcl** [comment] 2021-03-14 20:33
**Hello @ayaanmondal!**

It appears that your machine is missing Java! 

> [ERROR] *** A required dependency is missing: java

The [Shaka Player website](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) indicates you need Java Runtime Environment v8+ to compile the library.

It also indicates that you can can install it manually, or you can find a shell script on [build/install-linux-prereqs.sh](https://github.com/google/shaka-player/blob/master/build/install-linux-prereqs.sh) that should install all the prerequisites for Ubuntu.

> To quickly install these prerequisites on Ubuntu or Debian, you can run this script:
> ```shell 
> curl https://raw.githubusercontent.com/google/shaka-player/master/build/install-linux-prereqs.sh | bash 

If you decide to use the script, please let us know if it works on Ubuntu 20.04 so it can be added to the tested list!

**Comment by ayaanmondal** [comment] 2021-03-14 20:58
I install it with a different command.
How to run this project locally ? please help.

**Comment by nbcl** [comment] 2021-03-14 21:18
> I install it with a different command.

Great, I'm glad you could install it!

> How to run this project locally ? please help.

If you now have all the dependencies installed, you should be able to run  `python build/all.py` again to compile the library.

Once the library is compiled, I would recommend that you continue the official tutorial by creating the HTML page that is described in the [Basic Usage](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) section of the website!

Let me know if it works!

**Comment by Ankitsinghchadda** [comment] 2021-03-15 12:49
`
PS C:\Project\shaka_player> python build/all.py
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Generating Closure dependencies...
[INFO] Linting JavaScript...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Linting CSS...
Error: No files matching the pattern "C:\Project\shaka_player\demo\cast_receiver\receiver_app.css, C:\Project\shaka_player\demo\demo.less, C:\Project\shaka_player\ui\controls.less, C:\Project\shaka_player\ui\less\ad_controls.less, C:\Project\shaka_player\ui\less\buttons.less, C:\Project\shaka_player\ui\less\containers.less, C:\Project\shaka_player\ui\less\general.less, C:\Project\shaka_player\ui\less\other_elements.less, C:\Project\shaka_player\ui\less\overflow_menu.less, C:\Project\shaka_player\ui\less\range_elements.less, C:\Project\shaka_player\ui\less\spinner.less" were found.
    at C:\Project\shaka_player\node_modules\stylelint\lib\standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`
I am getting this error can you help me with this

**Comment by Ankitsinghchadda** [comment] 2021-03-15 12:50
@nbcl  which python interpreter do we have to associate with the virtual environment?

**Comment by Ankitsinghchadda** [comment] 2021-03-15 13:00
@nbcl

**Comment by nbcl** [comment] 2021-03-15 14:44
Hello @Ankitsinghchadda!

> I am getting this error can you help me with this

Your output appears to be similar to the one described in #2985:

```
[INFO] Linting CSS...
Error: No files matching the pattern "C:\Users<USER>\PycharmProjects\shaka-player\demo\cast_receiver\receiver_app.css, C:\Users<USER>\PycharmProjects\shaka-player\demo\demo.less, C:\Users<USER>\PycharmProjects\shaka-player
ui\controls.less, C:\Users<USER>\PycharmProjects\shaka-player\ui\less\buttons.less, C:\Users<USER>\PycharmProjects\shaka-player\ui\less\containers.less, C:\Users<USER>\PycharmProjects\shaka-player\ui\less\general.less, C:\U
sers<USER>\PycharmProjects\shaka-player\ui\less\other_elements.less, C:\Users<USER>\PycharmProjects\shaka-player\ui\less\overflow_menu.less, C:\Users<USER>\PycharmProjects\shaka-player\ui\less\range_elements.less, C:\Users
\PycharmProjects\shaka-player\ui\less\spinner.less" were found.
at C:\Users<USER>\PycharmProjects\shaka-player\node_modules\stylelint\lib\standalone.js:212:12
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This appears to be happening due to the use of `\` instead of `/` in Windows.

I would advice that you follow #3214, which is an an open pull request that tackles that issue! 

Let me know if that helps!

**Comment by ayaanmondal** [comment] 2021-03-15 15:53
@nbcl 
where should I create the myapp.js file ???

**Comment by joeyparrish** [comment] 2021-03-15 16:05
Anywhere you like that is accessible to your local web server.  For example, the root of shaka-player is a typical location.  But if you know how web servers work, you can put it wherever you want and configure your server accordingly.

**Comment by ayaanmondal** [comment] 2021-03-15 17:01
I am using python3 is there will be any error for that ?

**Comment by ayaanmondal** [comment] 2021-03-15 17:06
![Screenshot from 2021-03-15 22-33-20](https://user-images.githubusercontent.com/46599244/111192003-a147c000-85de-11eb-8fac-d76356325eb4.png)
Getting this after running python3 build/all.py

**Comment by Ankitsinghchadda** [comment] 2021-03-15 18:29
> Thank You @nbcl  for helping

**Comment by surajkumar-sk** [comment] 2021-03-15 19:10
@Ankitsinghchadda the solution for your problem will be merged to master branch with few hours . So just wait and update your repository for avoiding any conflicts in future .

**Comment by surajkumar-sk** [comment] 2021-03-15 19:17
@ayaanmondal when you run python ./build/test.py -browser chrome command , karma Jasmine will be launched running tests for checking if everything is working on a browser . That screenshot describes karma running tests on chrome . And as for all of your other questions @nbcl has already instructed you to read the docs . For beginning create the app.js file inside the shaka-player folder where all the files of shaka player are located .

**Comment by joeyparrish** [comment] 2021-03-16 00:59
@ayaanmondal, python 2 and 3 are both supported, but some issues that specifically affected the build on Windows have just been addressed.  Thank you, @surajkumar-sk, for the most recent fix!

@ayaanmondal, if you have any other issues getting started, please let us know, and we will be happy to help you.  Thanks for your interest in Shaka Player!

**Comment by sradhanjan** [comment] 2021-03-20 06:50
I am getting the following error when I try to compile the latest master code 

![image](https://user-images.githubusercontent.com/56840012/111861708-58915d80-8976-11eb-8162-ce50cb13d3b1.png)

(I have all the prerequisites required to run the program)

![image](https://user-images.githubusercontent.com/56840012/111861697-457e8d80-8976-11eb-8b6d-8d5b548c6076.png)

**Comment by surajkumar-sk** [comment] 2021-03-20 10:17
@sradhanjan did the previous versions of shaka-player work, or is this the first time you are running python build/all.py

**Comment by sradhanjan** [comment] 2021-03-20 10:31
@surajkumar-sk I had successfully compiled the 2.5.20 version of shaka-player, today I cloned the latest master code and encountered this issue

**Comment by surajkumar-sk** [comment] 2021-03-20 10:49
@sradhanjan  I am unable to reproduce the error on my machine (Windows 8.1 X64) which means the code is working fine. there's something wrong with your computer. which terminal are you using to run the command?

**Comment by surajkumar-sk** [comment] 2021-03-20 10:52
Is it windows default cmd or some other terminal software like hyper

**Comment by sradhanjan** [comment] 2021-03-20 11:07
@surajkumar-sk I am using git bash to compile the code, and windows cmd to check whether missing dependency is working or not

**Comment by sradhanjan** [comment] 2021-03-20 11:10
@surajkumar-sk I am using git bash to compile the code, and windows cmd to check whether missing dependency is working or not. Even in git bash node is working

![image](https://user-images.githubusercontent.com/56840012/111867574-eb43f380-899a-11eb-96d0-2739387974de.png)

**Comment by surajkumar-sk** [comment] 2021-03-20 11:10
@sradhanjan  check dependency on git bash or run that command in windows default cmd. In windows, it's kind of hard to tell what causes problems. so do both and send the results.

**Comment by surajkumar-sk** [comment] 2021-03-20 11:39
@surajkumar-sk run the command on windows cmd. After that, we could diagnose the problem

**Comment by sradhanjan** [comment] 2021-03-20 11:44
@surajkumar-sk 
Using git bash
![image](https://user-images.githubusercontent.com/56840012/111868361-8939bd00-899f-11eb-80f7-9f9ea9c112e7.png)

Using windows cmd
![image](https://user-images.githubusercontent.com/56840012/111868378-99ea3300-899f-11eb-929d-f1788cd4e664.png)

**Comment by surajkumar-sk** [comment] 2021-03-20 14:01
@sradhanjan I am unable to reproduce the error. tried removing node and npm from PATH in environmental variables. Installed that version of the node but still nothing. could you try re-installing node? working `node -v` does indicate node is installed and working but still trying re-installing that. If that doesn't work we will tag the members of shaka-player for help.

**Comment by sradhanjan** [comment] 2021-03-20 15:05
@surajkumar-sk now it's working fine, two versions of shaka-player were stored in same file. I deleted the previous one and now the latest code compiled successfully. Thankyou for the guidance

**Comment by surajkumar-sk** [comment] 2021-03-20 15:10
@sradhanjan 👍🙂

**Closed** 2021-03-21 04:34 UTC
Labels: gsoc, question
