### ISSUE TITLE
Unrecognised () option in captions & audio controls. 

### ISSUE THREAD

**Issue by anamdev** [google/shaka-player#2540] opened 2020-04-29 19:16 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari / macOS catalina

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8;panel=ALL%20CONTENT;panelData=HLS;build=uncompiled

**What did you do?**
1. On Safari browser, Select "Big Buck Bunny: the Dark Truths of a Video Dev Cartoon (HLS)" under All content. 
2. Click on the controls menu. You could observe **Unrecognised ()**; text under Captions. 
3. I passed few subtitles in my custom code and still can see **Unrecognised ()**;  under captions. 

**What did you expect to happen?**
**Unrecognised ()**;  should not be shown. 

**What actually happened?**
On safari browser, Under Captions/Audio track, I could see **Unrecognised ()**;  which should not be there. 
<img width="665" alt="Screen Shot 2020-04-30 at 12 36 55 AM" src="https://user-images.githubusercontent.com/7699219/80636913-cfcab400-8a7b-11ea-97f5-d3eead9f9f61.png">

**Comment by avelad** [comment] 2020-04-29 19:19
I think it is the same error as https://github.com/google/shaka-player/issues/2516

**Comment by joeyparrish** [comment] 2020-04-29 21:42
Yes, this appears to be a duplicate of #2516.  We're working on a fix already, so please subscribe to that issue to receive updates.  Thanks!

**Closed by joeyparrish** 2020-04-29 21:42 UTC
Labels: needs triage

**Comment by anamdev** [comment] 2020-04-30 04:50
Thanks, @joeyparrish @avelad
