### ISSUE TITLE
Bad display of WebVTT subtitles if cue starts with '<c.gray>&gt;&gt; '

### ISSUE THREAD

**Issue by phelou** [google/shaka-player#2004] opened 2019-06-21 10:35 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.2

**Can you reproduce the issue with our latest release version?**
Issue found with demo app (https://shaka-player-demo.appspot.com/demo) 
No problem if using local html with 
<script src="https://ajax.googleapis.com/ajax/libs/shaka-player/2.5.2/shaka-player.compiled.js"></script>

**Can you reproduce the issue with the latest code from `master`?**
![shaka_captions](https://user-images.githubusercontent.com/34345198/59917677-d8e20200-9422-11e9-8ad7-00f0f67f0a6e.png)

**Are you using the demo app or your own custom app?**

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Firefox Quantum

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Issue with such WebVTT files:
WEBVTT

00:00:00.000 --> 00:00:00.466 align:left line:11% position:10%,line-left
<c.gray>&gt;&gt; HE WAS SUPPOSED TO BE FAMOUS.</c>
<c.gray>I</c>

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by ismena** [comment] 2019-06-21 17:52
Hey @phelou thanks for the report. Could you send us the manifest you're using, so we can repro?
Feel free to send privately to shaka-player-issues@google.com if you can't share publicly.

**Comment by phelou** [comment] 2019-06-25 09:38
Hello,
Here is the manifest to reproduce the issue.
Thanks a lot !
[DASH_ESPN_static.zip](https://github.com/google/shaka-player/files/3324580/DASH_ESPN_static.zip)

**Comment by TheModMaker** [comment] 2019-06-25 21:24
Which of the images you posted is the expected?  Is the problem that the positioning is incorrect?  Is the positioning correct if there aren't any stylings?

We don't support the WebVTT stylings (e.g. `<c.gray>`).  We just pass the WebVTT text to the browser.  So different browsers may support different features with regard to the stylings.  Some browsers may ignore it and some may parse it and handle it.

**Comment by ismena** [comment] 2019-06-25 21:27
If the problem is the lack of style support, we can take this on as an enhancement for the custom text displayer.

**Comment by phelou** [comment] 2019-06-26 07:41
I understand that some browsers interpret style and others do not. What is surprising to me is that with the same browser (Mozilla) and same content, the display differs, depending on how I use shaka-player:
1: If I use a local html test page (see code below) display is correct.
2: I I use https://shaka-player-demo.appspot.com/demo URL, display shows the uninterpreted styles.
![issue2004](https://user-images.githubusercontent.com/34345198/60160749-4eb8e580-97f6-11e9-9189-71d34efbe487.png)

My html test file:
<!DOCTYPE html>
<html>
  <head>
    
    <script src="https://ajax.googleapis.com/ajax/libs/shaka-player/2.5.2/shaka-player.compiled.js"></script>
    
    <script src="myapp.js"></script>
  </head>
  <body>
    <video id="video"
           width="720"
           controls autoplay></video>
  </body>
</html>

**Comment by phelou** [comment] 2019-06-26 07:42
And here is myapp.js:
// myapp.js

var manifestUri = 'http://198.18.8.107/DASH_ESPN_static/DASH_manifest.mpd';

function initApp() {
  // Install built-in polyfills to patch browser incompatibilities.
  shaka.polyfill.installAll();

  // Check to see if the browser supports the basic APIs Shaka needs.
  if (shaka.Player.isBrowserSupported()) {
    // Everything looks good!
    initPlayer();
  } else {
    // This browser does not have the minimum set of APIs we need.
    console.error('Browser not supported!');
  }
}

function initPlayer() {
  // Create a Player instance.
  var video = document.getElementById('video');
  var player = new shaka.Player(video);

player.usingEmbeddedTextTrack();
player.setTextTrackVisibility(true);

  // Attach player to the window to make it easy to access in the JS console.
  window.player = player;

  // Listen for error events.
  player.addEventListener('error', onErrorEvent);

  // Try to load a manifest.
  // This is an asynchronous process.
  player.load(manifestUri).then(function() {
    // This runs if the asynchronous load is successful.
    console.log('The video has now been loaded!');
  }).catch(onError);  // onError is executed if the asynchronous load fails.
}

function onErrorEvent(event) {
  // Extract the shaka.util.Error object from the event.
  onError(event.detail);
}

function onError(error) {
  // Log the error.
  console.error('Error code', error.code, 'object', error);
}

document.addEventListener('DOMContentLoaded', initApp);

**Comment by joeyparrish** [comment] 2019-06-26 14:27
The difference in rendering is because your test page uses a different rendering mechanism than the demo.

The demo app uses the full UI library (shaka-player.ui.js), which does its own rendering of cues by default.  Your test page is using the non-UI library (shaka-player.compiled.js), which feeds parsed cues to the browser to render by default.  Both of these defaults can be changed.

Not all browsers support cue styles, so our UI library's rendering is meant to be a consistent alternative.  In this case Firefox supports something ours doesn't yet.

We'll schedule this as an enhancement for the renderer.  Thanks!

**Comment by phelou** [comment] 2019-06-26 14:43
Hi @joeyparrish , thanks for your answer. I am curious, could you tell me how to update my test page to use the full UI library, for subtitle rendering ? Thanks.

**Comment by TheModMaker** [comment] 2019-06-26 15:40
`shaka-player.compiled.js` is the non-UI build, `shaka-player.ui.js` is the same library with the UI built in.  The UI was only added in v2.5.

We also host old versions of the demo on appspot.  For example:  <https://v2-4-0-dot-shaka-player-demo.appspot.com>.  You can go to <https://index-dot-shaka-player-demo.appspot.com/> to see the list of all the old versions.

**Comment by avelad** [comment] 2021-03-15 09:59
Resolved with: https://github.com/google/shaka-player/commit/d882d282f9b90f101c7071ba884859abf76b08a8 (https://github.com/google/shaka-player/issues/3182)

**Closed** 2021-03-15 15:57 UTC
Labels: enhancement
