### ISSUE TITLE
Respect AdaptationSet @selectionPriority

### ISSUE THREAD

**Issue by thenewguy** [google/shaka-player#2740] opened 2020-07-19 17:37 UTC
There is a related issue https://github.com/google/shaka-player/issues/1877

However, this issue is different because the previous issue is actually a report around invalid syntax.

AdaptationSet @selectionPriority should be respected so that track choices can be influenced by the content creator who has additional knowledge of the content and stream choices.  For example, content creator may have codec preferences.  It is not always a simple choice of highest or lowest bandwidth.

**Comment by TheModMaker** [comment] 2020-07-20 17:45
This is a duplicate of #1877.  Even though that involved a syntax error, that issue is tracking our implementation of `@selectionPriority`.  If it was just a syntax error, we'd label it `bad content` and close the issue.

**Closed by TheModMaker** 2020-07-20 17:45 UTC
Labels: needs triage
