### ISSUE TITLE
Clearkey demo assets do not work in Firefox

### ISSUE THREAD

**Issue by dannyfinks** [google/shaka-player#877] opened 2017-06-13 17:48 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: v2.1.3-debug and v2.1.1

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: Have not attempted to

**Are you using the demo app or your own custom app**: Demo and JW Player on v2.1.1

**If custom app, can you reproduce the issue using our demo app**: Yes

**What browser and OS are you using**: macOS 10.12 - Firefox 53

**What are the manifest and license server URIs**:
https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one-clearkey/dash.mpd;lang=en-US

https://shaka-player-demo.appspot.com/demo/#asset=//yt-dash-mse-test.commondatastorage.googleapis.com/media/car_cenc-20120827-manifest.mpd;lang=en-US

**What did you do?** Load the demo app with the clearkey video asset

**What did you expect to happen?** Playback to begin

**What actually happened?** 
- Car Clearkey example did not load and gave error - Shaka Error MANIFEST.UNPLAYABLE_PERIOD () 
- Angel One example did not load

**Comment by cpeterso** [comment] 2017-06-14 02:06
The Angel One asset plays correctly for me in Firefox 53 on macOS 10.12 and Windows 10, but I can reproduce the "Shaka Error MANIFEST.UNPLAYABLE_PERIOD ()" error with the Car ClearKey asset.

**Comment by joeyparrish** [comment] 2017-06-15 16:41
The issue with "Car ClearKey" appears to be a bug in the content's manifest.  They use "mp4a.40.02" instead of "mp4a.40.2".  Chrome accepts both, but Firefox only accepts the latter.

```js
console.log('40.02', MediaSource.isTypeSupported('audio/mp4; codecs="mp4a.40.02"'));
console.log('40.2', MediaSource.isTypeSupported('audio/mp4; codecs="mp4a.40.2"'));
```

With "Angel One ... ClearKey server", I get different results from either of you.  For me, the content loads, then starts showing decode errors at 11 seconds:

https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one-clearkey/dash.mpd;lang=en-US;noadaptation;play

That same link fails for me in Chrome, too.

The Widevine version of the same works in Chrome, but fails in Firefox:

https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd;lang=en-US;noadaptation;play

@cpeterso, in Chrome, I am accustomed to using chrome:media-internals to look at what the media stack is doing and see more detailed errors.  What is the equivalent in Firefox?  If I ever knew, I must have forgotten.

**Comment by cpeterso** [comment] 2017-06-15 17:26
> The issue with "Car ClearKey" appears to be a bug in the content's manifest. They use "mp4a.40.02" instead of "mp4a.40.2". Chrome accepts both, but Firefox only accepts the latter.

Thanks. I filed [Firefox bug 1373314](https://bugzilla.mozilla.org/show_bug.cgi?id=1373314) for this issue.

> With "Angel One ... ClearKey server", I get different results from either of you. For me, the content loads, then starts showing decode errors at 11 seconds:

What OS and Firefox version are you testing?

> The Widevine version of the same works in Chrome, but fails in Firefox:

I was able to reproduce this error in Firefox 53, but not in Firefox 54 released this week.

> chrome:media-internals

You can install the [about:media Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/about-media/).

**Comment by joeyparrish** [comment] 2017-06-15 18:45
I'm running Firefox 54 on Ubuntu Linux.

**Comment by joeyparrish** [comment] 2017-06-15 18:51
Although I didn't check this morning what version I was.  After opening Firefox again, I'm definitely running 54 this time, and the error on the "Clear Key server" asset is gone.  Perhaps I got upgraded from 53 to 54 in the last 2 hours.

No issue with the Widevine version now, either.

This means the only remaining issue seems to be that the YouTube "Car" video doesn't play due to the codecs string being set to "mp4a.40.02":

https://shaka-player-demo.appspot.com/demo/#asset=//yt-dash-mse-test.commondatastorage.googleapis.com/media/car_cenc-20120827-manifest.mpd;lang=en-US;play

@cpeterso, since you've filed [Firefox bug 1373314](https://bugzilla.mozilla.org/show_bug.cgi?id=1373314), I'm going to mark this as "external bug" and follow along there.

Also, thanks for the tip on about:media.  It looks very useful, and I've installed it for next time I run into a decoder error.

@dannyfinks, does this help?

**Comment by dannyfinks** [comment] 2017-06-16 21:26
@joeyparrish that definitely helps. Thank you and @cpeterso for the quick follow up.

**Comment by cpeterso** [comment] 2017-07-21 16:55
This bug is fixed in Firefox 56.

**Comment by joeyparrish** [comment] 2017-07-21 17:18
Thanks!  Note that Firefox 56 is [currently scheduled](https://wiki.mozilla.org/RapidRelease/Calendar) for beta on 2017-08-08, and for stable release on 2017-09-26.

**Comment by joeyparrish** [comment] 2017-10-07 19:15
Firefox 56 is stable.  Closing.  Thanks all!

**Closed by joeyparrish** 2017-10-07 19:15 UTC
Labels: external
