### ISSUE TITLE
IE11: error 6006 (FAILED TO GENERATE LICENSE REQUEST) when playing video with separate video and audio keys

### ISSUE THREAD

**Issue by gigon** [google/shaka-player#1689] opened 2018-11-20 12:06 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: yes
**What version of Shaka Player are you using?**: v2.4.5

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: yes

**Are you using the demo app or your own custom app?**: both

**If custom app, can you reproduce the issue using our demo app?**: yes

**What browser and OS are you using?**: IE11 (11.1387) on Windows 10 (1703)

**What are the manifest and license server URIs?**: Will send by email

**What did you do?** 
Play my DASH video with separate keys for video and audio on your Demo app, on IE11.   
Notice in order to play the video you have to turn off CORS restriction in IE Security Settings
(Internet Options - Security - Custom Level- Misc. - Access Data Sources across domains (Enable this.)

**What did you expect to happen?** Play without issues

**What actually happened?**    
The video plays ok (with audio), **but after 10-15 seconds** I get Shaka error 6006 
(FAILED_TO_GENERATE_LICENSE_REQUEST), and this repeats every 10-15 seconds.   

- The same video plays without issues on Edge browser.
- The same video plays without issues on IE11 with DASHJS player.
- A similar video with a single playready key for video and audio plays well on IE11.

--

**Comment by TheModMaker** [comment] 2018-11-27 21:33
This is usually caused by the platform rejecting the content, and there is often nothing we can do about it.  I can't reproduce this on our Windows machine.  I get a different error and the video doesn't play at all.  Could you try with verbose logging and post those logs?  Did you try with the [nightly site](https://nightly-dot-shaka-player-demo.appspot.com/)?  Can you also look at the error object to get extended error codes, I think it will be in `error.data[0].errorCode`.  You could also look at `lib/polyfill/patchedmediakeys_ms.js` and look at the `onMsKeyError_` function to see if there is any more info in the native error object.

**Comment by gigon** [comment] 2018-11-28 06:49
Sorry but someone modified the license proxy after I posted the bug (as it
was many days ago...).

I am sending now the correct urls to shaka-player-issues@google.com.

With these urls I can reproduce it also on the nightly build.
Notice: it does play! you have to let it play for 5-10 seconds until you
see the shaka error message on top of the playing video.

**Comment by joeyparrish** [comment] 2018-11-28 21:51
I found a reference to this.  It's not documented by MS, but it seems to be a PlayReady-related error:

```c++
/*
*    MessageId:    MSPR_E_INVALID_CDMSESSION
*    Message Meaning:
*       Only one reactive CDM Session can be attached to a playback session at a time.
*    Hex Value:    0x8004B8AD
*/
#define MSPR_E_INVALID_CDMSESSION                                   MAKE_DRM_RESULT(DRM_SEVERITY_ERROR,  DRM_FACILITY_ITF, DRM_E_MSPRSDK_BASECODE+0x00AD)
```

https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/winrt/Windows.Media.Protection.PlayReadyErrors.h

Could our IE11 EME polyfill have a race condition?  That might explain the inconsistency in repro.

**Comment by gigon** [comment] 2018-11-29 08:05
@TheModMaker, please explain how come the same asset works fine, including audio, on Edge browser, 
if it has a bad PSSH box?   
And: do you have any reference Playready content with separate keys for video and audio?

**Comment by TheModMaker** [comment] 2018-11-30 00:37
>@TheModMaker, please explain how come the same asset works fine, including audio, on Edge browser,
if it has a bad PSSH box?

My guess would be Edge either more resilient against errors or has a different parser so it ignores the parts that are wrong.

> And: do you have any reference Playready content with separate keys for video and audio?

I just tried the Axinom `Multi-DRM, multi-key` asset and I get the same error, so maybe there is a platform bug or something the IE EME polyfill is doing.  See #959.

**Comment by joeyparrish** [comment] 2019-01-22 17:32
Extended error code and fix cherry-picked for v2.4.6.

**Comment by joeyparrish** [comment] 2019-05-08 02:47
> I just tried the Axinom Multi-DRM, multi-key asset and I get the same error, so maybe there is a platform bug or something the IE EME polyfill is doing.

Axinom has stated that they simply don't support IE with their content, so that is not going to be fixed.  It's still unclear if the content in this issue is encoded in the same way as Axinom's.  If that is the case, then there's nothing we can do.

**Comment by joeyparrish** [comment] 2020-02-12 21:15
Unlikely to get fixed given that Axinom doesn't support IE and our support for IE ends after v2.6.

**Closed by joeyparrish** 2020-02-12 21:15 UTC
Labels: EME, bug
