### ISSUE TITLE
twitter m3u8 do not play

### ISSUE THREAD

**Issue by sirpy** [google/shaka-player#851] opened 2017-06-06 09:41 UTC
tried in latest shaka demo with custom manifest
giving the following url
https://video.twimg.com/amplify_video/871710644747223041/pl/PhPZTa1P6Is0QuLS.m3u8

**Comment by ismena** [comment] 2017-06-06 16:49
Hi @sirpy,
Did you try it in Safari by any chance? We have an open issue about TS segments in Safari (#743). (Safari has a bug we haven't been able to work around yet).
I tried the manifest you provided on Chrome with TS support turned on and it worked.

**Comment by joeyparrish** [comment] 2017-06-06 16:53
TS content should also work in MS Edge.

**Comment by joeyparrish** [comment] 2017-06-07 21:27
This plays fine in Edge.  This is likely a duplicate of #743.  I've bumped 743 up in the milestones to v2.3.0, and I'm closing this as a duplicate.  @sirpy, please subscribe to #743 for updates.  Thanks!

**Closed** 2017-06-07 21:27 UTC
Labels: duplicate

**Comment by sirpy** [comment] 2017-06-09 11:28
how would do i enable TS support? i just tried it via the demo link to shaka,
can you paste the code or a link for a demo that plays it?

**Comment by ismena** [comment] 2017-06-09 16:54
@sirpy 
Ah, sorry my previous comment was confusing. I have a custom Chrome build with enabled TS, that's not applicable to a wider audience.
You can try our normal demo page with your asset in Microsoft Edge or cast it to Chromecast via Chrome if you have one handy.

**Comment by sirpy** [comment] 2017-06-12 20:58
i want to use shaka on my app to play both hls and mpd files, so i guess
it's not completely supported yet.

**Comment by ismena** [comment] 2017-06-12 21:23
We are bound by what browsers can support, so there's not much we can do about this on shaka side. As(if) more browsers add support for TS segments you will be able to use shaka player for it.
If you have mp4 content (.mp4 media files rather then .ts) described by hls manifest, it will work with most major browsers today.

**Comment by sirpy** [comment] 2017-06-14 20:54
the hls.js by dailymotion is able to play this file, so it's not a browser
limitation

**Comment by vaage** [comment] 2017-06-14 20:59
@sirpy Thanks for checking that but unfortunately I believe this is still a browser limitation. hls.js transmuxes TS into MP4 and Shaka Player has made the decision to avoid transmuxing in their player so there is not much that can be done.
