### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by jjs1233** [google/shaka-player#467] opened 2016-07-27 02:16 UTC
My colleague give me a mpd file which include multiple resolution video 
Sometime the shakaplayer loading error  
the  environment  I use is  the rails 
and  I also use the nginx   
there is the Chrome Console report
![1](https://cloud.githubusercontent.com/assets/14259711/17161778/c2c07cfa-53e2-11e6-908a-ec6a76564153.png)
and there is the mpd file 
[a.mpd.zip](https://github.com/google/shaka-player/files/385173/a.mpd.zip)

**Comment by jjs1233** [comment] 2016-07-27 02:17
It not happen very often  
Often there will be a third was a failure

**Comment by joeyparrish** [comment] 2016-07-27 16:39
Please provide details on the error.  What's the error code you're seeing?

**Comment by jjs1233** [comment] 2016-07-28 06:13
![1](https://cloud.githubusercontent.com/assets/14259711/17202495/1e8265c8-54cc-11e6-9087-93d5c88c02b7.png)
Is this the error code you want it?

But the resource is exist
if I open the link in brower it worked
![3](https://cloud.githubusercontent.com/assets/14259711/17202526/526def10-54cc-11e6-87f1-1c0a1361e1cc.png)

there is my javascript code to trigger the shakaplayer
`addLoadEvent(function() {
	shakaDemo.load("a.mpd");
 });`

Is the way I use have a problem?

Finally forgive my broken English and Thanks for your help

**Comment by jjs1233** [comment] 2016-07-28 06:17
![4](https://cloud.githubusercontent.com/assets/14259711/17202730/90f134ee-54cd-11e6-9977-596ba7342328.png)
Is this the error code you want it?

But the resource is exist
if I open the link in brower it worked
![6](https://cloud.githubusercontent.com/assets/14259711/17202761/e8c5dec2-54cd-11e6-8b53-08fcf8c9c2e5.png)


there is my javascript code to trigger the shakaplayer
`addLoadEvent(function() {
	shakaDemo.load("a.mpd");
 });`

Is the way I use have a problem?

Finally forgive my broken English and Thanks for your help

**Comment by joeyparrish** [comment] 2016-07-28 16:09
Yes, that is the error I wanted.  HTTP_ERROR is typically caused by a lack of CORS headers on your server.  Please read [the CORS page at MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for details.  If you don't have the right CORS HTTP headers on the resource, then the application cannot access the content from another domain.

**Comment by joeyparrish** [comment] 2016-08-11 20:18
@jjs1233, is this still an issue for you, or can we close it?

**Comment by joeyparrish** [comment] 2016-08-26 23:22
Closing due to inactivity.

**Closed by joeyparrish** 2016-08-26 23:22 UTC
Labels: question
