### ISSUE TITLE
Offline Content with widevine license: Playback

### ISSUE THREAD

**Issue by nitin02** [google/shaka-player#527] opened 2016-09-20 08:52 UTC
Shaka Player v2:

My setup has DASH-CENC content for playback using the widevine DRM hosted in a cloud storage. There are no issues with playback using the shaka player.

I'm now trying to implement a fully offline system wherein, all the content (including manifest) is available in storage and the license is also persistent. Do note that, I'm not trying to store anything during playback but all content is already available offline.

Is this possible using shaka player? What is the best way to implement this?

**Comment by sandersaares** [comment] 2016-09-20 10:05
See https://github.com/google/shaka-player/issues/512

Seems to be a popular request! Not possible, as far as I know, though. Note that browsers implementing PlayReady DRM (Edge and IE11) do support persistent licenses.

**Comment by joeyparrish** [comment] 2016-09-22 16:07
@nitin02, offline storage and playback are supported via the APIs in [`shaka.offline.Storage`](http://nightly.shaka-player-demo.appspot.com/docs/api/shaka.offline.Storage.html).  The storage system gives you back a structure containing an offline URI.  Just use `player.load(uri)` to play back offline content.  You can also list stored content with [`shaka.offline.Storage.prototype.list()`](http://nightly.shaka-player-demo.appspot.com/docs/api/shaka.offline.Storage.html#list).

Note that browsers must support EME's `persistent-license` session type in order to store encrypted content.  Currently, the only browser that does today is ChromeOS.  We hope to see `persistent-license` support on desktop Chrome, Edge, and others in the future.  When that happens, no changes should be necessary in Shaka Player.

@sandersaares, Edge and IE11 do not support persistent licenses in the way EME specifies.  In particular, they do not support the `persistent-license` session type.  PlayReady has a somewhat different concept of persistence which is independent of session type.  In fact, Edge ignores the requested session type completely:  https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7564170/

Because Edge and IE11 aren't following the spec, Shaka Player can't use persistent licenses on those browsers yet.

**Comment by sandersaares** [comment] 2016-09-22 19:13
Aha, that's interesting. I did not realize Edge and IE11 persistence was something different! Thanks for clarifying.

**Comment by joeyparrish** [comment] 2016-09-22 19:46
Yes, PlayReady persistence seems to be controlled by license policy rather than session type.  So you request a `temporary` session and sometimes there's no license request because PlayReady has found a persisted license already.  The trouble is that the app has no visibility into the persistence of temporary licenses, and can't ask for a persistent one explicitly.

**Comment by joeyparrish** [comment] 2016-10-04 21:59
Since this is essentially about which browsers support persistent licenses, I am closing this as a duplicate of #512.  Let us know if you feel this was a mistake on our part, and I can reopen for further discussion.

**Closed by joeyparrish** 2016-10-04 21:59 UTC
Labels: duplicate, question
