### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by akmv** [google/shaka-player#2153] opened 2019-09-24 09:36 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
master branch, ver. 2.5

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
TV with Tizen OS v4 and PC with Ubuntu + Mozilla Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung TV UE32N5300, firmware T-KTSNDEUC-1270.6

**What are the manifest and license server URIs?** I can provide it.

**What did you do?**

I used Shaka Player on Samsung TV. I installed this example on TV https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html and tried to play video.

**What did you expect to happen?**
I expected that memory consumption would not constantly increase.

**What actually happened?**
When I played video(6096000bps), I got memory leaks. When I started video, TV had 600MB. After 10 minutes of playing video TV had 100MB, video and TV began to lag. Sometimes, after 15-20 minutes the lags might stop and then the video played well. I tested this application on my PC with browser Mozilla Firefox and also found memory leaks. About 3 GB of memory leaked after one hour of playing. When I refreshed the page and tried to play another video, memory leak continued.

Memory monitoring for 10 minutes on TV
![image](https://user-images.githubusercontent.com/6725317/65499840-f2ce2d80-dec6-11e9-9863-5af08bbebaa5.png)

**Comment by Himanshu-kSingh** [comment] 2019-09-25 06:07
I am also facing the same issue

**Comment by TheModMaker** [comment] 2019-11-12 18:21
Marking as duplicate of #2059.

**Closed by TheModMaker** 2019-11-12 18:21 UTC
Labels: TV/STB, needs triage
