### ISSUE TITLE
Fairplay on Safari: Invalid config, wrong type for .drm.advanced.com.apple.fps.1_0

### ISSUE THREAD

**Issue by torlangballe** [google/shaka-player#2003] opened 2019-06-20 11:24 UTC
I've read #1199 and #382 (closed), but still can't get FairPlay to work on Mac with latest Safari.

**Invalid config, wrong type for .drm.advanced.com.apple.fps.1_0**

On MacOS 10.14.4
Safari Version 12.1 (14607.1.40.1.4)

Later I get:

> Assertion Failed: missing certificate!
assert — asserts.js:46
onWebkitNeedKey_ — patchedmediakeys_apple.js:240
rebuildInitData_ — patchedmediakeys_apple.js:196

> TypeError: null is not an object (evaluating 'b.byteLength')
rebuildInitData_ — patchedmediakeys_apple.js:196
onWebkitNeedKey_ — patchedmediakeys_apple.js:248
log.js:132

I tried converting the certificate with base64->ArrayBuffer, probably not the problem, same error either way.

Is this working now for everybody else?

I can send the full keyserver url and certificate if anybody wants.

**My player setup is:**
```
function initPlayer() {
    if (manifestUri !== "") {
        var video = document.getElementById('video');
        var player = new shaka.Player(video);
        player.configure('drm.servers.com\\.apple\\.fps\\.1_0', keyServerURL);
        player.configure('drm.advanced.com\\.apple\\.fps\\.1_0', zBase64ToArrayBuffer(certificate));
        window.player = player;
        player.addEventListener('error', onErrorEvent);
        player.addEventListener('buffering', onBufferingEvent);
        player.addEventListener('drmsessionupdate', onDrmsessionupdate);
        player.addEventListener('loading', onLoadingEvent);
        player.addEventListener('streaming', onStreamingEvent);
        player.addEventListener('onstatechange', onStateChangeEvent);
        player.addEventListener('emsg', onEmsgEvent);
        player.addEventListener('onstateidle', onStateIdleEvent);        
        player.addEventListener('error', onErrorEvent);
        player.load(manifestUri, null, mimeType).then(function () { // "application/dash+xml" as 3rd arg to force
            video.play();
        }).catch(onError);  // onError is executed if the asynchronous load fails.
    }
}
```

Tor

> KeyServer URL: – "https://udrmv3-ap.kaltura.com/fps/license?custom_data=eyJjYV9zeXN0ZW0iOiJodHRwczovL3Jlc3QtYXMub3R0LmthbHR1cmEuY29tL2FwaV92My9zZXJ2aWNlL2Fzc2…" (playdrmvideo, line 25)
KeyServer Type: – "com.apple.fps.1_0" (playdrmvideo, line 26)
Manifest: – "https://tglmp01.akamaized.net/out/v1/5fecbc1b98074aa29649b72a99a26d2a/master.m3u8" (playdrmvideo, line 27)
Mime: – "application/vnd.apple.mpegurl" (playdrmvideo, line 28)
Certificate: – "MIIE4jCCA8qgAwIBAgIIM3kBaxj0lbgwDQYJKoZIhvcNAQEFBQ..." (playdrmvideo, line 29)
IndexedDB.install (shaka-player.compiled.debug.js, line 79)
InputEvent.install (shaka-player.compiled.debug.js, line 79)
mathRound.install (shaka-player.compiled.debug.js, line 79)
MediaSource.install (shaka-player.compiled.debug.js, line 79)
[Info] Patching Safari 11/12 MSE bugs. (shaka-player.compiled.debug.js, line 79)
[Info] Using Apple-prefixed EME (shaka-player.compiled.debug.js, line 79)
PiPWebkit.install (shaka-player.compiled.debug.js, line 79)
VideoPlayPromise.install (shaka-player.compiled.debug.js, line 79)
[Info] Using native VTTCue. (shaka-player.compiled.debug.js, line 79)
init (playdrmvideo.js, line 25)
[Error] Invalid config, wrong type for .drm.advanced.com.apple.fps.1_0
	(anonymous function) (shaka-player.compiled.debug.js:78:204)
	mergeConfigObjects (shaka-player.compiled.debug.js:981)
	mergeConfigObjects (shaka-player.compiled.debug.js:980:428)
	mergeConfigObjects (shaka-player.compiled.debug.js:980:428)
	mergeConfigObjects (shaka-player.compiled.debug.js:987:378)
	configure (shaka-player.compiled.debug.js:1066:421)
	initPlayer (playdrmvideo.js:33)
	initApp (playdrmvideo.js:17)
[Info] Starting attach... (shaka-player.compiled.debug.js, line 79)
[Info] Starting load of https://tglmp01.akamaized.net/out/v1/5fecbc1b98074aa29649b72a99a26d2a/master.m3u8... (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.requestMediaKeySystemAccess (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySystemAccess (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySystemAccess.getConfiguration (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySystemAccess.createMediaKeys (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeys (shaka-player.compiled.debug.js, line 79)
[Info] Created MediaKeys object for key system – "com.apple.fps.1_0" (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.setMediaKeys (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.onWebkitNeedKey_ – WebKitMediaKeyNeededEvent (shaka-player.compiled.debug.js, line 79)
WebKitMediaKeyNeededEvent
[Error] Assertion Failed: missing certificate!
	assert (shaka-player.compiled.debug.js:76:196)
	onWebkitNeedKey_ (shaka-player.compiled.debug.js:1251:368)
[Error] TypeError: null is not an object (evaluating 'b.byteLength')
	rebuildInitData_ (shaka-player.compiled.debug.js:1249:383)
	onWebkitNeedKey_ (shaka-player.compiled.debug.js:1251:481)
PatchedMediaKeysApple.MediaKeys.createSession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession.generateRequest (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.onWebkitKeyError_ – Event (shaka-player.compiled.debug.js, line 79)
Event
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
PatchedMediaKeysApple.onWebkitNeedKey_ – WebKitMediaKeyNeededEvent {isTrusted: true, initData: Uint8Array, type: "webkitneedkey", …} (shaka-player.compiled.debug.js, line 79)
WebKitMediaKeyNeededEvent {isTrusted: true, initData: Uint8Array, type: "webkitneedkey", target: <video id="video">, currentTarget: <video id="video">, …}WebKitMediaKeyNeededEvent
[Error] Assertion Failed: missing certificate!
	assert (shaka-player.compiled.debug.js:76:196)
	onWebkitNeedKey_ (shaka-player.compiled.debug.js:1251:368)
[Error] TypeError: null is not an object (evaluating 'b.byteLength')
	rebuildInitData_ (shaka-player.compiled.debug.js:1249:383)
	onWebkitNeedKey_ (shaka-player.compiled.debug.js:1251:481)
PatchedMediaKeysApple.MediaKeys.createSession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession.generateRequest (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.onWebkitKeyError_ – Event {isTrusted: true, type: "webkitkeyerror", target: WebKitMediaKeySession, …} (shaka-player.compiled.debug.js, line 79)
Event {isTrusted: true, type: "webkitkeyerror", target: WebKitMediaKeySession, currentTarget: WebKitMediaKeySession, eventPhase: 2, …}Event
Woops, there was an error making the cors request: 0 http://127.0.0.1:8090/db/measurements/preAdd?mkey=85c2b83940cd55ea800959bd3c31d1a4&name=error&value=EME PatchedMediaKeysApple key error&pos=0 (zutil.js, line 178)
sendValue err: – 0 – "" (playdrmvideo.js, line 90)
Woops, there was an error making the cors request: 0 http://127.0.0.1:8090/db/measurements/preAdd?mkey=85c2b83940cd55ea800959bd3c31d1a4&name=error&value=EME PatchedMediaKeysApple key error&pos=0 (zutil.js, line 178)
sendValue err: – 0 – "" (playdrmvideo.js, line 90)
[Error] Failed to load resource: Could not connect to the server. (preAdd, line 0)
PatchedMediaKeysApple.onWebkitNeedKey_ – WebKitMediaKeyNeededEvent {isTrusted: true, initData: Uint8Array, type: "webkitneedkey", …} (shaka-player.compiled.debug.js, line 79)
WebKitMediaKeyNeededEvent {isTrusted: true, initData: Uint8Array, type: "webkitneedkey", target: <video id="video">, currentTarget: <video id="video">, …}WebKitMediaKeyNeededEvent
[Error] Assertion Failed: missing certificate!
	assert (shaka-player.compiled.debug.js:76:196)
	onWebkitNeedKey_ (shaka-player.compiled.debug.js:1251:368)
[Error] TypeError: null is not an object (evaluating 'b.byteLength')
	rebuildInitData_ (shaka-player.compiled.debug.js:1249:383)
	onWebkitNeedKey_ (shaka-player.compiled.debug.js:1251:481)
PatchedMediaKeysApple.MediaKeys.createSession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession.generateRequest (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.onWebkitKeyError_ – Event {isTrusted: true, type: "webkitkeyerror", target: WebKitMediaKeySession, …} (shaka-player.compiled.debug.js, line 79)
Event {isTrusted: true, type: "webkitkeyerror", target: WebKitMediaKeySession, currentTarget: WebKitMediaKeySession, eventPhase: 2, …}Event
Woops, there was an error making the cors request: 0 http://127.0.0.1:8090/db/measurements/preAdd?mkey=85c2b83940cd55ea800959bd3c31d1a4&name=error&value=EME PatchedMediaKeysApple key error&pos=0 (zutil.js, line 178)
sendValue err: – 0 – "" (playdrmvideo.js, line 90)
Woops, there was an error making the cors request: 0 http://127.0.0.1:8090/db/measurements/preAdd?mkey=85c2b83940cd55ea800959bd3c31d1a4&name=error&value=EME PatchedMediaKeysApple key error&pos=0 (zutil.js, line 178)
sendValue err: – 0 – "" (playdrmvideo.js, line 90)
[Error] Failed to load resource: Could not connect to the server. (preAdd, line 0)
PatchedMediaKeysApple.onWebkitNeedKey_ – WebKitMediaKeyNeededEvent {isTrusted: true, initData: Uint8Array, type: "webkitneedkey", …} (shaka-player.compiled.debug.js, line 79)
WebKitMediaKeyNeededEvent {isTrusted: true, initData: Uint8Array, type: "webkitneedkey", target: <video id="video">, currentTarget: <video id="video">, …}WebKitMediaKeyNeededEvent
[Error] Assertion Failed: missing certificate!
	assert (shaka-player.compiled.debug.js:76:196)
	onWebkitNeedKey_ (shaka-player.compiled.debug.js:1251:368)
[Error] TypeError: null is not an object (evaluating 'b.byteLength')
	rebuildInitData_ (shaka-player.compiled.debug.js:1249:383)
	onWebkitNeedKey_ (shaka-player.compiled.debug.js:1251:481)
PatchedMediaKeysApple.MediaKeys.createSession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession.generateRequest (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.onWebkitKeyError_ – Event {isTrusted: true, type: "webkitkeyerror", target: WebKitMediaKeySession, …} (shaka-player.compiled.debug.js, line 79)
Event {isTrusted: true, type: "webkitkeyerror", target: WebKitMediaKeySession, currentTarget: WebKitMediaKeySession, eventPhase: 2, …}Event
Woops, there was an error making the cors request: 0 http://127.0.0.1:8090/db/measurements/preAdd?mkey=85c2b83940cd55ea800959bd3c31d1a4&name=error&value=EME PatchedMediaKeysApple key error&pos=0 (zutil.js, line 178)
sendValue err: – 0 – "" (playdrmvideo.js, line 90)
Woops, there was an error making the cors request: 0 http://127.0.0.1:8090/db/measurements/preAdd?mkey=85c2b83940cd55ea800959bd3c31d1a4&name=error&value=EME PatchedMediaKeysApple key error&pos=0 (zutil.js, line 178)
sendValue err: – 0 – "" (playdrmvideo.js, line 90)
[Error] Failed to load resource: Could not connect to the server. (preAdd, line 0)

**Comment by torlangballe** [comment] 2019-06-20 11:35
BTW, I pulled latest from master and built today 20 june 2019.

**Comment by ismena** [comment] 2019-06-20 17:15
Thanks for the report! Let me bug the local fairplay expert @joeyparrish

**Comment by joeyparrish** [comment] 2019-06-20 18:22
It looks like the expected type is Uint8Array, so the ArrayBuffer is being ignored.  Please try Uint8Array and see if that solves it.

**Comment by TheModMaker** [comment] 2019-06-20 18:27
Also the `advanced` configuration is an object, so you need to specify this is a server cert.  It also is a Uint8Array, so you need to use that instead.

```js
player.configure('drm.advanced.com\\.apple\\.fps\\.1_0.serverCertificate',  cert);
```

**Comment by torlangballe** [comment] 2019-06-21 09:27
Great, I changed to Uint8Array and added the .serverCertificate to the configuration, and I'm not getting THOSE errors anymore. It's a shame #382 is closed as https://github.com/google/shaka-player/issues/382#issuecomment-490953057 shows a perhaps incorrect way of doing it.

My issue now is I'm getting webkitneedkey and webkitkeyerror I think. I am not running over HDMI cable, and am not doing any recording or airplay or anything fancy. Could it be a formatting issue from the key-server?

Relevant Output:

> Created MediaKeys object for key system – "com.apple.fps.1_0" 
PatchedMediaKeysApple.setMediaKeys 
PatchedMediaKeysApple.MediaKeys.setServerCertificate 
PatchedMediaKeysApple.onWebkitNeedKey_ – WebKitMediaKeyNeededEvent {isTrusted: true, initData: Uint8Array, type: "webkitneedkey", …} 
WebKitMediaKeyNeededEvent {isTrusted: true, initData: Uint8Array, type: "webkitneedkey", target: <video id="video">, currentTarget: <video id="video">, …}WebKitMediaKeyNeededEventbubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: nulldefaultPrevented: falseeventPhase: 0initData: Uint8Array 0, 0, 0, 115, 0, 107, 0, 100, 0, …]Uint8Array (84)isTrusted: truereturnValue: truesrcElement: <video id="video"><video id="video">target: <video id="video"><
PatchedMediaKeysApple.MediaKeys.createSession 
PatchedMediaKeysApple.MediaKeySession 
PatchedMediaKeysApple.MediaKeySession.generateRequest 
PatchedMediaKeysApple.MediaKeys.createSession 
PatchedMediaKeysApple.MediaKeySession 
PatchedMediaKeysApple.MediaKeySession.generateRequest 
PatchedMediaKeysApple.onWebkitKeyMessage_ – WebKitMediaKeyMessageEvent {isTrusted: true, message: Uint8Array, destinationURL: "", …} 
WebKitMediaKeyMessageEvent {isTrusted: true, message: Uint8Array, destinationURL: "", type: "webkitkeymessage", target: WebKitMediaKeySession, …}WebKitMediaKeyMessageEvent
PatchedMediaKeysApple.onWebkitKeyError_ – Event {isTrusted: true, type: "webkitkeyerror", target: WebKitMediaKeySession, …} 
Event {isTrusted: true, type: "webkitkeyerror", target: WebKitMediaKeySession, currentTarget: WebKitMediaKeySession, eventPhase: 2, …}Event
PatchedMediaKeysApple.MediaKeySession.update

**Comment by joeyparrish** [comment] 2019-06-26 20:49
@torlangballe, I'm not sure what you mean about https://github.com/google/shaka-player/issues/382#issuecomment-490953057 .  It shows `new Uint8Array()` wrapping an `ArrayBuffer`, right?

As for the rest, you've filed #2009, which appears to be a duplicate of #1923, so we'll continue there.  Thanks!

**Closed by joeyparrish** 2019-06-26 20:49 UTC
Labels: question

**Comment by TheModMaker** [comment] 2019-06-26 20:51
@joeyparrish I just edited your comment to use Uint8Array and pass the correct config path.

**Comment by joeyparrish** [comment] 2019-06-26 20:57
Ah!  Thanks, @TheModMaker, and my apologies to @torlangballe.
