### ISSUE TITLE
[HLS] Combines audio tracks into one

### ISSUE THREAD

**Issue by alex2844** [google/shaka-player#2694] opened 2020-06-29 11:29 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.0.1

**What browser and OS are you using?**
Chrome OS

```m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="Original",URI="./mono-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="Comments",URI="./mono-a2.m3u8"
```

**Comment by TheModMaker** [comment] 2020-06-29 16:21
Could you send us a manifest URL that contains this?  You can send it privately to shaka-player-issues@google.com.

**Comment by alex2844** [comment] 2020-06-29 16:56
This is a playlist from the local network

```
#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="Original",URI="./mono-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="Comments",URI="./mono-a2.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=960321,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="aac"
./mono-v1.m3u8
```

**Comment by alex2844** [comment] 2020-06-29 21:16
Found an example in the demo where this bug is visible

https://shaka-player-demo.appspot.com/demo/#audiolang=ru;textlang=ru;uilang=ru;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=ALL_CONTENT;panelData=HLS;build=compiled

```
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_5"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="de",NAME="stream_4"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="it",NAME="stream_8"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="fr",NAME="stream_7"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="es",NAME="stream_9"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_6"...
```

![Screenshot 2020-06-30 at 02 12 36](https://user-images.githubusercontent.com/18526177/86056677-3fa6ec00-ba77-11ea-953d-122b0b3f200e.png)

As you can see, there is not enough 1 audio track

**Comment by TheModMaker** [comment] 2020-06-29 22:18
In that case, the two English tracks have different audio channel counts.  I don't think we support switching between channel counts once playback has started so we filter out the extra English track and stay with the 2 channel.

HLS section 4.3.4.1.1 starts with:

> A set of one or more EXT-X-MEDIA tags with the same GROUP-ID value
   and the same TYPE value defines a Group of Renditions.  Each member
   of the Group MUST be an alternative Rendition of the same content;
   otherwise, playback errors can occur.

Which to me says that a group is for the same content, just in different languages or channel counts.  So having both main and commentary audio in the same group would be invalid.  So according to this, commentary audio would need to be another group.  But then later in the section, it says:

> A Playlist MAY contain multiple Groups of the same TYPE in order to
   provide multiple encodings of that media type.  If it does so, each
   Group of the same TYPE MUST have the same set of members, and each
   corresponding member MUST have identical attributes with the
   exception of the URI and CHANNELS attributes.

Which suggests that normal content only has one group per TYPE.  So I'm not sure whether different audio sources should be in the same group or not.  @ismena, what are your thoughts?  How do we handle this now?  I think the way it works is we need different audio sources to be in different groups and assume that a group is only for different languages of the same content.

**Comment by joeyparrish** [comment] 2020-06-30 02:38
> I don't think we support switching between channel counts once playback has started so we filter out the extra English track and stay with the 2 channel.

I think we do support switching channels, but I could be wrong.  There's no reason to filter based on channel count as far as I can tell.

What you see in the UI by default is only the languages.  Do you see all the tracks you expect if you call getVariantTracks()?  If so, the tracks are not truly merged, and this is only a UI issue.

**Comment by alex2844** [comment] 2020-06-30 08:52
```
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_5"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="de",NAME="stream_4"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="it",NAME="stream_8"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="fr",NAME="stream_7"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="es",NAME="stream_9"...
#EXT-X-MEDIA:TYPE=AUDIO,URI="...",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_6"...
```

I believe that when repeating language, you need to show
```
stream_5 (en)
stream_6 (en)
Deutsch
Italiano
Francais
Espanol
```

**Comment by joeyparrish** [comment] 2020-08-18 00:53
I've verified that with the content in question, the two English tracks have different channel counts but are otherwise indistinguishable (by role, etc).  https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8

All tracks are present when `getVariantTracks()` is called, which is as expected.  You can switch between 2-channel and 6-channel by calling `selectVariantTrack()` with the audio track of your choice.  This is also as expected.

If you change the channel count preference (`player.configure('preferredAudioChannelCount', 6)` for example), then selecting "English" will select the track with the preferred number of channels (by default, 2).  This is also as expected.

If there are multiple tracks with the same language, but different roles, those will show up separately in the UI.  And the UI can be configured to show roles as well as languages via `ui.configure('trackLabelFormat', shaka.ui.TrackLabelFormat.LANGUAGE_ROLE)`.  (The default is `shaka.ui.TrackLabelFormat.LANGUAGE`.)

So as far as I can tell, everything is working as intended.  Changing between 2-channel and 6-channel audio can still be done via the API and via preferences, though not through the UI.

Does this help?

**Comment by joeyparrish** [comment] 2021-04-13 21:25
Closing due to inactivity. If you need to reopen this issue, just put @shaka-bot reopen in a comment. Thanks!

**Closed by joeyparrish** 2021-04-13 21:25 UTC
Labels: working as intended
