### ISSUE TITLE
Firefox bug - Firefox does not support persistent state with Widevine

### ISSUE THREAD

**Issue by kidmiracleman** [google/shaka-player#401] opened 2016-06-06 09:08 UTC
Hi,

We are testing with a version of Shaka Player on Firefox beta  - this version supports the Widevine CDM

In eme_manager.js   - I am trying to force the use of persistent state via always setting "persistentState: 'required' "  On Chrome this allows use of the provider_client_token feature by initiating a request for a server supplied certificate that can be used to obfuscate the client side private data.

We don't see this server certificate request when we test on Firefox - therefore a provider_client_token is not returned by the Widevine license server.

Has anyone else tested this  - is persistentstate / provider_client_token supported on Firefox??

Tested on Firefox 47.03b (beta channel)  On OSX 10.10.5 and Windows 10   - Shaka Player 1.3.1 (I realise this is old, but works on Chrome)

**Comment by joeyparrish** [comment] 2016-06-06 23:14
This is not something we have tested yet, but I will look into it.

**Comment by robwalch** [comment] 2016-06-07 15:20
I just tried the [demo page](https://shaka-player-demo.appspot.com/demo/) with Firefox Nightly 50.0a1 (2016-06-07). The Unified Streaming "Tears of Steel (Widevine)" asset works! It did not work in FF 49 so it looks like mozilla has fixed the CDM issue(s) there.

I have not tried shaka-player v1.6.5 (the version jwplayer currently uses). It would be great if it just worked in 1.6.x but we're pretty excited about integrating shaka v2 once it's released.

**Comment by robwalch** [comment] 2016-06-07 20:08
Update: Widevine streams are playing shaka-player 1.6.5 with Firefox Nightly 50.0a1 (2016-06-07).

**Comment by joeyparrish** [comment] 2016-06-07 20:11
Thanks for testing for us, Rob!  Since this appears to be working in the latest Firefox with both versions of Shaka, I will consider the matter resolved by Mozilla.

**Comment by robwalch** [comment] 2016-06-08 18:51
Do you have an idea of what the issues are with getting EME working with Firefox 47? Firefox 47 is available now, and Mozilla has announced Widevine support would be available in this release.

Firefox 50 isn't expected to be released until November, so this puts us in a bind.

https://blog.mozilla.org/futurereleases/2016/04/08/mozilla-to-test-widevine-cdm-in-firefox-nightly/
https://blog.mozilla.org/futurereleases/2016/02/04/update-on-2016-firefox-release-schedule/

**Comment by cpeterso** [comment] 2016-06-09 04:24
@robwalch Widevine is now available in Firefox 47, which was released this week. The "Tears of Steel (Widevine)" video works for me with Firefox 47, 48 (Beta), and 50 (Nightly) on OS X. Can you please try retesting?

I suspect you may have hit a temporary problem during Firefox Nightly 49 that has been reverted. We tried to update to a newer version of the Widevine CDM about two weeks ago, but hit some content compatibility problems. [Firefox bug 1273214](https://bugzilla.mozilla.org/show_bug.cgi?id=1273214#c8) has more information.

**Comment by cpeterso** [comment] 2016-06-09 04:25
btw, the persistentState problem @kidmiracleman reported above is [Firefox bug 1278198](https://bugzilla.mozilla.org/show_bug.cgi?id=1278198). I think @robwalch saw a different problem.

**Comment by kidmiracleman** [comment] 2016-06-09 09:05
@joeyparrish - can this be reopened?  The intent of this ticket is to highlight a potential issue with persistentState and dependent provider_client_token feature of Widevine.

**Comment by joeyparrish** [comment] 2016-06-09 22:02
@kidmiracleman: As @cpeterso pointed out, the issue with persistentState seems to be [Firefox bug 1278198](https://bugzilla.mozilla.org/show_bug.cgi?id=1278198).  Since that is a bug in Firefox, not in Shaka, I've tagged it "bug" and "external".

I will reopen this issue until the Firefox bug has been confirmed fixed.

**Comment by robwalch** [comment] 2016-06-17 02:12
Yes I saw a different problem that is resolved in 47. Thanks!

**Comment by cpearce** [comment] 2016-07-25 22:08
From tomorrow onwards, Firefox Nightly (version 50) should support the persistentState attribute. Please re-test in an up-to-date Firefox Nightly build tomorrow, and let me know whether that works.

**Comment by joeyparrish** [comment] 2016-11-15 00:25
Firefox 50 is due out tomorrow and should have the fix.  Closing this issue.  Thanks, everyone!

**Closed by joeyparrish** 2016-11-15 00:25 UTC
Labels: bug, external
