### ISSUE TITLE
difficulties with Chromecast

### ISSUE THREAD

**Issue by legrengo** [google/shaka-player#1803] opened 2019-02-14 07:38 UTC
hello, I'm a beginner I try to run the Chromecast with shaka-player I'm looking for a while, I do not see where is the problem and yet the console tells me it's ok for the receiver

sorry for my poor English

https://www.ellealcatrase.eu/player2/

**Comment by legrengo** [comment] 2019-02-14 16:39
when I do
./build/test.py --browsers Chrome,Firefox,Edge
I have the following errors

[INFO] Running test (1 / 1)...
14 02 2019 17:30:39.213:ERROR [launcher]: No binary for Edge browser on your platform.
  Please, set "EDGE_BIN" env variable.
14 02 2019 17:30:50.670:ERROR [launcher]: Cannot start Firefox
        Error: no DISPLAY environment variable specified

14 02 2019 17:30:50.728:ERROR [launcher]: Cannot start Firefox
        Error: no DISPLAY environment variable specified

14 02 2019 17:30:50.780:ERROR [launcher]: Cannot start Firefox
        Error: no DISPLAY environment variable specified

14 02 2019 17:30:50.782:ERROR [launcher]: Firefox failed 2 times (cannot start). Giving up.
14 02 2019 17:30:56.358:ERROR [launcher]: Cannot start Chrome

(google-chrome:2283): Gtk-WARNING **: cannot open display:

14 02 2019 17:30:56.482:ERROR [launcher]: Cannot start Chrome

(google-chrome:2324): Gtk-WARNING **: cannot open display:

14 02 2019 17:30:56.631:ERROR [launcher]: Cannot start Chrome

(google-chrome:2346): Gtk-WARNING **: cannot open display:

14 02 2019 17:30:56.633:ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.
[INFO] Run complete
[INFO] Result (exit code): 1


I respected the installation documentation
Console:
Using native MSE as-is.
vttcue.js:36 Using native VTTCue.
drm_engine.js:1507 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.
service_worker.js:1 Uncaught (in promise) TypeError: Request failed
service_worker.js:1 Uncaught (in promise) TypeError: Request failed
﻿
​
I've been trying for days to find information

**Comment by TheModMaker** [comment] 2019-02-14 18:29
Can you describe more what the problem is with the Chromecast app?  What do you do to start casting?  What do you see on the Chromecast?

As for the test failures, there are two problems.  First you are running on Linux which doesn't support Edge, so remove that from the browsers list.  Second you appear to be running from an SSH connection or from something that doesn't have the DISPLAY environment variable set.  Usually when you run a command line locally it will set the DISPLAY variable to the current monitor so the browser knows where to display the browser.  If you run from an SSH connection or from a cron job, you'll need to set this manually to the correct display so the browser will appear.  You can alternatively run within a virtual frame buffer.  Enter the following instead:

```sh
DISPLAY=:0 ./build/test.py --browsers Chrome,Firefox
# Or alternatively
./build/test.py --browsers Chrome,Firefox --use-xvfb
```

**Comment by legrengo** [comment] 2019-02-15 03:36
I can tell you
no reaction from ChromeCast ^^


I give my tongue to the cat

**Comment by legrengo** [comment] 2019-02-17 14:45
there is no button to launch Chromecast

**Comment by theodab** [comment] 2019-02-20 20:09
Looks like the cast button on the UI got broken during a refactoring. I have a CL out to fix it.

**Comment by theodab** [comment] 2019-02-20 22:15
Does this change fix your problem? If not, I'll be happy to look into any further issues.

**Comment by legrengo** [comment] 2019-02-21 02:46
thank you for your answer ,
.I am not very good at solving the problem unfortunately

**Comment by legrengo** [comment] 2019-02-21 14:05
what do you mean by "refactoring" please ?

**Comment by vaage** [comment] 2019-02-21 16:33
@legrengo "refactoring" is the term for when the implementation of a behaviour is changed without changing the behaviour. Unfortunately while changing how we implemented something, we changed the behaviour.

As @theodab said, he submitted a fix to restore the correct behaviour while still maintaining the new implementation. It was committed in [do2759b](https://github.com/google/shaka-player/commit/d02759bdeaac88d4cda16389281fd707093229f4). If you checkout that version, you should see the correct behaviour restored.

As a favor to us, could you checkout `HEAD` or [do2759b](https://github.com/google/shaka-player/commit/d02759bdeaac88d4cda16389281fd707093229f4) and tell us if the behaviour you expected has been restored? If so, we can close the issue.

**Comment by legrengo** [comment] 2019-02-21 23:42
thanks for your relevant explanation
the Chromecast button appears in the hamburger menu (with the function picture in picture).
this solved the problem for me

thank you so much

**Comment by theodab** [comment] 2019-02-21 23:44
Glad to have helped.

**Closed by theodab** 2019-02-21 23:44 UTC
Labels: UI, bug
