### ISSUE TITLE
Multiplexed representations with DRM issue

### ISSUE THREAD

**Issue by maxbykov** [google/shaka-player#359] opened 2016-04-28 18:50 UTC
Hi,
after updating to the latest version we noticed that shaka player stopped working with multiplexed DRM-protected representations. The error is `DRM.REQUESTED_KEY_SYSTEMS_UNAVAILABLE`. Seems like this commit https://github.com/google/shaka-player/commit/3c3fe6980df88c28e195169afcaae381acf14429 introduced the issue.
Example manifest https://gist.github.com/maxbykov/137bd5dc9f27b0c0ccd2fd1302066fe2
The issue it introduced might be related to the `codecs="avc1.42c028,mp4a.40.2"` field and, as a result, fullMimeType will carry audio and video codec ids to the EME which will result in the error.
Though `codecs` extension is not mandatory per EME spec and passing `video/mp4` would work just fine (as it was before, I guess).

I understand that this fix for Edge is temporary solution, but is there any way we can somehow figure out the way to bring DRMed multiplexed representation back before MS will react? We tried stripping `codecs` parameter from `Representation` completely since it is optional per ISO/IEC 23009-1 (while keeping it for `SubRepresentation`), but this change faced another error from the player `STREAMING.INVALID_STREAMS_CHOSEN`, more precisely `MANIFEST.UNPLAYABLE_PERIOD`.

**Comment by tdrews** [comment] 2016-04-28 21:07
Hi, thanks for the report. We'll take a look.

**Comment by joeyparrish** [comment] 2016-05-03 08:07
We can't go back to the previous workaround, since the EME spec is getting more strict about specifying codecs and [Chrome has already moved to deprecate configurations without codecs](https://bugs.chromium.org/p/chromium/issues/detail?id=605661#c5).

In DrmEngine, we are already working around a [bug in Edge's EME implementation where multiple entries are not supported](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7223299/).  It seems that Edge's EME does not support the codecs string for multiplexed streams, either.  We could expand our hack further to completely exclude codecs for Edge, but that could blow up in our faces if Edge 14 or 15 updates to the newer EME working draft and starts requiring codecs as Chrome 51 is doing.

In general, we have never directly supported multiplexed streams.  We've never forbidden them, but we have never had a goal of supporting them, either.

I'm not sure what we will be able to do about this, but I **highly recommend** that you file a bug report with Microsoft about the lack of support for multiple codecs in the query.  If you do, please link to it here.

I'm removing the v2.0.0 label since we do not explicitly support multiplexed streams, but I will continue to investigate to see if we can fix it without too much risk.

**Comment by maxbykov** [comment] 2016-05-03 11:30
Thank you for your response. Unfortunately, we observed this issue in Chrome, I think the EME engine throws an error on getting `mp4/video;avc1.42c028,mp4a.40.2` in case of the example manifest during `requestMediaKeySystemAccess` where it expects only video codecs to be part of the `videoCapabilities`.

**Comment by joeyparrish** [comment] 2016-05-03 12:02
Ah, I see.  Then perhaps Chrome doesn't support multiplexed representations in EME.  If you file a bug against Chrome, please link to it here.

We will definitely not be able to work around this for Chrome, since Chrome will soon reject queries without a codec string.

**Comment by maxbykov** [comment] 2016-05-03 12:30
How would you estimate the chances that Shaka will support parsing `SubRepresentation` in the future? I mean, the missing piece is there, we are just not getting it. Or is it feasible to implement splitting the codecs string by audio/video category and then fulfilling `videoCapabilities/audioCapabilities` accordingly?

**Comment by joeyparrish** [comment] 2016-05-03 12:41
It's entirely possible that Widevine doesn't support multiplexed representations on all platforms.  It could be that the query is truthfully being rejected by the browser.  Or it could be that this type of query isn't supported.

What Shaka is doing is faithfully passing the information from the manifest to EME, and the EME implementation is rejecting it.  I think the best thing for you to do is to file a bug at http://crbug.com/ and find out if this is intended behavior on the part of Chrome or not.

If the answer is that the query should be split, we'll split it.

If the answer is that multiplexed representations are intentionally not supported by Chrome or Widevine, then there's not much we can do in Shaka.  Any changes we make now to split the codecs up for you may break on other platforms or may break in future versions of Chrome if multiplexed streams are not supported.

**Comment by maxbykov** [comment] 2016-05-03 13:59
Thank you, this is helpful.

**Comment by ddorwin** [comment] 2016-05-03 16:34
As Joey noted, `codecs` is now required by the spec in step 10 of the [Get Supported Capabilities for Audio/Video Type](https://w3c.github.io/encrypted-media/#get-supported-capabilities-for-audio-video-type) algorithm.

Step 11 of the same algorithm requires that:
* `videoCapabilities` contains a "video/" type and only video codecs
* `audioCapabilities` contains an "audio/" type and only audio codecs

Thus, this failure isn't related to whether multiplexed streams are supported - it is the use of an audio codec in `videoCapabilities`. (The reason this is not allowed is that the robustness levels for audio and video may differ and specifying audio codecs with the video robustness would likely unexpectedly fail on some clients.)

**Comment by maxbykov** [comment] 2016-05-03 16:48
So, it seems like this issue might be resolved only be adding support for `SubRepresentation` from where information about each component might be extracted.
If so, could we consider this issue as a feature request and get an approximation on feasibility or, ideally, timeframe for it? Based on that we can make an internal decision on supporting such multiplexed format from our side.
Thank you.

**Comment by joeyparrish** [comment] 2016-05-03 18:50
@ddorwin, is this reasonable from an EME perspecitve?  Just put audio mime types & codecs in audioCapabilities and video mime types & codecs in videoCapabilities even though the stream we deliver to the CDM will be multiplexed and contain both?

What about from a Chrome CDM perspective?  Will multiplexed content work with the Chrome CDM interface when the CDM is being asked to decode as well as decrypt?

**Comment by ddorwin** [comment] 2016-05-03 18:57
Yes, this seems reasonable from an EME perspective. CDMs just receive encrypted blocks, so the stream is demuxed before it reaches the CDM. Among other things, this means EME _should_ be independent of MSE vs. `.src=`.

For Chrome, the question is whether the MSE implementation supports such multiplexed streams. @wolenetz

**Comment by wolenetz** [comment] 2016-05-03 19:40
Chrome MSE supports multiplexed unencrypted streams. Note that a discontinuity detected in one component of the stream will impact all other components of the stream. One thing to note is that MSE SourceBuffer doesn't expose the 'buffered' ranges for each component, just their intersection TimeRanges. This means that there could be buffered media for some component(s) outside of those intersection TimeRanges, and may complicate player usage of arbitrary muxed streams, especially if the player doesn't have accurate metadata (or the streams aren't muxed to match that metadata precisely).

In Chrome MSE, each component of a multiplexed stream, like each standalone non-multiplexed component, is exposed to the decoding/playback pipeline internally the same way. For EME, however, I'm unclear if the key information/etc is extracted and reported correctly if it is meant to be used for more than one component. I defer to ddorwin@ on that point.

**Comment by ddorwin** [comment] 2016-05-03 21:52
I believe each multiplexed stream is a separate track and that each track has default key IDs, potentially PSSH boxes, etc. The demuxer will associate these with the blocks from the track, and this information will then be used when the CDM processes the blocks.

**Comment by joeyparrish** [comment] 2016-05-04 08:52
Okay, so we *could* support this by parsing `SubRepresentation` and `ContentComponent` and correlating the two, then populating this info to a new array member in the manifest's `Stream` object.  `Representation.mimeType` would be combined with each `SubRep`'s `codecs` and the associated `ContentComponent.contentType`.  For example, `mimeType` `video/mp4` + `contentType` `audio` + `codecs` `mp4a.40.2` => `audio/mp4; codecs=mp4a.40.2`.  `DrmEngine` then uses this new array of MIME types to build its query.

I'd like something simpler, though.

We *could* split the codecs string we have and rebuild those MIME types in `DrmEngine`, but then `DrmEngine` has to know how to map specific codecs to content types, and that seems brittle.  We shouldn't assume we can hard-code knowledge of specific codecs, as new ones can be introduced later.

I'm scheduling this for after v2.0.0 for now.

**Comment by maxbykov** [comment] 2016-05-04 17:48
Thank you Joey

**Comment by joeyparrish** [comment] 2016-10-04 23:27
@maxbykov, after further consideration and after consulting DASH interoperability guidelines, I have decided that we will not support multiplexed content.

DASH IOP v3.3 states:

> only non-multiplexed Representations shall be used, i.e. each Representation only contains a single media component.

Multiplexed content does not meet DASH guidelines for interoperability, and therefore we will not put any effort into supporting it in the player.

**Comment by joeyparrish** [comment] 2016-10-04 23:30
I'm closing the issue now, but if you feel strongly about this, we can, of course, discuss it further.  I would encourage you to use non-multiplexed content and to try to follow [IOP guidelines](http://dashif.org/wp-content/uploads/2016/06/DASH-IF-IOP-v3.3.pdf) as much as possible.

Thanks for using Shaka Player, and please let me know if there's anything else we can do for you.

**Closed by joeyparrish** 2016-10-04 23:30 UTC
Labels: enhancement, will not implement

**Comment by maxbykov** [comment] 2016-10-05 00:37
@joeyparrish thank you for the update
