### ISSUE TITLE
Seeking not working in Firefox for some streams

### ISSUE THREAD

**Issue by mattcoz** [google/shaka-player#239] opened 2015-11-30 19:48 UTC
I'm having issues with the following stream in Firefox. It plays fine, but if I try to seek ahead it will stop and I can't restart it. It buffers the video, just doesn't play it.

https://wowza.arclearn.com/ArcLearn/smil:I_ENT472.ism/manifest.mpd

This stream at the same server does not have the same problem:

https://wowza.arclearn.com/ArcLearn/smil:I_TESTVIDEO.ism/manifest.mpd

**Comment by cpeterso** [comment] 2015-12-01 02:55
@mattcoz: which version of Firefox are you testing and on which OS? I can seek in the I_ENT472 mpd with both Firefox 42 and Nightly 45 on OS X. I do see a lot of buffering delays (and Shaka's "Pac-Man" spinner), but I think that is a problem with the video encoding because I see that with Chrome, too.

**Comment by mattcoz** [comment] 2015-12-01 20:18
@cpeterso Tested in 42 and 45 Nightly on Windows 10 and 42 on Windows 7, can’t seek past around 20 seconds in and it freezes if I let it play that long. Tested in 42 on OSX 10.11, can seek and play fine. The buffering delays look to be a performance problem with our server, we’re looking into it.

**Comment by cpeterso** [comment] 2015-12-01 23:49
I can now reproduce with Firefox 45 on Windows 8. I think this is a Firefox bug, not a Shaka Player bug, because I can reproduce the seek problem when playing this mpd in other DASH players, such as [Bitdash](http://www.dash-player.com/demo/manifest-test/) and [DASH-IF](http://dashif.org/reference/players/javascript/index.html).

@joeyparrish: I think you can close this bug report as "not a Shaka bug". I filed [Firefox bug 1229592](https://bugzilla.mozilla.org/show_bug.cgi?id=1229592) to track this issue (and CC'd @mattcoz).

**Comment by joeyparrish** [comment] 2015-12-02 18:58
@cpeterso Thanks, Chris!

**Closed by joeyparrish** 2015-12-02 18:58 UTC
Labels: question
