### ISSUE TITLE
CEA-608 encoding issue with DASH stream

### ISSUE THREAD

**Issue by jtromo** [google/shaka-player#1981] opened 2019-06-07 21:13 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.0

**Can you reproduce the issue with our latest release version?**
**Can you reproduce the issue with the latest code from `master`?**
Using embedded playing on Chromecast

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Unable to play stream

**What browser and OS are you using?**
Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast Ultra 1.37 
Chromecast 1.39

**What are the manifest and license server URIs?**

Partner's stream with no DRM.

**What did you do?**

1. Use Shaka 2.5.0 with mux.js
2. Play DASH stream with CEA-608 captions

**What did you expect to happen?**
I expect the stream to play with CEA-608 captions from the start of the stream. 

**What actually happened?**

The stream starts with garbled/improperly encoded captions that fix themselves after a few seconds. After the initial issues, playback works as expected.

**Comment by theodab** [comment] 2019-06-14 22:21
I tried playing the asset you provided, but it doesn't seem to play. In browser or on Chromecast.
You mentioned that you are using a custom app, and on the demo you are unable to play the stream.
Is there anything we can do to try this stream ourselves?

**Comment by joeyparrish** [comment] 2019-06-17 17:15
We do have the stream URL, but it's giving us a 404.  There seem to be ongoing backend changes on the partner's side.  We will hold off on further work until we hear an update.

**Comment by jtromo** [comment] 2019-06-17 18:51
The partner's updated stream no longer reproduces the issue. I will update when we are able to get a reproducing stream.

**Comment by joeyparrish** [comment] 2019-07-09 18:04
@jtromo, since we can't reproduce the issue, I will close this for now.  Please feel free to reopen if this comes up again.

**Closed by joeyparrish** 2019-07-09 18:04 UTC
Labels: needs triage
