### ISSUE TITLE
HLS - Shaka player requests media playlists for all qualities, all the time

### ISSUE THREAD

**Issue by index23** [google/shaka-player#2293] opened 2019-12-11 13:55 UTC
First shaka player request is for HLS master playlist. After that, shaka player requests media playlists for each quality (defined in master playlist) and continues to do that all the time, regardless of current playing quality. Also after pausing video, player continues to requests media playlists for each quality. Is that expected behavior?

**Comment by joeyparrish** [comment] 2019-12-11 18:19
Yes, that is expected behavior right now.  We maintain segment indexes for all quality levels, codecs, bitrates, etc.

**Comment by index23** [comment] 2019-12-11 19:41
@joeyparrish thanks for quick response.

**Comment by TheModMaker** [comment] 2020-01-06 19:24
Since this appears to have answered your questions, I'll close this.  If you have any more questions, you can post a comment with `@shaka-bot reopen` to re-open this issue or open a new issue.

**Closed by TheModMaker** 2020-01-06 19:24 UTC
Labels: question
