### ISSUE TITLE
error 6006 and initDataTransform called twice per track.

### ISSUE THREAD

**Issue by abdevnet** [google/shaka-player#2245] opened 2019-11-18 16:27 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.6

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
didn't try.  my license server requires custom  data.

**What browser and OS are you using?**
Safari 12.1.1, MacOS 10.14.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**  I will email them.  in my simple.js files replace lines 4-7 with my email contents. 

**What did you do?**

Hit "test video" on my test page (simple.html).  errors are logged to console and I alert them.  After the errors you can right click the video turn on controls and then play the content.  

**What did you expect to happen?**
should play without errors.  initdatatransform should only be called once per keyid.

**What actually happened?**
errors are logged to console and I alert them.  After the errors you can right click the video turn on controls and then play the content.  also initDataTransform is called twice.  the 2nd time it is all garbled.

[fairplay.zip](https://github.com/google/shaka-player/files/3859579/fairplay.zip)

**Comment by shanmugapriyaEK** [comment] 2019-11-22 13:27
Hi @abdevnet , 

I analysed the your code for one of my issue. I did some refactoring of your fairplay.js and simple.js .
It started working for me. Hope it might help you. 
I simplified your simple and fairplay.js as . index.js without any error and on button load invoked loadVideo()

[index.js.zip](https://github.com/google/shaka-player/files/3879697/index.js.zip)

**Comment by abdevnet** [comment] 2019-11-26 17:15
Has anyone from the shaka team tried to reproduce this yet?  I sent all the urls for my fairplay server and content in an email to shaka-player-issues@google.com.

**Comment by abdevnet** [comment] 2019-11-26 17:18
@shanmugapriyaEK I didn't find your changes helpful.  You removed the code that processes the license request and response.

**Comment by shanmugapriyaEK** [comment] 2019-11-27 18:34
Yes. I removed your custom license request and response processor as it is different for me. In my case I had to send headers few other params and remove base64 encoding. 
You can get the skd(content id) by using the Shaka utils. 
By default when we set the drm.fairplayTransform to true. It does base64 encoding and sends spc You only had to add additional header information.

**Comment by TheModMaker** [comment] 2020-01-06 19:15
I think this is a duplicate of #2214.

**Closed by TheModMaker** 2020-01-06 19:15 UTC
Labels: needs triage

**Comment by abdevnet** [comment] 2020-01-08 15:22
@TheModMaker it may be but I did send specific instructions in the email on how to reproduce.  Is this issue going to be resolved anytime soon?

**Comment by TheModMaker** [comment] 2020-01-08 16:49
Since we've gotten a few reports of this, we'll try to get this fixed in v2.6.
