### ISSUE TITLE
switchHistory does not have variant/bandwidth info

### ISSUE THREAD

**Issue by russitto** [google/shaka-player#823] opened 2017-05-19 20:18 UTC
- What version of Shaka Player are you using?
Shaka 2.1.1
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
Both

  - If custom app, can you reproduce the issue using our demo app?
Yes

- What browser and OS are you using?
Chrome on Windows

- What did you do?
In developers tools: 
shakaDemo.player_.getStats().switchHistory

  - What content did you load?
Shaka Demo
    - If standard demo asset, which one?
Angel One multicodec multilingual

- What did you expect to happen?
Variant info in switch history, or bandwidth info

- What actually happened?
I got array of object with track id, nor variant/bandwidth info
![2017-05-19-170428_310x301_scrot](https://cloud.githubusercontent.com/assets/5013199/26264959/3c38cfe0-3cb5-11e7-884b-bcaacb6a49f5.png)

**Comment by joeyparrish** [comment] 2017-05-24 20:19
@russitto, the expectation was that applications would correlate `id` with the `id` field of `Track`.

Would it be more helpful to include the `Track` object itself and deprecate `id` in the history?

**Comment by russitto** [comment] 2017-05-24 20:44
Hi, `getTracks/getVariantTracks` uses variant id.` getStats()` uses track id.
Track objects are not public via api.
Please show me how to get track objects or include `Track` object in `getStats()`.

Thanks! :)

**Comment by joeyparrish** [comment] 2017-05-24 20:48
Ah, I see now.  We put IDs from the non-public `Stream` object into the history, rather than `Track` IDs.  Sorry about that.

**Comment by joeyparrish** [comment] 2017-05-24 20:58
- `Track` ID for variants is taken from `Variant` ID
 - `Track` ID for text is taken from `Stream` ID
 - `Stream` and `Variant` IDs are auto-incremented integers, not from manifest
 - `switchHistory` contains `Stream` IDs only

The crux of the problem is that variant `Tracks` have the `Variant` ID, but the two `Stream`s inside the `Variant` have their own IDs which are only seen in `switchHistory` and can't be correlated to anything through the public API.

**Comment by joeyparrish** [comment] 2017-05-24 21:53
It looks like the ID issue was already filed here: #823

**Comment by joeyparrish** [comment] 2017-05-24 21:56
If the IDs in `switchHistory` matched `Track` IDs, would that be sufficient?  Or would you still like to have `bandwidth` added to the history entries?

I'm starting to lean away from including the entire `Track`, but that is still a technically feasible option.

**Comment by russitto** [comment] 2017-05-25 08:27
It's fine with `switchHistory` matching `Track` IDs.
Thx

**Comment by joeyparrish** [comment] 2017-05-25 17:46
In that case, this is a duplicate of #785.  I will close this one, and you can follow along on that one.  Thanks!

**Closed** 2017-05-25 17:46 UTC
Labels: bug, duplicate

**Comment by joeyparrish** [comment] 2017-06-05 21:51
Cherry-picked to v2.1.3.
