### ISSUE TITLE
Chromecast Support Broken - "Launch Error"

### ISSUE THREAD

**Issue by PyRo1509** [google/shaka-player#253] opened 2015-12-27 06:11 UTC
When loading any of the Shaka Player Demos (1.6-1.6.2), clicking the cast icon on the player result in the following error to console:

    Launch Error
    sender.onError @ sender.js:334
    b.Lf @ cast_sender.js:2365
    b.cg @ cast_sender.js:2386
    chrome.cast.da.Sf @ cast_sender.js:2154

Tested on Chromebook and Macbook. 

This results in no action and inability to cast the demo.

**Comment by joeyparrish** [comment] 2016-01-05 01:05
Hi @PyRo1509,

Thanks for the report.  I can confirm your results.  It seems to be a configuration issue for the receiver application.  We *should* be able to fix it server-side.  I'll keep you posted.

**Comment by joeyparrish** [comment] 2016-01-06 22:38
Alright, it appears to be fixed now.  Thanks!

**Closed by joeyparrish** 2016-01-06 22:38 UTC
Labels: bug
