### ISSUE TITLE
A Period Missing Text Adaptation, 3.x Player Freeze 100%. 

### ISSUE THREAD

**Issue by dsparacio** [google/shaka-player#2998] opened 2020-11-19 17:52 UTC
@joeyparrish I am working on a fix for this but wanted to see if you could give me some direction on possible area in code base.  I spent a few hours diffing 2.x to 3.x to try to spot the issue.  Let me try to explain:  

_If you have content that has 6 periods.  and all periods **but the last**, has text adaptation (segment template, and text is enabled when entering the last period, we freeze 100% at the same exact same streamtime ~ 9 seconds into period._

1. This only happens when the vtt file is 30 second shorter than A/V duration. Checking spec if this is even allowed. 
1. Does not happen in 2.x, on 3.x codebase.  
1. If there is a mid-roll between 5th and 6th period,  we actually freeze 9 seconds in to the ad.  Seems as it is pre processing the last period and hitting this issue but not sure yet.  (ad insertion is not required to reproduce)
1. If I seek past this freeze by 1 second, I see the log lines in the attached image.  
![Screen Shot 2020-11-18 at 4 44 18 PM](https://user-images.githubusercontent.com/7864462/99703997-a8096080-2a4c-11eb-8e57-c7ada88618f7.png)

As I diff the version and change, It does not look like it files in text folder TextEngine or VTT parser changed regarding this.  So, I am now looking at Period.js and StreamEngine etc...  

I actually have some time to solve this issue and just looking for possible guidance on where to look if you have any.  I'll keep diffing files to spot something that may cause this.   I will of course PR this back if I find a good solution.  

Thanks in advance for any pointers here.

**Comment by TheModMaker** [comment] 2020-11-19 18:15
This appears to be a duplicate of #2957.  My guess is this is a regression in how we handle Period flattening.  I would guess the problem is in `lib/util/periods.js`, or maybe in `lib/media/streaming_engine.js` for how we fetch segments.

**Comment by dsparacio** [comment] 2020-11-19 18:18
@TheModMaker Darn,  I searched the issues and missed that. .Seems to be exactly it.  I am on it.  will circle back if I can find a fix

**Comment by dsparacio** [comment] 2020-11-19 18:18
Ill keep this open for a day or two, maybe more questions,  but essentially we can close this soon.

**Comment by dsparacio** [comment] 2020-11-19 19:55
Note keeping. 

Looking at L132 period.js
```
      // It's okay to have a period with no text, but our algorithm fails on any
      // period without matching streams.  So we add dummy text streams to each
      // period.  Since we combine text streams by language, we might need a
      // dummy even in periods with text streams already.
```
I see the dummy text stream added for last period.  I see 2 items in array for all other periods. The two items consist of real text item and this dummy item.  

Last period only has dummy item.

**Comment by dsparacio** [comment] 2020-11-19 21:13
So it is related to the stream buffer ahead balance act.  Not a solution but proven that if I do not return 1 in this block the issue goes away.  I am sure buffers compete now and race ahead.  So Ill look for a real solution now.
```
    if (timeNeeded >= minTimeNeeded + maxRunAhead) {
      // Wait and give other media types time to catch up to this one.
      // For example, let video buffering catch up to audio buffering before
      // fetching another audio segment.
      if (mediaState.type === 'text') {
        console.log('xxx time needed', timeNeeded, minTimeNeeded , maxRunAhead)
      }
      //return 1;
    }
```

**Comment by dsparacio** [comment] 2020-11-19 21:35
Observed that getCurrentTextStream is returning the first periods stream and expected the dummy stream to be the current if there is no text stream in period.  Maybe this is source of issue? 

{id: 1, originalId: "0,0,0,0,0,", segmentIndex: s…a.m…a.MetaSegmentIndex, mimeType: "application/mp4", createSegmentIndex: ƒ, …}

**Comment by dsparacio** [comment] 2020-11-19 22:56
More Notes
```
L1024
if (shaka.media.StreamingEngine.isEmbeddedText_(otherState) || otherState.type == ContentType.TEXT) {
    continue;
}
```
Solves issue, not properly, bandage, will continue to look for optimal solution.
Note, with this in place, solves issue and not seeing any frags of any media type running ahead of others. 3 at at time rinse and repeat.... 

I did expect to see text chunks race a head but did not.  maybe cause my stream has mp4 encapsulated vs vtt files. not sure yet

**Comment by dsparacio** [comment] 2020-11-21 00:32
period flatting looks correct, with the text combined,  I am seeing 4 periods text with original id 0 and no item in last period to represent text seeing the 5 indices for A/V.  That is, If I am interrupting the objects and code correctly.

![Screen Shot 2020-11-20 at 4 13 31 PM](https://user-images.githubusercontent.com/7864462/99862100-63192300-2b4d-11eb-945f-4233daceff89.png)

Looking for a place in code now that is trying to schedule text segs when there is no text track.   Seems like the buffer equalizing code is the place it is hanging for sure, but not the place for the fix. should not be fetching text here.

**Comment by dsparacio** [comment] 2020-11-23 18:30
@TheModMaker wondering if my notes/info sparks anything in your mind on possible next steps?  How do we know a given period has dropped the text track and to stop fetching text segments once the periods are flattened.

**Comment by TheModMaker** [comment] 2020-11-23 21:25
You can't know, that's the point of Period flattening.  We don't want to know about Periods within StreamingEngine.  I think the problem is that since we have nothing to buffer for text, we stall the other streams until we have segments for text.  There are two ideas I have that may fix this:

One would be to insert fake segments within the stream.  StreamingEngine would need to see these segments and not try to fetch them, but use it to calculate the amount buffered.

Second, we could extend the segment times of the previous segment to cover the whole Period that doesn't have content.  I think we use the reference times to calculate how far ahead we've buffered the streams, so this can be used to make the segments appear to buffer more.

**Comment by dsparacio** [comment] 2020-11-24 01:02
> You can't know, that's the point of Period flattening. We don't want to know about Periods within StreamingEngine. 

Figured this was the reason to flatten of course..and make sense.  

> One would be to insert fake segments within the stream. StreamingEngine would need to see these segments and not try to fetch them, but use it to calculate the amount buffered.

This seems more solid than the other option imo.  

Both seem like something I cannot implement on my own so I'll wait for the possible fix of https://github.com/google/shaka-player/issues/2957 which looks like it is slated for milestone 3.1

Thanks for your comments.

**Closed** 2020-11-24 01:02 UTC
Labels: question
