### ISSUE TITLE
Calling for not-existing Chunks

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#3735] opened 2021-11-02 13:59 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**What version of Shaka Player are you using?**

3.2.0 and 3.2.1

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `master`?**

yes

**Are you using the demo app or your own custom app?**

custom

**If custom app, can you reproduce the issue using our demo app?**

yes

**What browser and OS are you using?**

Windows / Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

n/a

**What are the manifest and license server URIs?**

https://sdn-global-streaming-cache.3qsdn.com/24666/files/21/10/11/3960246/24666-GVQnP7CqzRgXNDW.ism/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default

**What did you do?**

play the Video. the problematic Part happens at the end. 

**What did you expect to happen?**

the SDK should not ask for this Chunk, as it seems unnecessary and is non-existing. Additionally, I wonder why it keeps asking for this even after Playback ended.

**What actually happened?**

Roughly 10 Seconds before end, the Player starts asking for a non-existing Chunk. It keeps asking for this Chunk permanently, even after the Video is finished.  The Video runs fine though until the End, no Playback Error is reported.
I checked with other Engines (BitMovin, DashJS) - they never ask for that Chunk. The CDN informed me, that there are currently 100k+ 404 Requests for this (and a few other) Video(s) which seems unnecessary to me.

**Comment by boredom2** [comment] 2021-11-03 11:39
We see this Behaviour now more and more often.
For example also here: https://sdn-global-streaming-cache.3qsdn.com/42628/files/21/11/03/4118460/42628-DYXN8VFWwz9HGky.ism/manifest.mpd

This leads to various Issues and I would like to know, if there is something we can do about that?

**Comment by TheModMaker** [comment] 2021-11-15 19:55
Closing as duplicate of #3717.

**Closed by TheModMaker** 2021-11-15 19:55 UTC
Labels: type: bug
