### ISSUE TITLE
HLS range get : the range header is wrong and video is not play

### ISSUE THREAD

**Issue by yuanchieh-cheng** [google/shaka-player#1576] opened 2018-09-10 10:00 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
2.4.4
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:
yes
**What browser and OS are you using?**:
chrome 68 @ mac
**What are the manifest and license server URIs?**:
https://gist.github.com/yuanchieh-cheng/39b205431cf977819c3b3c05f82c2234
**What did you do?**
I wana play hls. The play list loaded correctly but range get is error.  
I found some error in console.  
```
Assertion failed: startByte must be < endByte
GET ${config.staticHost}/local_file/1.m4s 403 (Forbidden)
Unable to find byte-order-mark, making an educated guess.
HTTP error text: {"error":"Range Not Satisfiable"}
```
The range get header is wrong "range: bytes=NaN-NaN"
**What did you expect to happen?**
Range setting is correct and download partial source.
**What actually happened?**
no display.

**Comment by TheModMaker** [comment] 2018-09-10 16:07
First, for future reference, we need a playable URL, not the text of the manifests.  In general, we need to be able to put the URL in Shaka Player and see what it is trying to do.  But in this case, I can see what the problem is.  Second, we don't support substitutions, so the URLs won't be correct, see #1561 for more.

Lastly, the issue is your `EXT-X-BYTERANGE` tag is wrong.  It ends with a comma, which is against the spec.  The [spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.2) (in section 4.3.2.2) says that the format of the value is `<n>[@<o>]`, so it can only be a number at the end.

I also notice that most of your tags end in commas, which for attribute lists may be supported, but for interoperability should be removed.

**Comment by joeyparrish** [comment] 2018-10-11 20:30
@yuanchieh-cheng, does this answer your question?  May we close the issue?

**Closed** 2018-10-18 20:36 UTC
Labels: bad content, waiting on response
