### ISSUE TITLE
Cannot play live stream from dashcast

### ISSUE THREAD

**Issue by ram95014** [google/shaka-player#264] opened 2016-01-12 17:07 UTC
```
player.js:191 + video/mp4; codecs="avc1.64001e" is supported
stream_video_source.js:1562 Starting each stream from 50.01200008392334

app.js:884 Player error CustomEvent {isTrusted: false, srcElement: null, currentTarget: s…a.p…r.Player, target: s…a.p…r.Player}
  bubbles: true
  cancelBubble: false
  cancelable: false
  currentTarget: shaka.player.Player
  currentTarget: shaka.player.Player
  defaultPrevented: false
  detail: Error: The browser failed to decode the media content.
      at shaka.player.Player.onError_ (http://192.168.2.13/shaka/lib/player/player.js:425:15)
  eventPhase: 0
  isTrusted: false
  isTrusted: false
  path: Array[0]
  returnValue: true
  srcElement: null
  srcElement: null
  target: shaka.player.Player
  timeStamp: 1452618258366
  type: "error
  __proto__: CustomEvent
    app.onPlayerError_ @ app.js:884
    shaka.util.FakeEventTarget.recursiveDispatch_ @ fake_event_target.js:167
    shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:145
    shaka.player.Player.onError_ @ player.js:428

stream.js:700 Stream video/mp4: stream has started.
stream_video_source.js:1637 All Streams have completed startup!
stream_video_source.js:1705 Timestamp correction 0.2791860000000028

app.js:884 Player error CustomEvent {isTrusted: false, srcElement: null, currentTarget: s…a.p…r.Player, target: s…a.m…a.Stream}
    app.onPlayerError_ @ app.js:884
    shaka.util.FakeEventTarget.recursiveDispatch_ @ fake_event_target.js:167
    shaka.util.FakeEventTarget.recursiveDispatch_ @ fake_event_target.js:180
    shaka.util.FakeEventTarget.recursiveDispatch_ @ fake_event_target.js:180
    shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:145
    (anonymous function) @ stream.js:658
```

**Comment by joeyparrish** [comment] 2016-01-12 19:22
@ram95014 I'm going to need more information in order to diagnose.

- Can you provide a URL which reproduces the problem?
- What version of Shaka Player are you using?
- Can the problem be reproduced on our stock demo page, or is some custom app logic required to access your stream?

**Comment by joeyparrish** [comment] 2016-01-12 19:26
(I took the liberty of reformatting the log dump for readability)

**Comment by ram95014** [comment] 2016-01-12 20:24
I installed shaka player 1.6.2 on my local ubuntu instance. I generated a
VOD MPD and I was able to successfully playback the VOD content. However,
when I tried using a live DASH content using DashCast:
DashCast -vf x11grab -vres 800x600 -vfr 25 -v :0.0 -live
and tried to play it back with the player, I got the error that I had
pasted before.
The MPD file is like so (may not match the one that created the error log,
but very similar):

> <?xml version="1.0"?>
>
> <MPD xmlns="urn:mpeg:dash:schema:mpd:2011"
>> availabilityStartTime="2016-01-12T20:11:06.506Z"
>> minBufferTime="PT1.000000S" timeShiftBufferDepth="PT00H00M10S" type="dynamic
>
> " profiles="urn:mpeg:dash:profile:full:2011" minimumUpdatePeriod="PT1000S">
>
>  <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
>
>   <Title>dashcast.mpd</Title>
>
>  </ProgramInformation>
>
>  <Period start="PT0H0M0.000S" id="P1">
>
>   <AdaptationSet segmentAlignment="true" bitstreamSwitching="false">
>
>    <SegmentTemplate timescale="25" duration="25"
>> media="$RepresentationID$_$Number$_gpac.m4s" startNumber="1"
>> initialization="$RepresentationID$_init_gpac.mp4"/>
>
>    <Representation id="v1" mimeType="video/mp4" codecs="avc1.64001e"
>> width="640" height="480" frameRate="25" sar="1:1" startWithSAP="1"
>> bandwidth="1000000">
>
>    </Representation>
>
>   </AdaptationSet>
>
>  </Period>
>
> </MPD>
>
>
> As you can in the error log, the UTC time difference between the two
machines is small. I am using a chrome browser on a OSX machine, and the
Apache server is running on Ubuntu instance in a VM in the OSX.
Unfortunately, I am unable to create a publicly visible server at this time
for you to test at this time.
-Ram

**Comment by joeyparrish** [comment] 2016-01-27 03:46
In my tests, DashCast generates the wrong value for the `availabilityStartTime` attribute.  When current date & time in UTC at startup was "Wed Jan 27 03:23:55 2016", the manifest had `availabilityStartTime` of `2016-01-28T03:23:55.344`, one day in the future.

DashCast also generates an invalid period start time.  The `start` attribute format is an [XML duration](http://www.datypic.com/sc/xsd/t-xsd_duration.html), but DashCast uses `0` instead of `P0S`.

I'm tracking down the cause and I'll report these bugs to [gpac](https://github.com/gpac/gpac).  When I have, I'll link to the issues from here so that you can follow up with them.  But for now, it appears that there is no bug in Shaka.

**Comment by joeyparrish** [comment] 2016-01-27 04:11
This is odd.  I followed the DashCast build instructions from their website and ran into these two bugs.  However, the instructions refer to the gpac SVN repo, which does not seem to be current.  I filed gpac/gpac#388 to have them update their website, and I will retest with an up-to-date DashCast.

**Comment by joeyparrish** [comment] 2016-01-27 05:03
I retested with an up-to-date version of DashCast.  The `start` and `availabilityStartTime` problems in the old version are now fixed.

In my test, it seems that Chrome fails to decode the content.  Here's a snippet of the log I found in `chrome://media-internals`:

```
pipeline_state: kPlaying
error: video frame with PTS 0us has negative DTS -1409741us
error: Append: stream parsing failed.
pipeline_error: pipeline: decode error
pipeline_state: kStopping
pipeline_state: kStopped
```

@ram95014, please rerun your own test, and after the decode failure, check the value of `video.src`.  Then, open a tab with `chrome://media-internals` and click the button whose label shows the value of `video.src` you read from Shaka.  Finally, check to see if you have a similar log about negative DTS.  If so, we are seeing the same problem and you should [file a report with gpac](https://github.com/gpac/gpac/issues/new) and link to it here.

Thanks!

**Comment by joeyparrish** [comment] 2016-02-27 00:26
@ram95014 It's been a while since we heard from you.  Did you file a bug with gpac?  Did you find some other solution?

**Comment by ram95014** [comment] 2016-02-27 02:10
Hi joey,
I had to move on to other things. I had to stop working on dash...
Ram

**Comment by joeyparrish** [comment] 2016-02-27 17:01
@ram95014 Okay, no worries.  Thanks!

**Closed by joeyparrish** 2016-02-27 17:01 UTC
Labels: working as intended
