### ISSUE TITLE
Chrome PTS bug - DRM content not played

### ISSUE THREAD

**Issue by sridhardvvce** [google/shaka-player#601] opened 2016-11-19 13:24 UTC
Hi,

I am using the latest version of shaka player. 
I have encoded the content for widevine DRM. The content is not played using shaka player.

MPD URL: https://learnyst.s3.amazonaws.com/schools/1094/drm_courses/6677/paid/35010/online/smallfile_c33h9ukiikawrzqfflxr/stream.mpd

License server: https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=AQAAAA2dKbwAAABQthKBZh0V6A2V5VhNx2GK_jzRelKZZUf1HcazQFpWfi7ogFgbzJQtydjUb4kEBQxVuqCFOhz0umOtA6sLFTQLyeBu-nK_OT4tnCaLi8RvIIVJCg8txM7Oc5fwkjTDI5_RvKW9lw

Earlier we were using the shaka player to play DRM videos and the process of DRM encryption has not changed. We use amazon transcoder to transcode videos to multiple formats. As per the amazon suggestion we have changed the encoding parameters like bitrate and domensions recently. After that videos are not playing.

Please help me in debugging this issue.

**Comment by joeyparrish** [comment] 2016-11-29 00:25
Your video starts at 0.256 in Chrome.  This appears to be just over the threshold of the gap size Chrome is willing to skip.  In Firefox, the video starts at 0, so I think this is another symptom of Chrome's ongoing DTS/PTS bug.

Here's a link to the Chrome bug where you can let them know that this affects you:  https://bugs.chromium.org/p/chromium/issues/detail?id=398130

This is also a duplicate of #377, which is caused by the same Chrome bug.

**Comment by joeyparrish** [comment] 2016-12-19 19:27
Since this is a duplicate and an external bug, I'm going to close it.  We will keep #377 open while we track Chrome's progress on this.

**Closed by joeyparrish** 2016-12-19 19:27 UTC
Labels: bug, duplicate, external
