### ISSUE TITLE
Widevine encrypted content fails on Android Chrome

### ISSUE THREAD

**Issue by peyoh** [google/shaka-player#311] opened 2016-03-22 08:46 UTC
Hello,
the issue seems like 
[309](https://github.com/google/shaka-player/issues/309) 
but it is quite different as logs.

After KQ fixed Widevine issue in 
[edash WV issue 95](https://github.com/google/edash-packager/issues/95) , 

we try to use shaka demo page from Android Chrome with a WV encrypted channel. 
The console log seems ok, but no video was played.
```

onEncrypted_ [0, 0, 0, 116, 112, 115, 115, 104, 0, 0, 0, 0, 237, 239, 139, 169, 121, 214, 74, 206, 163, 200, 39, 220, 213, 29, 33, 237, 0, 0, 0, 84, 8, 1, 18, 16, 196, 76, 155, 237, 253, 46, 80, 68, 133, 34, 207, 135, 31, 176, 247, 165, 18, 16, 9, 163, 2, 55, 12, 39, 82, 213, 175, 118, 239, 188, 11, 122, 15, 36, 18, 16, 34, 1, 50, 216, 34, 4, 95, 97, 185, 252, 51, 218, 207, 104, 32, 240, 26, 12, 105, 110, 118, 101, 110, 116, 111, 115, 115, 121…] MediaEncryptedEvent {initDataType: "cenc", initData: ArrayBuffer, type: "encrypted", target: video#video, currentTarget: video#video…}
eme_manager.js:662 onSessionMessage_ MediaKeyMessageEvent {messageType: "license-request", message: ArrayBuffer, type: "message", target: MediaKeySession, currentTarget: MediaKeySession…}
eme_manager.js:546 onEncrypted_ [0, 0, 0, 116, 112, 115, 115, 104, 0, 0, 0, 0, 237, 239, 139, 169, 121, 214, 74, 206, 163, 200, 39, 220, 213, 29, 33, 237, 0, 0, 0, 84, 8, 1, 18, 16, 196, 76, 155, 237, 253, 46, 80, 68, 133, 34, 207, 135, 31, 176, 247, 165, 18, 16, 9, 163, 2, 55, 12, 39, 82, 213, 175, 118, 239, 188, 11, 122, 15, 36, 18, 16, 34, 1, 50, 216, 34, 4, 95, 97, 185, 252, 51, 218, 207, 104, 32, 240, 26, 12, 105, 110, 118, 101, 110, 116, 111, 115, 115, 121…] MediaEncryptedEvent {initDataType: "cenc", initData: ArrayBuffer, type: "encrypted", target: video#video, currentTarget: video#video…}
stream.js:700 Stream audio/mp4: stream has started.
eme_manager.js:770 onLicenseSuccess_ MediaKeySession {sessionId: "sid7", expiration: NaN, closed: Promise, keyStatuses: MediaKeyStatusMap}
eme_manager.js:546 onEncrypted_ [0, 0, 0, 116, 112, 115, 115, 104, 0, 0, 0, 0, 237, 239, 139, 169, 121, 214, 74, 206, 163, 200, 39, 220, 213, 29, 33, 237, 0, 0, 0, 84, 8, 1, 18, 16, 196, 76, 155, 237, 253, 46, 80, 68, 133, 34, 207, 135, 31, 176, 247, 165, 18, 16, 9, 163, 2, 55, 12, 39, 82, 213, 175, 118, 239, 188, 11, 122, 15, 36, 18, 16, 34, 1, 50, 216, 34, 4, 95, 97, 185, 252, 51, 218, 207, 104, 32, 240, 26, 12, 105, 110, 118, 101, 110, 116, 111, 115, 115, 121…] MediaEncryptedEvent {initDataType: "cenc", initData: ArrayBuffer, type: "encrypted", target: video#video, currentTarget: video#video…}
stream.js:700 Stream video/mp4: stream has started.
stream_video_source.js:1643 All Streams have completed startup!
stream_video_source.js:1711 Timestamp correction 
```

chrome://media-internals log shows: 

`DecryptingDemuxerStream: decryptor not set.`

Please tell me what I can do to debug this issue deeper?
This encrypted channel works fine with Shaka-player on Chrome for Linux Version 49.0.2623.87 
but is unable to play on several Chrome browsers for Android (mine is 49.0.2623.91 ). 

BRS

**Comment by joeyparrish** [comment] 2016-03-22 18:46
Using the latest release, v1.6.4, on http://shaka-player-demo.appspot.com/, I am unable to reproduce.  I can play "Car/CENC", which is encrypted with Clearkey, "Car/SegmentTemplate", which is encrypted with Widevine, and the Widevine version of "Sintel (4k)".

Chrome for Android does not allow autoplay, so you must click the "play" button on the video controls after loading a video.  Could that be your problem?

**Comment by peyoh** [comment] 2016-03-22 18:49
Hi Joe,
unfortunately not. 
I will prepare a test environment. You may help me to understand if this is Chrome, packager or player issue. 
BRS
Peyo

**Comment by joeyparrish** [comment] 2016-03-22 18:53
Are you able to visit the demo on appspot and play the assets I mentioned?

**Comment by peyoh** [comment] 2016-03-22 19:00
Yes. Car I'm able to play on Android.

**Comment by joeyparrish** [comment] 2016-03-22 19:07
If you can play other assets on Chrome on Android, it's probably not a problem only with Chrome or only with Shaka.  My early guess is that it's one of the following:

1. a packager bug
2. a problem with your packager options
3. a problem with your input content
4. an incompatibility between components (packager, content, Chrome, Player)

In any case, I'm happy to help you diagnose it further.

**Comment by peyoh** [comment] 2016-03-22 19:13
Aha. The system has many components so it is complicated. I will prepare the test environment and I will appreciate any help from you.

**Comment by joeyparrish** [comment] 2016-03-22 19:20
Sounds good.  To start, if you can provide manifest and proxy URLs that my team can access, we will try to reproduce.  Based on what we see, we will decide what the next step is.  If you can't provide URLs publicly, please send me a private email.  My email address can be found in CONTRIBUTORS.

**Comment by peyoh** [comment] 2016-03-24 15:31
Hi Joe, 
the networking issues was fixed. Credentials are in your mailbox.

**Comment by peyoh** [comment] 2016-03-28 12:00
Hello,
did you see something? Are you able to reproduce this issue? 

BRS

**Comment by joeyparrish** [comment] 2016-03-29 20:35
Hi Peyo, when I open your site on Android in the debugger, I see this in the JS console:

'goog.require could not find: shaka.player.DashVideoSource'

It seems that `CLOSURE_NO_DEPS` is set in the `window`, which breaks our library's uncompiled mode by telling Closure not to automatically load the deps file.  The culprit is `http://www.gstatic.com/eureka/clank/cast_sender.js`, which isn't included in the app itself, but seems to be included by Chrome on Android directly.  This JS file is not loaded on desktop.

This appears to be a bug that has already been filed against Chrome: http://crbug.com/597315

There are two ways you can work around this in the mean time:

1. Run in compiled mode by adding ?compiled to the URL
2. Patch in the deps file in load.js:

```
    loadScript('third_party/closure/goog/base.js');
    loadScript('third_party/closure/goog/deps.js');   // ADD THIS HERE
    loadScript('shaka-player.uncompiled.js');
```

Since Shaka appears to be working correctly when not interfered with, I will close this as "working as intended".  Please let me know if there's anything else I can do to help.

**Closed** 2016-03-29 20:37 UTC
Labels: working as intended
