### ISSUE TITLE
Add Travis as CI

### ISSUE THREAD

**Issue by leandromoreira** [google/shaka-player#364] opened 2016-05-03 13:50 UTC
Mostly to run the tests, it helps by providing each PR with a build pass or not. 

If that's fine, I'm willing to do so.

**Comment by joeyparrish** [comment] 2016-05-03 18:43
We run our tests with karma, and we already have a Jenkins-based build bot that builds and tests each PR on real browsers and real hardware.  We test PRs on Chrome Linux and we run all tests nightly on Linux, Mac, and Windows using Chrome, Firefox, Opera, IE 11, Edge, and Safari.

Our build bot is already integrated with github and reports status back to the pull request.  For an example of what this looks like, see: https://github.com/google/shaka-player/pull/315#issuecomment-203080412

Our integration tests require HTML5 video, MSE, and EME.  Running tests on PhantomJS won't work because they don't have HTML5 video ([issue](https://github.com/ariya/phantomjs/issues/10839)).  We stopped using BrowserStack because of their lack of PlayReady support, among other reasons.  We also considered SauceLabs, but they don't support PlayReady and don't seem to be considering it at the moment ([ticket](https://saucelabs.ideas.aha.io/ideas/SLIDEA-I-206)).

So far, the only solid solution we have found is to run our tests on real hardware, so I don't think Travis is viable at the moment.  Since we already have a bot that tests PRs, I'm going to close this as "working as intended".  Thanks!

**Closed** 2016-05-03 18:43 UTC
Labels: working as intended
