### ISSUE TITLE
Bad video and audio when playing DASH manifest with Playready DRM in MS Edge with mixed encrypted and unencrypted content

### ISSUE THREAD

**Issue by MilosRasic** [google/shaka-player#2974] opened 2020-11-09 18:42 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**What version of Shaka Player are you using?**

3.0.5

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `master`?**

yes

**Are you using the demo app or your own custom app?**

custom app

**If custom app, can you reproduce the issue using our demo app?**

yes

**What browser and OS are you using?**

tried in 3 Microsoft Edge environments:

* Chromium Edge on Windows 10
* Windows 10 PWA
* Xbox One PWA

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

Xbox One S, firmware 10.0.19041.4981

**What are the manifest and license server URIs?**

**manifest:** https://912c104801394c9cab5b8dde2613131f.mediatailor.us-east-1.amazonaws.com/v1/dash/7ffc6ab8a63f5ec1ed3ec78d43a51f07b54ada9e/AVOD/506793/dash/83ee997d-bef1-4221-b1d8-dc50590abb18/506793.mpd?ads.supplyId=1611&ads.w=1920&ads.h=1080&ads.pod_max_dur=90&ads.app_name=Redbox&ads.did=7b48357c-8fea-403b-9925-7c086944e2a5&ads.content_id=506793&ads.device_make=Xbox&ads.device_model=Unknown&ads.ic=IAB1&ads.content_title=The%20Brothers%20Bloom&ads.titleId=506793&ads.content_genre=Comedy&ads.studio_name=Summit&ads.content_rating=PG-13&ads.content_length=1:53&ads.url=https%3A%2F%2Fwww.redbox.com%2Fstream-free-live-tv

**license server:** https://digital.redbox.com/gapi/ondemand/latest/PlayReadyRightsManager.asmx

**custom license request header**

licenserequesttoken: eyJDb250ZW50SWQiOiI4M2VlOTk3ZC1iZWYxLTQyMjEtYjFkOC1kYzUwNTkwYWJiMTgiLCJQcm9kdWN0SWQiOiI1MDY3OTMiLCJWYWxpZFVudGlsIjoiMjAyMC0xMS0wOVQyMTo0NjozMy42NzgyNjYyKzAwOjAwIiwiUGxheWJhY2tNb2RlIjowLCJQdXJjaGFzZVR5cGUiOjAsIkRybVByb3ZpZGVyIjoiQnV5RHJtIn0.FlB6jyzyMR5mcvhUg3JdLwXlPdeCtL6s1oZXAAKHTjiuSeWQTgH258PN7gaH8DLqhTUoEYXX3fJ7hzzXGvvV9fUTgizSczjgd2ZUpG62AeXkmcSpj4KTuoNA4eWXFbp16FeB0oMuVBh7q14pquBH9T_FE3seWV7WIUuELmU9erbX5wrvhzn9rvA6F3gn8vwWaTGykS-BGJb4KAB9aZcJJydw2-vLUQNZzLm_lufOjFFUxrj0fcwuOkBE7VO2nFI2NPWpwoQFbB39guexCIUIpOy5iveVqvPWz2f7Bxgenl4ZyWf22CcLiuMhyzGSSFGCIMq44gQT0z6a0N16OVNyZQ

Not sure if these change for free content so I'll also email a link to our Xbox PWA which can also be opened in a browser normally.

**What did you do?**

Play a SSAI DASH manifest with mixed encrypted (movies) and unencrypted (ads) periods using Playready DRM in Microsoft Edge environment.

**What did you expect to happen?**

Decryption key is acquired and both movie and ads play correctly.

**What actually happened?**

Decryption key is acquired, ads are played correctly, but video and audio are garbled, as if content wasn't decrypted or was decrypted with a wrong key.

![image](https://user-images.githubusercontent.com/533052/98582407-38b0a580-22c3-11eb-84bd-0d89b47ae63f.png)

The same manifest works correctly with Playready on all other platforms we could try: Roku native player and Shaka Player on Vizio and Tizen TVs.

Some titles for which ads were left out by mistake are working fine, which points to the mix of encrypted and unencrypted content being the source of the problem.

**Comment by MilosRasic** [comment] 2020-11-10 12:39
Confirmed it's working fine with dash.js so this is definitely a Shaka Player problem:
https://rbxmilosttest.s3.amazonaws.com/index.html

Also confirmed licenserequesttoken does changed and the info I posted above is no longer valid. I've emailed the URL to our Xbox PWA and would be happy to deploy a custom build with a custom build of Shaka Player to assist with testing if we don't end up fixing this internally.

**Comment by TheModMaker** [comment] 2020-11-11 00:01
As you commented, this is probably a duplicate of #2759.  This error is likely a problem with the platform.  The reason it works in DASH.js is they tear down the whole media pipeline between each Period, so they don't see this problem.  We don't do that since it is really jarring and looks bad.  But that issue seemed to have some workaround so we can discuss there.

**Closed by TheModMaker** 2020-11-11 00:01 UTC
Labels: needs triage
