### ISSUE TITLE
Jagged audio/video at live edge causes the player to buffer indefinitely while starting download from the start of presentation.

### ISSUE THREAD

**Issue by duggaraju** [google/shaka-player#3417] opened 2021-05-18 22:15 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

3.1.0
**Can you reproduce the issue with our latest release version?**

yes
**Can you reproduce the issue with the latest code from `master`?**

yes
**Are you using the demo app or your own custom app?**

cusotm app
**If custom app, can you reproduce the issue using our demo app?**

yes
**What browser and OS are you using?**

Chrome, Windows
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Just load a manifest where one of stream is slightly behind the other.

**What did you expect to happen?**
The player plays from the live edge.

**What actually happened?**

The player goes in to buffering state and starts downloading all the fragments from the start of the manifest.  With large DVR window that can take a long time.

If the calculated live presentation time is greater than last index of one of the stream then

The logic in segment_index.js :
  getIteratorForTime(time) {
    let index = this.find(time);
    if (index == null) {
      index = -1;
    } else {
      index--;
    }
    // +1 so we can get the element we'll eventually point to so we can see if
    // we need to use a partial segment index.
    const ref = this.get(index + 1);

    let partialSegmentIndex = -1;

If it can't find the time. it sets index to =-1 and then starts downloading from index +1 (0).   If the audio/video do not align it would be better to fail or stop playing then going to buffering state and start downloading every single fragment from start.

**Comment by TheModMaker** [comment] 2021-06-28 17:53
Closing as a duplicate of #3393.

**Closed by TheModMaker** 2021-06-28 17:53 UTC
Labels: needs triage
