### ISSUE TITLE
How to fall back to other variant when segment unavailable (404)?

### ISSUE THREAD

**Issue by jonas-livesporttv** [google/shaka-player#3835] opened 2022-01-08 19:58 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.1

**Please ask your question**
I'm using HLS with multiple variant playlists. It can happen that certain segments of one variant become unavailable (return 404). Other variants are just fine and can be accessed with no problems. But observed behavior is that Shaka retries downloading the failed segment couple of times and then fails completely. Is there a way to fall back to a variant where the requested segment is available (= force the ABR mechanism to select a different variant)?

**Comment by avelad** [comment] 2022-01-10 07:42
There is an improvement to do it: https://github.com/google/shaka-player/issues/2541

**Comment by joeyparrish** [comment] 2022-01-10 17:00
Thanks, @avelad.  Closing as a duplicate of #2541.

**Closed by joeyparrish** 2022-01-10 17:00 UTC
Labels: type: question
