### ISSUE TITLE
Start playing live stream with certain offset from edge

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-player#1306] opened 2018-02-15 18:40 UTC
Hello,

is there a way to start playing the video for example 3600 seconds behind the live edge? I know there is the `player.load(manifestUri, opt_startTime)` method but the `opt_startTime` would have to be offset from the manifest start. But in our case, we can never know what is the exact length of the captured timeshift, we just know that we want to play live edge - 3600 seconds. 

Until now, I was using player.load(manifest) and then seek back using `video.currentTime = video.currentTime - liveOffset` in `video.ontimeupdate` event. It works however the downside is that the player first loads the live edge and only then it seeks (the customer sees the live edge, then buffering and only then the desired video).

Is there a way to start playing immediately from the offset that we need?

Thank you

**Comment by TheModMaker** [comment] 2018-02-15 19:24
Not yet, but this is a duplicate of #1178.

**Closed by TheModMaker** 2018-02-15 19:24 UTC
