### ISSUE TITLE
DASH MPD file can not be retrieve from CDN due to added clock parameter in queryString &_=Date.now()

### ISSUE THREAD

**Issue by edouardbe** [google/shaka-player#238] opened 2015-11-30 14:09 UTC
DASH MPD file can not be retrieve from CDN due to added clock parameter in queryString &_=Date.now()

Hi,

When the player is requesting the MPD file through a CDN, the added on-the-fly clock-time parameter in the queryString throws an error. 
I assume we have a specific configuration with the CDN which clearly rejects all calls with modified urls. We have to put secure tokens to protect our urls and the non-expected and added clock-time parameter is totally inconsistent with our requierements.

So I'm looking for a workaroud to not add the clock-time parameter.

I had a look on the source code : 
- ajax_request.js, lines 249-250
if ((this.estimator && !this.estimator.supportsCaching()) ||
      this.parameters.synchronizeClock) {

- and mpd_request.js, line 50, hard coded
 this.parameters_.synchronizeClock = true;

it seems there is no way to disable it programmatically.

Please, could you add a way to disable/enable the synchronizeClock o nthe mpd_request.js file?

By the way, we don only onDemand stream.

Thanks a lot

Regards,

Edouard

**Comment by joeyparrish** [comment] 2015-11-30 17:03
Thanks, Edouard.  This appears to be a duplicate of #235.  Please see the discussion there.

**Closed** 2015-11-30 17:03 UTC
Labels: duplicate

**Comment by edouardbe** [comment] 2015-12-01 10:34
Hi Joey,
Yes, it's a duplicate. Thanks for your attention.
Regards,
Edouard
