### ISSUE TITLE
Support for scrub bar with thumbnail images

### ISSUE THREAD

**Issue by aparnarevu** [google/shaka-player#3040] opened 2020-12-10 18:21 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.16

**Please ask your question**
We have the requirement to show the thumbnails while seeking or forward and backward button clicks on the player while casting but it's now showing on the sender app(iOS/Android). We're sending the below manifest file for the thumbnails.

        <AdaptationSet contentType="image" mimeType="image/jpeg">
            <Representation bandwidth="6892" height="72" width="128">
                <SegmentTemplate duration="368640" media="$Number%08X$.jpg?pbs=1563ac8fe0064e699952d257f6181240&amp;drm=1&amp;cloud=aws" startNumber="0" timescale="90000" />
                <BaseURL>https://url/</BaseURL>
                <EssentialProperty schemeIdUri="http://dashif.org/guidelines/thumbnail_tile" value="1x1" />
            </Representation>
            <Representation bandwidth="18774" height="144" id="upl256" width="256">
                <SegmentTemplate duration="368640" media="$RepresentationID$$Number%08X$.jpg?pbs=1563ac8fe0064e699952d257f6181240&amp;drm=1&amp;cloud=aws" startNumber="0" timescale="90000" />
                <BaseURL>https://url/</BaseURL>
                <EssentialProperty schemeIdUri="http://dashif.org/guidelines/thumbnail_tile" value="1x1" />
            </Representation>
        </AdaptationSet>

Is that version has support for the thumbnails?

**Comment by TheModMaker** [comment] 2020-12-10 18:25
We don't support thumbnail tracks, see #559.

**Comment by joeyparrish** [comment] 2020-12-10 18:29
To clarify, we don't support thumbnail tracks _yet_, and they are on our [roadmap](https://github.com/google/shaka-player/blob/master/roadmap.md).  We have no timeline for implementation because of a lack of resources, so we would be happy to discuss designs and accept PRs for thumbnails.

Thanks!

**Comment by joeyparrish** [comment] 2020-12-10 18:30
Closing as a duplicate of #559, which you can subscribe to or continue the discussion there.  Thanks!

**Closed by joeyparrish** 2020-12-10 18:30 UTC
Labels: duplicate
