### ISSUE TITLE
isTypeSupported always returning false in Windows 8.1 / IE11

### ISSUE THREAD

**Issue by rob-vualto** [google/shaka-player#617] opened 2016-12-02 16:23 UTC
I am unable to play *any* PlayReady encrypted content in Win 8.1 / IE11.
The `isTypeSupported` method on `MSMediaKeys` is returning false no matter what is passed.

For example:
`var audioResultOne = window['MSMediaKeys'].isTypeSupported("com.microsoft.playready", "audio/mp4");`
`var videoResultTwo = window['MSMediaKeys'].isTypeSupported("com.microsoft.playready", "video/mp4");`
`var audioResultOne = window['MSMediaKeys'].isTypeSupported("com.microsoft.playready", "audio/mp4; codecs=\"mp4a.40.2\"");`
`var videoResultTwo = window['MSMediaKeys'].isTypeSupported("com.microsoft.playready", "video/mp4; codecs=\"avc1.640015\"");`
All return false.

I have recreated this in shaka v1.6.5, v2.0.1-debug and dash.js v2.3.0 with multiple reference content including the Microsoft CENC content on the dash.js demo and "assets/oops_cenc-20121114-signedlicenseurl-manifest.mpd".

shaka v1.6.5 gives this error:
`Unsupported keySystem`

shaka v2.0.1-debug gives:
`Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()`

dash.js returns the following error:
`[89039] DRM: KeySystem Access Denied! -- Key system access denied! -- No valid audio/video content configurations detected!`

Does anyone know if Microsoft have changed something in IE? I cannot find any references to this issue.

**Comment by rob-vualto** [comment] 2016-12-02 16:24
relevant issue also on dash.js github: https://github.com/Dash-Industry-Forum/dash.js/issues/1676

**Comment by joeyparrish** [comment] 2016-12-02 19:39
I've got a Windows 8.1 box with IE 11 version `11.0.9600.17239`, update version `11.0.11`, and I can't reproduce your results:

```js
MSMediaKeys.isTypeSupported('com.microsoft.playready');
MSMediaKeys.isTypeSupported('com.microsoft.playready', 'video/mp4');
```

Both return true.  Have you asked for support from Microsoft?

**Comment by rob-vualto** [comment] 2016-12-05 10:22
@joeyparrish Thanks for testing. Sorry I should have put IE versions on the original comment. 
I am using IE 11 version `11.0.9600.18525`, update version `11.0.37`.

I have not asked Microsoft for support. Do you have a suggested place to raise a ticket with them?

**Comment by rob-vualto** [comment] 2016-12-05 10:57
@joeyparrish I have raised a ticket on the Microsoft Connect portal: https://connect.microsoft.com/playready/feedback/details/3114305

**Comment by joeyparrish** [comment] 2016-12-05 23:16
Looks like I do not have permission to view that Microsoft ticket.  In any case, since we can't reproduce your results and there isn't anything obviously wrong with Shaka in this regard, I'm going to close this ticket.  If you get any feedback from Microsoft that points back in our direction, let us know and we can reopen to investigate.  Thanks!

**Closed by joeyparrish** 2016-12-05 23:16 UTC
Labels: unable to reproduce
