### ISSUE TITLE
Error importing with CommonJS

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2549] opened 2020-05-05 07:03 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** master as of 2020-05-05

**Can you reproduce the issue with our latest release version?** No, because v2.5 doesn't the new compiler

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Custom

**If custom app, can you reproduce the issue using our demo app?**  No due Demo app is not using require (CommonJS)

**What browser and OS are you using?** Any

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Does not apply

**What did you do?**

Something like:
const shaka = require('../shaka-player/dist/shaka-player.compiled.js');
console.log(shaka.Player.version);

**What did you expect to happen?**
Shaka version is shown

**What actually happened?**

shaka.Player is undefined

**Comment by avelad** [comment] 2020-05-05 10:57
Note: in 2.5.x branch the problem does not happen.

**Comment by joeyparrish** [comment] 2020-05-05 16:30
I am not able to reproduce using "require" in nodejs, and our integration tests use https://github.com/requirejs/cajon, and those are passing, too.

Here's the exact code I ran in nodejs from the shaka-player working directory with the latest `master:

```js
const shaka = require('./dist/shaka-player.compiled.js');
console.log(shaka.Player.version);
```

What am I doing differently from you?  Are you using a specific module loader I should try?

**Comment by joeyparrish** [comment] 2020-05-05 16:40
I hadn't rebuilt the latest, actually.  I am able to reproduce now.

**Comment by joeyparrish** [comment] 2020-05-05 20:04
The commit which broke the module import was 1076b784658883aa2525a37dca209838db0f79fd, "Unfork Closure base and update the compiler", but the issue seems to stem from this bit of code in an external polyfill:

```js
// Support for CommonJS and AMD module formats.
/** @suppress {undefinedVars} */
(() => {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = EncryptionSchemePolyfills;
  }
})();
```

https://github.com/google/eme-encryption-scheme-polyfill/blob/d9c1e681d2bd1a5beb32072d12402270169e7550/index.js#L539-L545

If I edit the compiled bundle and remove the corresponding snippet, the issue disappears.

I don't know yet how the compiler upgrade has influenced the output of that bit of code, nor have I figured out why it's breaking things.

**Comment by joeyparrish** [comment] 2020-05-05 20:34
The new compiler outputs this for the export code in the polyfill:

```js
"undefined"!==typeof module&&module.exports&&(module.exports=Ar);
```

The old compiler output this for the same code:

```js
"undefined"!==typeof module&&module.Ld&&(module.Ld=vr);
```

So the fact that it didn't break with the old compiler seems to be because of a compiler bug where "module.exports" was renamed to "module.Ld".

**Comment by joeyparrish** [comment] 2020-05-05 20:46
Looks like it can be fixed by hiding "module" from the inner part of the bundle, preventing the polyfill's direct export from taking place.

**Comment by avelad** [comment] 2020-05-06 11:26
It works now but `shaka.polyfill` is not exported

**Comment by joeyparrish** [comment] 2020-05-06 23:47
This might be another artifact of the compiler upgrade.  The new one no longer

**Comment by joeyparrish** [comment] 2020-05-06 23:47
This might be another artifact of the compiler upgrade. The new one no longer lets us get away with exporting a class member without exporting the class itself.  This sounds like an aspect of that.  We'll look into it.

**Closed** 2020-05-13 20:54 UTC
Labels: bug
