### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by dakom** [google/shaka-player#770] opened 2017-04-30 14:24 UTC
The docs say to just run `./build/all.py` in order to compile a build, but `npm install` is required first afaik - or at least doing that fixed an error I got (something like unable to find node_modules/.last_update)

**Comment by TheModMaker** [comment] 2017-05-01 22:12
I cannot reproduce any error.  On a clean clone, running `./build/all.py` runs successfully for me.  To help discover the issue, please answer the following questions:

Have you tried with the latest `master`?
What platform are you running on?
What are the steps to reproduce?
What exactly is the error?

**Comment by joeyparrish** [comment] 2017-05-19 23:40
Since there has been no reply in over two weeks, I'm going to close this issue.  @dakom, we can reopen any time if you still need help with this.

**Closed by joeyparrish** 2017-05-19 23:40 UTC
Labels: question

**Comment by dakom** [comment] 2017-05-21 06:29
Sorry I missed this... yeah feel free to close, was a super minor point anyway (how far back do we go... need to install an OS before running the build script too :P)

Thanks!
