### ISSUE TITLE
Embedded Captions not displaying as expected on Live Stream in 2.5.6

### ISSUE THREAD

**Issue by murrumbidgee63** [google/shaka-player#2256] opened 2019-11-27 00:04 UTC
We have a live stream with captions in the manifest of the stream:
Example: https://ctv.iview.abc.net.au/video/IV1512H001S00
We are listening for the 'texttrackvisibility' event and call 'setCaptionsVisibility but, we can't get the captions to display! Any suggestions would be appreciated?

**Comment by theodab** [comment] 2019-11-27 00:38
That link directs me to a loading screen, and then a blank screen. I don't see any video playing, nor does the network tab show any record of a manifest being loaded. One of the files loaded does contain an error message saying that content is unavailable outside of Australia, so that might be the problem?
Anyway, I'm not sure what you meant by calling `setCaptionsVisibility`; that's not a function in Shaka Player. Did you mean `setTextTrackVisibility`? That shouldn't require waiting for a `texttrackvisibility` event, either; if you call `setTextTrackVisibility(true)` before text tracks are loaded, it should turn on text tracks by the time some tracks have loaded.
Can you see captions if you use our [UI layer](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-ui.html)? If they aren't showing up even then, it might be a problem with your content instead.

**Comment by stuartflanagan** [comment] 2019-11-27 05:34
I have discovered something interesting with this.
We are using the NPM version of the library. When using the CDN hosted version this works as expected.
Using the NPM version enabling captions does start loading the text track but the captions are not displayed.
Are there any known issues / differences between the hosted lib and the NPM lib?

**Comment by stuartflanagan** [comment] 2019-11-27 05:39
OK just downgraded our NPM version from `2.5.6` to `2.5.5` and captions have returned.

This might need to be set to a bug with 2.5.6?

**Comment by stuartflanagan** [comment] 2019-12-02 21:38
@murrumbidgee63 Hi just wondering if we should raise a separate issue or can we convert this issue to a bug?
We cannot upgrade to version 2.5.6 due to this.

**Comment by joeyparrish** [comment] 2019-12-02 22:17
Converted to a bug.  Sorry for the delay!  We will investigate.  Thanks!

**Comment by theodab** [comment] 2019-12-02 23:34
Could you please provide some form of reproduction steps for your issue? The link you provided does not play any sort of video for me.

**Comment by stuartflanagan** [comment] 2019-12-09 03:07
That will most likely be due to Geo blocking.
Can you confirm if you can play this URL please? This stream is not geoblocked.
https://ctv.iview.abc.net.au/video/NS1413V001S00

**Comment by theodab** [comment] 2019-12-09 20:01
That stream plays for me, yes.

**Comment by stuartflanagan** [comment] 2019-12-20 01:46
Just checked this issue on 2.5.7 which was released today. Unfortunately it is still an issue.
Embedded captions display fine for live stream in 2.5.5 but do not display in 2.5.6 or 2.5.7

**Comment by joeyparrish** [comment] 2019-12-20 18:36
@stuartflanagan, we never closed the issue or claimed it fixed, so this is to be expected.  We'll try to get it fixed soon, but a lot of us are off work for the winter holidays right now.

**Comment by madsva** [comment] 2020-01-13 10:28
Seeing this issue as well - also on Chromecast.

**Comment by michellezhuogg** [comment] 2020-01-27 19:10
Hello @madsva ,

Could you please check if https://ctv.iview.abc.net.au/video/NS1413V001S00 is still valid for us to test with? Or, could you please test again to see if you can still see this issue with Shaka version 2.5.8? Thank you!

**Comment by madsva** [comment] 2020-01-27 20:57
Hi @michellezhuogg 

I'm not the one who posted the url, so can't tell, sorry. I posted a similar issue, which seems to be fixed in the latest master: https://github.com/google/shaka-player/issues/2338

Best regards,
Mads

**Comment by joeyparrish** [comment] 2020-01-27 21:18
@murrumbidgee63, can you please check if this issue is still reproducible for you with our latest release, v2.5.8?  If not, can you please provide a manifest URI and license server URI (if needed) so we can reproduce the issue?

**Closed** 2020-02-03 21:36 UTC
Labels: bug, waiting on response

**Comment by DhouhaBchir** [comment] 2020-02-19 14:53
> Reverting to Shaka 2.5.5 in CAF

Hi @madsva, i have the same issue,
Can you please tell me how to revert to Shaka 2.5.5 in CAF ?

Best regards.

**Comment by DhouhaBchir** [comment] 2020-02-19 14:54
> Reverting to Shaka 2.5.5 in CAF

Hi @madsva, i have the same issue,
Can you please tell me how to revert to Shaka 2.5.5 in CAF ?

Best regards.
