### ISSUE TITLE
Switching text languages mid-playback clears buffer and remains with old languages until next period

### ISSUE THREAD

**Issue by salmoro** [google/shaka-player#1774] opened 2019-01-22 09:30 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.0-beta2 (also applicable to 2.4.5)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows 10 chrome 73 (applicable to other OSs as well)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8

**What did you do?**
1. Load & start playing (in demo app).
2. Turn on captions.
3. See captions appear on screen.
4. Switch text language.

**What did you expect to happen?**
1. Video should continue playing.
2. Buffered video portions should remain.
3. Newly selected language should appear at next caption display.

**What actually happened?**
1. Video stalls for a bit (until re-buffered).
2. Buffered video portion clears.
3. Previous languages continues to appear in captions and selected one does not.

**Comment by ismena** [comment] 2019-01-22 18:32
Hi @salmoro 
I'm having trouble with the repro. Do you see this on our [demo page](https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8;lang=en-US;build=uncompiled) or the [nightly build](https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8;lang=en-US;build=uncompiled)? Do the links have the correct asset? (It shouldn't matter, but still).

**Comment by salmoro** [comment] 2019-01-23 10:45
@ismena Sorry. I too am having trouble reproducing with the above content (even though I'm pretty sure I was yesterday). On private content I'm able to reproduced consistently. Can I PM you a link to private content?

**Comment by ismena** [comment] 2019-01-23 16:58
Yes! Please send it to shaka-player-issues@google.com (mention the issue # in the subject) and we'll take a look.
Please note that for protected content we will need drm information.

**Comment by michellezhuogg** [comment] 2019-03-19 22:21
Hello @salmoro , I am seeing 'Invalid Token' from the link you sent us via email. Is your content still available for testing?

**Comment by salmoro** [comment] 2019-03-25 14:15
@michellezhuogg Sorry about that. We've removed the authorization requirements for that link.

**Comment by joeyparrish** [comment] 2019-05-07 22:15
@salmoro, I don't see any subtitles on this content.  Several text languages show up in the menu, but I have yet to see any cues after a few minutes of playback.  So I'm unable to reproduce this issue.

**Comment by joeyparrish** [comment] 2019-05-07 22:16
If this is still an issue in the latest code, please provide instructions on how to reproduce (specific languages and timestamps may help), and we will take another look.

**Comment by salmoro** [comment] 2019-05-20 10:13
@joeyparrish I've just emailed a new link of our private content to shaka-player-issues@google.com (titled _Issue #1774_).

Steps to reproduce:

1. Open Shaka demo app https://shaka-player-demo.appspot.com (v2.5.0 -uncompiled).
2. Select "Custom Content" on the top bar and add the manifest URL (provided in email).
3. Begin playing the content.
4. Jump to about 1:30 (where subtitles exist).
5.  Click on the 3-dot menu on the bottom right of the player and select Captions->English and notice the English captions appear on the the screen.
6. Click again on the menu and select Captions->Espanol and notice how the English captions still remain.
7. Skip forward to 12:30 (new period) and notice how the Spanish Captions are now appearing on the screen.

**Comment by joeyparrish** [comment] 2019-05-20 13:25
Thanks!  I can confirm this bug now in v2.5.0.

Notes:
 - When seeking to time 90, there is an exception when the UI tries to update the audio language list.  `TypeError: Cannot read property 'language' of undefined` because `selectedTrack` is undefined.
 - When selecting the Spanish subtitles, the console shows many failed assertions with `Inconsistent active text stream`

**Comment by joeyparrish** [comment] 2019-05-20 13:26
This bug and all of the symptoms I documented above can still be seen in the nightly build.

**Comment by ismena** [comment] 2019-06-18 23:12
Hi @salmoro 
Sorry for the delay. The main problem should be now fixed in master.
We're not closing the issue just yet as I'm still seeing a few weird things with this content:
- The UI exception @joeyparrish mentioned is still there though unrelated to the subtitles
- Not all the subtitle languages are displayed when selected.

We'll need to look into this further.

**Comment by ismena** [comment] 2019-06-20 20:59
@salmoro the content is no longer available on the server. If you're interested in pursuing this issue further, please let us know by providing an updated manifest!

**Comment by salmoro** [comment] 2019-06-23 19:16
@ismena Sorry about that. Just sent you a new link via email. TY

**Comment by ismena** [comment] 2019-06-24 20:07
Got the link!
Changing subtitles works on latest master and our nightly build.
The only two languages missing are "hu" and "pt", and their vtt files are empty (don't actually provide any subtitles).

Please try the new master and let me know if you have any questions :)

**Comment by TheModMaker** [comment] 2019-07-29 18:10
I also cannot reproduce any error.  If this is still an issue for you or if you have further questions, you can ask us to reopen or have the bot reopen it by including @shaka-bot reopen in a comment.

**Closed by TheModMaker** 2019-07-29 18:10 UTC
Labels: bug
