### ISSUE TITLE
"Unhandled Promise Rejection: AbortError: Fetch is aborted" on Safari

### ISSUE THREAD

**Issue by hedgepigdaniel** [google/shaka-player#3020] opened 2020-12-02 05:31 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
3.0.1

**Are you using the demo app or your own custom app?**
A custom app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari 14 / OSX

**What did you do?**
1. Load MP4 HLS stream in Safari 14 OSX
1. Destroy the player while it is still in the initial bufferring process

**What did you expect to happen?**
No errors

**What actually happened?**
There is an unhandled promise rejection error: "AbortError: fetch was aborted"

This seems to be caused by the [stub polyfill for `MediaSource.abort()` used for Safari](https://github.com/google/shaka-player/blob/56bb045ff68325d6b9de7cb3d56265ce3162f164/lib/polyfill/mediasource.js#L65) - removing it fixes the problem.

It's especially unfortunate because the error is not obviously linked to shaka-player.

**Comment by joeyparrish** [comment] 2021-02-18 19:50
@hedgepigdaniel, can you still reproduce this issue on the latest release v3.0.8?  We've fixed some uncaught exceptions since v3.0.1.

I will also double-check the still-open WebKit but associated with that abort stub, to see if it's still an issue with Safari 14: https://bugs.webkit.org/show_bug.cgi?id=165342

Thanks!

**Comment by joeyparrish** [comment] 2021-02-18 19:59
Just confirmed that the WebKit bug is still present in Safari 14.0.2, so removing the abort stub is not an option for us.  Sorry!

That said, it's highly possible that the issue has been resolved in v3.0.8 (in https://github.com/google/shaka-player/commit/6994da412e3f2bdc0dec6d1962ab2c02dcf32c9f).  Can you please try with the updated release?

**Closed** 2021-02-25 20:06 UTC
Labels: needs triage, waiting on response

**Comment by littlespex** [comment] 2022-06-03 18:26
@joeyparrish I still see this error in Shaka v3.3.2, Safari 15.5
