### ISSUE TITLE
Live stream fails with "cannot find segment" console message

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#1117] opened 2017-11-09 20:34 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**: 2.2.5

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: both

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**: chrome on Mac but happens also on other browsers and OSs

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
Sent in the mail

**What did you do?**
pasted the video URL and press play

**What did you expect to happen?**
playback starts

**What actually happened?**
endless spinner, in console can see "cannot find segment" log output

**Comment by itaykinnrot** [comment] 2017-11-10 06:03
Not sure if it’s help but I’ll f I add this to the MPD - suggestedPresentationDelay to 30s it start to play but stuck after 10-20 sec

Thanks!

**Comment by vaage** [comment] 2017-11-13 19:09
@OrenMe In your email you mention that this content can be played by other players - I tried to play it with the players you mentioned, and it does not play. Are you sure that this content is suppose to be valid?

**Comment by OrenMe** [comment] 2017-11-13 19:23
@vaage yes, I just played it on dash.js [nightly](http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html) and on [bitmovin test page](https://bitmovin.com/hls-mpeg-dash-test-player/)(you will need to enable mix content as the stream is http and page is https)

**Comment by vaage** [comment] 2017-11-13 19:35
Thanks @OrenMe, I was able to reproduce it playing on other players and not on ours. I have added it to our bug queue and we should be able to get to be soon.

**Comment by OrenMe** [comment] 2017-11-14 20:48
Hi @vaage thanks for the update, let me know if you require additional info.

**Comment by OrenMe** [comment] 2017-11-16 10:24
Hi @vaage @joeyparrish please see this issue in ExoPlayer: https://github.com/google/ExoPlayer/issues/3457
It relates to this same stream.
Particularly this: https://github.com/google/ExoPlayer/issues/3457#issuecomment-344727212 and this: https://github.com/google/ExoPlayer/issues/3457#issuecomment-344873473

**Comment by OrenMe** [comment] 2017-11-21 10:20
Hi @vaage any update on this? thanks.

**Comment by TheModMaker** [comment] 2017-11-21 17:44
As discussed in the ExoPlayer issue, your value of `Period@start` is changing.  This is something we don't support and trying to support would probably be difficult.  We will probably wait until the discussion on the IOP (Dash-Industry-Forum/DASH-IF-IOP#160) is done to see whether this should be a supported use case.  But it may be difficult to support this use case, especially since there are better ways to do the same thing.

**Comment by itaykinnrot** [comment] 2017-11-22 14:32
Now we have the same stream with Period@start that is not changing - works on ExoPlayer but not on shaka :-( please check.
Thanks!

**Comment by joeyparrish** [comment] 2017-11-22 20:17
This may be related to #1105.  I have a fix for that in review now, so I will check the fix against this stream, as well.

**Comment by joeyparrish** [comment] 2017-11-22 21:24
Actually, this seems to be unrelated to #1105.

What I see in a manifest I just fetched is:

availabilityStartTime="2017-11-22T20:14:27.659Z"
fetch time 2017-11-22 20:21:56 UTC
Time since AST = 7 minutes 29 seconds
timeShiftBufferDepth="PT30S"
Oldest segment time = 14214923537, timescale 90000 = 157943.6 seconds = 43 hours, 52 minutes, 23 seconds
presentation time offset = 0

So there are no segments within the availability window (7:15 to 7:30).  All segments are way past the end of the window.

**Comment by itaykinnrot** [comment] 2017-11-22 21:57
The stream is playable on other players

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joeyparrish** [comment] 2017-11-22 22:16
I'm sure it is, but that doesn't mean the content is correctly described in the manifest.

If we ignored availabilityStartTime, we would be able to play this.  But the manifest is not self-consistent, and this is not something we are going to support at this time.

After #999, we would no longer rely on availabilityStartTime, which would enable us not only to better deal with drift, but to play broken content such as this.

Because the segment descriptions do not agree with the rest of the manifest, this is broken content, and the encoder/packager that created it should be fixed.

**Closed** 2018-01-12 00:39 UTC
Labels: bad content
