### ISSUE TITLE
Dropping many frames on a low-end machine

### ISSUE THREAD

**Issue by hyurtseven81** [google/shaka-player#632] opened 2016-12-19 22:22 UTC
- What version of Shaka Player are you using?
2.0.2
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
Both are same for the problem
  - If custom app, can you reproduce the issue using our demo app?
Yes

- What did you do?
Drm encrypted video content with multiple audio and 6 bitrates.
  - What content did you load?
Drm encrypted video content with multiple audio and 6 bitrates
    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?

- What did you expect to happen?
It should be playable smoothly

- What actually happened?
The player can buffer without problems and it has enough buffer to play but in every 5-15 seconds it pauses 0.1 - 1 seconds on low-end machine.

Core 2 duo 2 Ghz
2 Gb Ram
Windows 8
Chrome 55 with or without hardware accelerated.

There no problem on high-end machines.

Thank you.

**Comment by joeyparrish** [comment] 2016-12-20 00:39
@hyurtseven81, can you please collect some additional data for us?  In the demo app, reproduce the problem.  Then, open the JS console and run this:

```js
JSON.stringify(shakaDemo.localPlayer_.getStats());
```

Then copy the resulting string and paste it here for us.  That will help us understand what the Player and browser were doing when the problem occurred.  Thanks!

**Comment by hyurtseven81** [comment] 2016-12-20 17:26
Hi this is from shaka player demo:

{"width":1024,"height":426,"streamBandwidth":847976,"decodedFrames":2421,"droppedFrames":277,"estimatedBandwidth":1354235.0455966967,"playTime":100.9060001373291,"bufferingTime":10.399999856948853,"switchHistory":[{"timestamp":1482257692.107,"id":18,"type":"audio","fromAdaptation":true},{"timestamp":1482257692.107,"id":16,"type":"video","fromAdaptation":true},{"timestamp":1482257692.107,"id":1,"type":"text","fromAdaptation":true},{"timestamp":1482257714.235,"id":12,"type":"video","fromAdaptation":true},{"timestamp":1482257733.92,"id":15,"type":"video","fromAdaptation":true},{"timestamp":1482257750.902,"id":14,"type":"video","fromAdaptation":true},{"timestamp":1482257762.185,"id":15,"type":"video","fromAdaptation":true},{"timestamp":1482257771.055,"id":14,"type":"video","fromAdaptation":true},{"timestamp":1482257790.403,"id":15,"type":"video","fromAdaptation":true}]}

And this is from my implementation:

{"width":960,"height":540,"streamBandwidth":1928000,"decodedFrames":989,"droppedFrames":598,"estimatedBandwidth":2797661.432542304,"playTime":74.41499996185303,"bufferingTime":4.71399998664856,"switchHistory":[{"timestamp":1482257883.496,"id":1,"type":"audio","fromAdaptation":true},{"timestamp":1482257883.496,"id":5,"type":"video","fromAdaptation":true},{"timestamp":1482257892.207,"id":8,"type":"video","fromAdaptation":true},{"timestamp":1482257900.254,"id":5,"type":"video","fromAdaptation":true},{"timestamp":1482257908.544,"id":6,"type":"video","fromAdaptation":true},{"timestamp":1482257932.689,"id":7,"type":"video","fromAdaptation":true},{"timestamp":1482257940.81,"id":8,"type":"video","fromAdaptation":true},{"timestamp":1482257950.422,"id":7,"type":"video","fromAdaptation":true}]}

Thank you for your helps

**Comment by joeyparrish** [comment] 2016-12-20 19:02
It looks like the real problem is not that we enter a buffering state, but rather that the browser can't decode the content fast enough.  It is dropping a lot of frames.  In one set of stats, it dropped 277 / 2421 (11.4%), and in another it dropped 598 / 989 (60.4%).

This is not something we can control directly.  The best thing to do would be to limit the resolution chosen on low-end hardware.

If you suspect the hardware is low-end, we offer a configuration you can use to restrict the resolution:

```js
player.configure({ restrictions: { maxHeight: 480 } });
```

Or:

```js
player.configure({ restrictions: { maxPixels: 640 * 480 } });
});
```

If the limit is a known hardware limitation, we also have this API which is used to limit to 1080p on Chromecast:

```js
player.setMaxHardwareResolution(720, 480);
```

If you don't know which hardware will drop frames, the best you can do is react to dropped frames dynamically.  There are a few ways to do this.

1. You can write your own AbrManager plugin which uses dropped frames to inform adaptation decisions and blacklist resolutions that can't be decoded fast enough.
2. You can modify our default AbrManager plugin (SimplerAbrManager) to account for dropped frames and send us a PR.
3. You can periodically check `player.getStats().droppedFrames` in your application and use that info to call `player.setMaxHardwareResolution()` when a lot of frames are being dropped.

Does this help?

**Comment by hyurtseven81** [comment] 2016-12-20 19:09
Thank you for your help, i'm gonna try your resolution solution and i will share the results here.

Thank you again.

**Comment by hyurtseven81** [comment] 2016-12-20 19:40
By the way is there an optimal drop rate threshold?

**Comment by joeyparrish** [comment] 2016-12-20 19:57
We have never had enough data to determine a good threshold for dropped frames.  This is the main reason our default AbrManager does not account for dropped frames yet.  It's something we'd like to be able to offer, though.

**Comment by hyurtseven81** [comment] 2016-12-20 20:10
Thank you again, i will try to find a solution.

**Comment by ToreJuloe** [comment] 2017-01-13 09:35
I hope you don't mind me hijacking this thread.

Perhaps it would be possible to dream up some kind of benchmarking while decoding segments?
I have encountered the same problem, but we ended up throttling the bitrate for all users, while adding a settings option to the GUI to manually set the max allowed quality level.

Lacking an API in the browser to provide useful information about the hardware configuration, I've been trying to figure out another way to guess the most appropriate quality level for playback, before we start dropping frames, but I've had no success yet.

From my experience, it's the Widewine CDM that creates a significant performance overhead, so if it was at possible to do some sort of timing of the content decryption, that might be a way to go, but from what I've gathered, that information, like the chrome://media-internals, is buried to deep in the guts of the browser to be retrieved.

Last year it was widely reported that Netflix would only play 720p (3000kbps) video content in Chrome (and this is also true for Firefox), while Edge and Safari would be served 1080p (5800kbps), and this still holds true. This could indicate some known performance problems, comparatively speaking, with Widevine, but I think that browser sniffing or CDM detection as a basis for quality choice is not an ideal solution and neither is reacting to frame drops, since at the point where this is detected, the user experience has already suffered.

Have you guys already looked into this stuff or do you have any brilliant insights or ideas regarding the subject?

**Comment by joeyparrish** [comment] 2017-01-24 23:36
Sorry, I have no insight into Netflix's heuristics for this.

I think the most reasonable path forward for Shaka Player in the near term is for someone to develop an algorithm that uses dropped frames as feedback to set restriction on what resolutions we choose.  It is unfortunate that we should have to drop frames first to do this, but I see no other way with today's APIs.

There are some new APIs being developed for detecting capabilities: https://github.com/WICG/media-capabilities

The media capabilities API could, in future, tell us which resolutions/codecs/etc will play well before we play them.  In the mean time, dropped frames is all we really have.

**Comment by joeyparrish** [comment] 2017-03-20 17:28
It's been a while since anyone commented on this.  Does anyone have any experience to share regarding dropped frames as an ABR feedback mechanism?  If not, I will eventually close the issue.

**Comment by ToreJuloe** [comment] 2017-03-20 19:30
For my part, my question was answered, thank you.
I don't have any concrete experience implementing a method for observing dropped frames as an ABR signal, but I know that Dash.js has something of the sort implemented:
https://github.com/Dash-Industry-Forum/dash.js/blob/master/src/streaming/rules/abr/DroppedFramesRule.js

However, I've worked with a player based on Dash.js and it operated with a total number of lost frames during the course of the playback, which is not an ideal solution, since frame drops can also be caused by a number of different outside factors, such as resizing the browser window, even on a very fast machine. Therefore it seems to me, that such an algorithm should be able to account for temporary fluctuations in the frequency of frame drops (which should ideally be zero per second), caused by either observable user action (scrolling, resizing etc.) or actions taken outside the context of the browser.
I apologize for lacking the mathematical vocabulary to perhaps properly explain this, but I think that what I'm thinking of is calculating from a rolling window or moving average, so as not to penalize the entire playback of a movie back to lowest bitrate, because the user switched to full screen in the first couple of minutes.
Perhaps dropped frame checking could be a little more aggressive around the time when ABR switches to a better quality and larger segments are being decrypted for the first time.

**Comment by joeyparrish** [comment] 2017-03-31 20:47
@ToreJuloe, thanks.  I've filed https://github.com/google/shaka-player/issues/745 to track any efforts we make in future on using dropped frames for ABR feedback.  I'll go ahead and close this issue now.

**Closed by joeyparrish** 2017-03-31 20:47 UTC
Labels: question
