### ISSUE TITLE
Spurious TextTrack in src mode

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2516] opened 2020-04-21 09:03 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.10

**Can you reproduce the issue with our latest release version?** yes

**Can you reproduce the issue with the latest code from `master`?** yes

**Are you using the demo app or your own custom app?** Demo 

**What browser and OS are you using?**
Safari 13.1 and Chrome 81 over macOS 10.15.4

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es;textlang=es;uilang=es;asset=https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4;panel=ALL_CONTENT;panelData=HLS;build=uncompiled
 
![Captura de pantalla 2020-04-21 a las 11 01 56](https://user-images.githubusercontent.com/8983024/79847092-8913f480-83bf-11ea-86a1-8d2aeb40e3da.png)

https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=ALL_CONTENT;panelData=HLS;build=uncompiled

<img width="1438" alt="Captura de pantalla 2020-04-21 a las 10 51 26" src="https://user-images.githubusercontent.com/8983024/79846991-6681db80-83bf-11ea-84c7-8700de8e2e00.png">

**What did you do?**

Load the previous stream in src mode
See `shakaDemoMain.player_.getMediaElement().textTracks`

**What did you expect to happen?**
Only the stream textracks are showed.

**What actually happened?**

The textracks shown in the stream are not the same that UI displays. There are a spurious text track called "Shaka Player TextTrack"

**Comment by joeyparrish** [comment] 2020-04-21 16:53
This is how our `SimpleTextDisplayer` works.  It creates a single track that it owns, and inserts streamed cues into it.  It's not a great experience with the browser's built-in video controls.  If you have a custom controls UI, this is not an issue, though.  And if you use our UI, we have a `TextDisplayer` implementation that doesn't use `TextTrack` and doesn't create this problem.

So this is working as intended for the moment, but you have some options to change it:

1. Use our controls UI instead of the browser's controls
2. Use your own custom controls UI instead of the browser's controls
3. Use `shaka.ui.TextDisplayer` plugin without our complete UI, rendering text into a custom div you control
4. Use your own custom `TextDisplayer` plugin instead of `SimpleTextDisplayer`

Does this help?

**Comment by avelad** [comment] 2020-04-21 17:15
I also thought it was intentional, but I have used the UI that gives the demo app, and the error appears in the subtitle list when loaded in src mode. Why give the user an option that does not work and appears in the UI? 
I think the ideal would be not to load any `TextDisplayer` if it is in src mode. What do you think?

**Comment by joeyparrish** [comment] 2020-04-21 17:25
Oh, now I see the problem!

In src= mode, the list of text tracks is based on the video element's TextTrack API.  This makes sense for something like native HLS playback, but the TextTrack we added gets in the way.

This shouldn't happen in the demo where we're using our own UI and a non-TextTrack-based text displayer.  We'll look into it.

**Comment by joeyparrish** [comment] 2020-04-21 17:27
Easy repro link:

https://shaka-player-demo.appspot.com/demo/#audiolang=de;textlang=de;uilang=de;asset=https://storage.googleapis.com/shaka-demo-assets/heliocentrism/sun/v-0480p-0750k-vp9.webm;panel=CUSTOM%20CONTENT;build=uncompiled

Screenshot:

![Screenshot 2020-04-21 at 10 26 25](https://user-images.githubusercontent.com/6843156/79894711-b6aa6f00-83ba-11ea-81af-e256066c65b2.png)

**Comment by joeyparrish** [comment] 2020-04-21 17:46
In our demo, first the Player is constructed.  When it initializes MediaSource, `shaka.ui.TextDisplayer` gets constructed.

Then the demo calls resetConfiguration(), which resets it to `shaka.text.SimpleTextDisplayer`.  When that gets constructed, the extra text track is created.  When this gets destroyed, it leaves the `TextTrack` object alive on the `<video>` element.

Then the demo applies asset-specific configuration, which sets the displayer back to `shaka.ui.TextDisplayer`.  This happens twice, and each time a displayer is destroyed and another one created.

**Comment by joeyparrish** [comment] 2020-04-23 18:30
The fix for this caused #2523, so we are reopening this issue.

**Comment by joeyparrish** [comment] 2020-04-23 19:08
Possible alternate solutions:

1. Make the default config for the UI build refer to the UI text displayer.  This would prevent the creation of this extra track when using the UI build.  Currently, the default is always the native TextTrack-based text displayer, and the UI itself simply reconfigures that.  An app could trip over this if they use `player.resetConfiguration()`, so we should probably change this if we can.  It is complicated by the compiler, of course, since we can't check for the UI classes from a build that doesn't have them.  A compiler variable could help, similar to how we can use `if (DEBUG)` already.

2. Have `Player` filter out the specific track label used by `SimplerTextDisplayer`.

We should probably do both, in my opinion.

**Comment by avelad** [comment] 2020-04-23 19:15
In my application, I have filtered the track using the label, but I think your option 1 is the best, if both options are mixed, the solution is perfect :)

**Closed** 2020-05-05 04:16 UTC
Labels: bug
