### ISSUE TITLE
Fairplay not working

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2364] opened 2020-01-31 05:57 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
Shaka player hosted demo

**Can you reproduce the issue with our latest release version?**
I am using shaka player hosted demo. Also it happens in latest release version

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
I am using shaka hosted demo

**If custom app, can you reproduce the issue using our demo app?**
I am using shaka hosted demo

**What browser and OS are you using?**
MacOS, Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
ManifestURL: https://media.axprod.net/VTB/Makemedia/Encrypted_Cbcs/Manifest.m3u8
LicenseServerUrl:  https://drm-fairplay-licensing.axtest.net/AcquireLicense
License certofocate url: https://vtb.axinom.com/FPScert/fairplay.cer

**What did you do?**

Create custom content with shaka hosted demo and use the above manifest and license url

**What did you expect to happen?**
Video should play

**What actually happened?**
Video is not playing. Getting below error:
Shaka Error DRM.INIT_DATA_TRANSFORM_ERROR (RangeError: Malformed FairPlay init data)

I have debugged the code and found that the data-transform is happening twice. First time data-transform is success. But second time it is giving the above error

**Comment by sridhard** [comment] 2020-01-31 10:36
Hi,

In shaka.media.DrmEngine.prototype.attach, If we change listen to listenOnce in the below code, it works:

  return Promise.all([setMediaKeys, setServerCertificate]).then(() => {
    if (this.isDestroying_) { return Promise.reject(); }

    this.createOrLoad();
    if (!this.currentDrmInfo_.initData.length &&
        !this.offlineSessionIds_.length) {
      // Explicit init data for any one stream or an offline session is
      // sufficient to suppress 'encrypted' events for all streams.
      const cb = (e) =>
          this.newInitData(e.initDataType, new Uint8Array(e.initData));
      **_this.eventManager_.listenOnce(this.video_, 'encrypted', cb);_**
    }
  }).catch((error) => {
    if (this.isDestroying_) { return; }
    return Promise.reject(error);
  });

**Comment by ismena** [comment] 2020-01-31 18:14
@TheModMaker @joeyparrish 
Can I get one of you Fairplay experts to take a look, please?

**Comment by TheModMaker** [comment] 2020-02-03 18:38
Seems like a duplicate of #2214, which was closed by @joeyparrish.  What version of Safari are you using?

**Comment by michellezhuogg** [comment] 2020-02-03 19:47
We tested on Safari 13.0.4, and Mac version 10.15.2.

**Comment by sridhard** [comment] 2020-02-06 01:45
@TheModMaker I am using safari 13.0.5

**Comment by sridhard** [comment] 2020-02-07 10:26
@joeyparrish @TheModMaker @michellezhuogg any update on this issue?

**Comment by TheModMaker** [comment] 2020-02-10 20:00
Closing this as a duplicate of #2214, you can follow that for more updates.  Also note that I'm getting timeouts for the certificate URL.

**Closed by TheModMaker** 2020-02-10 20:00 UTC
Labels: needs triage
