### ISSUE TITLE
Player does not wait for vue element

### ISSUE THREAD

**Issue by francoism90** [google/shaka-player#3622] opened 2021-09-03 12:16 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
See #3155, it's the same issue.

`TypeError: can't access property "name", e is null`

**What did you expect to happen?**
Proper init onMounted.

**What actually happened?**
```
// VideoPlayer.vue
onMounted(() => load(props.model));

// UsePlayer.ts
const player = new Player(videoPlayer.value);
```

**Comment by theodab** [comment] 2021-09-30 06:49
You didn't provide any sort of code sample for us to work with. So I can't say for sure what the problem you are having is.
But I did just spend a little while diagnosing #3155, so assuming you are using a similar architecture to the demo code they posted...

In that person's demo code, they make a "data" object that contains the player. According to Vue's documentation on the data object, anything you put inside [becomes one of their reactive Proxy objects](https://v3.vuejs.org/api/options-data.html#data-2) (unless you prefix the name of the property with with `$` or `_`). So this means that Vue was converting the player instance into a Proxy object wrapping the player instance.

According to Vue's documentation on Proxy objects, nested objects inside their Proxy objects [are also converted into Proxy objects](https://v3.vuejs.org/guide/reactivity.html#proxied-objects). In my investigations, I found that this ended up converting some internal variables of the player instance into Proxy objects, which was messing up critical internal logic within the player.

I don't think this is something we can reasonably account for within Shaka Player. At best we might be able to add a more informative error, or an FAQ entry, or something.

So instead, don't store your player instance inside a data object, and it should hopefully be fine? Indeed, their documentation recommends as much:
> In data, we don't recommend to observe objects with their own stateful behavior like browser API objects and prototype properties. A good idea would be to have here just a plain object that represents component data.

**Comment by francoism90** [comment] 2021-09-30 07:39
@theodab Thanks for looking into the issue and sorry for not providing an example.

I'm testing dash.js which does seem to work/allow this:
https://github.com/francoism90/mediadb-app/blob/main/src/composables/useDash.ts

As you can see I inject the player in a `ref` object after creation which should be reactive, if I do the same thing with Shaka.js it tells me `TypeError: can't access property "name", e is null`. To me it looks like the video element cannot be found, not the player variable?

I'm I missing something else or is it indeed working as expected? :)

**Comment by theodab** [comment] 2021-09-30 09:14
Well, in #3155, the line that was actually failing was this:
https://github.com/google/shaka-player/blob/a72adca9fd62144f70da61314e785074f374427a/lib/player.js#L636
This is part of the code that is responsible for Shaka Player transitioning from one stage of the loading process to another. I found during investigation that we have some checks that are based on object equality, like this:
https://github.com/google/shaka-player/blob/a72adca9fd62144f70da61314e785074f374427a/lib/player.js#L6194
Which fail because `goingTo` has become a Proxy object, according to the developer tools, and thus is no longer equal to the non-proxy `this.loadNode_`.

I guess we could fix that by removing the object equality checks, and comparing the nodes in a different manner. However, I am not sure of the full set of changes we would need to make for Shaka Player to completely support being made into a Vue Proxy.

Admittedly, I guess this isn't strictly speaking "working as intended". It's not like we designed the player to not work as a Vue reactive object. It's just that integrating with third-party frameworks like Vue or Electron has never been a large priority for us. I'll re-tag the issue.

**Comment by joeyparrish** [comment] 2021-09-30 20:33
I believe it's best to document that you should not wrap Shaka Player in a reactive object in Vue.  I don't believe we should remove object equality checks.

Let's call this a duplicate of #3155, which we'll close with a docs update.

Quoting @theodab from https://github.com/google/shaka-player/issues/3155#issuecomment-931598183 :

> if you define Shaka Player outside of a data object (or prefix the variable name with $ or _ to make Vue not make it reactive) it loads the asset successfully.

Any objections to this resolution?

**Comment by joeyparrish** [comment] 2021-09-30 20:34
Duplicate of #3155

**Closed** 2021-10-04 21:48 UTC
Labels: status: duplicate
