### ISSUE TITLE
Minor stall on period transition

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1435] opened 2018-05-10 18:05 UTC
(Migrated from an internal report by @kqyang.)

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.7

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: yes

**Are you using the demo app or your own custom app?**: demo

**What browser and OS are you using?**: Chrome Linux

**What are the manifest and license server URIs?**:
Demo app repro URI: https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/wvtemp/kqyang/ads4/out.mpd;lang=en-US;noadaptation;debug;play;build=uncompiled

**What did you do?**
Play the first 15 seconds of the content

**What did you expect to happen?**
Smooth playback

**What actually happened?**
Stall at around 12 seconds

**Comment by theodab** [comment] 2018-05-22 17:00
A little further testing:
This happens with Chrome on Linux. It doesn't happen with any other combination of platform and browser I tested (Firefox on Linux, Chrome on Mac, Firefox on Mac, Chrome on Windows).
So it's presumably some bug with MediaSource in Chrome Linux. I guess the question is if it's something we can work around or not. More investigation will be required.

**Comment by TheModMaker** [comment] 2018-09-10 18:49
Here is some info from that internal report for outside people and if you (like me) forgot what the discussion was.

The last frame of the first Period ends 32 microseconds after the end of the Period, so the `availabilityWindowEnd` drops the last frame.  This causes a gap to appear in the buffered ranges, but the browser seems to play over it without stalling.  Because the browser doesn't fire a `waiting` event, our gap-jumping logic doesn't trigger to jump the gap.  Even though the browser plays through the gap, it stalls a few seconds later, and our stall-detection logic triggers and pushes things forward.

This has been fixed by Chrome's PTS fix, so once that isn't behind a flag, this problem will go away.  We could fix this by fudging the `appendWindowEnd` so the last frame isn't dropped.

**Comment by kqyang** [comment] 2018-09-10 21:04
> The last frame of the first Period ends 32 microseconds after the end of the Period, so the availabilityWindowEnd drops the last frame. This causes a gap to appear in the buffered ranges, but the browser seems to play over it without stalling. Because the browser doesn't fire a waiting event, our gap-jumping logic doesn't trigger to jump the gap. Even though the browser plays through the gap, it stalls a few seconds later, and our stall-detection logic triggers and pushes things forward.

There is actually no frame being dropped and adjusting `apendWindowEnd` does not help. There is a GAP in buffered range using DTS, which is what Chrome is using right now. The GAP is about ~83.3 milliseconds. The problem is gone if the buffered range uses PTS instead of DTS as there is no GAP if using PTS, i.e. if the Chrome's PTS flag is enabled.

The problem happens intermittently. It plays smoothly sometimes, and stalls for one second sometimes.

The reason for the intermittent stall is because:

- Gap jumping timer is scheduled to run every 0.25 seconds, which is larger than the gap.
- Gap jumping logic kicks in only if the current playback time is within the range [gap_start - 0.1, gap_end)
- With a gap of ~0.0833, gap jumping logic kicks in ~73.32% (0.1833 / 0.25) of the time. When gap jumping logic kicks in, player jumps over the gap successfully and results in a smooth playback.
- For the remaining ~26.68% of the time, when the gap jumping timer is scheduled to run, the current playback time has already progressed past gap_end, so the gap jumping logic does not kick in.
  - The reason why the playback time could get past gap_end is because Chrome's playback time is based on audio playback time, which continue to progress until told to stop later. (This is why we are observing a visual stall but continuous audio playback).
- Eventually after playing the audio alone with stuck screen for a few seconds, current playback time stops progressing, which triggers Shaka Player's stall handling logic. The stall handling logic manages to get the playback out of the stuck state, with a few seconds of video lost.

There are a few ways we can make this playback smooth:
- Decrease gap jumping timer frequency to be less than the duration of a typical video frame, e.g. every 0.04 seconds.
- Increase the gap jumping logic back off time so back_off + video frame duration >= gap jumping interval, e.g. set back off time to 0.22 seconds.
- Improve Chrome to force audio to stop immediately when video stops. OR expose both audio playback time and video playback time to the player.

Anyway, the root cause is that there are gaps in the content if using DTS and Chrome uses DTS in buffered range API.

In Shaka Packager, we have workarounded the problem by using EditList in v2.2, so for multi-period contents packaged using Shaka Packager v2.2 or above, the problem should not occur.

@joeyparrish Leave it to you to decide how Shaka Player wants to move forward. It'll be ok with me if you decide to just close the issue.

**Comment by kqyang** [comment] 2018-09-10 21:15
The scenario described above actually applies to all small GAPs, i.e. gap duration < gap jumping interval - gap start back_off, so another option we can do is to adjust gap start back_off for small gaps. I can prepare a CL if you are ok with this.

**Comment by joeyparrish** [comment] 2018-11-29 22:58
This turns out to be fixed by the same fix for #1597 (a fudge factor applied to the append window end)

**Closed** 2018-11-30 18:50 UTC
Labels: bug
