### ISSUE TITLE
Video does not play smoothly while playing FHD video

### ISSUE THREAD

**Issue by MegaLabs1** [google/shaka-player#269] opened 2016-01-18 15:38 UTC
Hi colleagues!
in addition to https://github.com/google/shaka-player/issues/247 we've found that PC with Google Chrome (8GB RAM, core i7)cannot play FHD video (7mbps video, 128k audio streams) smoothly. The process has little freezes which spoil the impression from watching movies. These usually begin after ~10 minutes passes. I've found that player spend ~1-5% CPU and a lot of RAM, but widevine CDM spend ~40-50% CPU and 40M RAM. Is it a Google Chrome issue, or these freezes are caused by Shaka ?

**Comment by joeyparrish** [comment] 2016-01-18 23:29
Shaka doesn't do any more work for high bitrates than for low bitrates as far as I can tell.  For high bitrates, network requests for segments take longer and decode requires more CPU time, but neither of those things happens in JavaScript or blocks JavaScript.

On desktop Chrome, I expect everything is being decoded in software.  Do you get better results on a device with a hardware decoder?

**Comment by MegaLabs1** [comment] 2016-01-19 09:24
Looks like we have problems with FullHD profiles only. I tried Android LG G4 with Chrome+Shaka and it showed exactly the same short freezes with audio and video. Otherwise, 720p profile works correct without errors (about 4mbps video, 128kbps audio). Any suggestions?

**Comment by joeyparrish** [comment] 2016-01-25 18:24
Can you share the contents of player.getStats() after one of these FHD playbacks?  That might help determine if Shaka is part of the problem.

**Comment by joeyparrish** [comment] 2016-02-27 00:27
@MegaLabs1, it's been a while since we heard from you.  Is this still a problem for you?  Can you share logs or stats with us?

**Comment by MegaLabs1** [comment] 2016-02-29 07:12
Yes it is still a problem, but we reduced maximum quality for shaka with 720p resolution.
what logs could be usefull for you?

**Comment by joeyparrish** [comment] 2016-02-29 17:49
1. Please check out the latest source from master.  We just fixed a performance regression that was introduced on Feb 1 in v1.6.3.

2. Please use an uncompiled build for playback so that we get logs.

3. Run shaka.log.setLevel(shaka.log.Level.DEBUG) to enable debug logging.

4. Play a problematic piece of content at full HD resolution.

5. After some time of observable problems (freezes, etc.), run player.getStats().

6. Send the debug logs from the JS console and the value of player.getStats() after playback problems.

Thanks!

**Comment by MegaLabs1** [comment] 2016-03-02 13:25
thanks, Joey, we'll try it in our lab.

**Comment by joeyparrish** [comment] 2016-03-29 20:51
@MegaLabs1, I haven't heard from you in a while.  Is this still an issue for you?

**Comment by MegaLabs1** [comment] 2016-03-31 12:37
Hi, @joeyparrish ! 
it is not clear, it seems we use some other build (1.6.4): 

shaka.setLevel(shaka.log.Level.DEBUG)
VM1651:2 Uncaught TypeError: Cannot read property 'Level' of undefined(…)

player.getStats()
VM1828:2 Uncaught TypeError: player.getStats is not a function(…)

what version should we use?

**Comment by joeyparrish** [comment] 2016-03-31 16:05
I think you misread the log call: `shaka.log.setLevel(shaka.log.Level.DEBUG)`

You should also be using an uncompiled version of the library to get logging.

**Comment by MegaLabs1** [comment] 2016-03-31 16:12
shaka.log.setLevel(shaka.log.Level.DEBUG)
VM2157:2 Uncaught TypeError: Cannot read property 'setLevel' of undefined(…)

bq. You should also be using an uncompiled version of the library to get logging.
i think it is the reason why we cannot get logs..

**Comment by joeyparrish** [comment] 2016-03-31 16:17
Yes, logging is disabled by default when compiling.  You can change the log level in your build (change shaka.log.MAX_LOG_LEVEL=0 in build/lib.sh), or you can use the uncompiled version.  In general, you should use the uncompiled version to debug.  It is very difficult to debug with the compiled library, even with logs enabled.

**Comment by joeyparrish** [comment] 2016-04-06 20:53
@MegaLabs1, any updates?

**Comment by joeyparrish** [comment] 2016-04-11 04:59
I'm going to go ahead and close this issue.  If this is still a problem for you, let us know and we can reopen for discussion.  Thanks!

**Closed by joeyparrish** 2016-04-11 04:59 UTC
Labels: question
