### ISSUE TITLE
Shaka player does not play video when play button is pressed

### ISSUE THREAD

**Issue by sridhardvvce** [google/shaka-player#600] opened 2016-11-19 04:42 UTC
Hi,

This is continuation of issue #585 .

@joeyparrish I have updated the latest code. 

If I play the video several times the issue will be reproduced 1 or 2 times (say 1 out of 10 times). When the video is not played if I seek a little the video starts playing.

Since the #585 ticket was closed I raised a new ticket.

Please help in fixing the issue

**Comment by joeyparrish** [comment] 2016-11-29 00:28
@sridhardvvce, can you please test something for me?  I have been working on a bug today that may be related.

In lib/media/playhead.js, in the constructor, change `this.startWatchdogTimer_()` to `this.onWatchdogTimer_()`.  I expect this will make the bug reproducible 10 out of 10 times.  Please let me know if this is the case.  If so, I should have a fix out soon.

**Comment by joeyparrish** [comment] 2016-12-02 23:20
I believe this was fixed by 84fb9d42.  If not, please let me know and we can reopen and investigate.

**Comment by joeyparrish** [comment] 2016-12-27 22:58
As mentioned by @sridhardvvce in #637, this is not fixed yet.  Reopening to investigate.

**Comment by joeyparrish** [comment] 2016-12-27 23:00
Manifest link from the original issue, #585: https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1094/courses/6677/paid/25537/online/11/004_video_youtube_1mb_fdq7pg2zj7la7v7bke29webTrack.mpd

**Comment by joeyparrish** [comment] 2016-12-27 23:06
@sridhardvvce, I am unable to reproduce your issue using the latest code from `master`.  Here's the link to what I'm doing to reproduce:

http://nightly.shaka-player-demo.appspot.com/demo/?asset=https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1094/courses/6677/paid/25537/online/11/004_video_youtube_1mb_fdq7pg2zj7la7v7bke29webTrack.mpd;play

Please provide detailed instructions to reproduce your issue.  Here's a template:

- What version of Shaka Player are you using?
  - Can you reproduce the issue with our latest release version?
  - Can you reproduce the issue with the latest code from `master`?
- Are you using the demo app or your own custom app?
  - If custom app, can you reproduce the issue using our demo app?
- What browser and OS are you using?
- What did you do?
  - What content did you load?
    - If standard demo asset, which one?
    - If custom asset, what manifest and license server URIs?
  - How did you interact with the content, if at all?
- What did you expect to happen?
- What actually happened?

**Comment by sridhard** [comment] 2017-01-02 16:46
Hi,

What version of Shaka Player are you using?
Can you reproduce the issue with our latest release version?
//I have not tried using the release version

Can you reproduce the issue with the latest code from master?
//Yes. I am able to reproduce using the code from master

Are you using the demo app or your own custom app?
If custom app, can you reproduce the issue using our demo app?
//I am able to reproduce with demo app.

What browser and OS are you using?
//Mac and chrome. I faced the same issue with windows and chrome

What did you do?

What content did you load?
//I disabled the audo play mode and tried to play the content manually

If standard demo asset, which one?
If custom asset, what manifest and license server URIs?
//I used custom asset: https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1094/courses/6677/paid/25963/online/tst/2016-05-18_20.12_SSC_CGL_Quant_Advance_MathswebTrack.mpd

How did you interact with the content, if at all?
//Play the content manually (disable auto play). The issue will be reproduced once in 10-15 times

What did you expect to happen?
What actually happened?

**Comment by sridhard** [comment] 2017-01-02 16:52
@joeyparrish 

I have taken the latest master code and used the demo player to test the content. I have removed the auto play from the video tag in the index.html of demo player.

Steps:
1. Launch the demo player and give the custom manifest URL(https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1094/courses/6677/paid/25963/online/tst/2016-05-18_20.12_SSC_CGL_Quant_Advance_MathswebTrack.mpd)

2. Once the play button is displayed, wait for 5 seconds

3. After 5-10 sec press the play button

4. Repeat the process for 10-15 times. 

Most of the times the content will be played when the play button is pressed. Some times it will display the loading progress and will not play the content. If we seek little bit then the content will start playing immediately

**Comment by sridhard** [comment] 2017-01-07 03:37
@joeyparrish are you able to reproduce the issue? Do you need any help from me?

**Comment by sridhard** [comment] 2017-01-07 09:58
@joeyparrish I have another video where this issue is reproduced most of the time https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1075/courses/8921/paid/42061/online/tst/2016-11-14_20_01__CGL17_Maths_Live_ClasswebTrack.mpd

**Comment by joeyparrish** [comment] 2017-01-09 18:55
Sorry for the delay.  We've been really busy lately!  We'll take a look and see if we can reproduce.

**Comment by TheModMaker** [comment] 2017-01-09 20:19
Here are the first few frame times of the audio stream, according to Chrome:

|DTS|PTS|
|-----|--------------|
|0 | -0.46439|
| 0.23219 | -0.23219 |
| 0.46439 | 0 |
| 0.69659 | 0.23219 |
| 0.92879 | 0.46439 |

The first few audio frames in the presentation have a `PTS < 0`, this causes Chrome's MSE to drop the early frames.  Then Chrome's DTS vs PTS problem (see #377) will see the first frame at 0.46439 seconds, which is a gap that the video element will not jump.  Additionally, the audio frames have a `DTS > PTS`, which Chrome is unsure if that is valid (see Chrome bug [354518](https://bugs.chromium.org/p/chromium/issues/detail?id=354518)).

So either this is Chrome's bug or the content is bad.  I would suggest contacting the encoder that made the content to make sure that `DTS <= PTS`.  If you could have `PTS == DTS == 0` for the first frame, that would fix it.

**Comment by sridhard** [comment] 2017-01-28 05:58
@joeyparrish I have tested this content with DASH player(http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/) and it plays fine.

https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1075/courses/8921/paid/42061/online/tst/2016-11-14_20_01__CGL17_Maths_Live_ClasswebTrack.mpd

But this content fails to play without seeking in shaka  player.
I have tried both shaka and DASH in chrome browser

**Comment by sridhard** [comment] 2017-01-28 06:00
@TheModMaker with DASH reference player(http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/) I am able to play the content.

In shaka player this content will play only when we seek initially.

**Comment by sridhard** [comment] 2017-01-29 02:26
@joeyparrish @TheModMaker I have tried this content with expressplay SDK also. The content is played successfully. Can you please help in resolving the issue in shaka player

**Comment by TheModMaker** [comment] 2017-01-30 21:08
I just pushed a change that should fix the problem.  Please try again with the latest from `master`.

**Comment by sridhard** [comment] 2017-02-04 04:56
@TheModMaker I have tested the latest code. But still the issue exist.

**Comment by sridhard** [comment] 2017-02-04 04:57
@TheModMaker this is the content URL: https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1075/courses/8921/paid/42061/online/tst/2016-11-14_20_01__CGL17_Maths_Live_ClasswebTrack.mpd

**Comment by sridhard** [comment] 2017-02-04 05:29
@TheModMaker . Sorry. It was my mistake. The issue is resolved Thanks a lot

**Comment by joeyparrish** [comment] 2017-02-04 23:05
Thanks for retesting.  Closing as resolved.

**Closed by joeyparrish** 2017-02-04 23:05 UTC
Labels: bad content

**Comment by hghazzi** [comment] 2017-03-15 19:43
@joeyparrish @TheModMaker I encountered this exact same issue using v2.0.6 as well as master on Chrome 57. Here's the sample stream: https://akadash0-test.akamaized.net/test/clear/test-multi-audio/master.mpd

It is reproducible in the demo page, and verified that this started occurring between v2.0.0 and v2.0.1

Thoughts?

**Comment by TheModMaker** [comment] 2017-03-15 20:18
@hghazzi First I am getting a 403 error for the manifest.  Please post an accessible manifest.

Also please open a new issue.

**Comment by hghazzi** [comment] 2017-03-15 20:45
@TheModMaker Done. Stream worked fine for me
