### ISSUE TITLE
Cannot cast Widevine DRM to Chromecast

### ISSUE THREAD

**Issue by amirch1** [google/shaka-player#306] opened 2016-03-15 11:35 UTC
In [Shaka Player Demo](http://shaka-player-demo.appspot.com/), when setting a custom Widevine MPD file and license URL, the movie loads and plays in the player but when casting to Chromecast, I see only the Shaka splash screen on the TV and no playback.

**stream:** http://cdnapi.kaltura.com/p/1788671/sp/178867100/playManifest/entryId/1_brk7q3nv/flavorIds/1_22v639vr,1_lg2flj9s,1_j3or55ly,1_7hyrnz30/format/mpegdash/protocol/http/a.mpd
**License:** https://udrm.kaltura.com/cenc/widevine/license?custom_data=eyJjYV9zeXN0ZW0iOiJPVlAiLCJ1c2VyX3Rva2VuIjoiZGpKOE1UYzRPRFkzTVh3SEtVTGxKMGs5N2hFQV96ZlE3SjI5TjNvWVhFRE5ocjd2UG0xX21jelZFX0ZOeVc0bTA4bDFHa3JRdC1tNjhweGROTVBReTg3TXc4UTlscUtuR3N4Ujk3R2xwVWlEOXJ2UHdvSjNMejYzZFE9PSIsImFjY291bnRfaWQiOiIxNzg4NjcxIiwiY29udGVudF9pZCI6IjFfYnJrN3EzbnYiLCJmaWxlcyI6IjFfaGxzNjI0aGssMV96cWszbmU0ZywxXzIydjYzOXZyLDFfbGcyZmxqOXMsMV9qM29yNTVseSwxXzdoeXJuejMwLDFfZ2dteHA0ZmMifQ%3D%3D&signature=eakaBigU46eyezi5mTyx6bZRMao%3D&files=MV8yMnY2Mzl2ciwxX2xnMmZsajlzLDFfajNvcjU1bHksMV83aHlybnozMA%3D%3D&
Can't seem to be able to debug the Chromecast receiver, probably due to LoggerLevel not being set.
Any advise as to whats going on?
Thanks!

**Comment by joeyparrish** [comment] 2016-03-15 16:37
Sorry, no, I'm not really sure.  Are you able to play other encrypted content using Shaka on the Chromecast?

**Comment by amirch1** [comment] 2016-03-16 09:17
I can see your Widevine examples manage to play on Chromecast after a large amount of waiting time (about half a minute). Our stream never starts to play. Any chance of getting the logs from your Chromecast receiver?

**Comment by sanbornhnewyyz** [comment] 2016-03-17 20:57
@amirch1 We are seeing a similar sounding problem but are starting to suspect we have a content issue. Do you have any logs at all? I would be curious what errors you're getting.

**Comment by amirch1** [comment] 2016-03-18 11:17
Seems to be an issue with the latest Chromecast firmware upgrade: https://code.google.com/p/google-cast-sdk/issues/detail?id=785

**Comment by joeyparrish** [comment] 2016-03-18 15:14
@amirch1, since this appears to be a Chromecast bug, I'm leaning toward closing this issue with the label "working as intended".  Any objections?

**Comment by amirch1** [comment] 2016-03-20 06:33
Agreed. Thanks!

**Closed** 2016-03-21 01:28 UTC
Labels: working as intended
