### ISSUE TITLE
The playback stops after 16 seconds - v2.0.0 version (non-debug)

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#549] opened 2016-10-13 13:52 UTC
Go to http://jsfiddle.net/YairAns/e3x6dcez/1/
After 16-25 seconds the playback will stop

In shaka demo which uses v2.0.0-debug version it plays ok.

Reproduce on chrome/FF on mac

**Comment by joeyparrish** [comment] 2016-10-13 18:26
I was able to reproduce your results on my Chromebook.  I see the playback stuck at 27.167347, and a gap in the video timeline from 24.12 to 25.12.  The buffered ranges are (0 - 24.12) and (25.12 - 59.512744).  The manifest only contains one Period, so this can't be caused by a gap between Periods.

**Comment by joeyparrish** [comment] 2016-10-13 18:29
If I disable ABR via `player.configure({abr: {enabled: false}});` there is not gap and the problem goes away.  So it may be that the Representations don't align, or it may be that we made a mistake when switching.

**Comment by joeyparrish** [comment] 2016-10-13 18:50
The only two video tracks are 1.5Mbps and 5Mbps, so you can't reproduce on slow or flaky wifi (wifi at this conference is currently acting up, so I'm having difficulty now).  It seems that you need more than 5Mbps to reproduce the bug.

**Comment by joeyparrish** [comment] 2016-10-13 21:04
Timestamps from the content (using DTS since [that's what Chrome is returning](http://crbug.com/373039) for buffered ranges):

| Segment number | Ideal timestamp from manifest | Low-bitrate media timestamp | High-bitrate media timestamp |
| ----- | ----- | ----- | ----- |
| 1 | 0 | 0 | 0 |
| 2 | 4 | 3.96 | 4.12 |
| 3 | 8 | 8 | 7.96 |
| 4 | 12 | 12 | 12.76 |
| 5 | 16 | 16 | 16.96 |
| 6 | 20 | 20 | 20.24 |
| 7 | 24 | 24 | 25.12 | 
| 8 | 28 | 28 | 28.4 |

This is the best way to reproduce the bug in Chrome, using your content and [our latest nightly build](http://nightly.shaka-player-demo.appspot.com/demo/):

```js
player = shakaDemo.localPlayer_;  // for demo app

// disable ABR
player.configure({abr: {enabled: false}});

// wait for time 16, then switch to the high bitrate track
switched = false;
video.addEventListener('timeupdate', function() {
  if (video.currentTime > 16 && !switch) {
    switch = true;
    // switch and clear 2 segments ahead (16 + 2*4 == 24)
    player.selectTrack(player.getTracks()[1], 2);
  }
});
```

The player clears ahead starting at 24, and then looks up the segment needed to fill in time 24.  Based on the manifest, that's segment 7, but due to the drift in the table above, this would have to be segment 6 instead.

The DASH spec allows content timestamps to wander away from the ideal time in the manifest by up to one half segment.  We have a mechanism to cope with this.  When we seek, we assume that some amount of drift exists and factor that into our calculation about what segment to fetch.

However, what we see here is that one Representation wanders away from the other Representation.  It appears that this should not be allowed.  DASH IOP v3.3, section 3.1 states:

> (Sub)Segments are constrained so that for switching video Representations within one Adaptation Set the boundaries are aligned without gaps or overlaps in the media data.

**Comment by joeyparrish** [comment] 2016-11-14 19:37
Closing this issue, as the media is not correctly aligned across Representations.  This is not interoperable content.

**Closed by joeyparrish** 2016-11-14 19:37 UTC
Labels: question
