### ISSUE TITLE
Period flattening error on DASH manifests with image AdaptationSet

### ISSUE THREAD

**Issue by jennyzhua** [google/shaka-player#3383] opened 2021-05-03 19:09 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What link can we use to reproduce this?**
manifest sent in email

**What version of Shaka Player are you using?**
v3.1.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36

**What did you do?**
Play the manifest in the demo app

**What did you expect to happen?**
Playback starts successfully

**What actually happened?**
Encountered Shaka Error MANIFEST.PERIOD_FLATTENING_FAILED ()

**Comment by avelad** [comment] 2021-05-05 08:42
After this PR https://github.com/google/shaka-player/pull/3365, the tileLayout information will be entered into the segments, so in theory DASH could be adapted to use the same format and eliminate this limitation.

**Comment by joeyparrish** [comment] 2021-05-07 19:08
I think the short-term solution needs to be a fix to period-flattening to ignore images.  That could be cherry-picked to the existing v3.0.x and v3.1.x release branches and can appear in a bugfix release, whereas any pending feature PRs are going to first appear in a future feature release.

**Comment by avelad** [comment] 2021-06-22 13:36
@jennyzhua Can you copy the manifest here (text) so I can work on the fix?

**Comment by joeyparrish** [comment] 2021-07-09 04:36
@jennyzhua, we have the content URL you shared privately, and I am working on this issue now.  The issue seems to be particular to having two different resolutions of images per period.  You _may_ be able to work around it by removing one on the backend or at runtime by manipulating the manifest in the client.  I hope to have a solution soon, though.

Thanks for your patience!

**Comment by joeyparrish** [comment] 2021-07-09 18:47
I have a fix working now in manual testing, and regression tests to cover this case as well.  The changes are in review now, and will be in our next release.

**Comment by avelad** [comment] 2021-07-12 16:56
@joeyparrish After closing this issue, will you release the version 3.2? What day?

**Closed** 2021-07-12 20:46 UTC
Labels: bug, priority:P1

**Comment by joeyparrish** [comment] 2021-07-12 22:34
I'm working on cherry-picks for the releases now.  v3.2.0 and v3.1.2 at least, and v3.0.13 and v2.5.24 if necessary.
