### ISSUE TITLE
Chrome CDM bug - DASH, HbbTV profile with Widevine encryption fails

### ISSUE THREAD

**Issue by faiyeah** [google/shaka-player#308] opened 2016-03-18 02:03 UTC
The Shaka player is v1.6.2, and it is launched on a chrome browser.

I wonder if HbbTV with widevine encryption is supported by Shaka at this moment. 

Sample content will be provided very shortly.

**Comment by joeyparrish** [comment] 2016-03-18 15:08
@faiyeah, there is no such restriction in Shaka or Widevine.  Can you please try the following?

1. Use the latest release of Shaka Player, v1.6.4
2. Enable debug logging (`?debug` in the URL of the demo app or `shaka.log.setLevel(shaka.log.Level.DEBUG)` in your own app in uncompiled mode)
3. Open the JavaScript console
4. Send us the JS logs

**Comment by joeyparrish** [comment] 2016-03-29 20:52
@faiyeah, we haven't heard from you in a while.  Is this still an issue for you?

**Comment by joeyparrish** [comment] 2016-04-06 20:07
@faiyeah, we haven't heard from you in a few weeks, so I'm going to go ahead and close this issue.  Please let me know if you are still having trouble and we can reopen and investigate.

**Comment by faiyeah** [comment] 2016-04-20 08:11
Sorry for my delayed response. 

Here I have attached two files, one is the shaka player log with hbbtv + widevine encryption content; while the other is the shaka player log with hbbtv and clear content. 

Please review, and re-open the issue. 

Sorry again for the inconvenience.

Ryan Chan

**Comment by tdrews** [comment] 2016-04-20 19:49
It looks like the license does not contain the correct keys for the content. Which license server are you using?

**Comment by faiyeah** [comment] 2016-04-21 07:20
I am using the following widevine server:
http://license.uat.widevine.com/cenc/getcontentkey/widevine_test

Ryan Chan

**Comment by tdrews** [comment] 2016-04-21 17:23
That URL is for obtaining encryption keys to encrypt content. Are you running your own Widevine proxy server? If not, you probably want to use http://widevine-proxy.appspot.com/proxy as the license server, e.g.,
```javascript
player.configure({
  drm: {
    servers: { 'com.widevine.alpha': '//widevine-proxy.appspot.com/proxy' }
  }
});
```

**Comment by faiyeah** [comment] 2016-04-22 08:23
Hi tdrews,

I apologize for the confusing and incomplete description of the issue. I would like to clarify the issue I observed. 

I think a more concrete issue that I would like to tackle is - "Encrypted content with HbbTV profile does not switch video qualities properly in Shaka Player v 1.6.5".

To reproduce the issue, I am providing 4 sample contents:
- https://www.dropbox.com/s/9583c8pta4aow7r/iso_clear.tar.gz?dl=0
 - Content A: Clear DASH content with ISO profile
- https://www.dropbox.com/s/845bvoqb4er3y11/iso_enc.tar.gz?dl=0
 - Content B: Encrypted DASH content with ISO profile
- https://www.dropbox.com/s/w02mjfqf4lc64vs/hbbtv_clear.tar.gz?dl=0
 - Content C: Clear DASH content with HbbTV profile
- https://www.dropbox.com/s/nno41093fs2wdq0/hbbtv_enc.tar.gz?dl=0
 - Content D: Encrypted DASH content with HbbTV profile

The Shaka Player which can reproduce the issue:
- http://v1-6-5.shaka-player-demo.appspot.com/

Steps to reproduce the issue:
- Host the contents above
 - Each content contains 3 different video qualities
  - 480 x 270 (500K)
  - 640 x 360 (1M)
  - 1280 x 720 (1.5M)
- Load the player
- Put the mpd URL in "Stream Setup > Custom manifest URL:"
- Leave the field "Stream Setup > Custom WV license server URL: [?]" empty
- Disable the adaptation by unchecking "Stream Info > Enable adaptation?"
 - By observation, it loaded the lowest bitrate (480 x 270) by default with the above contents
- Click "Load Stream"
- Do switching across different qualities in "Stream Info > Available video tracks:"
 - Only trigger switch when "Stream Info > Buffered behind:" is larger than "Stream Info > Buffered ahead:"
 - If switching is successful, we should be able to observe resolution changed in "Stream Info > Active resolution:", and the playback should continue, although sometimes with glitch (follow up issue will be created soon).

Issues observed:
- Switching failed for Content D. At the time of switching failure, the playback get stuck.

Here are the screenshots:
- Before switching, the playback is normal:
![normal](https://cloud.githubusercontent.com/assets/5735739/14735872/22648f08-08a6-11e6-8b8c-40d787df95c4.png)
- After switching, the playback get stuck:
![hang](https://cloud.githubusercontent.com/assets/5735739/14735882/324274da-08a6-11e6-8489-6b711d062a23.png)

Here is the console debug log:
[v1-6-5.shaka-player-demo.appspot.com-1461313174612.txt](https://github.com/google/shaka-player/files/231394/v1-6-5.shaka-player-demo.appspot.com-1461313174612.txt)

Addition comments:
- The switching issue does not occur for Content A, B, and C. So, I would personally guess this will only happen with combination of encryption and HbbTV content.

For more clarification, please definitely let me know.

Ryan Chan

**Comment by faiyeah** [comment] 2016-04-22 08:24
I have re-titled the issue so that it is reflecting exactly what is reported.

Ryan Chan

**Comment by tdrews** [comment] 2016-04-22 20:19
Thank you for the detailed report. I can reproduce the issue. Which packager are you using to create the content?

**Comment by faiyeah** [comment] 2016-04-23 01:07
You are very welcomed. This is output captured from Harmonic packager, in which they are the one of the very few to support HbbTV output profile.

Many thanks.

Best regards,
Ryan Chan
- sent from my iPhone

**Comment by tdrews** [comment] 2016-04-26 18:42
It appears that this is either a content issue, a decoder issue, or both. This may be a bug within the Chrome CDM (also see #304). The Chrome CDM team is investigating.

**Comment by joeyparrish** [comment] 2016-11-15 00:35
I've been told that a fix for this will be out in Chrome 56, which is currently scheduled for stable release at the end of January [according to chromium.org](https://www.chromium.org/developers/calendar).  You may be able to see the fix sooner when Chrome 56 goes to beta, but I have no information about when that would happen.

We'll keep this issue open until the fix is out.

**Comment by joeyparrish** [comment] 2016-12-13 23:39
Chrome 56 is now in beta.  Can you try it out and verify that this is now fixed?

**Comment by TheModMaker** [comment] 2017-02-21 21:47
Chrome 56 is now in stable. Closing due to inactivity. Feel free to reopen if the issue persists.

**Closed by TheModMaker** 2017-02-21 21:47 UTC
Labels: bug, EME, external
