### ISSUE TITLE
PlayReady IE11 Streams not working

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#890] opened 2017-06-16 19:10 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**: 2.1.1

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: Didn't try

**Are you using the demo app or your own custom app**: Both

**If custom app, can you reproduce the issue using our demo app**: With some streams

**What browser and OS are you using**: IE11 / Windows 10

**What did you do?**

Shaka Demo Page: Trying to load Axinom Multi-DRM on IE11. Works in EDGE. 
Custom App: Emailed Playready stream with custom headers. Also, works on EDGE, but not on IE11. 

Both produce the RESTRICTIONS_CANNOT_BE_MET error.

**NOTE**: Seems like none of the Playready/Multi-DRM streams are working on IE11, producing different errors.

**Comment by joeyparrish** [comment] 2017-06-16 21:14
Please try the latest release.  We fixed PlayReady-related issues in v2.1.3, and we just released v2.1.4 today.

**Comment by chrisfillmore** [comment] 2017-06-18 15:33
Fwiw I've seen the same behaviour in IE11 and Tizen because the polyfill uses the fake KEY_ID_, same as #884. Although playback still works, at least in some cases.

**Comment by joeyparrish** [comment] 2017-06-18 19:57
Ah, that make sense.  This is probably a duplicate of #884, then, for a different platform.

If that is the case, I would expect playback to work on content where all video streams use the same key ID, or in cases where the key IDs are not in the manifest but all keys are returned in the license.

One way or another, we need to make sure Shaka Player works as well as it can without key statuses.

**Comment by joeyparrish** [comment] 2017-06-19 18:30
I believe the same root cause is at work in both this issue and #884, and that a solution to this will work around #891.

**Closed** 2017-06-21 19:44 UTC
Labels: bug

**Comment by hghazzi** [comment] 2017-07-12 15:09
Just checking in, will this be released soon?

**Comment by joeyparrish** [comment] 2017-07-12 15:23
I'm sorry we haven't made a release lately.  Due to vacations and illness, I've been falling behind on things.  I believe this can be cherry-picked cleanly to v2.1.x and be released in v2.1.5, either this week or next week.

**Comment by hghazzi** [comment] 2017-07-12 15:32
Thanks for the update, feel better!

**Comment by joeyparrish** [comment] 2017-07-17 16:55
The fix for this has been cherry-picked and will be released in v2.1.5.

**Comment by hghazzi** [comment] 2017-07-17 17:43
Thanks, Joey. We started testing against master and still seeing an issue
with a stream that uses request headers. Trying to do some more debugging,
hoping to share them once I verify it's the same issue.

**Comment by hghazzi** [comment] 2017-07-17 18:38
Actually, did some more testing, and the fix might be working. We'll do further verification once 2.1.5 is released.

**Comment by joeyparrish** [comment] 2017-07-17 18:40
The tag is out, as is NPM.  I am still pushing the release out through other channels, after which I'll announce via email.  But you can go ahead with the github tag or NPM release.

**Comment by hghazzi** [comment] 2017-07-17 19:01
Great, thanks!

**Comment by jstephenson01** [comment] 2017-08-08 20:29
@joeyparrish , I was seeing the same Manifest.Restrictions_Cannot_Be_Met while playing a dash manifest in the Shaka Demo v2.1.4 in IE11 (Win10). I updated to Shaka v2.1.5, the asset is playing now ("Invalid argument" box pops up on player) but i am seeing new errors/warnings in the console(below)... (i also see that this user was seeing same https://groups.google.com/forum/#!topic/shaka-player-users/e_k0Bd5VEvM)


DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
demo
HTML1300: Navigation occurred.
demo
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
demo (99,13)
Patching input event support on IE.
Using ms-prefixed EME v20140218
Using native MSE as-is.
Using Promises polyfill.
Using VTTCue polyfill from 3 argument TextTrackCue.
No Period ID given for Period with start time 0,  Assigning a default
The last segment should not end before the end of the Period. [object Object]
   "The last segment should not end before the end of the Period."
   {
      [functions]: ,
      __proto__: { },
      endByte: 123230,
      endTime: 1353.875,
      position: 22,
      startByte: 118531,
      startTime: 1320
   }

Should only receive a Shaka error
(text:7) failed fetch and append: code=undefined
Wrong error type!
Player error Error: Invalid argument.
   "Player error"
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid argument.",
      message: "Invalid argument.",
      name: "Error",
      number: -2147024809,
      severity: 2,
      stack: "Error: Invalid argument.
   at Anonymous function (http://10.99.146.203/shaka-playerv2-5/lib/media/text_engine.js:181:7)
   at wrapper (http://10.99.146.203/shaka-playerv2-5/lib/polyfill/promise.js:344:9)
   at shaka.polyfill.Promise.flush (http://10.99.146.203/shaka-playerv2-5/lib/polyfill/promise.js:451:7)"
   }

Got a synthetic key status event, so we don't know the real key statuses. If we don't have all the keys, you'll need to set restrictions so we don't select those tracks.
Should only receive a Shaka error
(text:7) failed fetch and append: code=undefined
Wrong error type!
Player error Error: Invalid argument.
   "Player error"
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid argument.",
      message: "Invalid argument.",
      name: "Error",
      number: -2147024809,
      severity: 2,
      stack: "Error: Invalid argument.
   at Anonymous function (http://10.99.146.203/shaka-playerv2-5/lib/media/text_engine.js:181:7)
   at wrapper (http://10.99.146.203/shaka-playerv2-5/lib/polyfill/promise.js:344:9)
   at shaka.polyfill.Promise.flush (http://10.99.146.203/shaka-playerv2-5/lib/polyfill/promise.js:451:7)"
   }

Got a synthetic key status event, so we don't know the real key statuses. If we don't have all the keys, you'll need to set restrictions so we don't select those tracks.

**Comment by TheModMaker** [comment] 2017-08-09 16:26
@jstephenson01 This issue has been fixed so please don't post to this issue.  Please start a new issue for your issue.  Also include a test stream that reproduces your problem since I can play our PlayReady test assets without problem.
