### ISSUE TITLE
shaka-player works when loaded from localhost, but not when loaded from another machine

### ISSUE THREAD

**Issue by prasadkhambete** [google/shaka-player#904] opened 2017-06-21 23:26 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**: 2.1.0-debug, also tried on 2.1.x branch

**Can you reproduce the issue with our latest release version**:Yes

**Can you reproduce the issue with the latest code from `master`**:Yes

**Are you using the demo app or your own custom app**:demo app

**If custom app, can you reproduce the issue using our demo app**:NA

**What browser and OS are you using**:Chrome on Linux and MacOS

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
git clone https://github.com/google/shaka-player.git
cd shaka-player
python build/all.py
cd ..
sudo cp -R shaka-player /var/www/html

load the URL: http://localhost/shaka-player/support.html -> shows that Widevine is supported
try to load the URL from another machine : http://<ip address of machine hosting shaka>/shaka-player/support.html -> shows that Widevine is not supported

Looks like some javascript works when loaded from localhost but not from another machine

**What did you expect to happen?**

shaka player should work from localhost and any other machine

**What actually happened?**

worked on localhost (Widevine menu items enabled), but does not work on another machine (Widevine menu items grayed out)

**Comment by vaage** [comment] 2017-06-21 23:32
@prasadkhambete What happens if you try accessing it via `https` (your example is using `http`)?

**Comment by prasadkhambete** [comment] 2017-06-22 00:07
@vaage - Yes, it seems to work when accessed through https. This is not convenient though, because it requires additional steps to set up ssl for apache2 (apt-get install ssl-cert; a2enmod ssl; a2ensite default-ssl) - Why does it work through https but not http ?

**Comment by joeyparrish** [comment] 2017-06-22 03:11
@prasadkhambete, this https requirement is outside of our control.  The EME spec states that EME is only available from a secure context (https or localhost).  We just today [added a new FAQ entry](https://github.com/google/shaka-player/commit/678390b92a31867e909ebb36775d487964cbde7e#diff-7665f0fe1a636914c36548e343086ee3) about this, closing #867.  The new entry will appear in the nightly build in a few hours, but I have reproduced it here for your convenience:


#### EME and http URLs

EME requires a secure URL to use.  This means you have to use `https` or be on `localhost`.  Currently only Chrome enforces it, but other browsers will in the future.  Also, because of mixed content requirements, if your site is using `https`, then your manifest and every segment will also need to use `https` too.

See: Chrome's [announcement][], Firefox's [intent to remove][firefox_bug], and how to [disable for testing][allow_http].

[allow_http]: https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins
[announcement]: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/tXmKPlXsnCQ/ptOETCUvBwAJ
[firefox_bug]: https://bugzilla.mozilla.org/show_bug.cgi?id=1322517

**Comment by joeyparrish** [comment] 2017-06-22 03:11
Does this help?

**Comment by prasadkhambete** [comment] 2017-06-22 18:17
@joeyparrish - yes that makes it clear.Thanks! We will transition to use https for our internal test servers. The Chrome browser option to disable secure origin requirement for testing is useful, and will help in the mean time with test servers from external third parties (serving test content on the web) until they get transitioned to use https instead of http

**Comment by joeyparrish** [comment] 2017-06-22 18:19
Glad we could help!  Feel free to comment if you need anything else on this topic, and we can reopen the issue if needed.

**Closed by joeyparrish** 2017-06-22 18:19 UTC
Labels: question
