### ISSUE TITLE
bufferingStart fires before content is loaded

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#63] opened 2015-04-21 17:45 UTC
The bufferingStart event is firing as soon as the player is setup, regardless of whether you attempt to load any content. This seems counterintuitive because nothing is actually being buffered at this point. Is this the intended behaviour?

**Comment by joeyparrish** [comment] 2015-04-21 21:36
I believe this might have had the same root cause as #61, which we just pushed a fix for.  Can you please try again with the latest from master?

**Comment by sanbornhnewyyz** [comment] 2015-04-22 16:12
The autoplay attribute is working correctly now, thanks for the fix. 

But this one is still behaving the same way. I notice that on your demo player it does not do it because the player instance is not created until someone tries to load content and at that time it's created and event listeners are added. But in our case we are instantiating the player and adding event listeners on page load and then when someone picks content we just have to load it into our instance. So on our page load we are creating a player and adding listeners but not giving it a video source and the bufferingStart event is firing right away on page load.

**Comment by joeyparrish** [comment] 2015-04-22 20:46
Ah, I see.  Thanks for the report, as well as for re-testing.  We'll see what we can do to fix it.

**Comment by tdrews** [comment] 2015-05-05 17:52
I'm having difficulty reproducing this issue from the trunk.

The 'bufferingStart' event is dispatched from `Player.enteringBufferingState_`, which is called by `Player.onWatchdogTimer_`, which is triggered via `Player.startWatchdogTimer_`, which is only called from `Player.onWatchdogTimer_` and `Player.load`.

Are you still seeing this issue on the trunk?

**Comment by sanbornhnewyyz** [comment] 2015-05-06 15:01
I'm using v1.3.0-28-g77552f2

**Comment by sanbornhnewyyz** [comment] 2015-05-06 15:14
Actually, that's not entirely true. It will fire if you run out your current buffer during playback. But it does not fire when you first load content and start buffering because onWatchdogTimer_  checks that the video isn't paused before firing Player.enterBufferingState. Is that the correct behaviour? I would think it should fire when it initially starts buffering content even if the player is paused.

**Comment by tdrews** [comment] 2015-05-06 17:22
This is the intended behavior of ecc1f8027908e5e582853889d09639f05737a50b, but perhaps we can do better. The challenge is handling autoplay=true/false, user invoked pauses, and corner cases resulting from the interplay between play/pause calls in the code-base.

I'll open a new issue to track 'bufferingStart' not firing during start-up.

**Closed by tdrews** 2015-05-06 17:22 UTC
Labels: bug, medium?
