### ISSUE TITLE
TTML and CEA-608 captions conflicting with each other when present in text tracks list

### ISSUE THREAD

**Issue by dhubertus** [google/shaka-player#3199] opened 2021-03-09 23:01 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes
* Possibly loosely related:
   * https://github.com/google/shaka-player/issues/3186

**What version of Shaka Player are you using?**
* v2.5.20 but can repro on v3.0.8

**Can you reproduce the issue with our latest release version?**
* Yes, can repro ono v3.0.8

**Can you reproduce the issue with the latest code from `master`?**
* Have not tried, but can repro on v3.0.8 shaka demo player.

**Are you using the demo app or your own custom app?**
* Custom app.

**If custom app, can you reproduce the issue using our demo app?**
* Yes can repro on the demo app

**What browser and OS are you using?**
* Chrome Version v89.0.4389.82 (Official Build) (x86_64)
* MacOS v10.15.7

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Please let us know if and when you want to reproduce and we will provide you with a way to access our video streams.

**What did you do?**
* Using shaka demo player v3.0.8
   * Play a multi-period static dash asset that contains ttml and cea-608 text tracks.
   * Seek out of the first period
   * Toggle captions ON (ttml captions are selected in this case)
      *  Note: captions for ttml look to be from the first period although playing video/audio from later period
   * Select cea-608 text track (now cea-608 text track is playing and all looks to be ok)
   ```javascript
   const player = document.getElementById('video').ui.getControls().getPlayer();
   const trackToSelect = player.getTextTracks().find((track) => track.mimeType === 'application/cea-608');

   player.selectTextTrack(trackToSelect);
   ```
   * Toggle captions OFF then ON again
   * I believe to be seeing both ttml and cea-608 captions although only one is active.
      * ttml captions show immediately (and are playing text from the first period)
      * cea-608 captions show properly but won't appear until already buffered content has been played.

**What did you expect to happen?**
* We would expect only the active text track to be displaying and to be in sync with the audio.

**What actually happened?**
* Note the above scenario may seem odd as this is how I was able to repo on the shaka demo player.
   * The above steps will get the player in a state in which there are multiple text tracks being displayed. Although only one is declared active when checking player.getTextTracks().
   
<img width="450" alt="Screen Shot 2021-03-09 at 3 07 18 PM" src="https://user-images.githubusercontent.com/25044263/110548938-911b7680-80ee-11eb-825a-36c5d6cafbe8.png">
<img width="552" alt="Screen Shot 2021-03-09 at 3 07 35 PM" src="https://user-images.githubusercontent.com/25044263/110548943-94166700-80ee-11eb-9934-60eaa1d92e52.png">

* For our custom application, we are selecting cea-608 text tracks off the bat as we are not looking to display the ttml track.
* When we toggle captions OFF then ON we end up in the same state as above.
```javascript
player.setTextTrackVisibility(val);
```
* We see the ttml captions from the first period immediately (not active track)
* We will see the cea-608 text track (active text track) but does not show until we've made it through already buffered content
* We have implemented a workaround to parse out adaptation sets with mime type application/ttml+xml and this looks to fix both the duplicate active text track behavior as well as the delay in viewing the cea-608 text tracks. Although not ideal.
* We are looking to raise this bug in the hopes to help resolve the issue at its source or highlight any improper usage we may be doing on our end! Thanks!

**Comment by theodab** [comment] 2021-03-12 09:36
You can send the reproduction issue (URIs and such) to shaka-player-issues@google.com, and I'll look into the issue.

**Comment by dhubertus** [comment] 2021-03-12 21:25
Sent over the information on how to access the application and how to reproduce the described issue. Please reach out if can assist in any way! Thanks for taking a look

**Comment by theodab** [comment] 2021-03-18 23:19
I tried to reproduce this for a while, but failed.
For whatever reason, I can't see your embedded captions at all. Even if I specifically play an embedded track (by picking the spanish captions, for example, which only have an embedded version), the text displayer has no cues. I've tried in our demo player using both v3.0.X and v3.1.X, same thing in both. I don't know how to change the language in your application, but I've been unable to reproduce the error there too.
So for all I know, the player might be loading cues from both caption tracks at once, and I just can't tell because the embedded captions aren't being loaded properly to begin with. It's hard to say.
I'm not sure why yet, honestly. mux.js parsing captions shouldn't be platform-dependent. And even if it was, I am also testing using Chrome on Mac.

**Comment by dhubertus** [comment] 2021-03-19 20:28
@theodab Thank you for taking a look! Apologies it didn't go to plan, let me create some screen recordings and improve the repo steps. I'll pass the recordings along via the email provided.

**Comment by dhubertus** [comment] 2021-03-30 16:05
@theodab Apologies again for the delayed response, but I have sent over updated repro steps including a screen recording of these steps to assist with the issue.

Thanks again for taking a look and please reach out if we can help in any way!

**Comment by theodab** [comment] 2021-04-09 10:17
Alright. With the new repro steps and video you produced, I was able to reproduce this issue. Thanks for your patience!
I'll look into why this is happening. It does feel like a bug to me, you're right, so for now I'm marking it as a bug.

**Comment by theodab** [comment] 2021-04-30 02:54
With that fix, the embedded and non-embedded captions should no longer be able to play at the same time. I'm still looking into why your non-embedded captions are so out of sync, though. Sorry for the delays!

**Comment by dhubertus** [comment] 2021-04-30 17:16
Great to hear, thank you again for taking a look at this issue and for the update!

**Comment by theodab** [comment] 2021-05-07 10:10
So, your content is a multi-period manifest. It has a single master captions file that contains captions for the entire run-length, which is inserted separately into each non-ad period.
The content is super offset because if we are in (say) period 17 and see a captions file listed as an `AdaptationSet` on that period, we assume that the captions file is meant to start at the start time of period 17, so we offset everything by that amount of time. Thus, if you seek to right after an ad break ends, the captions "start over" from that point, so to speak.

According to the [DASH IOP](https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf), section `6.4.5. Guidelines for side-loaded TTML and WebVTT files`:

> Such external files are assumed to have a timeline aligned with the Period, so that TTML time
> 00:00:00.000 corresponds to the start of the Period. The presentation time offset is expected to be
> not presented, and if present, expected to be ignored by the DASH client.

So it sounds our current behavior is to-spec, and not a bug. With something as complex as the DASH spec, it always helps to check! In that case, then, each period should have its own caption file, that contains just the captions for that period, and is timed relative to the period rather than relative to the entire presentation.

I'm going to close this issue for now. If you run into any further caption sync/overlapping problems, feel free to re-open this! I didn't have a good way of testing the segmented captions solution, so I'm only mostly sure it will fix things.

**Closed by theodab** 2021-05-07 10:10 UTC
Labels: bug, priority:P1
