### ISSUE TITLE
AirPlay support HLS/FairPlay

### ISSUE THREAD

**Issue by raskri** [google/shaka-player#2177] opened 2019-10-08 06:39 UTC
I have implemented the initDataTransform function and set fairPlayTransform to false in version 2.5.5. HLS/FairPlay streaming works fine. 

But sending the stream over to an Apple TV with AirPlay does not work. I can see that the initDataTransform function is called but nothing more is happening. Apple TV sys-log complains about a "slow decrypt key". So I'm guessing there is some issue inside the handling of "webkitneedkey" event. Have you guys experienced the same issue?

**Comment by avelad** [comment] 2019-10-08 12:04
I have seen the same thing, and I venture to say that it is related to: https://github.com/google/shaka-player/issues/2031

**Comment by joeyparrish** [comment] 2019-10-08 18:10
We don't have an AppleTV device in our lab yet.  Let's work on the assumption that this is a duplicate of #2031 for now.  If we have a fix for that, @raskri, would you be able to test it for us on AppleTV?

**Comment by raskri** [comment] 2019-10-09 07:03
@joeyparrish, I can test yes! But I'm not sure if #2031 is related.

**Comment by karlg-arris** [comment] 2019-10-28 08:22
@joeyparrish 
One thing to note is that when an AirPlay session is established for FairPlay protected content, an EME key request event is proxied from the ATV via the browser CDM.  This request will be for the existing key/contentId.  
This also happens when AirPlay is disconnected.

In both cases the key request must be serviced by the license end-point (since each request contains session-bound crypto).  Is there a chance that filtering logic in Shaka is ignoring these requests as redundant?

Just a thought...

**Comment by TheModMaker** [comment] 2019-10-28 22:36
If the init data is the same, then we'll ignore the duplicate key request.  You can check to see if that is the issue by removing the duplicate checks and seeing if that works:

https://github.com/google/shaka-player/blob/02847e3b1ff51e2db85be64fa99e411cff087efe/lib/media/drm_engine.js#L536-L541

**Comment by gscragg** [comment] 2019-11-26 20:34
I can confirm removing that check got airplay working for me.

What is the way forward here?

The DRM Engine can listen for `webkitcurrentplaybacktargetiswirelesschanged` events and clear the `activeSessions_` property, or export an API method that we can call directly when we know we want to start an airplay session?

**Comment by avelad** [comment] 2019-11-27 07:56
I created https://github.com/google/shaka-player/pull/2257 to resolved this issue.

**Closed** 2020-01-03 20:20 UTC
Labels: enhancement

**Comment by joeyparrish** [comment] 2020-01-15 22:26
These changes have been cherry-picked for v2.5.8.
