### ISSUE TITLE
Shaka Play Demo page fails to load on certain Android devices

### ISSUE THREAD

**Issue by mikesalvia** [google/shaka-player#952] opened 2017-07-27 15:39 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

Yes, there is an issue for Android Chrome but it appears to happen at a different point and creates a different error.

**What version of Shaka Player are you using**:

2.1.5-debug (from Shaka Player Demo)

**Can you reproduce the issue with our latest release version**:

Yes

**Can you reproduce the issue with the latest code from `master`**:

Unknown

**Are you using the demo app or your own custom app**:

Demo

**If custom app, can you reproduce the issue using our demo app**:

Yes

**What browser and OS are you using**:

Various versions of Chrome for Android

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**

Loaded the page on Samsung S6

**What did you expect to happen?**

Dropdown to populate and player to load.

**What actually happened?**

No player loads and dropdown does not populate.

**Additional Notes**
I have been debugging this issue and noticed that on certain phones (Android version/Chrome version) Shaka fails to play and the demo page even fails to load, I haven't been able to find a pattern as to why it is happening but here are some of the findings.

Working (no reset required)
- Chrome 58.0.3029.83 on Galaxy S5 running Android 6.0.1
- Chrome 59.0.3071.125 on Galaxy S5 running Android 6.0.1

Working (after destructive reset of Chrome, cache only)
- Chrome 59.0.3071.125 on Google Nexus 5X running Android 6.0.0
- Chrome 59.0.3071.125 on Google Nexus 5X running Android 6.0.1

Not Working (even after resetting Chrome completely, removed Chrome and re-installed)
- Chrome 58.0.3029.83 on Galaxy S7 running Android 6.0.1
- Chrome 59.0.3071.125 on Galaxy S6 running Android 7.0.0

**Comment by mikesalvia** [comment] 2017-07-27 15:40
May relate to #519

**Comment by joeyparrish** [comment] 2017-08-04 19:10
@mikesalvia, can you attach a JavaScript debugger to your phone while it is in this failed state?  https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

It would be useful to see the logs, as that may provide us with a good clue about what has failed.  Based on the symptom (not populating the list), it is likely a network error or JavaScript exception.

**Comment by mikesalvia** [comment] 2017-08-07 16:14
@joeyparrish I will get this to you ASAP!

**Comment by mikesalvia** [comment] 2017-08-10 16:17
@joeyparrish I have been debugging this via Remote Debugger in DevTools with @hghazzi and we are seeing no errors in the Console. I have visit some other demo sites for DRM and this looks to be an issue also on demo.castlabs.com when trying to play protected content. In both situations, I never see a pop-up to allow my device to be uniquely ID'd for protected content. On other devices this dialogue is displayed and upon choosing `Yes`, content plays correctly.

If I disable protected content all together... The Shaka demo page successfully loads but all Widevine streams are disabled (greyed out).

This maybe not necessarily a Shaka-related issue but perhaps a Widevine/Chrome/Android issue.

**Comment by mikesalvia** [comment] 2017-08-10 16:26
@joeyparrish Screenshots of DevTools... Also one thing I was able to figure out was that it is when `return access.createMediaKeys();` is executed an exception is thrown...
<img width="1632" alt="screen shot 2017-08-10 at 12 21 00 pm" src="https://user-images.githubusercontent.com/6209204/29180849-117788ca-7dc7-11e7-93f0-c789555817bd.png">
<img width="970" alt="screen shot 2017-08-10 at 12 21 56 pm" src="https://user-images.githubusercontent.com/6209204/29180848-117450b0-7dc7-11e7-8e6c-fa42c7fd77c6.png">
<img width="797" alt="screen shot 2017-08-10 at 12 24 15 pm" src="https://user-images.githubusercontent.com/6209204/29180847-11739864-7dc7-11e7-883a-f3528b63df08.png">

**Comment by hghazzi** [comment] 2017-08-10 17:41
Also, on devices that do work, we see the chrome popup which asks to Allow Protected Content (attached). On the devices that does not work, it does not appear even after all site settings are cleared. Same thing is happening on https://demo.castlabs.com/, which seems to be using the shaka player

**Comment by joeyparrish** [comment] 2017-08-10 21:48
What exception is thrown from requestMediaKeySystemAccess?  I don't see it in any of your screenshots. 
 The error console screenshot doesn't show any exceptions or errors.

**Comment by mikesalvia** [comment] 2017-08-15 01:14
@joeyparrish I can investigate more but it looks like the exception is suppressed by the `.catch` block.

**Comment by mikesalvia** [comment] 2017-08-15 01:15
<img width="714" alt="screen shot 2017-08-14 at 9 15 02 pm" src="https://user-images.githubusercontent.com/6209204/29298449-adbb7c48-8135-11e7-88e2-1158209dc460.png">

This is the block I am referring to.

**Comment by mikesalvia** [comment] 2017-08-21 16:10
@joeyparrish I am doing some more digging and all I can see as far as an exception is a warning about `Robustness`... As seen in the screenshot above the exception is being caught and handled so nothing is displayed in console log.

**Comment by joeyparrish** [comment] 2017-08-22 23:23
@mikesalvia, the warning about robustness is generated by Chrome, not by us.  It is unimportant and misleading, and I apologize for the confusion.  (See http://crbug.com/720013 for more info.)

Inside the catch() block of the Promise chain, can you please log `arguments[0]`?  That will show us what the error was.  If createMediaKeys() throws an exception, that is highly unusual.  Normally, you would fail requestMediaKeySystemAccess instead.

Can you use Shaka Player v1?  The v1 demo didn't probe like this, and I'd be interested to see if it is the probing itself that is broken or if the failed probe is accurate.  Here's a quick link to v1.6.5 that will attempt to load and play a Widevine-encrypted asset: https://v1-6-5-dot-shaka-player-demo.appspot.com/?asset=//storage.googleapis.com/widevine-demo-media/sintel-4k-widevine/sintel.mpd;dash

And finally, I know this may seem like a dumb question, but are you sure you have Widevine on this device?

**Comment by joeyparrish** [comment] 2017-08-29 18:03
@mikesalvia, any feedback?  Can you log `arguments[0]` in the `catch()` clause?  Does v1 have the same issue?  Can you confirm that Widevine is present on the device?

**Comment by vaage** [comment] 2017-09-05 16:23
@mikesalvia Is this still an issue you are facing? If so, please take a look at what @joeyparrish is asking so that we can continue to help resolve this issue. If it is no longer an issue, please let us know so we can close the issue or feel free to close the issue yourself. Thanks.

**Comment by mikesalvia** [comment] 2017-09-06 15:46
@joeyparrish and @vaage was on vacation. Just returned I will work with @hghazzi on this when back in office. Sorry about delay.

**Comment by joeyparrish** [comment] 2017-09-06 15:55
No worries!

**Comment by mikesalvia** [comment] 2017-09-13 20:32
@joeyparrish So I checked and I do have WideVine module installed on my devices... I did some watching of `arguments[0]`.

And this is the value I saw... This also appeared to cycle through a few DRM solutions before completing... I think it hit my breakpoint in `catch` about 4-5 times before failing out and not being able to create keys...

<img width="435" alt="screen shot 2017-09-13 at 4 18 25 pm" src="https://user-images.githubusercontent.com/6209204/30399243-11600264-98a1-11e7-9967-10d1227574e4.png">
![screen shot 2017-09-13 at 4 20 36 pm](https://user-images.githubusercontent.com/6209204/30399240-111983de-98a1-11e7-83f2-074717c4276e.png)
![screen shot 2017-09-13 at 4 20 43 pm](https://user-images.githubusercontent.com/6209204/30399241-111e9ebe-98a1-11e7-9907-b44935f38342.png)
![screen shot 2017-09-13 at 4 29 50 pm](https://user-images.githubusercontent.com/6209204/30399242-1146f03a-98a1-11e7-936d-846ba59c94aa.png)

**Comment by joeyparrish** [comment] 2017-09-13 20:34
Sorry, I was unclear.  You're giving me arguments[0] right before createMediaKeys(), which is the MediaKeySystemAccess object.  I meant arguments[0] in the catch() statement right after createMediaKeys() fails.  That would be the error thrown by createMediaKeys().  Thanks!

**Comment by mikesalvia** [comment] 2017-09-13 20:36
That is the captured in the `DOMException: Unsupported keySystem` which is what `arguments[0]` gives me in the promise chain.

**Comment by mikesalvia** [comment] 2017-09-13 20:37
So the first screenshot the 1st console log is indeed where you said before createMediaKeys() the 2nd is inside of the catch after that had failed.

**Comment by mikesalvia** [comment] 2017-09-13 20:41
![screen shot 2017-09-13 at 4 41 12 pm](https://user-images.githubusercontent.com/6209204/30399641-61358dc6-98a2-11e7-8b63-ba5863b7c3f1.png)

**Comment by mikesalvia** [comment] 2017-09-14 16:34
@joeyparrish Will that help? We are finishing up a release today should be able to get some assistance from @hghazzi to provide any finer details.

**Comment by joeyparrish** [comment] 2017-09-14 16:58
I admit, I'm stumped.  I can't reproduce this, and all evidence ("Unsupported keySystem") points to Widevine being missing or unavailable on your device.

**Comment by joeyparrish** [comment] 2017-09-14 17:02
Shaka Player is only able to interact with Widevine through EME.  It seems that the request we're making of EME is correct, and EME is telling us that it can't fulfill the request.

Unless we can find something wrong with the request, there's nothing else Shaka Player can do to fix it.

It does seem strange that requestMediaKeySystemAccess() returns a MediaKeySystemAccess object, but createMediaKeys() fails.  Normally, requestMediaKeySystemAccess() should fail if the key system is unavailable.  If it succeeds, createMediaKeys() should also succeed.  So something is not right here.

You may need to file a bug with Chromium to pursue this further.  Please CC me on the bug when you do, and I will try to make sure it gets brought to the attention of the right people in Chrome.

**Comment by mikesalvia** [comment] 2017-09-28 15:27
@joeyparrish Thanks much! And will totally do!

**Comment by mikesalvia** [comment] 2017-10-05 19:53
@joeyparrish Opened a bug with Chromium some of there questions seemed odd but filled it best I could and included this link.

Here is the ticket in Chromium bug tracker... https://bugs.chromium.org/p/chromium/issues/detail?id=772120

**Comment by joeyparrish** [comment] 2017-10-07 18:41
Thank you!  We will follow along on crbug and do what we can to help there.

**Comment by joeyparrish** [comment] 2017-11-02 16:20
Closing here since the associated crbug has been closed.  Let us know if we can do anything else to help with this.

**Closed by joeyparrish** 2017-11-02 16:20 UTC
Labels: external, unable to reproduce
