### ISSUE TITLE
Firefox and CORS on manifest Redirect (302)

### ISSUE THREAD

**Issue by mjaddani** [google/shaka-player#1498] opened 2018-07-18 06:15 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.4.2

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**:Both

**If custom app, can you reproduce the issue using our demo app?**: Yes

**What browser and OS are you using?**:
Firefox 61 on Windows 10

**What are the manifest and license server URIs?**: see email

**What did you do?**
We have a service router who redirect all manifest request to the correct origine server. 
This redirect (302) works fine on Chrome but on Firefox we have this error

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur xxxxxxxxxxxxxxxx. Raison : échec de la requête CORS.
Impossible de charger « xxxxxxxxxxxxxxxxxx ». Un service worker a communiqué un objet « promise » à FetchEvent.respondWith() qui a été rejeté avec la raison « TypeError: NetworkError when attempting to fetch resource. ».

Do you have any  idee to resolve this ?

**What did you expect to happen?**
We want to have the same think like Chrome.

**What actually happened?**

**Comment by chrisfillmore** [comment] 2018-07-18 15:36
Is this the same as https://github.com/google/shaka-player/issues/1476 ?

**Comment by mjaddani** [comment] 2018-07-20 04:41
Yes i think, it's the same. Does exist any workaround ?

Best regards

2018-07-18 17:36 GMT+02:00 Chris Fillmore <notifications@github.com>:

**Comment by mjaddani** [comment] 2018-07-20 19:29
Yes you can reproduce with my  content.

I keep it for you, it’s very importante for us because we have projet for
football champions league

Best regards

Le ven. 20 juil. 2018 à 21:27, Joey Parrish <notifications@github.com> a
écrit :

**Comment by joeyparrish** [comment] 2018-07-20 19:39
I can reproduce in Firefox 61.0.1, 62.0b10, and 63.0a1.

The error logs from Firefox complain about our ServiceWorker, which is interesting.  It could be a bug in service_worker.js, or a bug in Firefox's ServiceWorker implementation, or maybe something in Firefox we can work around in our ServiceWorker.

I will dig a little deeper.

**Comment by mjaddani** [comment] 2018-07-20 19:41
Many thanks

2018-07-20 21:39 GMT+02:00 Joey Parrish <notifications@github.com>:

**Comment by mjaddani** [comment] 2018-07-23 10:01
I'have the same issue with IE11.

**Comment by joeyparrish** [comment] 2018-07-26 19:13
I haven't been able to figure this out yet.  In the mean time, I recommend that you not use a ServiceWorker in your application.  Our demo uses one, but if you aren't using ServiceWorker, you should not run into this bug.

**Comment by mjaddani** [comment] 2018-07-26 21:33
For disabling serviceWorker, we will just remove serviceworker.js ?


Le jeu. 26 juil. 2018 à 21:13, Joey Parrish <notifications@github.com> a
écrit :

**Comment by joeyparrish** [comment] 2018-07-26 21:49
That depends on what your application looks like.  Are you using our demo service worker in your app verbatim?

In the Shaka Player demo app, we have this snippet that registers the service worker:

https://github.com/google/shaka-player/blob/fa4954452663ae6d392b3a779e8b263d4dcd9aee/demo/main.js#L160

You would comment out the equivalent bit of code in your own app and then clear whatever service worker may already be installed by your browser.  In Chrome, you do this in the "Application" tab of the JS console.  In Firefox, I'm not sure where that happens.

If that is an effective workaround for you, then I recommend you do that for now until we can find the cause and provide a fix.

**Comment by mjaddani** [comment] 2018-08-01 11:06
We have found a solution, it's to use the params <Location> on the manifest. If we don't do a redirect but we rewrite the manifest with a good <Location> params, it's work on every Browser Firefox, Chrome, Edge, IE11.

**Comment by joeyparrish** [comment] 2018-08-30 21:54
Investigation into #1392 revealed that we are handling requests in our service worker that could be ignored instead.  This may have some bearing on this issue as well.

**Comment by mjaddani** [comment] 2018-08-30 21:58
Now, we rewrite manifest params "<Location>" on the mpd and it's works for all browser.

**Comment by joeyparrish** [comment] 2018-08-30 22:10
Now that I've dug a bit deeper, avoiding fetch handling in our service worker doesn't solve your problem.  Nor does removing the service worker completely.  I still get CORS errors in Firefox for your content.  So I suspect the problem is between Firefox and your server, and has nothing to do with Shaka.

Since you have a workaround anyway, may I close this issue?

**Closed** 2018-09-06 22:36 UTC
Labels: external, waiting on response
