### ISSUE TITLE
ShakaPlayer support persistent licenses on Edge browser

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2341] opened 2020-01-14 04:58 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest code from master

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Edge

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Windows-10 browser

**What are the manifest and license server URIs?**
Url from Demo Player

**What did you do?**
We want to download content offline using shaka-player on edge. 

**What did you expect to happen?**
Content should be downloaded.

**What actually happened?**
Shaka-player is not supporting persistent licenses on Edge. Shaka player need to support com.microsoft.playready.recommendation system for play ready support.

This issue is already discussed in #1495 

Dashjs support persistent licenses for edge with PR
https://github.com/Dash-Industry-Forum/dash.js/issues/2658

**Comment by sridhard** [comment] 2020-01-14 05:08
@swenkeratmicrosoft @TheModMaker @joeyparrish I used com.microsoft.playready.recommendation key system. Using this I am able to create a session with persistent-license. But if I reuse the persisted-license then I am getting the below error when I load the session with the sessionID.

DOMException: Failed to execute 'load' on 'MediaKeySession': Failed to find CDM session in handler map. (4294967295)

**Comment by joeyparrish** [comment] 2020-01-14 18:12
We don't yet support `com.microsoft.playready.recommendation` yet, as you pointed out.  So I think we have to close this as a duplicate of #1495.

**Closed** 2020-01-14 18:17 UTC
Labels: duplicate
