### ISSUE TITLE
Infinite buffering on Chromecast 1st generation

### ISSUE THREAD

**Issue by madsva** [google/shaka-player#1809] opened 2019-02-18 13:30 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.4.4 running on Chromecast

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Chromecast, CastReceiverManager Version: 2.0.0.0079, CAF Recever Version: 3.0.0040 (Styled media receiver or Custom Receiver). 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast 1st generation

**What are the manifest and license server URIs?**
I've send the URI to shaka-player-issues at google do com with ticket in subject

**What did you do?**
1) Connect to the styled media receiver (or to a custom media receiver)
2) Play back the stream
3) Stop the stream
4) Start the stream again

**What did you expect to happen?**
Playback would start

**What actually happened?**
Player is buffering and switches a frame once in a while, but never starts actual playback. Other streams works fine. Seems only to happen on Chromecast 1st generation, but buffering is significant on Chromecast Ultra as well.
See https://photos.app.goo.gl/G1XG7whVknBhiCb3A

**Comment by theodab** [comment] 2019-02-21 18:33
I tried the provided stream out on a Chromecast v1 in the newest version. Sometimes, it's able to play fine for a while, but eventually falls behind and gets stuck in eternal buffering. Other times, it gets stuck in eternal buffering from the start.
We perennially run into these kinds of issues; the hardware on v1 Chromecasts is pretty slow.

**Comment by mhosman** [comment] 2019-07-23 14:24
Same issue here!

**Comment by joeyparrish** [comment] 2020-04-08 00:02
I think I may have found the cause of this bug in Shaka Player while working on an unrelated issue.  At least, the mistake I just found in our sources could potentially explain this behavior on Chromecast.  I'll put together a fix as soon as possible and ask for someone to confirm the fix if they can.  Unfortunately, the original streams that were shared with us for this issue are no longer available.

**Comment by joeyparrish** [comment] 2020-04-08 00:10
The bug I found was introduced into our codebase about 1 month before this issue was filed, but the original issue referred to v2.4, and the bug was only released in v2.5.

Still, I hope it will help.  It's possible that the v2.5 refactors removed the original bug and replaced it with this one.  :-)

**Closed** 2020-04-08 21:32 UTC
Labels: bug

**Comment by joeyparrish** [comment] 2020-04-08 22:07
The fix has been pushed to the nightly build of the Shaka Player demo and the corresponding receiver app:

https://nightly-dot-shaka-player-demo.appspot.com/demo/

Please let us know if the behavior is improved or not.  Thanks!

**Comment by madsva** [comment] 2020-04-15 07:59
Thanks, appreciate it 👍 

I'll test as soon as https://github.com/google/shaka-player/issues/2338 has been deployed as well - thanks :-)

**Comment by joeyparrish** [comment] 2020-04-15 15:01
#2338 is marked as "unable to reproduce", so there's nothing to deploy for that.  We had another issue recently about a TTML parsing issue with non-ASCII subtitles.  Perhaps you're thinking of that issue?  That fix has already been deployed.

**Comment by madsva** [comment] 2020-04-15 15:17
Yeah, you're right, I'm mixing two issues.

I'm referring to a CAF issue: https://issuetracker.google.com/issues/147083944#comment18 where subtitles now are left-aligned - but the original issue with a small black subtitle box is fixed. Not sure if it's Shaka-player related or not, but it's for sure not a discussion to take in this issue. Thanks for your help :-)
