### ISSUE TITLE
MP3 HLS in Firefox "No decoders for requested formats" MP3 to MP4 remux required

### ISSUE THREAD

**Issue by jmooradi** [google/shaka-player#1292] opened 2018-02-10 00:36 UTC
Using information from #1210

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:
2.3.2

**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:
yes

**Are you using the demo app or your own custom app?**:
Demo app

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Firefox 59.0 & Mac High Sierra

**What are the manifest and license server URIs?**:
http://wilma.betalounge.com/mod/_definst_/mp3:lounge/2005/050910_dsl_de.mp3/playlist.m3u8

**What did you do?**
https://shaka-player-demo.appspot.com/demo/#asset=http://wilma.betalounge.com/mod/_definst_/mp3:lounge/2005/050910_dsl_de.mp3/playlist.m3u8;lang=es;build=uncompiled

**What did you expect to happen?**
mp3 to play

**What actually happened?**

**Player error 
category: 4
code: 9009
data: Array []
handled: false
message: "Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()"
severity: 2

Warning: Cannot play media. No decoders for requested formats: audio/mpeg

Firefox is able to play the mp3 if you paste an mp3 directly in the url

**Update 1:** Firefox returns false for MediaSource.isTypeSupported("audio/mpeg")

**Update 2:**  Looking further it appears firefox requires mp3 to be remuxed as mp4, is mux.js able to be used for this?
https://bugzilla.mozilla.org/show_bug.cgi?id=932516

**Comment by ismena** [comment] 2018-02-20 17:55
@michellezhuogg 
Do you happen to know whether mux.js can remuxe mp3 into mp4?

@joeyparrish 
Would you like me to schedule this?

**Comment by joeyparrish** [comment] 2018-02-20 18:04
I added it to the backlog for now.  We will be doing v2.5 planning as soon as v2.4 comes out, but v2.4 is already too large.

**Comment by joeyparrish** [comment] 2021-09-29 21:28
Part of this is Firefox's support, which we don't control.  The other part is our own support of MP3, which is part of "containerless" format support, tracked in #2337.

I'll close this as a duplicate.

Duplicate of #2337

**Closed by joeyparrish** 2021-09-29 21:28 UTC
Labels: type: enhancement
