### ISSUE TITLE
Shaka Requests HLS Segments that don't exist (segment0000.ts)

### ISSUE THREAD

**Issue by rdglge** [google/shaka-player#2363] opened 2020-01-30 21:10 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.8

**Can you reproduce the issue with our latest release version?**
I believe 2.5.8 is the latest

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried master

**Are you using the demo app or your own custom app?**
I am using a demo and put in my own manifest url.

**If custom app, can you reproduce the issue using our demo app?**
not custom

**What browser and OS are you using?**
Chrome on Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
not embedded

**What are the manifest and license server URIs?**

I am not using a license server

I am running on a machine on my local network with a 172.x.x.x ip address

**What did you do?**

Created an audio only HLS stream using gstreamer.
Gstreamer was configured to only keep the last 5 segments on disk to prevent filling the disk.
In my case I have a master.m3u8 that points to a playlist.m3u8
The playlist.m3u8 lists the 5 segments as seg00154.ts, seg00155.ts, seg00156.ts, seg00157.ts and seg00158.ts

**What did you expect to happen?**
I expect to the player to download and play seg00154.ts 

**What actually happened?**

The player requests seg00000.ts and gets a 404 response and then throws an error.

shaka-player.compiled.js:376 GET http://172.16.3.158/hls/1/seg00000.ts 404 (Not Found)
shaka-player-app.js:46 Error code 1001 object D {severity: 2, category: 1, code: 1001, data: Array(5), handled: false}

**Comment by joeyparrish** [comment] 2020-01-30 21:46
If you don't give us a URL for your content or instructions on how to reproduce the issue, we will not be able to help you.  You can send private information to shaka-player-issues@google.com if necessary.

**Comment by rdglge** [comment] 2020-01-30 21:51
@joeyparrish,

I don't have a public facing web server to host this on.

I could provide the segment files and the playlists if you have somewhere to upload to. (The content is based on big buck bunny).

**Comment by rdglge** [comment] 2020-01-30 21:55
master.m3u8 looks like this:

#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2",AUDIO="default-audio-group"
playlist.m3u8

playlist.m3u8  looks like this

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:154
#EXT-X-TARGETDURATION:5

#EXTINF:3.9893331527709961,
seg00154.ts
#EXTINF:3.9893331527709961,
seg00155.ts
#EXTINF:3.9893331527709961,
seg00156.ts
#EXTINF:3.9893331527709961,
seg00157.ts
#EXTINF:3.754666805267334,
seg00158.ts
#EXT-X-ENDLIST

**Comment by ismena** [comment] 2020-01-31 19:09
Hi @rdglge 
This is very interesting. So, you have a LIVE playlist that starts with a seg00000, but only keeps 5 segments at a time, right?
And you loaded it into the player as soon as it started running?

It's gonna be hard to debug without us having a way to repro it, but I'll do must best to blindly debug with you. What it sounds like is that there *was* a 000 segment at some point, but it's long gone by the time the player decided to request it.
Can you try this on our [nightly demo page](https://nightly-dot-shaka-player-demo.appspot.com/demo/) (make sure you're running an uncompiled build) and run the following commands in your debugger command line:
1) shakaDemoMain.player_.getAssetUri() - does it return the same URI that you expected for the your playlist?
2) shakaDemoMain.player_.isLive() - does it return true?

Also, please take a screenshot of the stack trace of the error, when you get it in the debugger and paste it here for me.

**Comment by rdglge** [comment] 2020-01-31 19:21
I did not load it into the player as soon as it started running. That is the point with a live stream. The player cannot assume there is a segment0 on the server.  The player could join the stream at any point during the stream.

I emailed  shaka-player-issues@google.com the playlist files and the segment files.

In order to reproduce the bug, place the files in a directory being served by a web server (I use apache2 in this case). Then give shaka-player the manifest of the master playlist file. This should reproduce the bug.

**Comment by rdglge** [comment] 2020-01-31 19:29
I tried to load the manifest from the demo page but it seems to require https.

I tried:

shakaDemoMain.player_.load("http://http://172.16.3.158/hls/1/master.m3u8");





Mixed Content: The page at 'https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled' was loaded over HTTPS, but requested an insecure resource 'http://http//172.16.3.158/hls/1/master.m3u8'. This request has been blocked; the content must be served over HTTPS.

**Comment by rdglge** [comment] 2020-01-31 22:07
OK. I was trying to reproduce this today at the following url:

https://rdglge.github.io/shaka-demo/

It works as expected.

I can no longer reproduce the error I was seeing yesterday.

**Comment by joeyparrish** [comment] 2020-02-01 00:58
I was also unable to reproduce the issue using the playlist text you sent.

**Comment by joeyparrish** [comment] 2020-02-01 00:59
Since none of us, including the OP, can reproduce the issue, I think we should go ahead and close it.  @rdglge, please feel free to reach out again if you need anything else.

**Closed by joeyparrish** 2020-02-01 00:59 UTC
Labels: unable to reproduce
