### ISSUE TITLE
Allow multiple language preferences

### ISSUE THREAD

**Issue by llooz** [google/shaka-player#3655] opened 2021-09-20 16:07 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
no, custom requirement

**What browser and OS are you using?**
macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

will send to the email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

We have a requirement to select the default language based on a sorted priority list
Example:
1. Italian
2. English
3. French

`preferredAudioLanguage` accepts only 1 language so we use `selectAudioLanguage`, by choosing the right language, when `.load` fullfills. 

**What did you expect to happen?**
The playback starts with best video and audio variants from the startup.

**What actually happened?**

All works fine but the video variant initially selected isn't the "best fit" for the initial bandwidth, it will switch to the best one just after the first segment is fetched.
This happens only if we call `selectAudioLanguage`, if we use `preferredAudioLanguage` the video variant selected is the best one. (video and audio variants are separate tracks)

It seems that using `selectAudioLanguage` inside the `.load` fulfillment or the first `trackschanged` event somehow interfers with the initial ABR selection. 
Is it a bug or is there another way to prioritize the language selection based on the available ones?

**Comment by joeyparrish** [comment] 2021-10-04 21:18
I'm going to rename this as an enhancement to accept multiple preferred languages, in priority order.  This is already the format of `navigator.languages`, so an array in our config would work nicely with the information the browser provides.

**Comment by joeyparrish** [comment] 2021-10-04 21:21
We would be happy to review a PR for this.  Backward compatibility is a concern, so I would suggest adding fields like preferredAudioLanguage**s** (plural) to the config, and deprecating the original, single-string fields.  The original fields could then be removed in v4.

If you want to contribue, look at the source to `player.configure` in lib/player.js and note the way we use `shaka.Deprecate.deprecateFeature` to manage changes to config fields.

**Comment by joeyparrish** [comment] 2021-10-04 21:27
It turns out that we already have #1591, so I will actually close this as a duplicate of that, and update that with the comments I left here.  Thanks!

**Comment by joeyparrish** [comment] 2021-10-04 21:27
Duplicate of #1591

**Closed** 2021-10-04 21:27 UTC
Labels: status: duplicate, type: enhancement, flag: seeking PR, flag: good first issue, priority: P2
