### ISSUE TITLE
Safari: Clearing buffer after end of presentation reached freezes the video

### ISSUE THREAD

**Issue by bhh1988** [google/shaka-player#992] opened 2017-08-26 21:59 UTC
I am on Safari 10.1.2, and I am testing this on HEAD of master on shaka but I believe this bug's been around for awhile now. I noticed that when I try to select a different variant (e.g. alternative audio or video stream) and have the buffer be cleared, the video freezes. After debugging it, I see that the problem is that in `media_source_engine.js`, in the `remove_` function, once `remove` gets called on the sourcebuffer there is no 'updateend' event emitted. I discovered that this is only a problem once buffering has already reached the end of the presentation (and Firefox/Chrome do not have this problem). Suspecting it was a Safari bug, I dug up something @joeyparrish had filed on webkit awhile back: https://bugs.webkit.org/show_bug.cgi?id=159230. When I hit his example script [here](http://storage.googleapis.com/shaka-demo-assets/_bugs/safari-mse-clear/index.html), it actually works fine on Safari (updateend event is emitted after calling `remove()`). So I'm suspecting that maybe it's not just a browser bug but shaka does something to the sourcebuffer after the end of presentation is reached, which puts it in a bad state such that it doesn't emit 'updateend'.

I have a test sample [here](https://cloud.box.com/s/ijcafs3s65if1nx1krc3wvdm3c98zsum). It contains a manifest.mpd that points to two audio tracks, which have different language tags. Load it in the demo app on Safari, and switch between languages - once the buffering has reached the end of the video, you'll notice that switching between languages freezes the playback. Logs show that it's stuck on trying to clear the sourcebuffer. You can shorten the period in the manifest.mpd to reproduce more quickly.

**Comment by joeyparrish** [comment] 2017-08-28 20:45
We have polyfills to work around MediaSource issues on both Safari 9 and 10, and they may need to be tweaked or updated.  We will try to reproduce, file bugs on Apple as appropriate, then find a workaround in JS.  Thanks!

**Comment by theodab** [comment] 2017-09-06 22:42
I've reproduced the issue. It looks like it also happens if the end of the buffered range has reached the end of the video, not just if the video has ended.
It definitely looks like a polyfill issue; if I disable the MediaSource polyfill it works better. I'll look into fixing it.

**Comment by theodab** [comment] 2018-01-08 23:40
I tried to reproduce this now, running 11.0.2, and I can't reproduce this anymore.
So I guess it was an issue on Safari's end, and it's fixed now? Or maybe over the past 120 days I have totally forgotten how to reproduce it, but I think it's that first one.
Tentatively closing for now.

**Closed by theodab** 2018-01-08 23:40 UTC
Labels: bug
