### ISSUE TITLE
load promise doesn't resolve on iOS Safari

### ISSUE THREAD

**Issue by benbro** [google/shaka-player#2062] opened 2019-07-30 14:59 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Not relevant

**What browser and OS are you using?**
Safari 12.1.1 on iOS 12.3.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
No relevant

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-live-assets/player-source-aac.m3u8

**What did you do?**

```javascript
let player = new shaka.Player(videoEl);
player.load(src).then(() => {
  console.log('load callback');
}).catch(e => {
  console.log(' load error');
})
```

**What did you expect to happen?**
load promise should resolve and the callback get called.

**What actually happened?**

The load callback isn't called on iOS Safari.

**Comment by CurtisConway** [comment] 2019-08-12 22:00
I've observed the same thing happening myself. I think it's because behind the scenes on browsers that support HLS natively, but do not support Media Source Extensions, the HTMLMediaElement is just being fed the manifest by targeting the element and just using `src="{manifest}"`.

I don't know for sure, so don't quote me on this, but I think the promise is resolved when the MediaElement dispatches one of the 'loadedmetadata', 'loadeddata' or 'canplaythrough' events. On IOS if you listen to these events directly you'll notice none of them actually hit when the source is passed through. What I did as a workaround was just wrap the `.load` method into its own promise.

```javascript
function loadSource(){
    const supportsMSE = typeof MediaSource !== 'undefined';

    return new Promise((resolve) => {
        if (supportsMSE) {
            this.shakaPlayer.load(this.hlsManifestUrl)
                .then(() => {
                    resolve();
                });
        } else {
            this.mediaElement.src = this.hlsManifestUrl;

            setTimeout(() => {
                resolve();
            }, 100);
        }
    });
}
```

**Comment by joeyparrish** [comment] 2019-08-14 17:38
We did much of our early development for iOS on desktop Safari by disabling MediaSource.  I will need to go back and test in more detail on iOS specifically.  Thanks for the report!

**Comment by chrisfillmore** [comment] 2019-08-14 18:26
@joeyparrish more generally, does the load() promise have a particular meaning? It doesn't indicate that playback has started or is even necessarily capable of starting, since DRM flows are still pending. Whether using MediaSource or src=, it seems the Promise can basically be ignored, except in cases where it rejects.

**Comment by joeyparrish** [comment] 2019-08-14 20:17
It indicates that the content has been "loaded", which frankly, we should define in a much more specific way.  Once loaded, track lists are valid, seeking is possible, etc.

And a Promise not resolving at all is definitely a bug, though, even if the app ignores it.

**Comment by bjg2** [comment] 2019-08-22 10:21
Hey guys, we've been debugging this for few days though shaka code and browserstack. Yes, "loadeddata" never happens on iphone safari. We're working with HLS there (I guess that's the only option for that setup).

There is a simple enough repro you can do:
 * Go to https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-live-assets/player-source.m3u8;panel=SEARCH;build=debug_compiled and take a look at the console
 * On desktop chrome load finishes as expected (logs continue to fire after Starting load...):
![image](https://user-images.githubusercontent.com/6639273/63506300-8af68280-c4d5-11e9-886e-dcc0a7f1e380.png)
 * On iphone safari it does not (logs stop at Starting load...):
![image](https://user-images.githubusercontent.com/6639273/63506379-aeb9c880-c4d5-11e9-915f-714bf1d4f207.png)
 * If you play this video in desktop chrome everything works as expected, there are resolutions to choose, etc:
![image](https://user-images.githubusercontent.com/6639273/63506600-1e2fb800-c4d6-11e9-9e18-a4d26abfa5fc.png)
 * If you play this video in iphone safari you can do it, but some options are missing, like resolutions:
![image](https://user-images.githubusercontent.com/6639273/63506556-07896100-c4d6-11e9-8f1a-ad1cda3450d1.png)

At videobolt.net we use shaka for our video player. When there are a lot of videos on a page our usecase is: we do the load, get manifest, and stop the loading of the video until it is clicked. When the video is clicked we continue the load as usual. Also manifest data is important for us because of the resolutions etc, and that data seems not to be available if load doesn't end.

What's the suggestion on how to solve this issue? Should we try to downgrade to some earlier shaka version?

**Comment by CurtisConway** [comment] 2019-08-22 15:09
@bjg2 - Unfortunately you'll never be able to see the resolutions in IOS Safari. Shaka utilizes a browser API called [Media Source Extensions](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API). MSE is pretty much what makes adaptive playback possible in the browser.

We can see by looking at the [Compatibility Table](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API#Browser_compatibility), IOS Safari is the only modern browser that remains unsupported. I believe this is because Apple has their own native HLS implementation in Safari, it works by default by just appending the .m3u8 playlist to the source attribute on the HTMLMediaElement. Unfortunately it's not quite as robust as Shaka's MSE implementation, so you don't get the ability to enable/disable specific tracks in the playlist.

I've had success with IOS by checking the [readystate on the MediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState) after my loadSource method in my comment above. On IOS the ready state should pretty much always be 2 at that point. In that case I just call the  load method on the MediaElement directly _`shaka.getMediaElement().load()`_ and playback works as expected.

**Comment by avelad** [comment] 2019-12-04 12:27
One solution it's use [progress](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/progress_event) event to resolve the promise,  but i don't know if it has other implications.

**Comment by joeyparrish** [comment] 2020-01-27 23:31
I'm unable to reproduce this issue with Shaka Player v2.5.8 or the nightly build running on iOS 12.  I get the 'loadeddata' event as expected with the content in our demo app.  (I tested specifically with the first item, "Big Buck Bunny: the Dark Truths".)

@avelad, @benbro, @CurtisConway, @bjg2, can you please try again in the latest builds?

 - v2.5.8: https://v2-5-8-dot-shaka-player-demo.appspot.com/demo/
 - nightly: https://nightly-dot-shaka-player-demo.appspot.com/demo/

**Comment by avelad** [comment] 2020-01-28 07:39
For me it's working with the last release.

Note: I only tested in iOS 12 and 13.

**Comment by joeyparrish** [comment] 2020-01-28 20:15
Thanks for confirming!

**Closed by joeyparrish** 2020-01-28 20:15 UTC
Labels: unable to reproduce
