### ISSUE TITLE
Live stream with DRM(Widevine / Playready) on Tizen 4 cannot be played

### ISSUE THREAD

**Issue by skipness** [google/shaka-player#1822] opened 2019-02-27 03:49 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.4.7

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Custom app

**If custom app, can you reproduce the issue using our demo app?** No, because demo app doesn't have any live stream with DRM for me to test with

**What browser and OS are you using?** Tizen 3 & Tizen 4

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** UA40MU6310 (Tizen 3) & UA43NU7100 (Tizen 4)

**What are the manifest and license server URIs?** I cannot provide it for personal reason

**What did you do?** 
Play live stream with DRM on Tizen TV
I tested both devices with same code and network environment
(I also tried [live stream without DRM](https://github.com/google/shaka-player/blob/7d014fd195206593a06a525283c6d3382ac680fb/demo/common/assets.js#L678) on Tizen 4 and it can be played)

**What did you expect to happen?**
Live stream can be played without any issues with Widevine or Playready on Tizen 3 and Tizen 4

**What actually happened?**
- Tizen 3.5
Can be play without any issues with both DRM

- Tizen 4.0
Widevine →  Keep loading and not playing anything
![image](https://user-images.githubusercontent.com/8035517/53464334-cebb8280-3a84-11e9-8d2c-b21e7360986f.png)
![image](https://user-images.githubusercontent.com/8035517/53464344-d4b16380-3a84-11e9-8eaa-363fe628219d.png)

Playready → Keep loading and not playing anything
![image](https://user-images.githubusercontent.com/8035517/53463818-ff022180-3a82-11e9-9946-683fb9216dd5.png)
![image](https://user-images.githubusercontent.com/8035517/53463824-045f6c00-3a83-11e9-88fe-69d9c3b638b9.png)

**Comment by ismena** [comment] 2019-02-27 22:11
Hi @skipness, thanks for reporting.

Firstly, do you think you're able to provide us the manifest for for the repro?
Feel free to send it privately to [shaka-player-issues@google.com](mailto:shaka-player-issues@google.com). It's really hard for us to diagnose problems without a clear repro.

Secondly, unfortunately, we don't have a Tizen 4 to test on, and our mastermind @joeyparrish says we're not getting one anytime soon :(
Joey, do you think, there's any way around this?

Either way, I'll leave the issue open for now in case someone outside the team is able to provide some insight.

Sorry :(

**Comment by skipness** [comment] 2019-02-28 02:48
>Hi @skipness, thanks for reporting. ...

@ismena I will talk with my colleagues to see if they can provide any manifest for your team to test.

**Comment by skipness** [comment] 2019-03-01 03:13
Little update
Even the live stream can be play in some rare case, I got the following result(using Widevine)：
![image](https://user-images.githubusercontent.com/8035517/53613897-a82b5200-3c12-11e9-984b-bb357dc78bcf.png)

**Comment by joeyparrish** [comment] 2019-03-01 03:30
@skipness, since your log shows the "stall inside buffered range" over and over, you could try making a change to this code to skip stall detection on Tizen:

https://github.com/google/shaka-player/blob/1095ecb009b363b8889998015793f0526ca6e01e/lib/media/stall_detector.js#L144-L148

If that doesn't help, we'll definitely need a way to reproduce the issue.  Thanks!

**Comment by selesh3** [comment] 2019-03-07 19:46
We see exactly the same behavior with Tizen 3 and Tizen 4. We will be happy to provide necessary information.

**Comment by skipness** [comment] 2019-03-08 07:45
> We see exactly the same behavior with Tizen 3 and Tizen 4. We will be happy to provide necessary information.

Good to hear someone else can provide information as we cannot provide any😟

**Comment by skipness** [comment] 2019-03-08 07:46
> @skipness, since your log shows the "stall inside buffered range" over and over, you could try making a change to this code to skip stall detection on Tizen:
> 
> [shaka-player/lib/media/stall_detector.js](https://github.com/google/shaka-player/blob/1095ecb009b363b8889998015793f0526ca6e01e/lib/media/stall_detector.js#L144-L148)
> 
> Lines 144 to 148 in [1095ecb](/google/shaka-player/commit/1095ecb009b363b8889998015793f0526ca6e01e)
> 
>  shouldBeMakingProgress() { 
>    // If we are in WebOS platform disable StallDetector. This is because WebOS 
>    // TVs tend to have long hardware pipelines that respond slowly, so we tend 
>    // to mistake slow operation for a stall. 
>    if (shaka.util.Platform.isWebOS()) { return false; } 
> If that doesn't help, we'll definitely need a way to reproduce the issue. Thanks!

@joeyparrish It doesn't help.

**Comment by joeyparrish** [comment] 2019-03-08 19:28
@skipness, thank you for reporting back on that.  We will try to reproduce with the information sent to us by  @selesh3.

**Comment by skipness** [comment] 2019-04-02 03:16
Any updates?

**Comment by vaage** [comment] 2019-04-02 17:43
@skipness we have not had time to dig deeper into this issue. Our team is spread thin right now and as a result, we had to focus on efforts. This issue demands a more resources than we have right now, specifically we don't have a Tizen 4 tv in our lab right now.

Rest assured that as long as "needs triage" is on this issue, it does get seen every week and reviewed to see if we can make significant progress.

**Comment by joeyparrish** [comment] 2019-08-14 17:16
@skipness, if you have time, could you please retest with Shaka Player v2.5.4 and let us know if this is still an issue in the latest release?

**Comment by skipness** [comment] 2019-08-15 04:11
v2.5.4 fixed the issue on Tizen. 
But I found that I cannot play live stream(with DRM) on WebOS. 
On WebOS 3.3, the live stream will freeze at one frame and on WebOS 4.0, the stream will only play frame by frame

**Comment by joeyparrish** [comment] 2019-08-15 18:05
Thanks for the update.  Unfortunately, we don't officially support WebOS yet, because we don't have a WebOS device in our lab yet.  So there's no way that we would be able to debug this right now.

Since the last time we offered advice on this, stall detection has become configurable.  On WebOS, it defaults to disabled.  Can you please try v2.5.4 with stall detection explicitly re-enabled?

```js
player.configure('streaming.stallEnabled', true);
```

**Comment by skipness** [comment] 2019-08-16 07:53
Update
 actually both version of WebOS can play the live stream without problem, but once I seek WebOS 3.3 will freeze at the same frame and 4.0 will played frame by frame. I have enabled stall detection already.
Here is what the console show:
![image](https://user-images.githubusercontent.com/8035517/63151440-18e8ee00-c03c-11e9-8f75-dcfea6521b62.png)

**Comment by joeyparrish** [comment] 2019-08-16 18:07
@skipness, so does WebOS still behave this way with stall detection turned off?

**Comment by skipness** [comment] 2019-08-19 09:28
Slightly different, after seeking live stream will remain at the same frame.
Here is the log:
![image](https://user-images.githubusercontent.com/8035517/63254635-a760a800-c2a6-11e9-815c-83fc224c938e.png)

**Comment by joeyparrish** [comment] 2019-08-19 19:21
Well, this seems at least like an improvement.  The 'frame-by-frame' behavior you got with stall detection enabled was the stall detector trying to kick the playhead to get it to move.  This doesn't seem to be effective in this case, so I would advise you leave it off.

The problem, though, is that it does appear to be stalled after a seek.  I'm not sure why this would be.

@theodab, can you reproduce this with the content emailed to us (search 1822) on our Tizen 3 device?

@skipness, can you please teach us how to get that wonderful remote debugger on Tizen?  Is it only on Tizen 4+?

**Comment by skipness** [comment] 2019-08-20 07:03
> @skipness, can you please teach us how to get that wonderful remote debugger on Tizen? Is it only on Tizen 4+?

Sure. Actually the debugger is available on all Tizen and WebOS platform and have quite similar way to open it (as both platform's IDE are base on Eclipse).

1. Install [Tizen Studio](https://developer.tizen.org/ko/development/tizen-studio/download?langredirect=1)
2. Create an [empty project](https://developer.tizen.org/ko/development/tizen-studio/web-tools/managing-projects/project-creation-wizard)
![image](https://user-images.githubusercontent.com/8035517/63317324-f78e4780-c344-11e9-8906-011bca2e16a4.png)
 Select `Template` here
![image](https://user-images.githubusercontent.com/8035517/63317356-21476e80-c345-11e9-8a24-4d24d9971e73.png)
Choose `Custom` at right bottom and make sure the platform is `TV-samsung v4.0`, you may required to install the 4.0 package to continue
![image](https://user-images.githubusercontent.com/8035517/63317448-7b483400-c345-11e9-8cef-e59cd765f234.png)
Choose empty project here (others are ok but empty project is easier for copy and paste work)
3. Create [certificate profile and certificates](https://developer.tizen.org/ko/development/tizen-studio/web-tools/managing-projects/certificate-registration)
4. Make sure you and your TV are on the same network
TV side:
Goto TV Apps section and type  `12345`, there should be a pop up for you to toggle developer mode and an input field to enter your PC ip address (details [here](https://developer.samsung.com/tv/develop/getting-started/using-sdk/tv-device)). Turn on developer mode and enter your ip address
PC side:
![image](https://user-images.githubusercontent.com/8035517/63318386-e6473a00-c348-11e9-9e6c-bb1213467543.png)
Launch remote device manager here
![image](https://user-images.githubusercontent.com/8035517/63318450-02e37200-c349-11e9-8b0a-1bf98b01c04d.png)
Then enter your TV's ip address here and click the connect toggle
5. Last step, right click the project you created and select `Debug As > Tizen Web Application`, the debugger will be display automatically

I have simplified the steps so if you have any problems when setting up／you need steps to get debugger on WebOS, please let me know.

**Comment by chrisfillmore** [comment] 2019-08-20 16:33
Not sure if this is your experience as well @skipness, but we have found the Tizen debugging process to be _full_ of gotchas. So, fyi Shaka team, try everything twice. Sometimes it just works the second time.

**Comment by skipness** [comment] 2019-08-21 03:01
@chrisfillmore Yea, I spent few days to figure out how to install apps and debugging on Tizen at the beginning...

**Comment by joeyparrish** [comment] 2021-05-05 18:36
It sounds like the main issue was resolved on Tizen some time ago, and that the remaining issues are on WebOS.  Since this issue was opened about Tizen, and since WebOS is not officially supported by us, I'm going to close this issue.  If you wish, you can open a new issue about WebOS, or the OP can comment `@shaka-bot reopen` to reopen this issue if they disagree.

**Closed by joeyparrish** 2021-05-05 18:36 UTC
Labels: TV/STB, bug, contributions welcome
