### ISSUE TITLE
[ERROR] *** A required dependency is missing: C:\Program Files\nodejs\node.EXE

### ISSUE THREAD

**Issue by theyashl** [google/shaka-player#3704] opened 2021-10-17 13:34 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v2.6.1

**What browser and OS are you using?**
Windows 10 Home

**What did you do?**
1. Clone git repo
2. `cd shaka-player`
3. run `python build\all.py`

**What did you expect to happen?**
Generate Compiled Bundle in dist folder

**What actually happened?**

Got an error saying, required dependency is missing: Node js. with path- `C:\Program Files\nodejs\node.EXE`.
But, node.exe is already installed with version 14.15.4. And can be accessed by the mentioned path.
![image](https://user-images.githubusercontent.com/49603432/137629443-08061182-b958-4b50-a395-47a69ca8b647.png)

**Comment by TheModMaker** [comment] 2021-10-18 17:47
Probably a duplicate of #3551.  Try cloning the project into a folder with a shorter path (e.g. `C:\shaka`).

**Closed as completed** 2021-10-20 06:36 UTC
Labels: type: bug, status: archived
