### ISSUE TITLE
shaka-player and webGL with drm content

### ISSUE THREAD

**Issue by eipporko** [google/shaka-player#379] opened 2016-05-12 10:47 UTC
Hello, 
I'm developing some drafts to study the viability of make video mosaics using webGL.
I've thought to give DASH support through a shaka player, building a texture with the content of the html5 video element attached to the player and rendering it in a webGL context.

I had successful with non-drm content. But with Widevine videos I've suffered some issues depending on the device, with Android mobiles the test works really good but in Mac/Linux, despite the shaka player works as expected, the texture in the webGL context is black. I'm using chrome both Android and (Mac/Linux).

Someone knows why this weird behavior? 

I am testing with the links supported in the documentation of shaka-player
Non-DRM: [//storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd](//storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd)
DRM: [//storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd](//storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd)

**Comment by joeyparrish** [comment] 2016-07-01 06:15
Sorry for taking so long to reply.  This slipped through the cracks.

I don't know why you would get that behavior.  We really don't have any expertise in webGL.  I would guess that some platforms and DRM systems may prevent you from capturing content by design, but that is just my best guess.

Since we don't have details on the internals of this, and since WebGL and capturing frames are both very much out of the scope of what Shaka is trying to provide, I'm going to go ahead and close this issue.  I'm very sorry we weren't able to help you with this, but I hope that Shaka has at least been a useful tool for mosaics of non-DRM content.

**Closed by joeyparrish** 2016-07-01 06:15 UTC
Labels: question

**Comment by iamprem** [comment] 2017-11-27 21:50
@eipporko were you able to make this work for widevine DRM videos in chrome? I'm planning to capture video frames of DRM protected using webGL and send it to server in my application.
