### ISSUE TITLE
Widevine CDM issues with robustness settings on Android 6.0.1

### ISSUE THREAD

**Issue by mathieuedet** [google/shaka-player#2171] opened 2019-10-04 07:56 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.5 (same problem with 2.5.4)

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
Custom application

**If custom app, can you reproduce the issue using our demo app?**
Get 3015 error code with demo.

**What browser and OS are you using?**
Android 6.0.1 (but works with 7.0 on same device)
Chrome 79 and Chrome 73 on Android 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Galaxy S6

**What are the manifest and license server URIs?**

Will be sent by email

**What did you do?**

Try to play DASH or HLS content with Widevine CENC (Android supports CMAF on 7.1 and above only)

**What did you expect to happen?**
Video should be play without any problem

**What actually happened?**

Playback stops at 5 seconds without shaka error (like a license error) on my app. When I flash device with Android 7.0, CDM version is updated from 3.0 to 4.0 and it works fine with cenc on same Chrome version, I don't know if the cdm version update is the source of the problem.

It works when I don't put robustness and ask only SD content.

Does someone know if the problem comes from the Android CDM version or from another thing ? 

The robustness config seems to be not functional on the demo, security_level received on the proxy should be L1 (for the S6) when I set video and audio robustness in navigation menu but this params seems to not be us. 
When I harcode video robustness in drm_engine.js to HW_SECURE_ALL and audio robustness to SW_SECURE_CRYPTO, I get error code 3015 error code.

**Comment by joeyparrish** [comment] 2019-10-04 16:32
So it fails on Android 6, but succeeds on Android 7, and in both cases, you set videoRobustness to HW_SECURE_ALL and audioRobustness to SW_SECURE_CRYPTO.  Is that correct?

**Comment by joeyparrish** [comment] 2019-10-04 16:37
If you're trying to force L1, you may have the wrong audio robustness.  From Chromium's source code, it appears that HW_SECURE_CRYPTO would be used for audio on L1.  Can you please try again with audioRobustness set to HW_SECURE_CRYPTO and videoRobustness set to HW_SECURE_ALL?

https://cs.chromium.org/chromium/src/chrome/renderer/media/chrome_key_systems.cc?l=267-282&rcl=a13bcafd0f7c272da29af0f68738ae879c1bf5a4

```c++
  // Robustness.
  using Robustness = cdm::WidevineKeySystemProperties::Robustness;
  auto max_audio_robustness = Robustness::SW_SECURE_CRYPTO;
  auto max_video_robustness = Robustness::SW_SECURE_DECODE;

#if defined(OS_CHROMEOS)
  // On ChromeOS, we support HW_SECURE_ALL even without hardware secure codecs.
  // See WidevineKeySystemProperties::GetRobustnessConfigRule().
  max_audio_robustness = Robustness::HW_SECURE_ALL;
  max_video_robustness = Robustness::HW_SECURE_ALL;
#else
  if (base::FeatureList::IsEnabled(media::kHardwareSecureDecryption)) {
    max_audio_robustness = Robustness::HW_SECURE_CRYPTO;
    max_video_robustness = Robustness::HW_SECURE_ALL;
  }
#endif
```

**Comment by joeyparrish** [comment] 2019-10-04 16:38
I'm tagging this as "working as intended" for now, but please try the recommended change and see if that helps.  If not, we can remove that tag and take a deeper look.

**Comment by mathieuedet** [comment] 2019-10-07 10:32
Thanks for your response @joeyparrish .It's my problem yes. I've tested but always the same problem. 

It's right, HW_SECURE_CRYPTO is the higher supported robustness for the audio on my device, so now, my code is checking every robustness support and select higher supported for audio and higher supported for video. Despite that, it always fails at 5 sec.

Just to be sure, I flashed my phone again on Android 7.0, and it works on 7.0. I don't have other phones with 6.0.1 or cdm version v3.0.0 to test.

I checked chromium sources and I found _supported_cdm_versions.h_ which seems to indicate that current minimum required version of cdm is 10.

When my device is on 7.0, license server logs indicates : 
'widevine_cdm_version' : 'v4.0.0-android'
oem_crypto_api_version: 11

When my device is on 6.0, license server logs indicates : 
'widevine_cdm_version' : 'v3.0.0-android'
oem_crypto_api_version: 10

Maybe, oem_crypto_api_version too ?

**Comment by joeyparrish** [comment] 2019-10-07 22:47
> It's right, HW_SECURE_CRYPTO is the higher supported robustness for the audio on my device, so now, my code is checking every robustness support and select higher supported for audio and higher supported for video. Despite that, it always fails at 5 sec.

With the robustness level corrected, what is the error code in Shaka Player?

> I checked chromium sources and I found supported_cdm_versions.h which seems to indicate that current minimum required version of cdm is 10.

This doesn't relate to Android, but to the versioned interface for the desktop CDM.  Desktop Chrome uses software-backed DRM, while Android has a completely different CDM implementation built into the OS.  So please ignore this.

**Comment by mathieuedet** [comment] 2019-10-08 09:50
> This doesn't relate to Android, but to the versioned interface for the desktop CDM. Desktop Chrome uses software-backed DRM, while Android has a completely different CDM implementation built into the OS. So please ignore this.

OK thanks, I preffered to ask to be sure.

I had a bad errors event implementation on my project, this is why I didn't get errors. So now all is ok for errors handling, I can indicate that the error code is **6008** with data[0] : 

> "Failed to execute 'update' on 'MediaKeySession': Update session failed."

Not everytime, I get these errors just after (link to update session failed) :

> "PIPELINE_ERROR_DECODE: video decode error"
or
> "PIPELINE_ERROR_DECODE: audio decode error"

According to the shaka player documentation, 6008 error code is surely a bad license or malformed license, but it works like a charm on the same device on Android 7.0 with a cenc encryption too. Is there is license edition to do for some cdm version ?

**Comment by joeyparrish** [comment] 2019-10-08 18:11
I'm not sure how the Android version could affect this.  Are you running a license server proxy or the Widevine license SDK?

**Comment by mathieuedet** [comment] 2019-10-09 07:40
I'm not sure too but we know that CMAF was added to Android 7.1, maybe there is a thing between 6.0.1 and 7.0 that was edited too...
I'm running license server proxy (we need to add some extra informations). I send you logs by mail.

**Comment by joeyparrish** [comment] 2019-10-09 16:06
@mathieuedet, I think that whatever this is, it seems to be an issue outside of Shaka Player.  I would suggest you contact Widevine for further support: https://www.widevine.com/contact

**Comment by mathieuedet** [comment] 2019-10-10 08:55
I have contacted Widevine support, I'll back on this issue once I'll have their response

**Comment by joeyparrish** [comment] 2019-12-02 21:22
Since it's been a while, I'm going to close this for now.  If you'd like to reopen the issue, just reply with `@shaka-bot reopen`.  Thanks!

**Closed by joeyparrish** 2019-12-02 21:22 UTC
Labels: working as intended
