### ISSUE TITLE
Playback issue with multi-period DASH live stream on latest Shaka version

### ISSUE THREAD

**Issue by rohitsw-g** [google/shaka-player#2654] opened 2020-06-16 05:13 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://dai.google.com/linear/dash/event/0ndl1dJcRmKDUPxTRjvdog/manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v3.0.0-uncompiled

Playback works fine with older versions of Shaka
https://v2-5-13-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://dai.google.com/linear/dash/event/0ndl1dJcRmKDUPxTRjvdog/manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What browser and OS are you using?**
Chrome/83.0.4103.97 

**What did you do?**
Play back stream with latest shaka demo
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://dai.google.com/linear/dash/event/0ndl1dJcRmKDUPxTRjvdog/manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What did you expect to happen?**
Playback should be smooth across periods. 

**What actually happened?**
Seems like the player is mixing up base urls across periods.  Media files are being requested using mixed URLs causing download failures.

**Comment by theodab** [comment] 2020-06-16 16:00
Actually, wait, no, we've already fixed this. Check out the nightly:
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://dai.google.com/linear/dash/event/0ndl1dJcRmKDUPxTRjvdog/manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

I think this is a duplicate of #2650.

**Closed by theodab** 2020-06-16 16:00 UTC
Labels: bug
