### ISSUE TITLE
Cannot read property 'next' of null

### ISSUE THREAD

**Issue by MilosRasic** [google/shaka-player#2956] opened 2020-11-02 09:46 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**What version of Shaka Player are you using?**

3.0.5

**Can you reproduce the issue with our latest release version?**

no

**Can you reproduce the issue with the latest code from `master`?**

no

**Are you using the demo app or your own custom app?**

custom app

**If custom app, can you reproduce the issue using our demo app?**

no

**What browser and OS are you using?**

Vizio SmartCast, Chromium v72 web engine

This is the only platform where we've released with shaka-player 3.0.5 for now so this doesn't mean other platforms are not affected.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

Caught in production on multiple Vizio SmartCast models, firmware versions 4.60.23-1 and 1.10.15.1-2.

**What are the manifest and license server URIs?**

Requires custom license token and I don't think it's necessary to understand the problem.

**What did you do?**

Caught an error in production using our crash reporting tool with the following stack trace

```
Error Playback SDK - Cannot read property 'next' of null 
    Playback SDK - Cannot read property 'next' of null 
    node_modules/shaka-player/lib/media/streaming_engine.js:1515:18 C.b
     [synthetic:es6/generator_engine] :796:37 Da
     [synthetic:es6/generator_engine] :700:9 P.next
     [synthetic:es6/execute_async_generator] :53:11 b
```

which points to the following block of code in streaming_engine.js:

```
    // Only advance the segmentIterator if the stream hasn't changed.
    if (mediaState.stream == stream) {
      const ref = mediaState.segmentIterator.next().value;
      shaka.log.v2(logPrefix, 'advancing to next segment', ref);
    }
```

Obviously `mediaState.segmentIterator` was null.

This happens rarely, only 6 times since our first release with shaka-player 3.0.5 on October 30th.

Was unable to reproduce while playing the exact same content.

**What did you expect to happen?**

If something went wrong with the stream, playback or network, I'd expect a standard Shaka Player error with error code and error name.

**What actually happened?**

JavaScript error was thrown.

**Comment by joeyparrish** [comment] 2020-11-03 01:50
This sounds very similar to #2768, which was just fixed in v3.0.5.  We'll take a look.  Thanks!

**Comment by sky-hugolima** [comment] 2020-11-04 16:20
Hi !
We've also observed a significant increase (from 0.001% to 0.5% of all playbacks) of the same error reported by the author, from using Shaka 3.0.1 to 3.0.5., and we've also traced the error down to:
```
if (mediaState.stream == stream) {
      const ref = mediaState.segmentIterator.next().value;  // segment iterator is sometimes null when we get here
      shaka.log.v2(logPrefix, 'advancing to next segment', ref);
    }
```
I've been able to reproduce it, but it's very hard to find a way to reproduce it consistently, we've also done an A/B release with a custom shaka version where we changed the previous check to `(mediaState.stream == stream && mediaState.segmentIterator)` which resulted in eliminating all uncaught exception errors, but seemed to have caused additional unrecoverable stalls in re-buffering.

I also have no idea how it's possible to reach a state where we have the same stream (so there wasn't a switch ?) but the `segmentIterator` on the `mediaState` is `null`.

**Comment by joeyparrish** [comment] 2020-11-04 16:32
Yes, I'm puzzled by that, too.  We had a similar issue that was only solved by careful analysis of StreamingEngine code paths.  I expect this will turn out the same.

**Comment by sky-hugolima** [comment] 2020-11-05 14:23
I'm not 100% sure but I suspect the issue is caused if when during `fetchAndAppend_` (which stores a reference to the current stream), there's a double call to `switchInternal_` where the first call changes to a different stream, clearing the `mediaState.segmentIterator`  and the second one goes back to the previous stream, causing the protection logic on the `append_`  method to fail. 

This is the only cause I can think of that would make this happen, and since our initial mitigation that added and additional check (mediaState.stream == stream && mediaState.segmentIterator)  actually caused the stream to stall, it makes some sense since now we'll never call next on segmentIterator.

**Comment by sky-hugolima** [comment] 2020-11-05 14:37
On the other side, I don't quite understand why the `mediaState` even needs to store a copy of the `segmentIterator` on the first place... I mean the `mediaState.segmentIterator`  belongs to `mediaState.stream` (e.g. it's the segmentIterator for the stream's segmentIndex), and the segmentIndex should be already created before we need it on `makeAbortDecision`  or on `update_`, so couldn't we just access it directly the the stream when we need it, instead of keep a copy of it on the mediaState (that then needs to be set null on switches) ?

**Comment by sky-hugolima** [comment] 2020-11-05 14:44
It can also be relevant to mention that had set `switchInterval`  to 2 seconds on VOD, which is probably at play here, allowing multiple switches to occur during a segment request.

**Comment by zh3** [comment] 2020-11-05 17:43
> I'm not 100% sure but I suspect the issue is caused if when during `fetchAndAppend_` (which stores a reference to the current stream), there's a double call to `switchInternal_` where the first call changes to a different stream, clearing the `mediaState.segmentIterator` and the second one goes back to the previous stream, causing the protection logic on the `append_` method to fail.
> 
> This is the only cause I can think of that would make this happen, and since our initial mitigation that added and additional check (mediaState.stream == stream && mediaState.segmentIterator) actually caused the stream to stall, it makes some sense since now we'll never call next on segmentIterator.

Based on @sky-hugolima 's reasoning the problem would happen if there was an adaptation change, followed by an immediate change back to the previous adaptation. To test this I added a 1Mbps and 2.5Mbps profile for network throttling in chrome dev tools and set the switchInterval to 0.1 in the demo app. Then switching between these bandwidth profiles reproduces the problem relatively reliably, especially if you switch the bandwidth when the streaming engine logs "Aborting current segment request."

Video of reproducing the issue in demo app:
https://drive.google.com/file/d/1LCFbNO-47IMAxIqc6BI5IowD85LQ3hmu/view?usp=sharing

**Comment by sky-hugolima** [comment] 2020-11-06 12:57
>On the other side, I don't quite understand why the mediaState even needs to store a copy of the segmentIterator on the first place

I think I do understand it now... the segmentIterator instance must be created and owned by whatever process wants to download segments, so that for example we could have concurrent playback and download (for offline viewing) of the same stream, and that's why the stream's segmentIndex doesn't initialise and keep the iterator itself on creation.

**Comment by TheModMaker** [comment] 2020-11-10 19:11
The reason we have a per-MediaState iterator is because they are iterators.  An iterator is a stateful object that holds a position within a list as you iterate over it.  So when we seek or switch streams, we need to create a new iterator so we have the new position.  This is used for streaming so we download the current segment and move the iterator forward.  So the current iterator should also point to the same stream as we are currently using.  We set the iterator to `null` to force other code to get a new iterator for the new position.

If the error is in [advanceToNextSegment_](https://github.com/google/shaka-player/blob/3484ac8c7c236c76b69d887a17688b39985a93d4/lib/media/streaming_engine.js#L1574), I'm not sure why it would stall if we also added a check for `segmentIterator != null`.  After that function, it should schedule another update and the [onUpdate_ call](https://github.com/google/shaka-player/blob/3484ac8c7c236c76b69d887a17688b39985a93d4/lib/media/streaming_engine.js#L858) should create a new iterator.

**Closed** 2020-11-23 21:18 UTC
Labels: bug
