### ISSUE TITLE
Stuttering in video on large .mpd files

### ISSUE THREAD

**Issue by raskri** [google/shaka-player#408] opened 2016-06-09 10:29 UTC
Using .mpd files with large scrollback buffers(8000 lines, 3 hours) creates stuttering in video stream in Chrome(50.0.2661.102 (64-bit)). I'm using Widevie DRM. 

This is not an issue on Firefox(47).
Tested on 1.6.X and 2-beta2.

Im guessing its do to the parsing of the file .mpd file each 5th second or so, but as it is not stuttering in Firefox(47), is there maybe a way to optimize and make the stuttering stop for Chrome?

**Comment by joeyparrish** [comment] 2016-06-10 04:57
Sounds like a duplicate of #405, assuming your content uses SegmentTimeline or SegmentList.  You can follow along there if so.  If not, let us know and we can reopen and investigate.

I can't guess why the issue is noticeable for Chrome but not Firefox, but it shouldn't matter to the fix.

**Closed by joeyparrish** 2016-06-10 04:57 UTC
Labels: duplicate
