### ISSUE TITLE
webcomponentsjs: xml parsing failure

### ISSUE THREAD

**Issue by shanmugapriyaEK** [google/shaka-player#1349] opened 2018-03-09 14:19 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**:2.3.3

**Can you reproduce the issue with our latest release version?**:yes

**Can you reproduce the issue with the latest code from `master`?**:No

**Are you using the demo app or your own custom app?**:custom app

**If custom app, can you reproduce the issue using our demo app?**:No

**What browser and OS are you using?**:IE11 and Edge

**What are the manifest and license server URIs?**:

**What did you do?** I updated our application from 2.8.8 to 2.3.3. Playback fails in IE 11 and Edge with error code 9009

**What did you expect to happen?** Expected to play

**What actually happened?** Load failed. 

Can you please help me out. Same content is playing in the shaka demo application

**Comment by joeyparrish** [comment] 2018-03-09 17:28
The docs for that error code are unclear: https://v2-3-3-dot-shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:9009

They currently state:

> When the manifest contains no period playable streams, it means the manifest is unsupported by the browser.

But they should say something more like:

> The content container or codecs are not supported by this browser.  For example, this could happen if the content is WebM, but your browser does not support the WebM container, or if the content uses HEVC, but your browser does not support the HEVC codec.

If you can provide the manifest and license server URIs we requested in the issue template, we could help you understand what container/codec is not supported in your case.  Can you provide us with the manifest URI?

I will update the docs for that error code.

**Comment by joeyparrish** [comment] 2018-03-09 17:32
We also appear to have made a mistake in the error code.  The 9000's are used for offline storage problems, which this is not.  It should have been assigned an error code in the 4000's.

**Comment by shanmugapriyaEK** [comment] 2018-03-12 08:44
Thank you Joey. I have shared the demo app where you could play the content. 
Note: I am able to play the content in shaka demo app (2.3.3) as well as in our sample app with shaka version 2.8.8
But when I updated our application from 2.8.8 to 2.3.3 , I could not play the content in IE11 as well as in Edge.

**Comment by joeyparrish** [comment] 2018-03-12 10:43
Do you mean 2.2.8?  2.8.8 is still in the future at this point.  :-)

**Comment by chrisfillmore** [comment] 2018-03-12 15:25
@joeyparrish https://github.com/google/shaka-player/commit/4dec8786bd5ea5876a4b1e57439987fd030a1519 changed XmlUtils.findChildren and moved `child instanceof Element` out of the assertion. This check is returning false in IE11 in our custom app, and playback is failing. If I remove the check, playback works fine.

I have no explanation for why the instanceof check returns false in our custom app. Shaka demo app works fine. If I write a simple test app, the instanceof check returns true. We don't polyfill DOMParser or anything like that so I have no idea why we're seeing this problem. We'll keep digging.

(If you have any ideas or speculation, I'd be happy to hear it.)

**Comment by joeyparrish** [comment] 2018-03-12 15:46
@chrisfillmore, is this the same app as @shanmugapriyaEK?  Or just a similar result in a separate app?

**Comment by joeyparrish** [comment] 2018-03-12 15:47
Since the docs have been clarified for the error code, I've removed the "docs" label and put this back into the triage queue.  We will try to reproduce the issue on IE and see if there is something that needs to be fixed in the library.

**Comment by chrisfillmore** [comment] 2018-03-12 15:56
Sorry yes @shanmugapriyaEK and I are working on the same app.

**Comment by joeyparrish** [comment] 2018-03-12 16:01
Wonderful, thanks.  That's useful information, as is the bit about the XML parsing.  We will look into it soon.

**Comment by chrisfillmore** [comment] 2018-03-12 16:05
Also, I should add, `child instanceof Element` returns false whether we test in 2.2.8 or 2.3.3.

We also get the error in Edge.

**Comment by joeyparrish** [comment] 2018-03-12 16:06
Understood.  Thanks!

**Comment by chrisfillmore** [comment] 2018-03-12 17:03
I have both our custom app, and the Shaka demo app, running side-by-side in separate tabs in MS Edge 40.15063.0.0, both with uncompiled Shaka v2.3.3. I'm setting a breakpoint in MpdUtils.parseXml, on line 418 `if (xml) {`. I am testing with the same mpd in both.

In our custom app, typing `xml instanceof Document` returns `false`. In the Shaka demo app, the same check returns `true`. I am baffled by this result.

**Comment by chrisfillmore** [comment] 2018-03-12 17:11
Fyi our custom app index.html declares `<!DOCTYPE html>`.

**Comment by chrisfillmore** [comment] 2018-03-12 17:11
Here is the content I'm testing with:
https://qpvod.cdnwo.net.rogers.com/ss/s/astr0632826002107302/2017-07-27-14-39-15/ASTR0632826002107303/output_dash.ism/index-r.mpd

**Comment by chrisfillmore** [comment] 2018-03-12 17:40
@joeyparrish does the Shaka demo app load the library in a different way than a client app would via the three script tags?

```
<script src="./debug/shaka-player/third_party/closure/goog/base.js"></script>
<script src="./debug/shaka-player/dist/deps.js"></script>
<script src="./debug/shaka-player/shaka-player.uncompiled.js"></script>
```

**Comment by joeyparrish** [comment] 2018-03-12 20:52
You may want to compare results with the uncompiled, debug, and release builds:

https://shaka-player-demo.appspot.com/demo/#build=uncompiled
https://shaka-player-demo.appspot.com/demo/#build=debug_compiled
https://shaka-player-demo.appspot.com/demo/#build=compiled

**Comment by shanmugapriyaEK** [comment] 2018-03-13 09:35
All the uncompiled, debug, and release builds of Shaka demo application is working fine.

**Comment by chrisfillmore** [comment] 2018-03-13 21:07
I've determined that this is triggered by some component of our client UI application. It is definitely not a Shaka bug (feel free to add external label).

I don't know exactly the source... there are some UI libraries we use (VueJS, webcomponents.js), perhaps they are having some impact in IE11 and Edge which is triggering this behaviour (shadow DOM? I barely know anything about UI dev anymore).

**Comment by joeyparrish** [comment] 2018-03-13 21:09
Shadow DOM doesn't sound right to me.  Could there be a polyfill installed by one of those?  Perhaps over Element, Node, or DomParser?

**Comment by chrisfillmore** [comment] 2018-03-14 16:49
I've narrowed it down to an old version of [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs) that we use:

https://github.com/webcomponents/webcomponentsjs/releases/tag/v0.7.23

When I remove this dependency from our app, I don't get the instanceof failures. Still not sure exactly what is causing the failure though.

**Comment by joeyparrish** [comment] 2018-03-14 16:53
Thanks!  Since you have narrowed in down to webcomponentsjs, I'm going to let you continue the investigation on your own.  I don't think we'll have much to contribute since we have no experience with that library.  Sorry we weren't able to help with this one, but I'm glad you're making progress.  Let us know if there's anything we can offer.

**Comment by chrisfillmore** [comment] 2018-03-14 17:00
If I'm able to isolate the bug and provide a reproducible test case, I will file a bug with Microsoft and link it here. I will also test if newer versions of webcomponentsjs have the same issue. I'll keep you posted.

**Comment by chrisfillmore** [comment] 2018-03-14 17:09
Looks like webcomponentsjs polyfills Document, Element, etc. That's what's causing the failures.

**Comment by joeyparrish** [comment] 2018-03-21 21:58
Error code docs update for cherry-picked for v2.3.4.

**Comment by joeyparrish** [comment] 2018-04-12 21:40
@chrisfillmore, do you have a bug link with webcomponentsjs that we can track?  Or since you mentioned that it was "an old version", have you managed to solve this by upgrading webcomponentsjs?

**Comment by chrisfillmore** [comment] 2018-04-12 22:01
I have not yet tested a newer version of webcomponentsjs. I just filed a ticket internally to upgrade. If you don't mind waiting until the end of next week, then I'll update you with the results of the upgrade. If it's still a problem, I will file a ticket with webcomponentsjs.

**Comment by joeyparrish** [comment] 2018-04-12 22:10
Sounds good.  Thanks!

**Comment by pcruiksh** [comment] 2018-05-03 16:03
I can confirm upgrading to recent webcomponents v1.2.0 resolves the failing instanceof checks

**Comment by chrisfillmore** [comment] 2018-05-03 18:06
@joeyparrish we are satisfied to close this ticket. Thanks

**Comment by joeyparrish** [comment] 2018-05-03 18:10
Great, thanks!

**Closed by joeyparrish** 2018-05-03 18:10 UTC
Labels: external
