### ISSUE TITLE
Shaka player is not working on iPhone device.

### ISSUE THREAD

**Issue by WhiteDove101** [google/shaka-player#1113] opened 2017-11-07 17:13 UTC
iPhone/iPad issues.
After I install all successfully, it is working on Chrome, Firefox and Opera for Windows and Mac OS.
Also it is working well on Android device.
But it is not played on iPhone/iPad device.
The video is not loaded and played.
I tested it on Chrome and Safari on iPhone/iPad.
![img_0412](https://user-images.githubusercontent.com/26065238/32507273-0f8cdda6-c3b5-11e7-9167-cc459a352816.PNG)
![img_0415](https://user-images.githubusercontent.com/26065238/32507274-0ff6976e-c3b5-11e7-82ed-508bd414fc7a.PNG)

**Comment by joeyparrish** [comment] 2017-11-07 17:39
CC @kqyang for resolution

@WhiteDove101, we do not currently support iOS browsers due to the lack of MediaSource API (a critical API we need in the browser to do adaptive playback).

I'm closing this as a duplicate of #997, in which we are making plans to support iOS in a limited capacity through Apple's native HLS implementation.  The most we would be able to do on iOS is pass the HLS manifest URL down to Apple and let them play it back for us, so this would prevent Shaka Player from having any control over buffering, networking, etc.

In the mean time, you can use Apple's HLS implementation directly on iOS browsers:

```js
video.src="/path/to/foo.m3u8";
video.play();
```

What we will provide in future as part of #997 will be no more than a convenient wrapper around that.

**Closed by joeyparrish** 2017-11-07 17:39 UTC
Labels: duplicate

**Comment by WhiteDove101** [comment] 2017-11-07 18:21
Thanks.
