### ISSUE TITLE
In Android 5 chrome, the shaka player can not request a license.

### ISSUE THREAD

**Issue by mateon01** [google/shaka-player#1027] opened 2017-09-18 06:38 UTC
hi there.

During the test in the mobile environment, i check that the request to issue a license does not work and leave this inquiry.

Shaka 2.2.1 does not work properly on some Android devices. 

Shaka Player can not process license requests in Android 5 version of Chrome.

Android7 and version 6 of the same environment confirmed normal operation.

If you have any information about this issue, please share it.

**Comment by theodab** [comment] 2017-09-18 22:30
This issue appears to be a duplicate of #1023. I will close this one, since the older issue has more discussion.

**Closed** 2017-09-18 22:31 UTC
Labels: duplicate
