### ISSUE TITLE
playing back live manifest with segment timeline and gaps between periods stucks 

### ISSUE THREAD

**Issue by igorshevach** [google/shaka-player#592] opened 2016-11-16 16:28 UTC
- What version of Shaka Player are you using?
v2.0.0-debug

  - Can you reproduce the issue with our latest release version?
yes

  - Can you reproduce the issue with the latest code from `master`?
it's master

- Are you using the demo app or your own custom app?
demo app

  - If custom app, can you reproduce the issue using our demo app?
-

- What did you do?

played back test dvr(live) stream with discontinuities  

  - What content did you load?
   the manifest below describes last 200 sec of video/audio content   
   the live timestamps are bound to UTC through both UTCTiming and presentation delay 
 so that player could buffer and start playing without delay.

    - If standard demo asset, which one?
custom manifest
    - If custom asset, what manifest and license server URIs?
[manifest.txt](https://github.com/google/shaka-player/files/595092/manifest.txt)

  - How did you interact with the content, if at all?
watched it

- What did you expect to happen?
playback switches periods while advancing

- What actually happened?
playback stuck at the end of period before gap
in the logs it specifies first segment number belonging to next period which it is unable to find in the previous one. basically the playback time is clipped to last period despite the live buffer range which advances on:

playhead.js:169 seekrangeEnd: 532620583 earliestStart: 53261943
(audio:53) timeNeeded=532614344.226
(audio:53) next position known: position=53261436
(audio:53) segment does not exist: currentPeriod.startTime=532614254.517 position=53261436

live window is: 53261943 - 532620583
timeNeeded is clipped to the last period it used to playback
next segment number calculated is: 53261436
however it belongs to period succeeding the period (currentPeriod.startTime=532614254.517)
hence the segment is not found.

**Comment by joeyparrish** [comment] 2016-11-16 19:24
The manifest text is not enough to debug.  We would need an actual manifest URL in order to access the content and reproduce your issue.

However, it sounds like this is a duplicate of #555.  We don't currently support gaps in media, but in #555 we are considering how best we could do that in the future.  Please follow along there.

**Closed** 2016-11-16 19:24 UTC
Labels: duplicate, enhancement
