### ISSUE TITLE
Chrome drops frames on resuming playback

### ISSUE THREAD

**Issue by interlark** [google/shaka-player#3006] opened 2020-11-25 04:03 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.6

**Can you reproduce the issue with our latest release version?** yes

**Can you reproduce the issue with the latest code from `master`?** yes

**Are you using the demo app or your own custom app?** yes

**If custom app, can you reproduce the issue using our demo app?** no-custom

**What browser and OS are you using?**  Chrome\Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** no-embedd

**What are the manifest and license server URIs?** Let's say https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd

**What did you do?** I found very annoying thing to me: sometimes when you do pause and play back again, the video on Chrome browser drops frames. And visually it seems that when you un-pause it - it skips frames. It happens on Chrome, I've tested on FF - it's ok there. Is it wellknown issue, any workarounds?

**What did you expect to happen?**  No any stutters, freezers, dropping frames.

**What actually happened?** Frames skips on resuming playback.

Note: maybe I wrong, but FF when video is PAUSED, sometimes plays 1 extra frame - maybe that's why when it resumes it dosen't skip any.

You can try in on [Sintel](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=uncompiled) or any other video from [shaka-player-demo.appspot.com](https://shaka-player-demo.appspot.com/)

Maybe I could do something manually to avoid such behavior? Like as FF, play 1 extra frame when it need it.

**Comment by interlark** [comment] 2020-11-25 04:32
I've tested the issue with videojs, hls.js and dash.js. This bug remains on all of them. That's so frustrating. So, there no way to overcome it? If there's some Windows users, could you answer if the issue exist on the latest Windows NT (with Chrome browser)?

**Comment by joeyparrish** [comment] 2021-02-18 01:14
This sounds like a nuance of browser behavior that we have no control over in JavaScript.  I'm sorry about that!

My advice is to file issues on the various browser vendors and describe the issue and steps to reproduce it in as much detail as you can:

 - Chrome/Chromium: http://crbug.com/
 - Safari/WebKit: https://bugs.webkit.org/
 - Firefox: https://bugzilla.mozilla.org/

**Comment by joeyparrish** [comment] 2021-02-18 01:14
I'm going to close this for now, since it doesn't appear that we can do anything about it.

If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!

**Closed by joeyparrish** 2021-02-18 01:14 UTC
Labels: external
