### ISSUE TITLE
HLS ClearKey implementation not working.

### ISSUE THREAD

**Issue by sbbullet** [google/shaka-player#2588] opened 2020-05-23 17:47 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes. But I couldn't find the one with exact issue I am facing.

**What version of Shaka Player are you using?** 2.5.11 and mux.js

**Why is my ClearyKey implementation not working with HLS VOD? Please help me.**

I encrypted the video with the shaka packager for HLS VOD. I used raw encryption and provided keys for corresponding DRM labels as well. But upon providing the same key_id and key as used for encryption and the same when configuring shaka player DRM. But it throws` Error code 4026 object` 

Commands I have used.

```
 $audioKeyId = 'c67a47172d17c1deb95c29a52912d3c8';
      $audioKey = 'fa3fe0aff6fd7997cde83936f072325c';

      $SDKeyId = '5c7dae345fba69c9c255ae1a89837ee3';
      $SDKey = '0fdb23138c7fe6095f5ef004ed102cae';

      $HDKeyId = 'a65387d9505de7d4bd32f4a7073ea776';
      $HDKey = '699b310358ad75065271bb8d80d4d828';

                            (packager \
                                        'in={$this->videoFolder}/input720.mp4,stream=audio,segment_template={$this->videoFolder}/segmented/audio/\$Number\$.aac,playlist_name={$this->video->slug}/segmented/audio/audio_main.m3u8,hls_group_id=audio,drm_label=AUDIO' \
                                        'in={$this->videoFolder}/input360.mp4,stream=video,segment_template={$this->videoFolder}/segmented/video/360p_\$Number\$.ts,playlist_name={$this->video->slug}/segmented/video/360p_main.m3u8,iframe_playlist_name={$this->video->slug}/segmented/video/360p_iframe.m3u8,drm_label=SD' \
                                        'in={$this->videoFolder}/input540.mp4,stream=video,segment_template={$this->videoFolder}/segmented/video/540p_\$Number\$.ts,playlist_name={$this->video->slug}/segmented/video/540p_main.m3u8,iframe_playlist_name={$this->video->slug}/segmented/video/540p_iframe.m3u8,drm_label=SD' \
                                        'in={$this->videoFolder}/input720.mp4,stream=video,segment_template={$this->videoFolder}/segmented/video/720p_\$Number\$.ts,playlist_name={$this->video->slug}/segmented/video/720p_main.m3u8,iframe_playlist_name={$this->video->slug}/segmented/video/720p_iframe.m3u8,drm_label=HD' \
                                        --segment_duration 4 \
                                        --fragment_duration 4 \
                                        --enable_raw_key_encryption \
                                        --keys label=AUDIO:key_id={$audioKeyId}:key={$audioKey},label=SD:key_id={$SDKeyId}:key={$SDKey},label=HD:key_id={$HDKeyId}:key={$HDKey} \
                                        --hls_master_playlist_output \"{$this->mpdPath}/{$this->video->slug}.m3u8\"
```

**My Shaka Player Setup**

```
<!DOCTYPE html>
<html>
  <head>
    <!-- Shaka Player compiled library: -->
    <script src="https://cdn.jsdelivr.net/npm/shaka-player@2.5.11/dist/shaka-player.compiled.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mux.js@5.6.2/dist/mux.min.js"></script>
  </head>
  <body>
    <video id="video"
           width="640"
           controls autoplay></video>
  </body>
  <script>
  	var manifestUri = "http://127.0.0.1:8000/contents/DRMTest/faint-official-video-linkin-park.m3u8";



function initApp() {
  // Install built-in polyfills to patch browser incompatibilities.
  shaka.polyfill.installAll();

  // Check to see if the browser supports the basic APIs Shaka needs.
  if (shaka.Player.isBrowserSupported()) {
    // Everything looks good!
    initPlayer();
  } else {
    // This browser does not have the minimum set of APIs we need.
    console.error('Browser not supported!');
  }
}

function initPlayer() {
  // Create a Player instance.
  var video = document.getElementById('video');
  var player = new shaka.Player(video);

  // Attach player to the window to make it easy to access in the JS console.
  window.player = player;

 player.configure({
   	drm: {
   		clearKeys: {
   			'c67a47172d17c1deb95c29a52912d3c8': 'fa3fe0aff6fd7997cde83936f072325c',
   			'5c7dae345fba69c9c255ae1a89837ee3': '0fdb23138c7fe6095f5ef004ed102cae',
   			'a65387d9505de7d4bd32f4a7073ea776' : '699b310358ad75065271bb8d80d4d828',
   		}
    }
   });

  // Listen for error events.
  player.addEventListener('error', onErrorEvent);

  // Try to load a manifest.
  // This is an asynchronous process.
  player.load(manifestUri).then(function() {
    // This runs if the asynchronous load is successful.
    console.log('The video has now been loaded!');
  }).catch(onError);  // onError is executed if the asynchronous load fails.
}

function onErrorEvent(event) {
  // Extract the shaka.util.Error object from the event.
  onError(event.detail);
}

function onError(error) {
  // Log the error.
  console.error('Error code', error.code, 'object', error);
}

document.addEventListener('DOMContentLoaded', initApp);
  </script>
</html>
```

Please help me

**Comment by TheModMaker** [comment] 2020-05-26 16:34
4026 is [HLS_KEYFORMATS_NOT_SUPPORTED](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4026).  This is probably a duplicate of #2146.

**Comment by joeyparrish** [comment] 2020-05-27 22:23
Yes, this appears to be a duplicate of #2146.  The root of the issue is that we don't support the "identity" key format in HLS.  #2146 is to track adding that feature.

I'm going to close this issue now and tag @sbbullet in the other one to bring it to their attention.  If you're interested in contributing a PR to add support for this key format, we'd be happy to have your help!

**Closed by joeyparrish** 2020-05-27 22:23 UTC
Labels: question
