### ISSUE TITLE
fails to play demo HLS content on Shaka demo page

### ISSUE THREAD

**Issue by dulmandakh** [google/shaka-player#1012] opened 2017-09-07 07:37 UTC
**What version of Shaka Player are you using**:

Latest or v2.2.1 (on Shaka player demo)

**Can you reproduce the issue with our latest release version**:

Yes

**Can you reproduce the issue with the latest code from `master`**:

Didn't tried it

**Are you using the demo app or your own custom app**:

Demo app

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:

Safari Version 10.1.2 (12603.3.8) on MacOS (10.12.6)

**What are the manifest and license server URIs**:
Angel One (HLS, multilingual)

**What did you do?**
1. Angel One (HLS, multilingual) from content list
2. Click load

**What did you expect to happen?**
Start playing the video

**What actually happened?**
Show "The provided value is non-finite" text in the box, and starts playing the audio, but not video. When I pause and resume playback, I can see the video.

**Comment by vaage** [comment] 2017-09-07 16:13
Thank you for bring this to our attention. This is a duplicate of #991. We have a fix in progress for it.

**Closed** 2017-09-11 16:32 UTC
Labels: bug, duplicate

**Comment by joeyparrish** [comment] 2017-09-11 16:45
The fix will be cherry-picked to v2.2.2.
