### ISSUE TITLE
PIP controls doesnt work after change manifest (Chrome)

### ISSUE THREAD

**Issue by ViktoriaFrantalova** [google/shaka-player#3406] opened 2021-05-13 12:27 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
no

**What browser and OS are you using?**
Chrome Version 90.0.4430.212 (Official Build) (x86_64), MacOS 11.2.3

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
{"drm":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":0},"servers":{},"clearKeys":{},"advanced":{},"delayLicenseRequestUntilPlayed":false,"logLicenseExchange":false,"updateExpirationTime":1},"manifest":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":0},"availabilityWindowOverride":null,"disableAudio":false,"disableVideo":false,"disableText":false,"defaultPresentationDelay":0,"dash":{"clockSyncUri":"","ignoreDrmInfo":false,"xlinkFailGracefully":false,"ignoreMinBufferTime":false,"autoCorrectDrift":true,"initialSegmentLimit":1000,"ignoreSuggestedPresentationDelay":false,"ignoreEmptyAdaptationSet":false},"hls":{"ignoreTextStreamFailures":false,"useFullSegmentsForStartTime":false}},"streaming":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":0},"rebufferingGoal":2,"bufferingGoal":10,"bufferBehind":30,"ignoreTextStreamFailures":false,"alwaysStreamText":false,"startAtSegmentBoundary":false,"smallGapLimit":0.5,"jumpLargeGaps":false,"durationBackoff":1,"forceTransmuxTS":false,"safeSeekOffset":5,"stallEnabled":true,"stallThreshold":1,"stallSkip":0.1,"useNativeHlsOnSafari":true,"inaccurateManifestTolerance":2},"offline":{"usePersistentLicense":true},"abr":{"enabled":true,"defaultBandwidthEstimate":10000000,"switchInterval":8,"bandwidthUpgradeTarget":0.85,"bandwidthDowngradeTarget":0.95,"restrictions":{"minWidth":0,"maxWidth":null,"minHeight":0,"maxHeight":null,"minPixels":0,"maxPixels":null,"minFrameRate":0,"maxFrameRate":null,"minBandwidth":0,"maxBandwidth":null}},"preferredAudioLanguage":"","preferredTextLanguage":"","preferredVariantRole":"","preferredTextRole":"","preferredAudioChannelCount":2,"restrictions":{"minWidth":0,"maxWidth":null,"minHeight":0,"maxHeight":null,"minPixels":0,"maxPixels":null,"minFrameRate":0,"maxFrameRate":null,"minBandwidth":0,"maxBandwidth":null},"playRangeStart":0,"playRangeEnd":null} 

**What did you do?**
You open codesandbox: https://codesandbox.io/s/shaka-player-multiple-forked-lchdy?file=/index.html
After the change manifest in PIP, it stops working in the Chrome browser.
It works great in the Safari browser. 

**What did you expect to happen?**
Change state and buttons when you click on the button Play/Pause in PIP after change manifest.

**What actually happened?**
1. click the button `attach1`
2. open PIP 
3. change state when you click on the button Play/Pause in PIP
3. click the button `changeManifest` (start to play another video in PIP)
4. click the button Play/Pause in PIP, but the video can't be stopped and Play/Pause buttons have stopped changing.

**Comment by joeyparrish** [comment] 2021-05-13 20:24
I can reproduce your results, but the buttons in the PiP window are entirely created and controlled by the browser, not by us.  There is discussion in the W3C about ways to extend the PiP API to allow applications/players to place their own buttons in the PiP window, but that has not happened yet.

So this should really be filed as a Chrome bug: https://crbug.com/

When you file a Chrome bug, please link to it here, and I will be sure to bring it to the attention of the appropriate members of the Chrome team.  Thanks!

**Comment by ViktoriaFrantalova** [comment] 2021-05-14 09:05
Thanks! I reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=1209142

**Comment by joeyparrish** [comment] 2021-05-14 16:13
Excellent.  I've CC'd some engineers who should be able to help, and I've added another set of repro steps using the Shaka Player Demo.

**Comment by joeyparrish** [comment] 2021-05-14 16:26
This can also be reproduced without MediaSource or Shaka Player.  Here's a static HTML page that demonstrates the issue with src= playback and no dependencies:  https://storage.googleapis.com/shaka-demo-assets/_bugs/crbug-1209142/pip.html

**Comment by WINOFFRG** [comment] 2021-06-23 11:57
Looks like this is not the issue with **Chrome 91.0.4472.114 (Official Build) (64-bit) (cohort: Stable)** on Windows 10 OS. Checked today, The sample provided above doesn't have any video play/pause issue.

**Comment by joeyparrish** [comment] 2021-06-23 18:06
Confirmed fixed in ChromeOS 91 (`chrome:version` reports `91.0.4472.102 (Offizieller Build) (64-Bit)`)

**Closed** 2021-06-23 18:07 UTC
Labels: external
