### ISSUE TITLE
HLS play error - hang in transmuxing

### ISSUE THREAD

**Issue by PrasannaLearnyst** [google/shaka-player#1449] opened 2018-05-26 16:04 UTC
What version of Shaka Player are you using?
Tested in the latest code and also in https://shaka-player-demo.appspot.com

Can you reproduce the issue with our latest release version?
Yes

Can you reproduce the issue with the latest code from `master`?
Yes

Are you using the demo app or your own custom app?
Demo app

What browser and OS are you using?
Chrome desktop browser MAC

What are the manifest and license server URIs?
URL1: https://s3-ap-southeast-1.amazonaws.com/learnyst/testfolder/sample/expresshls/hls.m3u8
URL2: https://s3-ap-southeast-1.amazonaws.com/learnyst/testfolder/sample/expresshls/hls1.m3u8

What did you do?
If we play using URL2 then we get error 
Shaka Error MANIFEST.HLS_MASTER_PLAYLIST_NOT_PROVIDED ()
so the EXT-X-ENDLIST fro the hls1.m3u8 file

Creating new file without EXT-X-ENDLIST which is URL1 (hls.m3u8) 
If we play using URL1 then, the video is played only for two seconds and stopped.

**Comment by ismena** [comment] 2018-05-29 21:15
Hi @PrasannaLearnyst, thanks for reporting!
EXT-X-ENDLIST tag is a [Media playlist](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.3.4) tag and should not be part of the Master Playlist, so removing it is the right thing to do.

Regarding the playback getting stuck after 2 seconds, it looks the third segment somehow gets stuck in transmuxing and thus hangs the playback. 
I tried it in Edge (as an example of a browser that has native support for ts) and it works.
@michellezhuogg could you advise on transmuxing, please?

**Comment by PrasannaLearnyst** [comment] 2018-05-30 04:59
Hi @ismena,
Thank you for the response.

The m3u8 is from Expressplay SDK, will raise the issue in Expressplay.

**Comment by ismena** [comment] 2018-05-30 20:27
I don't think anything's wrong with the content. The notes I left are for other members of my team, so if someone other than me picks this up, they know what's already been done.

I think the problem is either on mux.js side (the open source library we use for transmuxing) or in our integration with them. We will investigate further and reach out to mux.js developers if need be.

**Comment by PrasannaLearnyst** [comment] 2018-05-31 05:08
@ismena ,

It will be helpful, thanks

**Comment by joeyparrish** [comment] 2018-06-01 18:09
Filed upstream against mux.js: https://github.com/videojs/mux.js/issues/194

**Comment by joeyparrish** [comment] 2018-06-01 18:10
We think the mux.js bug can be converted from a hang into an error without waiting for the bug to fixed.  We consider that an improvement, but mux.js will ultimately have to fix the bug.

**Comment by ismena** [comment] 2018-06-01 21:27
@PrasannaLearnyst as @joeyparrish mentioned, we believe that this is a bug in mux.js and have reached out to them about it.
We will throw an e

**Comment by ismena** [comment] 2018-06-04 16:42
@PrasannaLearnyst from their explanation, it sounds like the segment states that it has both audio and video, but in fact has only video.
Could you follow up on this with your encoder? (Feel free to join the discussion on the mux.js bug if they introduce new info).

Mux.js devs have given us a hint on how to work around the problem, but it does sound like the content's description of itself is incorrect (based on the info we get from mux.js, unfortunately I'm not an expert on ts).

**Comment by PrasannaLearnyst** [comment] 2018-06-05 04:11
@ismena checked the encoder file, it has the audio from 00:00 to end time and sure will join the MuxJS discussion.

**Comment by joeyparrish** [comment] 2018-06-12 19:16
Setting `'remux': false` doesn't fix it.  Instead, I get a MediaSource error from Chrome that says "Initialization segment misses expected aac track".  I will follow up with mux.js.

**Comment by PrasannaLearnyst** [comment] 2018-06-12 19:27
@joeyparrish , thank you

**Comment by joeyparrish** [comment] 2018-06-12 19:28
So far, there doesn't seem to be an easy way to fix this in Shaka Player.  I've tried a few things, but I've had no luck.  I'm hoping for more feedback from mux.js, and possibly a fix from them.  For now, this will stay marked as "external".

For a workaround that you can control @PrasannaLearnyst, could you demultiplex your TS content library?  This is something you might be able to try with one asset just for testing purposes, and if it works, you could consider what it would take to do that to your entire content catalog.

**Comment by ismena** [comment] 2018-06-12 20:54
@PrasannaLearnyst For some reason I have a feeling I've seen a comment from you saying that you checked and was audio in the segment in question after all. Am I imagining things? 

(Apologies if I'm confused, but that's a whole different direction of the conversation with mux.js if that's the case).

**Comment by joeyparrish** [comment] 2018-06-12 22:02
The workaround introduced by @ismena has been cherry-picked for v2.3.9 and v2.4.1.

**Comment by sridhard** [comment] 2018-07-06 04:17
@joeyparrish @ismena Any updates on this issue?

**Comment by ismena** [comment] 2018-07-06 16:02
The code I have submitted is to make sure we throw an error in this case instead of hanging.
As for fixing the problem, @joeyparrish, could you give an update on what direction we want to go with this?

**Comment by joeyparrish** [comment] 2018-07-06 16:54
The workaround suggested by mux.js would take serious rearchitecture in Shaka Player, which we don't have the resources to work on right now.  We are waiting for a fix from mux.js in https://github.com/videojs/mux.js/issues/194

**Comment by joeyparrish** [comment] 2020-04-07 23:50
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.

**Closed by joeyparrish** 2020-04-07 23:50 UTC
Labels: external
