### ISSUE TITLE
Can't play stream if filename has Ampersand in name

### ISSUE THREAD

**Issue by mephillips423** [google/shaka-player#1380] opened 2018-03-29 01:03 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: YES

**What version of Shaka Player are you using?**: 2.3.4

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: My App

**If custom app, can you reproduce the issue using our demo app?**: No, I don't have control of filenames

**What browser and OS are you using?**: Firefox, Chrome, Edge on PC

**What are the manifest and license server URIs?**: NA
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**

I can't play streams if the filename has an Ampersand "&" in the filename:  IE WithAmp&.avproxy.mp4
When loading with javascript the url has been url encoded:

var videoUrl = 'https://centos1:1937/vod/x/stream/WithAmp%26.avproxy.mp4/manifest.mpd'
...
shakaPlayer.load(videoUrl)

I can play all other streams as long
as the filename does not contain an ampersand (ie 'Alläöüß€åæéøëïóàâçNonAlphaNumSansNTFSAndAmp !#$%'()+,-.;=@[]^_`{}.avproxy.mp4' or WithoutAmp.avproxy.mp4)

**What did you expect to happen?**

Stream playback

**What actually happened?**

OnError handler
Error code 4001 object

**Comment by joeyparrish** [comment] 2018-03-29 02:52
We will not be able to reproduce your issue without a manifest URI.  Can you please provide one?

Error code [4001 is `DASH_INVALID_XML`](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4001), so I doubt that the ampersand in the URL is the source of the problem.

**Comment by joeyparrish** [comment] 2018-03-29 03:06
Here's a counterexample with an ampersand in the URL:

https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/_bugs/1380-%26-counterexample/angel-one/dash.mpd;lang=en-US;play;build=uncompiled

This plays, so I suspect you might have some encoding problem in your XML.  Could it be that some part of the URL appears in your manifest, and that it's not properly escaped inside the XML?  For example:

```xml
<BaseURL>Wrong&encoding.mp4</BaseURL>
<BaseURL>Right&amp;encoding.mp4</BaseURL>
```

I'm only guessing, but if that's not it, then please send a manifest URL so we can reproduce your issue and help you debug.  Thanks!

**Comment by joeyparrish** [comment] 2018-04-02 16:52
@mephillips423, you have not provided a manifest URI, and we are unable to reproduce your issue with our own content.  I'm going to go ahead and close this as "unable to reproduce".

If you still need help with this, you can request the issue be reopened by replying with "@shaka-bot reopen".  This will trigger our build bot to put the issue back into queue for us to look at.

Thanks!

**Closed by joeyparrish** 2018-04-02 16:52 UTC
Labels: needs triage, unable to reproduce

**Comment by mephillips423** [comment] 2018-04-02 17:26
Thanks for responding. You are always so responsive and helpful.

Do you think it is & in the Title>rat/streamcache/11/19/2018/0328/172711430/WithAmp&.avproxy.mp4</Title>?

Here is the manifest URI and what is returned, it is not publicly accessible.  Putting this XML in a validator shows an error for the & in the Title element

https://centos1:1937/vod/x/rat/streamcache/11/19/2018/0328/172711430/WithAmp%26.avproxy.mp4/manifest.mpd

<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:mpeg:dash:schema:mpd:2011"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
     profiles="urn:mpeg:dash:profile:isoff-live:2011"
     type="static"
     publishTime="2018-03-29T16:04:56Z"
     mediaPresentationDuration="PT9.195S"
     minBufferTime="PT1.5S">
<ProgramInformation>
    <Title>rat/streamcache/11/19/2018/0328/172711430/WithAmp&.avproxy.mp4</Title>
</ProgramInformation>
<Location>https://centos1:1937/vod/x/rat/streamcache/11/19/2018/0328/172711430/WithAmp%26.avproxy.mp4/manifest_w189634277.mpd</Location>
<Period id="0" start="PT0.0S">
    <AdaptationSet id="0" group="1" mimeType="video/mp4" width="640" height="272" par="47:20" frameRate="24000/1001" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <SegmentTemplate presentationTimeOffset="0" timescale="90000" media="chunk_ctvideo_rid$RepresentationID$_cs$Time$_w189634277_mpd.m4s" initialization="chunk_ctvideo_rid$RepresentationID$_cinit_w189634277_mpd.m4s">
            <SegmentTimeline>
                <S t="0" d="180180" end="180180" t_unscaled="0" d_unscaled="2002" end_unscaled="2002"/>
                <S t="180180" d="180180" end="360360" t_unscaled="2002" d_unscaled="2002" end_unscaled="4004"/>
                <S t="360360" d="180180" end="540540" t_unscaled="4004" d_unscaled="2002" end_unscaled="6006"/>
                <S t="540540" d="180180" end="720720" t_unscaled="6006" d_unscaled="2002" end_unscaled="8008"/>
                <S t="720720" d="106830" end="827550" t_unscaled="8008" d_unscaled="1187" end_unscaled="9195"/>
            </SegmentTimeline>
        </SegmentTemplate>
        <Representation id="p0va0br888555" codecs="avc1.4d401e" sar="1:1" bandwidth="888555" />
    </AdaptationSet>
    <AdaptationSet id="1" group="2" mimeType="audio/mp4" lang="eng" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate presentationTimeOffset="0" timescale="48000" media="chunk_ctaudio_rid$RepresentationID$_cs$Time$_w189634277_mpd.m4s" initialization="chunk_ctaudio_rid$RepresentationID$_cinit_w189634277_mpd.m4s">
            <SegmentTimeline>
                <S t="0" d="96096" end="96096" t_unscaled="0" d_unscaled="2002" end_unscaled="2002"/>
                <S t="96096" d="96096" end="192192" t_unscaled="2002" d_unscaled="2002" end_unscaled="4004"/>
                <S t="192192" d="96096" end="288288" t_unscaled="4004" d_unscaled="2002" end_unscaled="6006"/>
                <S t="288288" d="96096" end="384384" t_unscaled="6006" d_unscaled="2002" end_unscaled="8008"/>
                <S t="384384" d="56976" end="441360" t_unscaled="8008" d_unscaled="1187" end_unscaled="9195"/>
            </SegmentTimeline>
        </SegmentTemplate>
        <Representation id="p0aa0br125455" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="125455">
        </Representation>
    </AdaptationSet>
</Period>
</MPD>

**Comment by mephillips423** [comment] 2018-04-02 17:36
I agree the problem is with the manifest. Correct to close bug. We have filed a bug with the stream server software.

**Comment by joeyparrish** [comment] 2018-04-02 21:05
Yes, it could be the title.  Any raw ampersand in the contents of any tag is invalid XML.

Thanks for the update!
