### ISSUE TITLE
What can cause buffering range outside of presentationTime 

### ISSUE THREAD

**Issue by chadacious** [google/shaka-player#3130] opened 2021-01-30 00:49 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.7

**Please ask your question**
I have a dash manifest of with SegmentTimeline and  Representations of the form:
```
        <SegmentList duration="383698" timescale="96000">
          <Initialization range="0-1614"/>
          <SegmentURL mediaRange="24579-64787"/>
          <SegmentURL mediaRange="64788-103055"/>
          <SegmentURL mediaRange="103056-148764"/>
```

Initially the playback is ok, but if I seek forward, the playback stops. Examining the buffered info, I see that the video has buffered sometimes ahead and sometimes behind the presentationTime. See the following console output with an example of me setting current time to 2000ms:
```
(video:5) timeNeeded=2010.4176458333482
streaming_engine.js:955 (video:5) update_: presentationTime=2000 bufferedAhead=12.929583000000093
streaming_engine.js:991 (video:5) buffering goal met video
streaming_engine.js:1784 (video:5) updating in 0.5 seconds
streaming_engine.js:946 (audio:18) timeNeeded=2010
streaming_engine.js:955 (audio:18) update_: presentationTime=2000 bufferedAhead=10.005333000000064
streaming_engine.js:991 (audio:18) buffering goal met audio
streaming_engine.js:1784 (audio:18) updating in 0.5 seconds
JSON.stringify(window.videoPlayer.getBufferedInfo())
"{"total":[],"audio":[{"start":2000,"end":2010.005333}],"video":[{"start":2023.104416,"end":2036.033999}],"text":[]}"
```

And here is another look filtered for just fetchAndAppend:
```
window.videoPlayer.getMediaElement().currentTime = 2000
2000
streaming_engine.js:1157 (audio:18) fetchAndAppend_: presentationTime=2000 reference.startTime=2000 reference.endTime=2002
streaming_engine.js:1157 (video:4) fetchAndAppend_: presentationTime=2000 reference.startTime=1998.427083333348 reference.endTime=2002.4239375000147
streaming_engine.js:1157 (audio:16) fetchAndAppend_: presentationTime=2000 reference.startTime=2002 reference.endTime=2004
streaming_engine.js:1157 (audio:16) fetchAndAppend_: presentationTime=2000 reference.startTime=2004 reference.endTime=2006
streaming_engine.js:1157 (video:4) fetchAndAppend_: presentationTime=2000 reference.startTime=2002.4239375000147 reference.endTime=2006.4207916666815
streaming_engine.js:1157 (audio:16) fetchAndAppend_: presentationTime=2000 reference.startTime=2006 reference.endTime=2008
streaming_engine.js:1157 (audio:16) fetchAndAppend_: presentationTime=2000 reference.startTime=2008 reference.endTime=2010
streaming_engine.js:1157 (video:4) fetchAndAppend_: presentationTime=2000 reference.startTime=2006.4207916666815 reference.endTime=2010.4176458333482
streaming_engine.js:1157 (video:3) fetchAndAppend_: presentationTime=2000 reference.startTime=2006.4207916666815 reference.endTime=2010.4176458333482
JSON.stringify(window.videoPlayer.getBufferedInfo())
"{"total":[],"audio":[{"start":2000,"end":2010.005333}],"video":[{"start":2023.104416,"end":2036.033999}],"text":[]}"
```

In the above buffered info, the video start should be 2000, not 2023.  From the fetchAndAppend logs it seems like it should have the correct buffered content but it doesn't.

I've tried tracing through the code a bit but would appreciate some help pinpointing where the calculation happens that could cause the video buffering to be out of sync. I'm assuming it will be a problem with the manifest I'm consuming, but not quite sure what to look for. Is it a timescale problem?

When I'm in this state, if I then set the currentTime to within the video buffered info range (so for the above example, if I do `window.videoPlayer.getMediaElement().currentTime = 2023`) The playback continues.

This same manifest plays fine in exoplayer. I'll try dash.js out as well just to see how it handles it.

**Comment by TheModMaker** [comment] 2021-02-19 00:00
This is caused by your manifest and your media segments not matching.  Your manifest says the segment starts at 2000, but it really starts at 2023.  What we do is fetch that segment, thinking it will start at 2000 and we buffer ahead; but when we give it to the browser, the media appears at the wrong time since the media data has a different start time.

Exoplayer can play it because it is a native player that can control the timestamp handling.  We historically don't support content where the media and the manifest don't match.  The point of a manifest is to tell us when the segments start at.

This could be a problem with using the `duration` attribute.  If your segments are slightly bigger (or even some of them are), then the times in the media will be larger than the manifest and will drift ahead.  This won't be visible when playing since we just buffer segments in series; but when you seek, we'll start buffering based on what is in the manifest.  If you can control the manifest generation, using `<SegmentTimeline>` instead may help.

**Comment by TheModMaker** [comment] 2021-02-19 00:05
One thing that may help is to set the `streaming.jumpLargeGaps` configuration to `true`.  This should cause us to jump ahead when this happens.  You'll skip 23 seconds of content, but it should play.

**Comment by joeyparrish** [comment] 2021-02-19 19:00
In addition to what @TheModMaker said, I would add that even with that workaround, if your manifest is off by such a large amount of time, seeking can never be done accurately based on that metadata.  So it would be best if you could fix your content.

**Comment by chadacious** [comment] 2021-02-23 20:34
Your explanations make perfect sense and is essentially what I thought as well.

However, in the case where I don't have control, or have reasons not to fix the source manifest, is there any way that I could extend something in the shaka-player with some additional logic that would attempt to seek forward or backward depending, in an attempt to realign the buffer?

**Comment by TheModMaker** [comment] 2021-03-22 21:46
One thing you may be able to do is adjust the `timestampOffset` value of the segments or the manifest.  If you have a constant value the manifest is off by (e.g. the manifest is always 30 seconds behind), then you can change the DashParser to include that in the `timestampOffset` field.  This field is used to adjust media times to match the presentation times.  So if the media times are 30 seconds ahead, then you'd reduce the `timestampOffset` field by 30.

You may even be able to do this with `player.getManifest()`.  If you iterate over the variants and the segments in the `segmentIndex`, then you can adjust each segment's offset values.  You can use the `manifestparsed` event for when we parsed the manifest but before we started playing.  For example, something like:

```js
for (const variant of player.getManifest().variants) {
  // Careful, these fields can be null.
  for (const stream of [variant.video, variant.audio]) {
    await stream.createSegmentIndex();
    // Careful, segments can be shared by-reference between streams.
    for (const segment of stream.segmentIndex) {
      segment.timestampOffset -= 30;
    }
  }
}
```

However, all this, and your content in general, is not officially supported.  We only support spec-compliant content and the DASH spec says that the manifest needs to match the media segments with only a small difference (up to a max of the segment duration).  So I'm going to close this as "bad content".

**Closed by TheModMaker** 2021-03-22 21:46 UTC
Labels: question
