### ISSUE TITLE
[nginx] Shaka+Swarm: Bad Gateway in download mpd

### ISSUE THREAD

**Issue by Pierpaolo1992** [google/shaka-player#648] opened 2017-01-08 09:34 UTC
Hi, first i've tried an nginx-container as proxy cache for multimedia contents (with backend tomcat, on post 8080) and i've used shaka library for streaming them on Chrome and Firefox.

The setup and conf file are there: https://github.com/google/shaka-player/issues/641

Now i've used docker swarm for creating a service (on post 9999) of N identicals nginx-container as proxy cache.

With the difference that instead of 

`manifestUri: '//172.17.0.1:9000/example-av.mpd',  `

now js code point to 
`
manifestUri: '//172.17.0.1:9999/example-av.mpd',  `

If i browse (On chrome or Firefox) at this url: 172.17.0.1:9999/example-av.mpd

i can see all the mpd (created by shaka packager).

if i point to my html index page (hosted on port 8080), and load .mpd (that points to 172.17.0.1:9999/example-av.mpd) there is a 502 bad gateway error.

![screen](https://cloud.githubusercontent.com/assets/13939351/21748766/9006d304-d58d-11e6-8a2a-fe8f4b1977f4.png)

And so there is a Shaka Error NETWORK.BAD_HTTP_STATUS

I don't know how to solve this problem, because if with my browser i point to 172.17.0.1:9999/example-av.mpd i GET, but not always, the mpd resource.

![screen1](https://cloud.githubusercontent.com/assets/13939351/21748778/081d093a-d58e-11e6-8ac1-8350032efbac.png)

On Chrome (v. 55.0.2883.75 (64-bit)) and Firefox (v. 50.1.0) sometimes it works, but without a precision regularity.

Edit: now bad gateway error on both chrome and firefox.

**Comment by joeyparrish** [comment] 2017-01-09 18:52
This sounds like an nginx issue, as specific HTTP responses are outside the control of the client.  We can't directly offer support for nginx, but here's what I would suggest you try next:

1. Compare a successful HTTP request to a failed on.  Look for differences in request headers and try to determine what causes the difference in the response.
2. Try to reproduce the error without Shaka Player.  Make requests with curl or wget or XHR.  If you can reproduce the problem without Shaka Player, it will probably be easier to get support from nginx.
3. Contact nginx directly for support.  https://www.nginx.com/support/

I will leave this issue open for a while in case any Shaka users with nginx experience have any better advice for you.  Good luck!

**Comment by joeyparrish** [comment] 2017-03-21 21:41
Since nobody has had anything to add here, I'm going to close this issue.  I hope you were able to get support from nginx.

**Closed by joeyparrish** 2017-03-21 21:41 UTC
Labels: external, question
