### ISSUE TITLE
Check mark icon does not update when turning text on

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#2484] opened 2020-04-06 22:46 UTC
If you load an asset with subtitles, but subtitles aren't on by default, and then you select the text track that would be selected by default, the check mark does not move from "off".
I think this is because we are getting a `texttrackvisibility` event (which tells us to change the state of the captions icon in the overflow menu), but not a `textchanged` event (which tells us to move the checkmark).
Looking at our version archive, this problem seems to have started appearing between `v2.5.9` and `v2.5.10`.

**Comment by joeyparrish** [comment] 2020-04-06 23:13
It could be a side-effect of the change not to send change events when the track is the same as it was before.  Since we have special rules for not streaming text until it is displayed, there could be an edge case we didn't take care of.

I can reproduce this on v2.5.10 and the current nightly, but not with my period-flattening changes.  In those changes, I reimplemented the logic for when to send change events, making StreamingEngine the authority on what's being streamed instead of Player.

So it might make sense to make a fix for this in the v2.5.x branch instead of `master`.

**Comment by joeyparrish** [comment] 2020-04-09 17:33
Fixed in v2.5.x

**Closed by joeyparrish** 2020-04-09 17:33 UTC
Labels: UI, bug
