### ISSUE TITLE
Streaming not working with encrypted Widevine

### ISSUE THREAD

**Issue by mhosman** [google/shaka-player#1173] opened 2017-12-06 15:40 UTC
The player is not requesting the license. No errors.

* Tested in Chrome (latest version) and Firefox (latest version)

**Comment by mhosman** [comment] 2017-12-07 12:51
Maybe a time issue? How can I to solve this? Tank you very much.

**Comment by joeyparrish** [comment] 2017-12-07 21:58
@mhosman, how was this resolved?

**Comment by mhosman** [comment] 2017-12-08 15:11
Hey, sorry I closed this by mistake. Is not resolved. For example, I have this unencrypted content. It's playing ok With DashIf last player reference. Not in Shaka:

https://lsp07.boldmss.com:5550/Teledoce/Teledoce.isml/Teledoce.mpd

**Comment by joeyparrish** [comment] 2017-12-08 17:58
Okay.  I've put it back in queue to be reproduced by the team.  Thanks!

**Comment by mhosman** [comment] 2017-12-11 16:31
Hey @joeyparrish, there's any update for this issue? I'm still not able to reproduce this content in Shaka. Thank you very much!

**Comment by joeyparrish** [comment] 2017-12-11 18:39
Not yet.  Sorry!

At any given time, there is one team member on duty to triage and reproduce issues, oldest first.  There are currently 6 items ahead of this one [in queue](https://github.com/google/shaka-player/issues?q=is%3Aopen+label%3A%22needs+triage%22+sort%3Acreated-asc).

**Comment by joeyparrish** [comment] 2017-12-12 19:54
This appears to be bad content.

The manifest has `availabilityStartTime="1970-01-01T00:00:00Z"`, which indicates that timestamp 0 in the media corresponds to January 1, 1970, UTC.

At unix timestamp 1513108176 (seconds since 1970, UTC), I fetched the manifest.  At that time, the first audio segment had timestamp 627266560 and timescale 48000.  Dividing 627266560 by 48000 yields 13068.05 seconds.

The first video segment had timestamp 326751 and timescale 25.  Dividing 326751 by 25 yields 13070.04.

Neither the video nor audio segments are anywhere near the current unix timestamp.  So the availabilityStartTime attribute is not consistent with the media timestamps.

I see a comment at the top of your manifest that says "Created with Unified Streaming Platform(version=1.7.32)".  I recommend you contact Unified Streaming to see if there are any updates.  It could be a bug which has already been fixed by them.  If not, you should ask them for further support to correct the manifest.

I hope this helps!  Let us know if there's anything else we can do.

**Closed** 2017-12-15 05:50 UTC
Labels: bad content
