### ISSUE TITLE
Persistent license in a VOD / Live not a "Streaming license call" but an offline license call

### ISSUE THREAD

**Issue by deisenbacher01** [google/shaka-player#2839] opened 2020-09-09 14:41 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled
https://wvm.ezdrm.com/demo/stream.mpd
https://widevine-dash.ezdrm.com/proxy?pX=BF9CEB

**What version of Shaka Player are you using?**
v3.0.4-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

**What did you do?**
This is more of a feature question and not a bug. The offline "Download" button works and downloads the VOD stream as well as the persistent DRM license. In this test stream its a 10 min license.  Is there a way to have the shaka player download a license for offline but keep the source as online and not call for a streaming license.  Basically allow for a persistent licence for VOD and Live streams without downloading the streams.

**What did you expect to happen?**
Listed above

**What actually happened?**

This is more of a feature question and not a bug. The offline "Download" button works and downloads the VOD stream as well as the persistent DRM license. In this test stream its a 10 min license.  Is there a way to have the shaka player download a license for offline but keep the source as online and not call for a streaming license.  Basically allow for a persistent licence for VOD and Live streams without downloading the streams.

**Comment by TheModMaker** [comment] 2020-09-09 16:25
We don't support that, but there is already #1956 to track adding it.

**Comment by deisenbacher01** [comment] 2020-09-09 16:30
Thx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joeyparrish** [comment] 2020-09-09 16:58
I'm going to close this as a duplicate of the feature request in #1956.  Thanks!

**Closed by joeyparrish** 2020-09-09 16:58 UTC
Labels: needs triage
