### ISSUE TITLE
Captions status inconsistent after reloading

### ISSUE THREAD

**Issue by michellezhuogg** [google/shaka-player#1879] opened 2019-04-10 22:05 UTC
1. Load the demo app with Angel One. Turn on the English Captions.
2. Hit 'Load' button again.
The captions menu shows that 'English' is selected, however English captions is not being displayed.

**Comment by joeyparrish** [comment] 2019-04-10 22:41
The text container appears to be at z-index -1, while the controls and video are both at z-index 0.  So the text is not only behind the controls, but the video.  I think this is a duplicate of #1878.

**Comment by avelad** [comment] 2019-04-11 08:26
I see the same issue

**Comment by joeyparrish** [comment] 2019-04-11 15:09
I stand corrected.  Separate issue.

**Comment by TheModMaker** [comment] 2019-04-23 20:04
This also happens if you set the `Preferred audio language` to a different value than `Preferred text language`.  The UI says captions are enabled but none show.  I also get an assertion failure saying `text visibility has fallen out of sync`.

**Closed** 2019-05-03 16:00 UTC
Labels: bug
