### ISSUE TITLE
Safari 10.1 update

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#752] opened 2017-04-10 16:56 UTC
I don't think this is a real problem for anyone yet, but Safari 10.1 was released recently:

https://webkit.org/blog/7477/new-web-features-in-safari-10-1/
https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html

My cursory search of the release notes doesn't turn up anything about changes to the EME implementation, but it looks like it has changed. Whereas Safari 10.0.x reported the following DRM support from Shaka support page:

`
"drm": {
    "com.apple.fps.1_0": {
      "persistentState": true
    },
    "com.apple.fps": {
      "persistentState": true
    },
    "org.w3.clearkey": null,
    "com.widevine.alpha": null,
    "com.microsoft.playready": null,
    "com.apple.fps.2_0": null,
    "com.adobe.primetime": null
  },
`

10.1 now reports:

`
"drm": {
    "org.w3.clearkey": null,
    "com.widevine.alpha": null,
    "com.microsoft.playready": null,
    "com.apple.fps.2_0": null,
    "com.apple.fps.1_0": null,
    "com.apple.fps": null,
    "com.adobe.primetime": null
  },
`
This is because Safari now implements `navigator.requestMediaKeySystemAccess`, but the promise rejects even for Fairplay keySystems. Creating `new WebKitMediaKeys` still works.

**Comment by TheModMaker** [comment] 2017-04-10 17:45
IIRC, even though the old versions say they supported Fairplay, they didn't.  Safari doesn't support EME according to the spec and our polyfill for it is incomplete.  We would like to add it, but it is a complex feature to add.  We are working on it and you can track it in #382.

So really, this is better since I don't think we supported it before.  Though this is promising since Safari might start implementing the current spec.  :crossed_fingers:

**Comment by joeyparrish** [comment] 2017-04-10 19:33
Previous versions of Safari were based on EME v0.1b (non-object-oriented) with a webkit prefix.  The new version is object-oriented, but not up to recent standards, and still with a webkit prefix.

We never supported fairplay with the old version, but we will endeavor to support it with the new version.

I will close this as a duplicate of #382.  Thanks!

**Closed** 2017-04-10 19:33 UTC
Labels: duplicate
