### ISSUE TITLE
Tizen video have buffer but stuck on readyState 1

### ISSUE THREAD

**Issue by uafgin** [google/shaka-player#1988] opened 2019-06-11 11:01 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
5.0 (SMART-TV; LINUX; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 TV Safari/537.36

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
firmware: T-KTM2DEUC-1260.8 sdkVersion:Tizen 4.0 model: NU8500

**What are the manifest and license server URIs?**
i am using Widevine DRM
manifest:
**MANIFEST TEXT REMOVED BY THEODAB AS IT WAS BREAKING GITHUB'S FORMATTING**

**What did you do?**
after 2/3 days leaving the TV open tried to load aLive Stream video

**What did you expect to happen?**
play the Live stream content

**What actually happened?**
player does not play any content,
readyState stuck on 1
video.buffered.end(0) - video.buffered.start(0) = 12
video.duration is infinity as it should be(dynamic manifest)
loadeddata event does not fire(as i said readyState stuck on 1)

i've tried to seek so the player clear the buffer, it did clear the buffer but still stuck readyState 1.
i've tried to use "error" event on video element, but i get nothing from it.
l've tried to reinstall the app and use other versions of shaka.
i think its more samsung bug, when i turn off the tv for like 10 min and turn on everything works fine, what could possibly make the video element fail to load frames?

**Comment by chrisfillmore** [comment] 2019-06-11 19:54
When you say "2/3 days leaving the TV open", do you mean streaming video for 2 or 3 days?

Does this problem only reproduce after streaming for that long?

**Comment by uafgin** [comment] 2019-06-12 06:01
doesnt have to stream all the time, it happen whether i stream or not stream.
it can happen also after one day i didnt find the exact trigger,
i can reproduce it after extended use of the tv (at least 1 day).

**Comment by joeyparrish** [comment] 2019-08-14 17:19
Looking more carefully at the conditions of this issue, I notice something that seems wrong:

> readyState stuck on 1
> video.buffered.end(0) - video.buffered.start(0) = 12
> video.duration is infinity as it should be(dynamic manifest)
> loadeddata event does not fire(as i said readyState stuck on 1)

`video.duration` should not be `Infinity`, even for a live stream or a dynamic manifest.  Shaka Player always sets the duration to a large, finite value, because otherwise the browser will not allow us to seek in the stream.

@uafgin, can you confirm these details for us?  Also, if you have time, can you please retest with Shaka Player v2.5.4 and let us know if this is still an issue in our latest release?  Thanks!

**Comment by uafgin** [comment] 2019-08-15 06:38
the issue changed since samsung version 1270,
this time it doesnt get stuck on unencrypted live channels, but with widevine drm encryption i am still getting the same issue.
i am not sure its shaka is the issue because the same code runs on LG television perfectly. it seems to be more samsung issue.
i guess something goes wrong i dont know exacly whats going on behind because i dont get any error messages, i guess something with the EME or CDM i am not sure..
i tried also with the lastest version release, still no change.
i've turned my pc to the drm server so i can try more options, maybe it get stuck with L3 only, maybe HDCP can do better or L1, if this wont work i'll try the widevine classic,
once i catch the issue i'll let you know more details.

**Comment by joeyparrish** [comment] 2019-08-15 18:08
If you can, please send accessible manifest and license server URIs to shaka-player-issues@google.com for us to reproduce the issue on our Tizen 3 device.  (I know you said Tizen 4, but we don't have a Tizen 4 yet.)  The content URIs will remain private, and will not leave Google or the Shaka Player team.

Thanks!

**Comment by uafgin** [comment] 2019-08-18 15:44
hey, thank you joey,
i finally managed to solve the issue!
well, i found out that samsung have some kind of issue with the licence duration, once its over the tv cannot play drm content no more even if i request anew key.
my settings was:
Request: {
  "payload": "hidden",
  "content_id": "hidden",
  "provider": "hidden",
  "allowed_track_types": "SD_HD",
  "policy_overrides": {
    "can_play": true,
    "license_duration_seconds": 35999
  }
} 
after aperioud of 10 hours i couldnt watch the content no more.
once i increased it to 864000(10 days) the problem solved.
or it will come back if the customer watch tv for 10 days(not common i guess)
thank you for your time, i'll report this issue to samsung and hopefully they'll fix it.

**Comment by joeyparrish** [comment] 2019-08-18 18:14
Excellent!  I'm glad you were able to find the issue.  Thank you for taking the time to report back and share what you learned.

Since this seems to be a bug in Tizen's Widevine implementation, there doesn't seem to be anything Shaka Player can do to work around it.  (We can't control the policy at the player level, and the workaround seems to be at the Widevine policy level.)  So I'm marking this issue as "external" and closing it.

Please let us know if you need anything else.  Cheers!

**Closed by joeyparrish** 2019-08-18 18:14 UTC
Labels: TV/STB, external
