### ISSUE TITLE
Playback may continue with artificial restriction on all tracks

### ISSUE THREAD

**Issue by anuragkalia** [google/shaka-player#2152] opened 2019-09-20 11:52 UTC
It is a simple bug. If I set restrictions that is not met by any of the stream, it throws a RESTRICTIONS_CANNOT_BE_MET error but the stream continues. The assumption here is that the restrictions did not affect the instance of shaka player. But probing the player instance for `getVariantTracks()` returns empty array.

**Comment by ismena** [comment] 2019-09-20 17:32
@anuragkalia 
Thanks for the report. Let's if i got the repro steps correctly:
1. start a video
2. use player.configure() to set restrictions that aren't met by any of the streams

Expected:
Video stops playing

Observed:
The currently selected streams continue to play

Is that right?

**Comment by anuragkalia** [comment] 2019-09-23 06:05
Steps to repro:
1. Open https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=HOME;build=uncompiled
2. In console, type: 
```
shakaDemoMain.player_.getVariantTracks()
```
3. In console, type: 
```
shakaDemoMain.player_.configure({
    restrictions: {
        minHeight: 720
    }
})
```
4. In console, type: 
```
shakaDemoMain.player_.getVariantTracks()
```

Expected: 
After step 4, video should continue to play. Step 4 should return same array as step 2.

Observed:
Video continues to play. Step 4 gives empty array instead.

**Comment by theodab** [comment] 2019-09-23 23:13
It looks like what is happening is that the player tries to pick a new variant in response to the configuration change. It realizes that there is no such variant, and defaults to not changing the variant at all.
According to [the documentation](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.PlayerConfiguration) on that configuration field:

> The application restrictions to apply to the tracks. These are "hard" restrictions. Any track that fails to meet these restrictions will not appear in the track list. If no tracks meet these restrictions, playback will fail.

So I think that what we are doing currently is not the correct behavior, as you surmised. But the intended behavior is apparently to just stop playing, not ignore the new restriction.

**Comment by michellezhuogg** [comment] 2019-10-10 22:14
Hello @anuragkalia ,
In your case no video meets the restriction of 'minHeight: 720', so getVariantTracks() will return an empty array, which is expected. Could you please let us know if there's anything else that's different from your expected behavior?
Thank you!

**Comment by joeyparrish** [comment] 2019-10-15 23:52
> Expected:
> After step 4, video should continue to play. Step 4 should return same array as step 2.

> Observed:
> Video continues to play. Step 4 gives empty array instead.

The empty tracks array is working as intended.  If all tracks are restricted, there are effectively no tracks, making the content unplayable.

However, since your restrictions are fictional/arbitrary, the video **does** continue to play.  This is also to be expected.

The restrictions system is intended for your application to communicate to Shaka Player that these tracks **cannot** be played, for example, because you won't have the keys.  (This can take the place of key statuses, which are missing on IE 11.)  If you restrict **everything** after startup, but the current track is actually **still playable**, then it will, of course, continue to play.

Since the continuation of playback is a natural consequence of the active track being playable, and the empty tracks array is a natural and intended consequence of the restrictions, there is no corrupted state in Shaka Player.  (I'll rename the issue accordingly.)

Now, we could change this behavior so that the playback **artificially** stops on error `RESTRICTIONS_CANNOT_BE_MET`, but it's not clear why this would be worth the effort.  Can you explain why you want to restrict all tracks in the first place?

**Comment by joeyparrish** [comment] 2019-12-02 21:22
Since it's been a while, I'm going to close this for now.  If you'd like to reopen the issue, just reply with `@shaka-bot reopen`.  Thanks!

**Closed by joeyparrish** 2019-12-02 21:22 UTC
Labels: working as intended
