### ISSUE TITLE
MEDIA_SOURCE_OPERATION_FAILED is thrown when playing encrypted Angel One assets

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#897] opened 2017-06-19 21:43 UTC
**What did you do?**
(Tested on the nightly build in Chrome).
Choose second or third asset on the demo page (Angel One Widevine or clearkey).
Press "Load".

**What happened?**
Error 3014 (MEDIA_SOURCE_OPERATION_FAILED) is thrown.

**Comment by TheModMaker** [comment] 2017-06-19 21:53
I believe this is caused by [CrBug 718651](https://bugs.chromium.org/p/chromium/issues/detail?id=718651&desc=2), which is a duplicate of [CrBug 728773](https://bugs.chromium.org/p/chromium/issues/detail?id=728773).  It has been fixed in Chrome Canary (61) and I can't reproduce the error on that.  Also note the error only happens on the low bandwidth tracks, so you'll need to disable ABR.

**Comment by joeyparrish** [comment] 2017-06-19 21:55
I can reproduce on Chrome 59 with low res tracks, but not high res tracks.  So I think it was that Chrome bug.  We'll keep this open until the fix is in Chrome stable.

**Comment by joeyparrish** [comment] 2017-08-10 21:11
Chrome 61 is currently in beta, and is scheduled for stable release around September 5.

**Comment by TheModMaker** [comment] 2017-09-11 17:09
Chrome 61 is in Stable, and I think this fix was cherry-picked to 60 anyway.  But now it works.

**Closed by TheModMaker** 2017-09-11 17:09 UTC
Labels: external
