### ISSUE TITLE
End of stream event doesn't fire

### ISSUE THREAD

**Issue by dobrusev** [google/shaka-player#372] opened 2016-05-06 15:57 UTC
Hello,

I'm listening for the HTMLMediaElement.ended when I play video content with shaka player, but for some manifests such event is not triggered.
Is this shaka player related or have to look somewhere else?

Thank you  in advance!

**Comment by joeyparrish** [comment] 2016-05-06 18:32
It is hard to say whether it's Shaka-related or not.  It could be that we're misinterpreting a manifest, or it could be broken content.  If you can provide an example of content that triggers the issue for you, we could take a look and help determine the cause.

Can you send us a manifest URL?

**Comment by joeyparrish** [comment] 2016-07-01 06:10
@dobrusev Is this still an issue for you or can we close it?

**Comment by dobrusev** [comment] 2016-07-12 16:27
Hello,

I'm sorry for the delayed response. Yes it's still an issue! Here is a manifest url:
http://teststreams.livesport-massive.com/out/u/DASH-unencrypted.mpd

**Comment by joeyparrish** [comment] 2016-07-12 22:23
This stream looks broken.  Shaka prints tons of warnings when loading this content.

Most of the Representations are missing content.  All of your video and audio Representations have the same timescale (90000), so we can compare times directly across all AdaptationSets:

The 1080p video Representation ends with `<S t="25923600" d="637200"/>`.  The final timestamp is 26560800.  This is about the same as the presentation duration (292 seconds).

The other video Representations end with `<S t="12963600" d="360000"/>`.  The final timestamp is 13323600.  They are missing about 2.5 minutes worth of segments.

The last audio Representation in the manifest ends with `<S t="25925520" d="639360"/>`.  The final timestamp is 26564880.  Again, this is about the same as the presentation duration.

The other audio Representations end with `<S t="12965520" d="359040"/>`.  The final timestamp is 13324560.  These are also missing about 2.5 minutes worth of segments.

The reason you don't see `ended` events with this manifest is because the video can't reach the end.  The chosen audio and video Representations are different lengths.

Please report this to your encoder vendor.  All Representations in a Period should cover the entire Period.  Small inconsistencies are generally well-tolerated, but 2.5 minutes is gigantic.

**Comment by dobrusev** [comment] 2016-07-13 13:12
Thank you @joeyparrish for you response.

**Comment by joeyparrish** [comment] 2016-07-13 15:06
Happy to help!

**Closed by joeyparrish** 2016-07-13 15:06 UTC
Labels: question
