### ISSUE TITLE
Stream keeps stalling on random moments, or on discontinuities in HLS

### ISSUE THREAD

**Issue by RonaldvB** [google/shaka-player#2687] opened 2020-06-26 11:27 UTC
Shaka player version:
V.3.0.1

When the player runs our stream, it seems to be running ok-ish until it hit's a discontinuity in the HLS (marked with EXT-X-DISCONTINUITY).

We than seen console logging:
![image](https://user-images.githubusercontent.com/18549945/85852361-b2327600-b7b0-11ea-8cb1-3b4fefdb0006.png)

But i do not know what this means? 
It eventually recovers and continues, but i don't understand why it would stall? other players, videoJS, seem to be playing the stream just fine

**Comment by michellezhuogg** [comment] 2020-06-26 16:07
Hello @RonaldvB , 
It may stall for various reasons, and we'd love to find the root cause of this issue.
1. Could you please follow our bug report template here, and let us know which version of Shaka Player you're using?
https://github.com/google/shaka-player/issues/new?assignees=&labels=&template=bug_report.md
2. Could you please share with us the manifest you're testing with? It would help us to reproduce this issue and look into it. If it's private content, you can send an email to shaka-player-issues@google.com. Thank you!

**Comment by RonaldvB** [comment] 2020-06-27 09:40
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
V.3.0.1

**Can you reproduce the issue with our latest release version?**
We're using the demo player online, so yes?

**Can you reproduce the issue with the latest code from `master`?**
NA

**Are you using the demo app or your own custom app?**
Demo app

**What browser and OS are you using?**
Chrome ( 83.0.4103.97 ) on Mac Catalina (10.15.5)

@michellezhuogg  i've asked our customer if we can share the stream, not sure if it has to be private, but i'll let you know :-)
thanx in advance

**Comment by RonaldvB** [comment] 2020-06-28 08:00
This is one of our streams:
https://streaming002.sniffercat.com/scheduler/scheduleMaster/118.m3u8

**Comment by michellezhuogg** [comment] 2020-06-29 05:24
Thank you! Verified the bug, and we'll work on the fix.

**Comment by RonaldvB** [comment] 2020-06-29 06:25
Is there maybe a way we can fix something in our HLS to fix this?

**Comment by michellezhuogg** [comment] 2020-07-01 05:29
Hello @RonaldvB , 
We have a potential fix for this! Could you please make your test manifest available again, so that we can verify it?

**Comment by RonaldvB** [comment] 2020-07-01 06:20
> Hello @RonaldvB ,
> We have a potential fix for this! Could you please make your test manifest available again, so that we can verify it? Thank you!

can i send it via the email you provided?

**Comment by michellezhuogg** [comment] 2020-07-01 06:26
Yes please!

**Comment by RonaldvB** [comment] 2020-07-02 08:11
Ha @michellezhuogg  i've send a new link :)
In the meanwhile we've also done some updates

**Closed** 2020-07-07 22:50 UTC
Labels: HLS, bug
