### ISSUE TITLE
Live stream buffering at the edge - SegmentTimeline issue

### ISSUE THREAD

**Issue by HeidiW** [google/shaka-player#578] opened 2016-11-08 23:27 UTC
Hello,

I am using the latest version of the Shaka player, in version 7.7.3 of JW Player (latest). 

I was able to reproduce the issues in the Shaka debug tester. This stream:

http://62.65.139.49/out/i/300.mpd

plays in the Shaka debug player but does not stream smoothly. The time on the seek bar loads while the marker appears in the middle of the seek bar, while the stream buffer looks to alternate between longer and shorter (although with DASH should I be seeing buffer behavior at all?). The stream frequently displays the loading icon during play.

For the customer's second stream, which includes DRM:

http://62.65.139.49/out/i/301.mpd

The stream fails to play either in the Shaka player or in JW Player, and I see this message in the console:

provider.shaka.js:1 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.(anonymous function) @ provider.shaka.js:1
provider.shaka.js:1 DOMException: The play() request was interrupted by a call to pause().(anonymous function) @ provider.shaka.js:1

Please let me know if you need license server URI information. The customer did provide that but I am not sure if it is needed here.

Thanks in advance for your insights as to why these streams are not playing smoothly, or not playing at all.

Yours, Heidi

**Comment by joeyparrish** [comment] 2016-11-15 01:06
Hello Heidi,

I believe I am able to reproduce your issue.  Here's what I see with the clear stream.  The player is unable to play at the calculated live edge.  Occasionally, it almost catches up, but for me, it is about 17 seconds behind.

Looking at the manifest, it seems that it is not ideally configured.  I don't know what encoder you're using, nor what options it gives you, so I'll go through what I see in the manifest and what that means for the player.

-----

The use of SegmentTimeline means that the player cannot predict segments that are not explicitly described in the timeline.  Until it updates the manifest, it can't fetch any new content.

The manifest says that it should be updated only every 30 seconds (`minimumUpdatePeriod="PT30S"`), so the player is naturally pretty far behind.  The manifest also says that only 50 seconds of content is accessible on the server at any given point (`timeShiftBufferDepth="PT50.00S"`).  So we're behind the live edge by up to 30 seconds, but we would fall off the trailing edge as little as 20 seconds later.  Once that happens, the player never catches up.

The content seems to be in roughly 10-second segments (`timescale="90000"` and typically `d="900000"`).  So the player can't fetch in any increment smaller than 10 seconds.

Finally, there is no delay specified in the manifest (`suggestedPresentationDelay="PT0.00S"`).  So we are trying to play exactly at the edge, which is impossible with SegmentTimeline, 30 second manifest updates, and 10 second segments.

-----

If you're going to use SegmentTimeline, you have to tune these parameters to get good playback.  I suggest more frequent updates, smaller segments, and a presentation delay.

I think 4 seconds is a segment size that allows better reaction time without too much overhead.  Some people prefer to use 2-second segments, or 6-second segments.  But I strongly suggest something less than 10.

If your manifest's update frequency is on the order of 3 segment lengths, you can expect to be about 1.5 segments behind on average.  To start, try a frequency around half of that.  So, for 4-second segments,  update the manifest every 6 seconds.

Finally, you need to set a presentation delay.  A presentation delay creates a difference between what the player knows about and what the user sees.  Setting the delay to 6 seconds means the calculated live edge on the server is 6 seconds ahead of the live edge the user sees during playback.  This covers up the back and forth you see on the progress bar as the player updates the manifest and fetches new content.

-----

If you can switch from SegmentTemplate+SegmentTimeline to SegmentTemplate+duration, you can avoid most of these issues.  With a fixed duration, segments can be predicted without a manifest update, which means the player can stay *much* closer to the live edge.  The manifest update period can be much longer and the segment size is less important.  You can also get away with a smaller presentation delay, especially with small segments.

-----

Does this help?
-Joey

**Comment by HeidiW** [comment] 2016-11-15 19:46
Hi Joey,

Thank you for the detailed feedback. I have a passed your observations and recommendations on to our customer. I learned from this as well. Would you mind keeping this issue open for a couple of days? I am hoping the customer will let us know the result as they address the various points in your response.

Heidi

**Comment by joeyparrish** [comment] 2016-11-15 21:11
Happy to leave the issue open for now.  Let us know if we can do anything else to help, and you can close the issue whenever you feel that this has been resolved.

**Comment by joeyparrish** [comment] 2017-01-24 23:24
Hi Heidi, it's been a couple months.  Is it okay for us to close the issue now?

**Comment by HeidiW** [comment] 2017-01-27 22:32
Apologies! Yes, please do close this.

**Closed** 2017-01-27 22:40 UTC
Labels: question
