### ISSUE TITLE
DRM.FAILED_TO_ATTACH_TO_VIDEO (Operation is not permitted)

### ISSUE THREAD

**Issue by bhushanudupa** [google/shaka-player#3564] opened 2021-08-04 05:15 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
OWN CUSTOM APP

**If custom app, can you reproduce the issue using our demo app?**
NOT TRIED

**What browser and OS are you using?**
Firefox / Chrome / Ubuntu 20.04

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
DIDN'T TEST WITH EMBEDDED DEVICES

**What are the manifest and license server URIs?**

Manifest URI: [Manifest URI](https://this-simple-bucket.s3.ap-south-1.amazonaws.com/Demi+Lovato-+Heart+Attack/stream.mpd)
License Server: [License server URL](https://widevine-dash.ezdrm.com/widevine-php/widevine-foreignkey.php?pX=34AC6C)
**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Player Config: {"drm":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":30000,"stallTimeout":5000,"connectionTimeout":10000},"servers":{"com.widevine.alpha":"https://widevine-dash.ezdrm.com/widevine-php/widevine-foreignkey.php?pX=34AC6C"},"clearKeys":{},"advanced":{},"delayLicenseRequestUntilPlayed":false,"logLicenseExchange":false,"updateExpirationTime":1},"manifest":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":30000,"stallTimeout":5000,"connectionTimeout":10000},"availabilityWindowOverride":null,"disableAudio":false,"disableVideo":false,"disableText":false,"disableThumbnails":false,"defaultPresentationDelay":0,"dash":{"clockSyncUri":"","ignoreDrmInfo":false,"disableXlinkProcessing":false,"xlinkFailGracefully":false,"ignoreMinBufferTime":false,"autoCorrectDrift":true,"initialSegmentLimit":1000,"ignoreSuggestedPresentationDelay":false,"ignoreEmptyAdaptationSet":false,"ignoreMaxSegmentDuration":false,"keySystemsByURI":{"urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b":"org.w3.clearkey","urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed":"com.widevine.alpha","urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95":"com.microsoft.playready","urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95":"com.microsoft.playready","urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb":"com.adobe.primetime"}},"hls":{"ignoreTextStreamFailures":false,"useFullSegmentsForStartTime":false}},"streaming":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":30000,"stallTimeout":5000,"connectionTimeout":10000},"rebufferingGoal":2,"bufferingGoal":30,"bufferBehind":30,"ignoreTextStreamFailures":false,"alwaysStreamText":false,"startAtSegmentBoundary":false,"gapDetectionThreshold":0.1,"smallGapLimit":0.5,"jumpLargeGaps":false,"durationBackoff":1,"forceTransmuxTS":false,"safeSeekOffset":5,"stallEnabled":true,"stallThreshold":1,"stallSkip":0.1,"useNativeHlsOnSafari":true,"inaccurateManifestTolerance":2,"lowLatencyMode":false,"autoLowLatencyMode":false,"forceHTTPS":false,"preferNativeHls":false},"offline":{"usePersistentLicense":true},"abr":{"enabled":true,"useNetworkInformation":true,"defaultBandwidthEstimate":1000000,"switchInterval":8,"bandwidthUpgradeTarget":0.85,"bandwidthDowngradeTarget":0.95,"restrictions":{"minWidth":0,"maxWidth":null,"minHeight":0,"maxHeight":null,"minPixels":0,"maxPixels":null,"minFrameRate":0,"maxFrameRate":null,"minBandwidth":0,"maxBandwidth":null}},"preferredAudioLanguage":"","preferredTextLanguage":"","preferredVariantRole":"","preferredTextRole":"","preferredAudioChannelCount":2,"preferForcedSubs":false,"restrictions":{"minWidth":0,"maxWidth":null,"minHeight":0,"maxHeight":null,"minPixels":0,"maxPixels":null,"minFrameRate":0,"maxFrameRate":null,"minBandwidth":0,"maxBandwidth":null},"playRangeStart":0,"playRangeEnd":null,"useMediaCapabilities":true}

**What did you do?**

I took song names of a playlist from database(Array). Wanted to play songs one after the other. I used `video.addEventListener('ended', () => {});` function to play songs one after the other.

**What did you expect to happen?**
It should play the next song in the playlist queue.

**What actually happened?**

Shaka player could play only one file. I also called a function which gets new URI for next song. I'm passing this URI as a parameter to `initPlayer()` function. But next song in the playlist(Queue) is not playing instead it displays `6003 FAILED_TO_ATTACH_TO_VIDEO` error.
`Object { severity: 2, category: 6, code: 6003, data: (1) […], handled: false, message: "Shaka Error DRM.FAILED_TO_ATTACH_TO_VIDEO (Operation is not supported)", stack: "shaka.util.Error`
 I have also tried to move the project to my website with HTTPS. Still getting same error.

**Comment by michellezhuogg** [comment] 2021-08-16 05:40
Hello @bhushanudupa , I can play your test manifest with the latest Shaka Player demo. Did you see the error message only with v3.0.10 ? Or did you see the error message only when playing a second song after the first one?

**Comment by bhushanudupa** [comment] 2021-08-16 06:14
@michellezhuogg 
First of all I would like to thank you for replying.
I see the error message only when playing a second song after the first song.

**Comment by TheModMaker** [comment] 2021-08-23 20:08
I cannot reproduce with the demo page on Windows.  I tried loading the manifest a second time in the demo and it works fine. 
 Please provide a link to a page that can reproduce the error.  Also if you can try on Mac or Windows too, that would help.

**Comment by bhushanudupa** [comment] 2021-08-24 04:45
@TheModMaker 
I have tried it in Ubuntu. I don't have any other OS. I will try to install it and give it a try.
Thanks for your response.

**Comment by joeyparrish** [comment] 2021-09-29 19:02
@bhushanudupa, can you please share with us the relevant parts of your application code?  I suspect the issue may be in how you are calling Shaka Player, rather than with Shaka itself.

**Comment by enjikaka** [comment] 2021-12-01 13:36
I'm also experiencing this. Subsequent loads in Firefox 94 on macOS 12.0.1 fails with 6003. First load plays fine. Content is DASH with Widevine.

**Comment by enjikaka** [comment] 2021-12-01 15:15
Finally found out the issue on my side. I was connecting the media elements via `createMediaElementSource` to an AnalyserNode. If I disable that code then firefox doesn't error on subsequent loads any more. Tried to only disconnect the MediaElementAudioSourceNode before shaka load too, but that didn't work. :(

**Comment by bhushanudupa** [comment] 2021-12-02 07:18
> media element isn't properly reset for next playback

@enjikaka As far as I know, as you rightly mentioned, it's because media element isn't properly reset for next playback. I have also tried some methods like detach() but no help.
Since we didn't have time to concentrate more on this, we moved to DashJS player where it worked amazingly without any glitch.

**Comment by theodab** [comment] 2021-12-04 00:31
Well, in that case, I'll close the issue. Feel free to re-open if you come back to Shaka Player, I suppose.

**Closed by theodab** 2021-12-04 00:31 UTC
Labels: type: bug, priority: P2
