### ISSUE TITLE
Cast connection is not recover after create a new CastProxy

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#768] opened 2017-04-28 10:04 UTC
- What version of Shaka Player are you using? 2.1.0
  - Can you reproduce the issue with our latest release version? Yes
  - Can you reproduce the issue with the latest code from `master`? Yes

- Are you using the demo app or your own custom app? Custom app
  - If custom app, can you reproduce the issue using our demo app? This case it's not avalaible on demo app

- What browser and OS are you using?
Chrome 58 on Ubuntu 17.04

Error:

Create a CastProxy (and init the player) and load any manifest (eg: https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd). Cast (canCast() returns true)and reproduce some seconds and destroy the player (shakaControl.player_.unload()) and then remove video tag of the current DOM (using components with AngularJS). Note: Cast Receiver is avalaible.

Next, add a new video tag (reusing the same component but, inserting it again in the dom), create a new CastProxy (and init the player) and load any manifest (eg: https://storage.googleapis.com/shaka-demo-assets/tos-ttml/dash.mpd). Now canCast() return false and it doesn't reuse the previous conection that it's available.

Note: if I reload the page instead of the previous, it's works.

**Comment by theodab** [comment] 2017-08-30 18:14
I believe I have reproduced and found a fix for this bug. The fix will be out soon.
I found your bug report a little confusing, so if this fix does not in fact solve your problem, please let me know.

**Comment by joeyparrish** [comment] 2017-08-31 03:18
@avelad, can you please retest with the master branch?  We think this might fix the issue, but we are not certain if we understood the report correctly.  Thanks!

**Comment by avelad** [comment] 2017-08-31 07:30
@theodab @joeyparrish , I can reproduce the error, I'll try to share with you a code example.

**Comment by theodab** [comment] 2017-09-11 22:22
Those code samples aren't enough for me to personally replicate your issue.

However, I did notice that when destroying the cast proxy, you do nothing with the return value when calling castProxy_.destroy().
CastProxy.destroy() is an asynchronous method, and it returns a promise that is fulfilled when the CastProxy is fully destroyed.
Not waiting for the proxy to be fully destroyed before setting everything to null could possibly be the source of your problem.
You could rewrite that unload method to be something along the lines of...
```
var destroyPromise = (isAvailable ? castProxy_.destroy() : Promise.resolve());
destroyPromise.then(function() {
  // the rest of the unload method goes here
});
```

**Comment by avelad** [comment] 2017-09-12 08:24
@theodab, I sent you an email with the source code and video with the problem. I hope that help, if not contact me.

**Comment by theodab** [comment] 2017-10-05 23:32
Okay, I fixed a bug and changed the behavior of the cast sender so that you can re-connect to a session properly after destroying it.
However, that example code you sent me does have some bugs. I've made a modified version with the changes you'll want to make pointed out in comments. I'll send it to your email.

**Comment by avelad** [comment] 2017-10-06 06:19
@theodab , thanks for all. I'll check the changes and I tell you if it works (I need some days).

**Comment by avelad** [comment] 2017-10-11 13:51
hi @theodab , I just tested the latest commit, and it works perfectly!!! Do you think that it's possible make a cherry-pick to 2.2.3?

**Comment by theodab** [comment] 2017-10-11 16:06
It's possible, since these changes are smallish bugfixes and not major feature work, but that decision is up to Joey.

**Closed** 2017-10-11 16:06 UTC
Labels: bug

**Comment by joeyparrish** [comment] 2017-10-16 19:33
Yes, I see no problem cherry-picking these to v2.2.3, which I hope to release this week.
