### ISSUE TITLE
Decoder error in Edge since Edge 16

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#1092] opened 2017-10-30 08:28 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**: 2.2.3

**Can you reproduce the issue with our latest release version**: yes, and previous versions as well

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: using my own, but can reproduce on demo app as well

**If custom app, can you reproduce the issue using our demo app**: yes

**What browser and OS are you using**: WIndows 10, edge

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
Test page was sent in email.

**What did you do?**
Try to play a DRM protected media

**What did you expect to happen?**
playback starts

**What actually happened?**
error is thrown from video element, no license request is sent

**Additional data**
since the fall creators update of Windows build 1709 with Edge 41.16299.15.0/Edge HTML16.16299 and IE11 11.15.16299.0 any PlayReady DRM playback fails with either error 3014 data [4] or error 3016, data [4, c00d3ee98].

It doesn't happen on previous windows build (1703) and previous Edge/IE11 versions.
I will send a test page that shows the issue separately via the email.

**Comment by OrenMe** [comment] 2017-11-01 05:13
Hi @TheModMaker, were you able to observe the issue with the test page I sent?

**Comment by joeyparrish** [comment] 2017-11-06 19:51
I have reproduced your issue with the test page you sent, as well as in our demo app.  The Shaka Player error codes 3014 and 3016 tend to indicate decoder errors.  The MS-specific error code (c00d3e98) seems to indicate a decoder failure as well.

I have not analyzed the content itself, but this could be a regression in Microsoft's decoders.  I'm not sure what you can do to debug further in Edge.  I suggest you file a bug with Microsoft here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If you file a bug with MS and share the bug link with me, I can forward it to some folks at Microsoft who may be able to help you further.

**Comment by joeyparrish** [comment] 2017-11-07 00:14
Someone from Microsoft just informed me that the error code c00d3e98 is a media error about an unsupported format.  You should definitely file a bug with Edge and link back to it here so we can help get it to the attention of the right people.

**Comment by joeyparrish** [comment] 2017-11-07 04:07
Our friends at Microsoft reproduced the bug with your test page, and have filed an internal bug on this, reference ID 14554354.  Hope that helps!

**Comment by OrenMe** [comment] 2017-11-07 07:08
@joeyparrish thank you so much!!! is there any external reference I can get to the internal reference ID?

**Comment by joeyparrish** [comment] 2017-11-07 17:48
Not that I have been able to find.  But if you file a bug of your own, you can reference that in the report, so that Microsoft can link the two together.  Through your own filing, you may be able to get status updates from them when they solve the issue.

**Comment by zshenker** [comment] 2017-11-10 20:01
@OrenMe Could you say what tools you are using to package/encrypt the media when you are having these issues?

I am encountering the same issues with media from Shaka Packager, but have been able to get successful playback in Edge 16 with DASH CENC(Widevine + PlayReady) content from Bento4.

@joeyparrish Would you have any more insights into what the actual issue is here, and if there might be any changes in the media packaging/encryption that could work around this issue?

**Comment by zshenker** [comment] 2017-11-10 20:19
Thanks @joeyparrish. One of the big differences I can see in the media from Shaka Packager vs from packagers where playback is working, is that from Shaka Packager, the first 2 segments are not encrypted(clear), where as in the other cases I have been testing all segments are encrypted.

**Comment by joeyparrish** [comment] 2017-11-10 22:27
Interesting.  You can control that clear lead in Shaka Packager.  Are you willing to re-package some content to test that theory?  Try with `--clear_lead 0` if you're using the command-line packager.  (The default is 10s.)

**Comment by kqyang** [comment] 2017-11-10 23:02
It looks related to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12658991/.  We have a workaround in Shaka Packager to make it work in Edge 15 by swapping the order of sinf and avcC boxes. Looks like this is broken in Edge 16 too. @joeyparrish We should talk to our friends at Microsoft again about this long time bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12658991/.

**Comment by zshenker** [comment] 2017-11-10 23:11
@joeyparrish @kqyang I just re-packaged my content with `--clear_lead 0` and confirm I am now getting successful playback in Edge 16.

**Comment by leejonghyeon0106** [comment] 2017-11-22 02:29
I am having same issue on Edge, IE after Fall Creator Update. It is hard to re-package contents since I have many contents. Is there any solution without re-packaging contents?
If there is any update please share information. Thanks.

**Comment by leejonghyeon0106** [comment] 2017-11-22 02:44
I am having same issue on Edge, IE after Fall Creator Update. It is hard to re-package contents since I have many contents. Is there any solution without re-packaging contents?
If there is any update please share information. Thanks.

**Comment by joeyparrish** [comment] 2017-11-22 18:07
@leejonghyeon0106, since the issue is in Edge/IE/Windows, there's nothing Shaka Player can do to fix it.  Please leave a comment on the external bug report and ask Microsoft for solutions/workarounds: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12658991/

**Comment by zshenker** [comment] 2018-03-22 02:24
@joeyparrish @kqyang Did you ever here anything further from the Edge team on this?

**Comment by kqyang** [comment] 2018-03-22 02:44
@zshenker I heard that they already had it fixed in latest Edge (Windows Insider) and they are investigating providing fixes to older versions of Edge, but I haven't verified myself. Can you test and verify if it is really fixed?

**Comment by joeyparrish** [comment] 2018-04-12 21:01
The latest copy of Edge I have is Edge/16.16299, on which I can still reproduce the error.

**Comment by joeyparrish** [comment] 2018-04-12 21:03
The external issue is still in an open state: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12658991/

**Comment by kqyang** [comment] 2018-04-12 21:49
If it is fixed, it should be in their later Feb or March release, i.e. in release 17xxx. 16299 is released last September.

**Comment by Murmur** [comment] 2018-05-08 08:03
I have Edge/16.16299(Win10) browser and had problems with plaready protected dash content. This issue gave me a solution, it is a packager not encrypting the first segment. Quick fix was to change `startNumber="2"` and content worked but 10s was skipped in the start. Unfortunately I have no control of the packager so must contact the provider.

**Comment by zouhir** [comment] 2018-05-15 23:36
I have tested the page included in the internal bug report referenced with ID 14554354 and it seems to be working on Edge 17 _preview_

I will be setting something up to reproduce this the external bug https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12658991/ -- since I read above they are pretty related, hopefully that one will be resolved too..

I am keeping my eye on this...

**Comment by joeyparrish** [comment] 2018-05-29 20:51
We have others reporting that this has been fixed in the latest release of Edge.  Please update!

**Closed by joeyparrish** 2018-05-29 20:51 UTC
Labels: external
