### ISSUE TITLE
Fairplay playing seems to stop on webkitneedkey

### ISSUE THREAD

**Issue by torlangballe** [google/shaka-player#2009] opened 2019-06-24 08:28 UTC
I've now managed to set up the certificate as in #2003, but am getting a webkitneedkey error and nothing plays, then a webkitkeyerror. From all else I've read it might be something to do with the Kaltura-server not giving keys in the right format, but I can't seem to get much details on it.

I've tried running directly on my macbook pro screen to avoid any HDMI issues.

Does anybody know what is causing this?

tor
 
> IndexedDB.install (shaka-player.compiled.debug.js, line 79)
InputEvent.install (shaka-player.compiled.debug.js, line 79)
mathRound.install (shaka-player.compiled.debug.js, line 79)
MediaSource.install (shaka-player.compiled.debug.js, line 79)
Patching Safari 11/12 MSE bugs. (shaka-player.compiled.debug.js, line 79)
Using Apple-prefixed EME (shaka-player.compiled.debug.js, line 79)
PiPWebkit.install (shaka-player.compiled.debug.js, line 79)
VideoPlayPromise.install (shaka-player.compiled.debug.js, line 79)
Using native VTTCue. (shaka-player.compiled.debug.js, line 79)
Starting attach... (shaka-player.compiled.debug.js, line 79)
Starting load of https://tglmp01.akamaized.net/out/v1/5fecbc1b98074aa29649b72a99a26d2a/master.m3u8... (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.requestMediaKeySystemAccess (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySystemAccess (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySystemAccess.getConfiguration (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySystemAccess.createMediaKeys (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeys (shaka-player.compiled.debug.js, line 79)
Created MediaKeys object for key system – "com.apple.fps.1_0" (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.setMediaKeys (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeys.setServerCertificate (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.onWebkitNeedKey_ – WebKitMediaKeyNeededEvent (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeys.createSession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession.generateRequest (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeys.createSession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession.generateRequest (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.onWebkitKeyMessage_ – WebKitMediaKeyMessageEvent (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.onWebkitKeyError_ – Event (shaka-player.compiled.debug.js, line 79)
PatchedMediaKeysApple.MediaKeySession.update (shaka-player.compiled.debug.js, line 79)

**Comment by KieronAllsop** [comment] 2019-06-24 21:30
The log output seems very similar to that which you get with #1923. Appears at least partly related

**Comment by joeyparrish** [comment] 2019-06-26 20:48
Agreed, let's call this a duplicate of #1923.  Thanks!

**Closed** 2019-06-26 20:49 UTC
Labels: duplicate
