### ISSUE TITLE
Live contents cannot be paused(currentTime moves ahead)

### ISSUE THREAD

**Issue by SemihGk** [google/shaka-player#1042] opened 2017-10-02 16:06 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes.
**What version of Shaka Player are you using**:
2.2.2
**Can you reproduce the issue with our latest release version**:
Yes.
**Can you reproduce the issue with the latest code from `master`**:
Yes.
**Are you using the demo app or your own custom app**:
Demo App
**If custom app, can you reproduce the issue using our demo app**:
Yes.
**What browser and OS are you using**:
Chrome and Mac.
**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
You can test any live stream in demo app.

**What did you do?**
Paused the live stream and waited a min.

**What did you expect to happen?**
Current time should not be moved when I stop the video. Video should be able to continue from where you pause the stream.

**What actually happened?**
I stopped the video and current time was still moving. I believe player removes the previous buffers while chunks are downloading because of not to increase the memory. However, video buffering/downloading chunks should be stopped when you pause the video.

So, is there any way to stop buffering? As far as I have read the documentation, I could not find a way to stop stream. However, it should still be considered as a bug if the stream is not stopped automatically when you pause the video.

**Comment by joeyparrish** [comment] 2017-10-02 17:17
This is a duplicate of #982.  See https://github.com/google/shaka-player/issues/982#issuecomment-327233452 for a discussion of why this happens and what we propose to do to fix it.

Closing as a duplicate.  Please subscribe to #982 for updates.  Thanks!

**Closed by joeyparrish** 2017-10-02 17:17 UTC
Labels: duplicate

**Comment by SemihGk** [comment] 2017-10-02 17:29
Oh, sorry I could not find a similar ticket before post this ticket. Next time, I will spend more time for searching. Thank you.

**Comment by joeyparrish** [comment] 2017-10-02 18:00
No problem!  It's difficult to tell sometimes, even for us.  :-)
