### ISSUE TITLE
live+drm - player doesn't start to play 

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#673] opened 2017-02-01 08:35 UTC
- What version of Shaka Player are you using? v2.0.5-debug

  - Can you reproduce the issue with our latest release version?
 yes

- Are you using the demo app or your own custom app? app demo

- What browser and OS are you using? chrome 55/6 on both WIn 8.1 and macOS Sierra 10.12 

- What did you do?

Load https://shaka-player-demo.appspot.com/demo/?asset=https://klive-a.akamaihd.net/dc-1/live/edash/p/1804331/e/1_1h4m0b66/t/r1LIk_dFcJnVrhH113ndYQ/manifest.mpd;license=https://udrm.kaltura.com/cenc/widevine/license?custom_data=eyJjYV9zeXN0ZW0iOiJPVlAiLCJ1c2VyX3Rva2VuIjoiZGpKOE1UZ3dORE16TVh3cW5ZLUkyQWl5dktxUl9QVkh2RVlmdmUzTERzM2RQaE1VRjNzdG9MT2w1bzFkekNiUFAzUnNDNDFIUVNUQVBBOEtKTXFfNEVRem9IbGFkYlIybktONDVzb2FCM2sxX0MwRFo4YnNKeWNKbFE9PSIsImFjY291bnRfaWQiOiIxODA0MzMxIiwiY29udGVudF9pZCI6IjFfMWg0bTBiNjYiLCJmaWxlcyI6IjFfamJiOGpsOWwsMV8wOG0zOWhreSwxX21yamdpMmxyLDFfYm55eWh1anIifQ%3D%3D&signature=W1Fw0W19%2FTPwJUVxrJ4t6%2BEE5IU%3D;v

- What did you expect to happen?
playback should start

- What actually happened?
 shaka downloads many manifest.mpd files and the buffer is filled but the player does not play.
playback starts only after ~2.5 min.

This is a sporadic issue, sometimes it works ok.

attached network and console logs and screenshot

Thanks,
Yair

![screenshot](https://cloud.githubusercontent.com/assets/17685520/22499877/e9db0a28-e869-11e6-9745-f58fabd40833.png)

[console-log.txt](https://github.com/google/shaka-player/files/744197/console-log.txt)

[network-log.txt](https://github.com/google/shaka-player/files/744195/network-log.txt)  (change to .har extension after download to able opening in charles)

**Comment by TheModMaker** [comment] 2017-02-01 17:33
It looks like the player is downloading segments that are close to the playhead initially.  If the media segments have a start time that is slightly more than what is in the manifest, then the buffer will start after the playhead and the video won't start to play.  This shouldn't happen.

Unfortunately your URL doesn't work, the license server is giving me a 403 error (`error while getting entitlement`).

**Comment by OrenMe** [comment] 2017-02-01 18:45
@TheModMaker here's a new one for this media: https://udrm.kaltura.com/cenc/widevine/license?custom_data=eyJjYV9zeXN0ZW0iOiJPVlAiLCJ1c2VyX3Rva2VuIjoiZGpKOE1UZ3dORE16TVh4NmdVUHVLS0pVWEpGZk9TNzAxNnRJRVprNDhLU0g3dVJzQkVROWVVS1RRTzIxU3lidDNrc0RxTFRBNG1OR3JQcG1faFFtbDFYblZMWjhvRF9qMjEySGVCSm1Wa1ZLQ1FBSDFvdXNWN3paRWc9PSIsImFjY291bnRfaWQiOiIxODA0MzMxIiwiY29udGVudF9pZCI6IjFfMWg0bTBiNjYiLCJmaWxlcyI6IjFfamJiOGpsOWwsMV8wOG0zOWhreSwxX21yamdpMmxyLDFfYm55eWh1anIifQ%3D%3D&signature=Y%2BOpyr6Jj1tRwr9mquqWf70GzZk%3D&

**Comment by TheModMaker** [comment] 2017-02-01 23:23
This only affects Chrome stable (56), this has been fixed in beta (57) and doesn't appear in Firefox.

The problem is that your license server sometimes takes a really long time to respond (20+ seconds).  Chrome doesn't seem to flush the media pipeline after updating EME if it takes longer than a few seconds.  But this has been fixed by Chrome.

**Comment by yairans** [comment] 2017-02-02 08:10
@TheModMaker 
Thanks a lot

**Comment by joeyparrish** [comment] 2017-03-21 21:44
Chrome 57 is the new stable release.  You should have the fix now.  If not, please let us know.

**Closed by joeyparrish** 2017-03-21 21:44 UTC
Labels: bug, EME, external
