### ISSUE TITLE
Playback stalled at start when playing VP9+Opus in DASH

### ISSUE THREAD

**Issue by kxloh** [google/shaka-player#1891] opened 2019-04-24 18:33 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.4.7, compiled; ABR manager disabled.

**Can you reproduce the issue with our latest release version?**
Yes, I'm using 2.4.7.

**Can you reproduce the issue with the latest code from `master`?**
Playback is fine when using the latest beta 2.5.0-beta3.

**Are you using the demo app or your own custom app?**
A custom app.

**If custom app, can you reproduce the issue using our demo app?**
I haven't tried.

**What browser and OS are you using?**
Chrome, latest Canary builds.
Occurs on several different devices running: Windows 7 Pro, Windows 10 Home, MacOS Sierra 10.12.6, and MacOS Mojave 10.14

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
No license server used.
The manifest is played from an internal media server at Google, not on the corp network. It's a simple MPD that points directly to the video and audio WEBM files.

**What did you do?**
Tried to play a VP9 + Opus video repackaged in DASH.

**What did you expect to happen?**
Playback to start immediately once the video has loaded.

**What actually happened?**
The video loads, but playback is stalled/frozen on the first frame for 1-2 seconds before playing normally.

**Comment by joeyparrish** [comment] 2019-04-24 18:46
> **If custom app, can you reproduce the issue using our demo app?**
> I haven't tried.

Please try!  https://v2-4-7-dot-shaka-player-demo.appspot.com/demo/#asset=

> **What are the manifest and license server URIs?**
> The manifest is played from an internal media server at Google, not on the corp network. It's a simple MPD that points directly to the video and audio WEBM files.

Please share it with us!  You can do so at shaka-player-issues@google.com.  Please reference this issue number.  Without this information, we obviously can't reproduce the problem or fix it.  Thanks!

**Comment by kxloh** [comment] 2019-04-24 19:08
Can I use the demo app to play my problematic video? If so, how do I point to my video?

**Comment by joeyparrish** [comment] 2019-04-24 19:20
Please use the link I put in my previous comment.  That will take you directly to v2.4.7 of the demo app, in a particular state where you're prompted to put in the manifest URL.  Fill out the form and then click the load button.

**Comment by kxloh** [comment] 2019-04-25 17:16
I take it the demo app can only access public URIs? I'm getting 'Shaka Error NETWORK.HTTP_ERROR... TypeError: Failed to fetch,0'. Do you have a site where I can temporarily upload the manifest and associated media files? Alternatively, do you have a version of the demo app that can access Google's corp network?

I sent additional information to the e-mail provided.

**Comment by joeyparrish** [comment] 2019-04-25 17:18
No, the demo can access any URL your browser can access, since you're running it in your browser.

Is it a CORS error?  Does your server disallow cross-origin access?

**Comment by kxloh** [comment] 2019-04-25 17:39
Yes, it's a CORS error. Let me see what I can do about that.

**Comment by kxloh** [comment] 2019-04-25 19:41
Sorry, it's not a CORS error when I try running the demo on one of the test machines. It's a mixed content error: 'This request has been blocked; the content must be served over HTTPS'.

The internal media server is setup to serve content over HTTP only. Not something I can change easily.

**Comment by joeyparrish** [comment] 2019-04-25 19:45
You could work around this by running the Shaka Player demo locally, so that everything is over localhost.

**Comment by BucherTomas** [comment] 2019-04-26 08:30
Alternatively, you can temporarily allow loading your stream over HTTP by using the following method https://techdows.com/2016/07/chrome-this-page-is-trying-to-load-scripts-from-unauthenticated-sources.html .
It is not just for scripts as the popup hints, it enables mixed content as well for that given open page, i.e. Shaka demo.

**Comment by kxloh** [comment] 2019-05-01 20:58
Bucher, thanks for the suggested work-around. Unfortunately, when I tried this, the first mixed content error I was getting became a warning, but then I got a second mixed content error from service_worker.js:213 that wasn't downgraded to a warning.

Joey, I got the demo running locally on the media server. Unfortunately for me, playback was fine when using the demo. I checked on a couple of different devices using all three versions (uncompiled, debug, and release). I'll have to do more investigating.

**Comment by joeyparrish** [comment] 2019-05-01 21:05
We've just fixed some bugs with regard to our service worker that could have resulted in CORS or mixed content errors that couldn't be worked around.  In short, I believe any request handled by the service worker is outside the scope of the page, so allowing mixed content on the page wouldn't help.  With the latest changes, the service worker avoid handling requests that aren't part of the app itself.

Sorry for any inconvenience this bug was causing in your testing.  It should be fixed now in `master`.

**Comment by ismena** [comment] 2019-05-13 17:50
Closing per Joey's comment.
Please let us know if you're still seeing the issue!

**Closed by ismena** 2019-05-13 17:50 UTC
Labels: waiting on response
