### ISSUE TITLE
Multiple audio languages with encryption

### ISSUE THREAD

**Issue by ruiposse** [google/shaka-player#112] opened 2015-06-24 10:12 UTC
Hi, in my tests I've been trying to get Shaka Player to work with multiple encrypted audio.

In eme_manager.js, ```chooseEncrypted_``` has the following code starting on line 345:
```
for (var j = 0; j < configs.length; ++j) {
      var cfg = configs[j];
      if (cfg.drmScheme.keySystem == keySystem &&
          cfg.fullMimeType == caps.contentType) {
        chosenCfgs.push(cfg);

        // Accumulate the DRM scheme info from all chosen StreamConfigs.
        if (!this.drmScheme_) {
          this.drmScheme_ = cfg.drmScheme;
        } else {
          var newScheme = /** @type {!shaka.player.DrmSchemeInfo} */(
              cfg.drmScheme);
          shaka.player.DrmSchemeInfo.combine(this.drmScheme_, newScheme);
        }
        break;
      }
    }
```
Not sure if this is a bug, but what seems to happen is that whenever there's more than one audio in the manifest, Shaka Player loops through them until it finds the first one that matches the supported drmScheme even thought it knows that there's more audio tracks that could be tested.

I've found that removing the ```break;``` fixes this issue.
Not sure if that's the proper solution, but I figure this could be a start :)

**Comment by sanbornhnewyyz** [comment] 2015-06-25 16:32
+1 

I have the same issue and this fixes the problem.

**Comment by joeyparrish** [comment] 2015-06-26 00:05
Thanks for the report.  Can either of you supply test content I could use to reproduce and debug the problem?  If it's something you can't post in public, an email would be fine.

**Comment by ruiposse** [comment] 2015-07-01 18:25
Unfortunately I cannot. All content is behind an authentication system.

**Comment by sanbornhnewyyz** [comment] 2015-07-03 15:20
I've emailed @joeyparrish with some test content that should reproduce the issue.

**Comment by joeyparrish** [comment] 2015-07-03 15:32
I can now reproduce the issue.  I'll see what I can do to fix it.  Thanks!

**Comment by joeyparrish** [comment] 2015-07-03 15:55
@sanbornhnewyyz, I can't reproduce the behavior in [your earlier comment](#issuecomment-115313235), where removing the break statement results in too many tracks.

In the test content you gave me, there are two audio languages, one audio bitrate per language, and three ContentProtections elements.  I added a check for PlayReady to app.interpretContentProtection_ in case it was important to have multiple DrmSchemeInfos as well.  With this setup, if I remove the break in chooseEncrypted_, I get exactly two audio tracks.

If I edit the manifest and add an additional audio Representation to each AdaptationSet (low bandwidth such that they are not selected by default), I now see four audio tracks as I would expect.  I can't seem to get them to duplicate per-ContentProtection or per-DrmSchemeInfo.  So for the moment, it seems as if removing the break statement is, in fact, the correct fix.

Is there something I'm missing to reproduce the "too many tracks" problem you described?

**Comment by sanbornhnewyyz** [comment] 2015-07-03 18:29
No, as far as I know I just removed that break statement.

**Comment by joeyparrish** [comment] 2015-07-06 17:46
Did some archaeology:  It seems this bug has always been there, ever since we started using requestMediaKeySystemAccess back in February (a253872).

Removing the break statement seems to me to be the correct fix.  You should be able to choose all matches for key system & codec.  The content from Sanborn that I've tested seems to be fixed by this.

Are there any objections to this fix?  Or counter-examples where it does not work as it should?

**Comment by sanbornhnewyyz** [comment] 2015-07-06 19:53
I have no objections.

**Comment by sanbornhnewyyz** [comment] 2015-07-07 14:18
I hate to do this but I actually still am having a problem with 1.4.0. When I call player.getAudioTracks() it returns 8 tracks instead of 2. But there are actually only 2 different tracks in the array and each of them is repeated 4 times. Am I failing to specify somewhere that I only want tracks with widevine protection?

**Comment by joeyparrish** [comment] 2015-07-07 16:17
No worries!  We want to get this solved for you.  Does this happen with the last sample you sent me, or will I need a new sample to reproduce?

**Comment by sanbornhnewyyz** [comment] 2015-07-07 18:08
It should work with the last sample I sent you but I was going to verify it. I'm having trouble playing the content in the sample app. Can you still play the content that I sent?

**Comment by joeyparrish** [comment] 2015-07-07 19:45
Yes, I can play it in the test app.  I just paste the URLs you gave me into the test app's manifest and license server fields.

**Comment by sanbornhnewyyz** [comment] 2015-07-07 21:19
Okay after some further examination it turns out the problem was caused by our incorrect contentProtection callback (thanks for the tipoff). We were ignoring schemeIdUri and just returning a DrmSchemeInfo instance every time and this caused it to think there were more tracks than there really were. After this change, the fix you put into 1.4.0 works perfectly. 

Thanks for the help.

**Comment by joeyparrish** [comment] 2015-07-07 21:26
No problem.  I'll try to replicate that and see if this is something we should account for somehow when processing the callback's results.

**Comment by joeyparrish** [comment] 2015-07-07 21:56
Looks like something we can/should take care of in EmeManager.  I've got a fix in review internally that seems to handle duplicate DrmSchemeInfos more gracefully.  Thanks for helping me repro it.

**Closed** 2015-07-08 16:04 UTC
Labels: bug

**Comment by sanbornhnewyyz** [comment] 2015-07-08 18:53
Great, thanks for the fix.
