### ISSUE TITLE
Message exchange format between Shaka Player and Server License

### ISSUE THREAD

**Issue by VinceBorz** [google/shaka-player#614] opened 2016-11-30 20:31 UTC
Hello, I am a new Shaka player user  and I'm doing some tests with Shaka player demo. I also activated the tool for Google Chrome developers and I have enabled the Google extension eme logger. In particular, I started watching Sintel 4k - Multicode, Widevine-  and observed the EME call flow. But when I analyzed the data exchanged with the License Server Widevine (the data message of MessageEvent of about 1800 bytes and the data message of UpdateCall, 640 bytes) I've seen data in raw format (the stream start with 08 02 12 hex) and not the json format I was expecting. Did I make a mistake? Does the format of the data exchanged with the License Widevine server not have the json format?
What is the structure of request and responce messages ?

Thanks for your help.

Best regards, Vinc

**Comment by joeyparrish** [comment] 2016-11-30 21:18
Hi Vinc,

I'm closing this as a duplicate of the message you sent to the mailing list here: https://groups.google.com/forum/#!topic/shaka-player-users/cSQxQZeqTA0

I'm sorry it took me so long to get caught up on email and reply to your original message.

I explained this on the mailing list as well, but in short, the Widevine license request and response formats are not JSON-based and are not public formats.  If you have any further questions about this, let's continue the conversation on the mailing list.

Thanks,
Joey

**Closed by joeyparrish** 2016-11-30 21:18 UTC
Labels: duplicate, question
