### ISSUE TITLE
Wrong role and language after DAI in v3.0+

### ISSUE THREAD

**Issue by dsparacio** [google/shaka-player#2785] opened 2020-08-12 21:35 UTC
Hi Shaka Team, We are seeing a regression in 3.0.2 when comparing to 2.5.14 around multi audio detection when there are duplicate lang string, one set with a role, the other no role. 

Basically, MPD has two audio tracks both with lang="en", but one has the role attribute for descriptive audio.  once parsed by shaka, we only see one english track, the one with the role attribute and the normal english audio track is dropped.   

Regular English Audio Track, no Role. (track dropped in 3.0.2 but available as expected in 2.5.14.)
```
<AdaptationSet id="5" contentType="audio" lang="en" segmentAlignment="true">
      <Representation id="5" bandwidth="126477" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000">
        <SegmentTemplate timescale="48000" initialization="init.m4v" media="seg_$Number$.m4s" startNumber="1">
```
Descriptive English Audio Track with Role.
```
<AdaptationSet id=“5” contentType=“audio” lang=“en” segmentAlignment=“true”>
   <Accessibility schemeIdUri=“urn:tva:metadata:cs:AudioPurposeCS:2007” value=“1"/>
   <Role schemeIdUri=“urn:mpeg:dash:role:2011” value=“description”/>
   <Representation id=“5” bandwidth=“127871" codecs=“mp4a.40.2” mimeType=“audio/mp4" audioSamplingRate=“48000”>
    <AudioChannelConfiguration schemeIdUri=“urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value=“2”/>
    <SegmentTemplate timescale=“48000" presentationTimeOffset=“118966848” initialization=“init.m4v” media=“seg_$Number$.m4s” startNumber=“417">
```

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Have not had time to try yet, but will

**If custom app, can you reproduce the issue using our demo app?**
Both

**What browser and OS are you using?**
Chrome

**Comment by joeyparrish** [comment] 2020-08-12 21:43
> we only see one english track

How are you observing the tracks?  Through our UI?  Or through a method like `getVariantTracks()`, `getAudioLanguages()`, `getAudioLanguagesAndRoles()`?

**Comment by dsparacio** [comment] 2020-08-12 21:56
this.audioTracks = this.player.getAudioLanguagesAndRoles();

**Comment by joeyparrish** [comment] 2020-08-12 22:05
I noticed that the two AdaptationSets and Representations you quoted in the original post seem to have the same IDs (5 & 5 both times).  Is that a typo or copy-paste mistake?  Or does your content contain two AdaptationSets with the same IDs, which in turn contain Representations with the same IDs?

If that's the case, that is likely the cause of your issue.  The DASH spec has something to say about the uniqueness of IDs, and we can make corresponding assumptions.

If that's not the case, please send a manifest URL to shaka-player-issues at google dot com so we can investigate.

Thanks!

**Comment by dsparacio** [comment] 2020-08-12 22:45
Nice catch, sorry my mistake it was a typo in copy/paste to ticket.  

We have all four of English audio in an period. We expect and are seeing that the ac-3 and ec-3 codecs are dropped for desktop and makes sense.  Id 4 is missing and that is what we are looking into.  

I'll gather up some shareable assets and send your way via the support email.  Thanks for taking a look. 

```
  <AdaptationSet id="2" contentType="audio" lang="en" segmentAlignment="true">
      <Representation id="2" bandwidth="192246" codecs="ec-3" mimeType="audio/mp4" audioSamplingRate="48000">
```
```
 <AdaptationSet id="3" contentType="audio" lang="en" segmentAlignment="true">
      <Representation id="3" bandwidth="384246" codecs="ac-3" mimeType="audio/mp4" audioSamplingRate="48000">
```
```
<AdaptationSet id="4" contentType="audio" lang="en" segmentAlignment="true">
      <Representation id="4" bandwidth="127956" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000">
```
```
  <AdaptationSet id="5" contentType="audio" lang="en" segmentAlignment="true">
      <Accessibility schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007" value="1"/>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="description"/>
```

**Comment by dsparacio** [comment] 2020-08-14 18:34
@joeyparrish email send with content and some other notes.  Please confirm you received it and of course keep it all private ;)

**Comment by joeyparrish** [comment] 2020-08-19 17:13
We have received it.  I hope to have time to test this by the end of the week.  Thanks!

**Comment by dsparacio** [comment] 2020-09-09 17:01
Will get back on this and make sure the media I sent over exhibits the issue.

**Comment by dsparacio** [comment] 2020-09-09 23:55
@joeyparrish  Not showing any issue with the media I sent on my side as well. I am sorry for the false alarm.  I am looking at notes to find what media did show this (if any) and if that media is valid regarding audio and roles etc. 

We had some test media but hoping that did not mix in and mislead me to file this.  

For today, can we leave this open?  I'll do more testing then come back and close it tomorrow?  

I also noticed that the Endianness change for IE and Edge made it into 3.0.4.  So we will look at bailing on our Fork of 2.10.14 and getting on 3.0.4 as well.  

Thanks for the effort.  I think the xbox decode issue is our last one.  We have moved shaka to be default provider in our player as of this release!

**Comment by joeyparrish** [comment] 2020-09-10 00:03
@dsparacio, thanks for the good news!

It's fine to leave this open a little longer.  Please let us know if/when you want to close it.

**Comment by dsparacio** [comment] 2020-09-14 19:30
@joeyparrish It is only happening with DAI involved, and is slightly different now but is an issue.  So maybe something on DAI side changed since I filled.   I always see all four tracks but when DAI is involved, there is a mix up on the labeling

When DAI inserts periods,  we get this info when calling getAudioLanguagesAndRoles()
![DAI-viacom](https://user-images.githubusercontent.com/7864462/93128692-bd48c400-f684-11ea-8be0-4522bad1cc17.png)

No DAI, same content encode otherwise, looks as expected when calling getAudioLanguagesAndRoles().
![Screen Shot 2020-09-14 at 12 12 35 PM](https://user-images.githubusercontent.com/7864462/93128813-e5d0be00-f684-11ea-8a0b-cabc06b38354.png)

**Something maybe related**
Still testing between DAI SDK and API implementation on our end for Desktop, as well as different Shaka version.  We are on latest 3.0.4 during this test.  

1. When using the same stream (we sent you for this issue orgianolly ) ,no DAI, Shaka is filtering out AC-3 and EC-3 on Desktop and starting as expected.  

But it fails on filter step with DAI injection.  If we use this DAI setting  dai.filterOutPremiumAudioCodecs = true, which does the manifest manipulation and removes all advanced codecs from manifest before shaka gets it,  no problem with playback. 

Since this other issue about Audio tracks is DAI specific, I will need to get you DAI content.  But just thinking they may be related.

**Comment by dsparacio** [comment] 2020-09-15 17:39
Tested with 2.5.16,  no issue with either reported/found in 3.0.4. 
1. It filters out AC-3 and EC-3, no fatal error, playback starts, no need to have DAI filter out from manifest.  
1. The Audio tracks act slightly different in 2.5.16 vs 3.0.4.  
    1.  In 2.5.16, we see a single track during Ad, with the UND label. - Once content segment, post ad starts,  I see the 4 audio tracks all labeled correctly for both label and role.  
   1. So in 3.0.4 we see what is above and have confirmed shaka return is producing the same info as the normalized cbs player objects show above. I suspect that the PreRoll Ad Audio Track info is getting mixed the content segments audio?  

So Since the Endianness change is in 2.5.16, which will allow us off our fork,  we will upgrade to that for now and work with you to resolve the others over next release.  


---------- 

I am going to file one more ticket for LG by the way.  We have been able to work around this issue with stallSkil and stallSkipThreshold,  but I have also read that those settings are not recommended on webos so we are in need of some advice here.

**Comment by joeyparrish** [comment] 2020-09-21 18:10
> In 2.5.16, we see a single track during Ad, with the UND label. - Once content segment, post ad starts, I see the 4 audio tracks all labeled correctly for both label and role.

That's because in v2.5.x and earlier, multi-period DASH generates a separate track list for each period.  This led to a bunch of strange issues, including track selections being changed in surprising ways across periods, and certain preferences being effectively ignored on transitions.

Since v3.0.0, we combine tracks across periods so that the track list, track selections, and preferences (language, resolution, etc) are stable across transitions.  However, it looks like the algorithm we wrote to stitch together tracks across periods probably has another bug in it still.

I double-checked my email and we still only have the non-DAI version of the content you sent us privately for this.  If you can send the DAI version, we should be able to take a look.  Thanks!

**Comment by dsparacio** [comment] 2020-09-22 21:14
@joeyparrish totally make sense.  I know exactly what you are talking about with new track across periods for the 2.5.x stuff and much nicer in the 3.0 outside of this small item.  Must just be pulling in the Ad track info from pre into period 1 of our content.  I can actually try to submit a PR for this specific issue to help out.   

This all came about when trying to deal with LG issue: I will file a new ticket for this we are just trying to gather content and scripts for DAI to pass along.

**Comment by joeyparrish** [comment] 2020-09-22 21:44
We would be very happy to have a PR if you have some idea of the cause.  Periods are combined in lib/util/periods.js and there are corresponding unit tests where you can mock up something similar to your actual content to create a regression test for it.

**Comment by joeyparrish** [comment] 2020-11-10 23:59
We have a similar issue filed internally (b/172605645) that may help.  We have a copy of a manifest that triggers a bug in period flattening related to audio description tracks.  Though we can't test playback exactly, we intend to use the manifest text to construct a failing regression test in `test/util/periods_unit.js` and iterate on a fix through that.  Once that is fixed, we hope that @dsparacio could confirm the fix before it goes out into a release.

**Comment by dsparacio** [comment] 2020-11-11 00:05
@joeyparrish - I am happy to test.  In fact we just upgrade and are testing 3.0.5 so timing is great here ping me when ready.

**Closed** 2020-12-15 17:46 UTC
Labels: bug

**Comment by dsparacio** [comment] 2020-12-15 19:32
We should reopen ?

**Comment by joeyparrish** [comment] 2020-12-15 19:51
@dsparacio, is there an issue with the fix we just pushed?  cf6aa88 ?  If so, then yes, we can reopen.  But in case you overlooked it in the issue history, we did close it with a commit that we believe is the appropriate fix.

**Comment by dsparacio** [comment] 2020-12-15 20:15
Missed that Joey sorry I'll text the commit today

**Comment by joeyparrish** [comment] 2020-12-16 18:05
No worries.  Thanks!

**Comment by dsparacio** [comment] 2021-01-14 22:15
Integrating this now and will test but I am sure it is fixed and really appreciate it being looked at.  Thank you so much!
