### ISSUE TITLE
HLS v4 url causes startup lags and deprecation messages

### ISSUE THREAD

**Issue by greenya** [google/shaka-player#1514] opened 2018-07-30 16:37 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes

**What version of Shaka Player are you using?**:
2.4.2

**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:
haven't tested

**Are you using the demo app or your own custom app?**:
both

**If custom app, can you reproduce the issue using our demo app?**:
yes

**What browser and OS are you using?**:
lastes chrome: Version 68.0.3440.75 (Official Build) (64-bit)

**What are the manifest and license server URIs?**:

n/a

**What did you do?**
I'm using urls from https://azure.microsoft.com/en-us/blog/live-247-reference-streams-available/
Specifically, "HLS v4". If i use that url directly, i get error: "This request has been blocked; the content must be served over HTTPS.". so i use "https", now it shows error: "HEAD request to guess manifest type failed!" --- which is expected and fine (no problem here). So i append ".m3u8", and final url becomes: https://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl).m3u8 --- and it works.

**What did you expect to happen?**
- start playing faster
- no deprecation messages

**What actually happened?**
it works, but:
- i have to wait about 30 seconds just to see "Play" button, and 10-15 more after i hit it
- i do see messages about deprecated interface: "The network request interface has changed!  Please update your application to the new interface, which allows operations to be aborted.  Support for the old API will be removed in v2.5." in the console.

P.S.: it actually plays pretty well after you leave it for those 1-1.5 min, no errors and good quality after that.

**Comment by joeyparrish** [comment] 2018-08-28 23:47
When I played this today with the latest Shaka Player, it played without error, and without appending m3u8 to the URL.

There were some messages in the JS console such as "Request header field range is not allowed by Access-Control-Allow-Headers in preflight response", but that is caused by the server config, and is not in the control of Shaka Player.

There is also the message "Unable to fetch a partial HLS segment! Falling back to a full segment request, which is expensive!  Your server should support Range requests and CORS preflights."  This is caused by the same server config (range requests & CORS), and is not in our control.

There are no deprecation errors in the console in the latest version of Shaka Player.

Beyond that, the content plays.  The fallbacks we have in place to handle servers which don't support range requests are functioning as intended.

Does that help?

**Comment by greenya** [comment] 2018-09-03 09:52
Thank you.
Its better now (playing starts much faster).

**Comment by joeyparrish** [comment] 2018-09-04 14:02
Okay, great.  Please let us know if you need anything else.  I'll go ahead and close this issue.

**Closed by joeyparrish** 2018-09-04 14:02 UTC
Labels: working as intended
