### ISSUE TITLE
MPEG DASH with Playready 

### ISSUE THREAD

**Issue by sam2007** [google/shaka-player#197] opened 2015-10-05 13:31 UTC
Hi Guys,

Does the current version of shaka player supports multiple DRM support on encrypted DASH streams? Lets say we have an MPEG DASH encrypted stream with refrence to both Playready and Widevine (System ID and PSSH), will shaka player choose playready automatically when executed on a microsoft environment which doesnt support Widevine (Microsoft edge or Intenet Explorer)? Or is shaka player limited only to using Widevine on MPEG DASH streams?

Regards,

Ferdinand

**Comment by sam2007** [comment] 2015-10-05 13:34
Sorry I didnt see that it was already added to the milestone

**Comment by joeyparrish** [comment] 2015-10-07 18:29
Shaka supports multiple DRM providers by design, but that assumes a compliant EME implementation from the browser.  In practice, Playready won't be supported until we land a polyfill for IE's version of MediaKeys.  There is a pull request for that in review now.

**Closed by joeyparrish** 2015-10-07 18:29 UTC
Labels: working as intended
