### ISSUE TITLE
Shaka Error TEXT.UNABLE_TO_EXTRACT_CUE_START_TIME

### ISSUE THREAD

**Issue by Romain-Bernier** [google/shaka-player#1970] opened 2019-05-28 10:39 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
master 2.5.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome Version 74.0.3729.169 on Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
I can't provide manifest but my use case is :
Live HLS with vtt subtitles and ts segments for audio and video.
Exemple of VTT segment :
```
WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:0

16:32:29.200 --> 16:32:31.640
Qui avait fait une depression.

16:32:32.800 --> 16:32:34.720
Je me sentais tres seule.
```

**What did you do?**
Start the player

**What did you expect to happen?**
That the error doesn't occur.

**What actually happened?**
When I start the player, shaka fetch the oldest VTT segment of the media playlist and get the error Shaka Error TEXT.UNABLE_TO_EXTRACT_CUE_START_TIME without display video. 
But half of the time, it work fine, shaka try to fetch the oldest VTT segment and then try to fetch video and audio segment and finally shaka fetch on of the younger VTT segment and display everything fine.

The comment 
`      // This could be a failure from the parser itself (init segment required)
      // or an exception from allCues.length being zero.`
above the code who launch the error is unclear for me allCues.length being zero  mean that
shaka can't support empty VTT like  : 
```
WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:0
```
or not ?

**Comment by TheModMaker** [comment] 2019-05-28 16:02
Without a sample asset, we cannot reproduce your error.  This is probably a duplicate of #1563, but without some content to test with, we cannot help.

**Closed** 2019-05-29 07:05 UTC
Labels: needs triage
