### ISSUE TITLE
Tizen: Shaka player skipping audio/aac in HLS Stream

### ISSUE THREAD

**Issue by simrankour** [google/shaka-player#2771] opened 2020-08-05 18:03 UTC
I am working on the Samsung Tizen TV application, in which I have to play .mpd and .m3u8 videos using Shaka player.
I am facing issues while playing HLS stream (.m3u8) as the video is playing correctly but there is no audio as Shaka player is skipping the audio/aac format.  

`Raw formats are not yet supported.  Skipping audio/aac`
`Skipping unsupported HLS stream audio/aac`
 
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, no open issue

**What version of Shaka Player are you using?**
v.3.0.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Tizen TV

**What are the manifest and license server URIs?**
https://content.jwplatform.com/manifests/yp34SRmf.m3u8

**What did you do?**
Play the HLS stream video with aac audio format. Video is playing perfectly but there is no audio as Shaka player is skipping audio/aac.

**What did you expect to happen?**
Expected Shaka player should play audio with aac format correctly. 

**What actually happened?**
Video is playing perfectly but there is no audio as Shaka player is skipping audio/aac.

**Comment by TheModMaker** [comment] 2020-08-05 18:07
Duplicate of #2615.  We don't support raw AAC at the moment.  We only support TS or MP4 for HLS.

**Comment by joeyparrish** [comment] 2020-08-05 18:08
As mentioned in the log ("Raw formats are not yet supported. Skipping audio/aac"), we can't support raw formats at this time.  AAC in MP4 should play fine, if this helps.

The enhancement to add support for raw AAC and other containerless formats is #2337, which you can subscribe to for updates once we have some.  Nobody is working on this feature at the moment.

**Closed** 2020-12-28 21:07 UTC
Labels: duplicate
