### ISSUE TITLE
Playback and even app freezes on Samsung Tizen TV (Tizen 4.0, 2018)

### ISSUE THREAD

**Issue by JakubRimal** [google/shaka-player#2220] opened 2019-10-29 17:22 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Latest (v2.5.5)

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes.

**Are you using the demo app or your own custom app?**
Both.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Tizen TV default browser.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
MN : UE32N5302
PD : 04/18/2019
SN : 0EH33HAM402498W
FW : T-KTSNDEUC-1270.6
FC : SWU-OU_T-KTSNDEUC_1270_190717
MI : T-KTSNDEUC
LS : EU
DI : U7CD36PSCYHKM
MA : 24FCE5D8E1CF
VS : 1270.190717

Samsung TV TizenBrowser: 2.1.3.0421293

**What are the manifest and license server URIs?**

Manifest: https://vst99-2.o2tv.cz/53480245581472403-samsung_tv.mpd
License: none

**What did you do?**

1. Open Internet Browser in Samsung TV
1. Go to https://shaka-player-demo.appspot.com/demo
1. Click CUSTOM CONTENT
1. Click plus button
1. Type manifest URL (see above)
1. Type some name
1. Click SAVE
1. Click PLAY

**What did you expect to happen?**
The player should play till the end of the stream.

**What actually happened?**

The player playback starts freezing after a while (e.g. 15 or 30 minutes), it completely stops playing after some more time (few minutes) and after some more time (e.g. 10 minutes) the whole app (Internet Browser) is completely frozen.

**Comment by kevinscroggins-youi** [comment] 2019-11-11 20:34
This is possibly related to https://github.com/google/shaka-player/issues/2059 and https://github.com/videojs/http-streaming/issues/674

**Comment by TheModMaker** [comment] 2019-11-12 18:17
Marking as duplicate of #2059.

**Closed by TheModMaker** 2019-11-12 18:17 UTC
Labels: needs triage
