### ISSUE TITLE
Playback not working in Chrome 44

### ISSUE THREAD

**Issue by jonoblinkbox** [google/shaka-player#52] opened 2015-04-07 17:31 UTC
In Chrome 44 (Canary), all playback is failing; when executing navigator.requestMediaKeySystemAccess in shaka.player.Player.prototype.buildKeySystemPromiseChain_ , the following error is raised:
DOMException: None of the requested configurations were supported.

This is happening in the test app using the "Car/CENC" (YT DASH EME test) - MP4, ClearKey" test manifest. Tested on version 1.2.1

**Comment by joeyparrish** [comment] 2015-04-07 20:10
This appears to be a duplicate of issue #45, which was fixed last week.  Can you please try with a newer version of Shaka Player from the master branch?

**Comment by joeyparrish** [comment] 2015-04-07 23:59
I was able to reproduce this using Chrome 44 and v1.2.2, but not using the master branch.  So I am fairly certain this is a dup of #45.

But since #45 was a fairly substantial compatibility issue affecting both Chrome 43 and 44, we've tagged a new bugfix release (v1.2.3) and updated the demo at http://shaka-player-demo.appspot.com/ .  Please check that the problem is resolved on appspot, and upgrade your application to v1.2.3 at your earliest convenience.  If this doesn't resolve the problem for you, please reopen this issue.

Thanks!

**Closed by joeyparrish** 2015-04-07 23:59 UTC
Labels: bug, duplicate

**Comment by jonoblinkbox** [comment] 2015-04-08 08:40
Ah sorry Joey, I had missed #45 - we'll upgrade to 1.2.3 as soon as we can. Thanks
