### ISSUE TITLE
[Question] MS Edge legacy: after scrubbing audio disappears for few seconds

### ISSUE THREAD

**Issue by glhvta** [google/shaka-player#2409] opened 2020-02-20 18:46 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9

**Please ask your question**
Hi,

Recently we found an issue in legacy MS Edge browser: after scrubbing in Edge browser audio disappears for few seconds. After that it restores and there are no issues with audio.
It can be reproduced on a shaka demo page with any test assets, for example:

- https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=HOME;build=uncompiled
- https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=HOME;build=uncompiled

It was observed that this issue is reproduced only in MS Edge legacy browser and _only without headphones_.

This issue was not observed in other browsers, including the new MS Edge on Chromium. 

We've also checked this behavior on other streaming platform (Netflix, youtube, Dash player demo page ) in legacy MS Edge and seems like this issue is not reproduced on them. 

Windows version:
Windows 10 Enterprise
Version: 1803
OS build: 17134.1184

MS Edge version
Microsoft Edge 42.17134.1098.0

Video with reproduced issue can be found here: 
https://drive.google.com/open?id=1J-_RISS_cuOZOfsCBm_uflMqZImf7YXv

As we know only the latest version of the MS Edge browser is supported by the shaka-player. But lots of our users are still using the legacy Edge browser. Maybe you can advise us something to look into so we can proceed with the investigation and make our custom fix.

Many thanks in advance!

**Comment by joeyparrish** [comment] 2020-02-20 19:54
Can you try testing in older release branches of Shaka Player to see when the issue was introduced?  You can find an index of releases here: https://index-dot-shaka-player-demo.appspot.com/

Thanks!

**Comment by glhvta** [comment] 2020-02-21 11:04
Hi, @joeyparrish , sure, 

We've made the check on the asset "Sintel" and the next results were observed:
 - this issue is reproduced on all the versions of shaka 2-x -x.
 - this issue is not reproduced on the versions of shaka-player 1-x-x

By the way, many thanks for the provided link to the page with all the shaka-player versions, it is really helpful 👍

**Comment by joeyparrish** [comment] 2020-02-21 16:38
Thanks for the info.  We will see what we can do.  Unfortunately, we already upgraded our Windows 10 lab machine to Chromium-based Edge, so we can't test this directly right now.  I'll try to find a way to get access to Edge legacy again.

**Comment by joeyparrish** [comment] 2020-02-21 21:01
It turns out that reverting to legacy Edge was very easy.  So we should be able to reproduce this issue soon.

**Comment by glhvta** [comment] 2020-02-21 21:30
great, thank you for looking into this issue

**Comment by karlovich** [comment] 2020-02-24 21:24
reproduced under my MS Edge too, 
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362
OS: Win10,
 

good for 1.6.5 https://v1-6-5-dot-shaka-player-demo.appspot.com/
reproduced from 2.0.0 https://v2-0-0-dot-shaka-player-demo.appspot.com/demo/

manifest
https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd

**Comment by DenisDashkevich** [comment] 2020-03-30 09:39
Hi @joeyparrish 

We faced the same issue,
Did you have a chance to check it?

**Comment by joeyparrish** [comment] 2020-03-30 15:27
Unfortunately, we are all on lock down due to COVID here in the Seattle area, and our office is closed.  We don't have physical access to our testing lab at the moment, and an audio issue isn't something I can debug remotely.  I don't have local access to Edge while I'm working from home.

Please accept our apologies for the delay.  In the mean time, you might consider adding an interstitial dialog to your app asking users of legacy Edge to upgrade to the new Edge or another evergreen browser.  Legacy Edge is no longer being actively supported by Microsoft, and at some point we will have to drop support as well.

**Comment by glhvta** [comment] 2020-08-25 07:53
Hello Joey,

This behavior was tested with v2.5.15 and v3.0.3 shaka and this issue still observed.

Shaka 3.0.3 video with this issue:
https://drive.google.com/file/d/1JbZYo7sql7X1htBbucegB3VXtGhHn1ea/view?usp=sharing

MS Edge version
Microsoft Edge 44.18362.449.0

Thanks.

**Comment by joeyparrish** [comment] 2020-10-12 16:55
Quick update, though it's not much of one:

I still have not found time to debug this in person in the lab.  I'm the only person on my team with physical building access, and I'm juggling a lot right now.  We can all access the lab and legacy Edge remotely, but without sound, that doesn't help on this issue.

According to latest data on https://caniuse.com/usage-table, some 17% of Edge usage is still legacy Edge, though that is only 0.45% of overall browser share.  In the past, we have made support decisions based on a 1% threshold.

So although we would really like to be able to help...

1. I have no immediate access to legacy Edge in person to debug, making this very hard to look into
2. Usage of legacy Edge is globally very low, making this low *priority*
3. Legacy Edge is no longer supported by Microsoft, making this low *priority* again
4. The most likely cause of this issue is a bug in a now-unmaintained, closed-source browser, making this unlikely to be resolved
5. The problem resolves itself shortly after seeking, and only affects users *without headphones*, making this seem to be a very low *severity* bug

Combined, sadly, it seems best to close this issue.  Please accept our apologies for not being able to do more.

**Closed** 2020-10-12 16:55 UTC
Labels: will not implement
