### ISSUE TITLE
Live Playready content is not playing in Shaka Player demo app.

### ISSUE THREAD

**Issue by rajlaxmi28** [google/shaka-player#674] opened 2017-02-02 06:03 UTC
Mpd file is attached below:
[TG_TEST_SD.txt](https://github.com/google/shaka-player/files/747308/TG_TEST_SD.txt)

- What version of Shaka Player are you using? - Shaka Player v2.0.5-debug

  - Can you reproduce the issue with our latest release version? - Yes

  - Can you reproduce the issue with the latest code from `master`? 

- Are you using the demo app or your own custom app? - Demo App

  - If custom app, can you reproduce the issue using our demo app?

- What browser and OS are you using?
Browser - IE11
OS - Windows10

- What did you do? - I created a live Dash content with <cenc:pssh> and <mspr:pro> data included in mpd. There is no pssh information stored in init.mp4. When I tried to play my content in shaka player (IE11), one frame is being displayed but content is not playing. I did not find any license call in debugger tool nor any console error. I did not understand how it is able to decrypt one frame and why there is no license call. I am attaching my mpd file and screen shot for shaka player & it's network log. I am not getting any console error why playback is not happenning.
![live_pr_shaka_network_log](https://cloud.githubusercontent.com/assets/25498535/22538489/a83b9fcc-e938-11e6-8a4e-9e0fbff4f6d7.png)
![img_20170202_111210842](https://cloud.githubusercontent.com/assets/25498535/22538540/1674342c-e939-11e6-9512-98f90e1f64a5.jpg)

  - What content did you load? - Custom

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?
Manifest url - http://192.168.3.125/mm/dash/live/7015/LIVESERVICE_1234/TG_TEST_SD.mpd
License Server url - http://192.168.3.125/drmclientproxy/playready/get_license

  - How did you interact with the content, if at all?
This content i created locally and using local server for getting license.

- What did you expect to happen?
I expected playback to happen

- What actually happened?
When I am trying to play this content, it is displaying first frame but not playing the content. It is continuously downloading live segments but there is not license call. When i have pssh data in my init segment and not in mpd then my content is playing fine. But i am trying to use mpd to play my content as pssh data may be different for segments. 

Please help me with this issue.

Thanks,
Raj Laxmi

**Comment by rajlaxmi28** [comment] 2017-02-02 09:32
[TG_TEST_SD.txt](https://github.com/google/shaka-player/files/747306/TG_TEST_SD.txt)

**Comment by TheModMaker** [comment] 2017-02-06 18:39
What packager are you using to encrypt content but not include a pssh?  Most packagers will add a pssh box when they encrypt the content.  Are you sure the content is actually encrypted?

You can include a `<cenc:pssh>` element in the mpd even if it is in the segments.  The value given in the manifest will override the one given in the content.  The player will ignore any pssh boxes in the content if there are pssh boxes in the manifest.

First I notice the `cenc:default_KID` attribute in the manifest doesn't match the key id specified in the pssh box.  This will cause the player to throw an error once the license request comes back since the license won't have that key id.  The attribute must either be missing or match the key id the content is encrypted with.

I don't see anything wrong with your content.  It is possible this is a bug in IE.  But without a live URL to test with, we can't help.  Can you please provide a public URL so I can test (you can send it privately if you want, my email is in [CONTRIBUTORS](https://github.com/google/shaka-player/blob/master/CONTRIBUTORS)).  What you gave is your internal IP, which I can't access.

**Comment by rajlaxmi28** [comment] 2017-02-15 07:36
Sorry for delay in response to your comment.
I have corrected the value of cenc:default_KID attribute in the manifest. It is now equivalent to kid specified in pssh box.

Public url:
Manifest : http://115.119.242.22/mm/dash/live/7015/LIVESERVICE_1234/TG_TEST_SD.mpd
License Server - http://115.119.242.22/drmclientproxy/playready/get_license

Thank you for your reply.

**Comment by TheModMaker** [comment] 2017-02-16 22:20
That URL works, but I am getting 404 errors for the segments.  Is the stream still running?  Please keep the stream running until this is fixed.

**Comment by TheModMaker** [comment] 2017-02-17 23:19
Now the stream works.  I am able to reproduce your error.  This seems to be a bug in Edge.

If you remove the audio stream from your manifest, I can play the video fine.  I am also able to reproduce with our test content by removing the `pssh` box from the audio init segments (video seems fine with it).

I will create a self-contained repro and submit a bug to Edge.  In the meantime, you'll have to put the `pssh` in the init segment.  There doesn't seem to be any workaround we can do.

**Comment by TheModMaker** [comment] 2017-02-21 19:07
FYI bug filed: <https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11016936/>

**Comment by rajlaxmi28** [comment] 2017-02-22 11:18
Thank you very much for you support.

**Comment by TheModMaker** [comment] 2017-02-22 17:26
I have occasionally seen Edge not send license requests, though not that often.  It is possible that it is storing the licenses on disk and when we request the license, it loads it from disk rather than asking the server.  But I'm not sure.

I don't know how key rotation works in PlayReady.  In Widevine, it works as you describe: media segments contain `pssh` boxes that describe newer licenses.  As we play the media, the browser gives us those boxes and we request new licences.

Try putting the first `pssh` box in the init segment and then newer `pssh` boxes in the media.  Also try putting a breakpoint in `DrmEngine.prototype.onEncrypted_` to see if we are getting the new events correctly.  You'll need to use the uncompiled library, but the demo app does by default.

As for testing, Shaka Player doesn't require https.  The demo site redirects because Chrome requires it.  If you are running a local copy of the player on your own web server, it will not redirect.  Additionally, `localhost` is a secure domain, so Chrome will still allow playing protected content.

**Comment by rajlaxmi28** [comment] 2017-03-02 07:03
Thank you very much for your support. It helped me a lot.

I will try to run a local copy of shaka player to check key rotation playback for playready.

**Comment by joeyparrish** [comment] 2017-10-07 19:14
Reported [fixed by Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11016936/) in Edge, but we are unsure what version and have not yet verified the fix.

**Comment by rajlaxmi28** [comment] 2018-02-06 14:26
As the issue [link to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11016936/]  seemed fixed, I tried to play a video only live content protected by Playready and has key rotation enabled. Content has pssh box in media content and ContentProtection Descriptor element in MPD; no pssh box in init segment.

When playing the content in Microsoft Edge, Shaka-Player is giving error "Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (InvalidAccessError) -- The CDM was unable to generate a license request for the init data it was given. The init data may be malformed or in an unsupported format. 
error.data[0] is an error message string from the browser." 

content url: http://111.93.150.213/mm/dash/live/7015/LIVESERVICE_1234/TG_TEST_SD.mpd
license server url: http://111.93.150.213/drmclientproxy/playready/get_license

**Comment by joeyparrish** [comment] 2018-02-12 19:55
@rajlaxmi28, what version of Edge are you running?

**Comment by rajlaxmi28** [comment] 2018-02-16 06:23
@joeyparrish I am using latest version of Edge (Microsoft Edge 41.16299.248.0).

**Comment by rajlaxmi28** [comment] 2018-02-20 13:29
Hi Joey,

Is there any update on this issue. For your reference i have provided public url to content.
content url: http://111.93.150.213/mm/dash/live/7015/LIVESERVICE_1234/TG_TEST_SD.mpd
license server url: http://111.93.150.213/drmclientproxy/playready/get_license

Please provide your feedback on this issue.

**Comment by joeyparrish** [comment] 2018-02-20 18:29
@rajlaxmi28, this is an issue with Microsoft Edge, so you will need to ask Microsoft for update: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11016936/

Although they have marked the bug fixed, they have never stated what version of Edge will contain the fix.

**Comment by rajlaxmi28** [comment] 2018-02-23 04:51
Thank you for your response.

**Comment by joeyparrish** [comment] 2018-02-23 18:14
I'm happy to help, and I'm sorry I can't give you an authoritative answer on this.  Hopefully Microsoft will get back to us, and if not, I can try to escalate the issue with them.

**Comment by rajlaxmi28** [comment] 2018-02-27 05:36
That would be very helpful. Much appreciated.

**Comment by joeyparrish** [comment] 2018-04-12 17:03
I just confirmed that this is fixed in Edge/16.16299.

**Closed by joeyparrish** 2018-04-12 17:03 UTC
Labels: EME, external
