### ISSUE TITLE
Shaka requests incorrect DRM than configured for live streams

### ISSUE THREAD

**Issue by tomaas-zeman** [google/shaka-player#1823] opened 2019-02-27 13:37 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.0-beta3

**Can you reproduce the issue with our latest release version?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
no

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 3+, WebOS 3.8

**What did you do?**
I played a live stream with the latest Shaka release (2.5.0-beta3)

**What did you expect to happen?**
Live stream is played and Widevine Modular is used as DRM.

**What actually happened?**
First of all, it's worth to mention that the same configuration of Shaka and our live stream worked perfectly with `2.5.0-beta2` so it kind of looks like a regression in `2.5.0-beta3`

Now when we pass live stream MPD playlist to Shaka, it incorrectly tries to ask PlayReady license server and fails with HTTP 500 License Acquisition Failed. But as per the configuration, we only expect to use Widevine Modular.

This is our Shaka configuration

```
{
    abr: {
        bandwidthDowngradeTarget: Device.config.video.abr.bandwidthDowngradeTarget,
        bandwidthUpgradeTarget: Device.config.video.abr.bandwidthDowngradeTarget,
        defaultBandwidthEstimate: 1000000,
        enabled: true,
        restrictions: {
            maxBandwidth: Infinity,
        },
        switchInterval: 10,
      },
    drm: {
        advanced: {
            'com.widevine.alpha': {
                audioRobustness: Device.config.video.drm.shakaRobustness,
                videoRobustness: Device.config.video.drm.shakaRobustness,
            },
        },
        servers: {
            'com.widevine.alpha': `${url.base}drm/widevine_modular?license_request=${drmConfig.LicenseRequest}`,
        },
    },
}
```

And this is (obfuscated) manifest which we use
```
<?xml version="1.0" encoding="utf-8"?>
<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
  xmlns:cenc="urn:mpeg:cenc:2013"
  xmlns:mspr="urn:microsoft:playready"
  xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd"
  type="dynamic"
  availabilityStartTime="1970-01-01T00:00:00Z"
  publishTime="2019-02-27T13:12:43.318119Z"
  minimumUpdatePeriod="PT2S"
  timeShiftBufferDepth="PT5M"
  maxSegmentDuration="PT5S"
  minBufferTime="PT10S"
  profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:com:dashif:dash264">
  <Period
    id="1"
    start="PT0S">
    <BaseURL>dash/</BaseURL>
    <AdaptationSet
      group="1"
      contentType="audio"
      lang="en"
      segmentAlignment="true"
      audioSamplingRate="48000"
      mimeType="audio/mp4"
      codecs="mp4a.40.5"
      startWithSAP="1">
      <AudioChannelConfiguration
        schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
        value="2">
      </AudioChannelConfiguration>
      <!-- Common Encryption -->
      <ContentProtection
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="9A04F079-1893-0F44-B138-04EEA3E74CA4">
      </ContentProtection>
      <!-- PlayReady -->
      <ContentProtection
        schemeIdUri="urn:uuid:1E2C0CAE-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
        <cenc:pssh>...ALgBjA...</cenc:pssh>
<mspr:IsEncrypted>1</mspr:IsEncrypted>
<mspr:IV_Size>8</mspr:IV_Size>
<mspr:kid>...+xOATu...</mspr:kid>
<mspr:pro>...AwADc...</mspr:pro>
      </ContentProtection>
      <!-- Widevine -->
      <ContentProtection
        schemeIdUri="urn:uuid:5E629AF5-79D6-4ACE-A3C8-27DCD51D21ED">
        <cenc:pssh>...TD0Sx...</cenc:pssh>
      </ContentProtection>
      <!-- Marlin -->
      <ContentProtection
        schemeIdUri="urn:uuid:EDEF8BA9-38DA-4063-8977-97FFBD9902D4">
<mas:MarlinContentIds>
  <mas:MarlinContentId>urn:marlin:kid:8930f44b138041e2c0cae1eea3e74ca4</mas:MarlinContentId>
</mas:MarlinContentIds>
      </ContentProtection>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
      <SegmentTemplate
        timescale="48000"
        initialization="SSH_new-$RepresentationID$.dash"
        media="SSH_new-$RepresentationID$-$Time$.dash">
        <!-- 2019-02-27T15:07:29.106645Z / 1551280049 - 2019-02-27T15:12:29.096000Z -->
        <SegmentTimeline>
          <S t="74461442357119" d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
          <S d="192511" />
          <S d="192512" />
          <S d="192513" />
          <S d="190464" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="audio_1=64000"
        bandwidth="64000">
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      group="2"
      contentType="video"
      par="16:9"
      minBandwidth="299968"
      maxBandwidth="6000000"
      maxWidth="1920"
      maxHeight="1080"
      segmentAlignment="true"
      sar="1:1"
      frameRate="25"
      mimeType="video/mp4"
      startWithSAP="1">
      <!-- Common Encryption -->
      <ContentProtection
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="9A04F079-1893-0F44-B138-04EEA3E74CA4">
      </ContentProtection>
      <!-- PlayReady -->
      <ContentProtection
        schemeIdUri="urn:uuid:1E2C0CAE-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
        <cenc:pssh>...AcAA6...</cenc:pssh>
<mspr:IsEncrypted>1</mspr:IsEncrypted>
<mspr:IV_Size>8</mspr:IV_Size>
<mspr:kid>...+xOATu...</mspr:kid>
<mspr:pro>...+ADwAL...</mspr:pro>
      </ContentProtection>
      <!-- Widevine -->
      <ContentProtection
        schemeIdUri="urn:uuid:5E629AF5-79D6-4ACE-A3C8-27DCD51D21ED">
        <cenc:pssh>...ATuo+...</cenc:pssh>
      </ContentProtection>
      <!-- Marlin -->
      <ContentProtection
        schemeIdUri="urn:uuid:EDEF8BA9-38DA-4063-8977-97FFBD9902D4">
<mas:MarlinContentIds>
  <mas:MarlinContentId>urn:marlin:kid:cae18930f441e2c0b13804eea3e74ca4</mas:MarlinContentId>
</mas:MarlinContentIds>
      </ContentProtection>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
      <SegmentTemplate
        timescale="25"
        initialization="SSH_new-$RepresentationID$.dash"
        media="SSH_new-$RepresentationID$-$Time$.dash">
        <!-- 2019-02-27T15:07:29Z / 1551280049 - 2019-02-27T15:12:29Z -->
        <SegmentTimeline>
          <S t="38782001225" d="100" r="74" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="video=299968"
        bandwidth="299968"
        width="384"
        height="216"
        codecs="avc1.4D401F"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=899968"
        bandwidth="899968"
        width="640"
        height="360"
        codecs="avc1.4D401F"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1800000"
        bandwidth="1800000"
        width="896"
        height="504"
        codecs="avc1.4D401F"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=2600000"
        bandwidth="2600000"
        width="1024"
        height="576"
        codecs="avc1.4D401F"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=4000000"
        bandwidth="4000000"
        width="1280"
        height="720"
        codecs="avc1.4D401F"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=6000000"
        bandwidth="6000000"
        width="1920"
        height="1080"
        codecs="avc1.4D4032"
        scanType="progressive">
      </Representation>
    </AdaptationSet>
  </Period>
  <UTCTiming
    schemeIdUri="urn:mpeg:dash:utc:http-iso:2014"
    value="https://time.akamai.com/?iso" />
</MPD>
```

**Comment by bcupac** [comment] 2019-02-27 16:38
had a similar problem, solved it with:

```
manifest: {
		dash: {
			ignoreDrmInfo: true
		},
	},
```

**Comment by ismena** [comment] 2019-02-27 22:01
Hi @tomaas-zeman, thanks for reporting!
First of all, it's really hard for us to diagnose an issue with no url provided for the repro.

Please feel free to send it privately to shaka-player-issues@google.com

Educated guess from looking at your report: we recently merged a PR for extracting playready drm info from the manifest. I think, this might be the reason it tries to acquire a play ready license.
If this is the case, the advice @bcupac gave you (thanks for responding btw :) ) should be able to do the trick as it will tell the player to ignore the extracted info.

Let us know how it goes!

**Comment by tomaas-zeman** [comment] 2019-02-28 07:00
Unfortunately I cannot share any details about the stream, it's not public.

The `ignoreDrmInfo` helped to avoid the exception when hitting bad DRM endpoint but the stream itself is buffering 99% of the time and it's more like a slideshow. On the other hand using `ignoreDrmInfo` with `2.5.0-beta2` has no effect, e.i. the stream is smooth.

Were there any other changes that may affect live streaming?

I know it's hard to reproduce but I knew that you did some modifications to DRM info extraction recently and since it works with `2.5.0-beta2` I thought that with a little bit of luck you could be able to root cause the problem just with the provided manifest / configuration

.

**Comment by joeyparrish** [comment] 2019-02-28 15:56
The only way we can debug the issue is if you provide us with instructions to reproduce the issue.  If you don't share a manifest URL or find a public manifest that reproduces the problem, there is absolutely nothing we can do to debug it.  It is extremely rare that the manifest text alone is enough to understand or fix a bug, especially a platform-specific or DRM-specific bug.

If you send a manifest URL and license server URLs to the email alias provided above, it will be kept confidential and will not be shared outside our team of developers at Google.  It will not be shared with any other part of Google or with any contributors outside Google.

If you absolutely can't share the content, you have a few options:

1. Try to change the minds of the people who make that decision
2. Get your infrastructure people to run a live stream using some public content, like Sintel, Big Buck Bunny, etc. and share that with us
3. Debug the issue yourself, asking us for tips when you get stuck

Please let us know what works best for you, and we'll do our best to accommodate you.  Thanks!

**Comment by tomaas-zeman** [comment] 2019-03-01 08:44
I'll try the third approach and get back to you when I have something useful.

**Comment by joeyparrish** [comment] 2019-03-01 17:30
Sounds good.  Thanks!

**Comment by tomaas-zeman** [comment] 2019-03-22 14:14
I gathered some debug information from our device. There is a recurring pattern right after the live stream is started. And it reflects what we observe on the TV - a slideshow basically.

This is a debug build from current `master` (last commit 9c224c1)

```
Jumping forward 15.16599988937378 seconds to catch up with the seek range. shaka-player.compiled.debug.js:694
(all): seeked: unbuffered seek: clearing all buffers shaka-player.compiled.debug.js:719
(audio:1) clear: nothing buffered shaka-player.compiled.debug.js:720
(video:3) clear: already waiting shaka-player.compiled.debug.js:720
2(audio:1) looking up segment: presentationTime=1553266391.278 currentPeriod.startTime=0 shaka-player.compiled.debug.js:741
Updating manifest... shaka-player.compiled.debug.js:552
Calling switch_(), bandwidth=1239 kbps shaka-player.compiled.debug.js:303
switch_ shaka-player.compiled.debug.js:1021
switch: switching to Stream (video:4) shaka-player.compiled.debug.js:717
switch: Stream (audio:1) already active shaka-player.compiled.debug.js:717
(audio:1) looking up segment: presentationTime=1553266391.278 currentPeriod.startTime=0 shaka-player.compiled.debug.js:741
(video:4) skipping update and clearing the buffer shaka-player.compiled.debug.js:731
(video:4) clearing buffer shaka-player.compiled.debug.js:770
(video:4) cleared buffer shaka-player.compiled.debug.js:771
(video:4) looking up segment: presentationTime=1553266391.278 currentPeriod.startTime=0 shaka-player.compiled.debug.js:741
Ignoring duplicate init data. shaka-player.compiled.debug.js:167
(audio:1) looking up segment: presentationTime=1553266391.278 currentPeriod.startTime=0 shaka-player.compiled.debug.js:741
3Updating manifest... shaka-player.compiled.debug.js:552
```
I can provide concrete runtime data that are being used of needed. Just let me know what would be helpful to you. 

Thanks

[full log](https://github.com/google/shaka-player/files/2996665/shaka-debug.txt)

**Comment by vaage** [comment] 2019-03-22 15:56
@tomaas-zeman looking at your log, I think we've arriving at the same conclusion, for some reason the playhead is falling out of the seek range, seeking forward, triggering an unbuffered seek. This would explain why you are seeing the slideshow-like playback.

So why does this happen? There are a few different internal systems in the player that can cause the player to seek forward (@TheModMaker please keep me honest and mention any I miss)?:

- [Gap Jumping](https://github.com/google/shaka-player/blob/master/lib/media/gap_jumping_controller.js) looks ahead and seeks when it thinks the player is about to enter a gap.
- [Stall Detection](https://github.com/google/shaka-player/blob/master/lib/media/stall_detector.js) tracks the player's progress, kicking it forward when it appears stuck.
- [Playhead](https://github.com/google/shaka-player/blob/master/lib/media/playhead.js) ensures the player is only within the availability window, which includes the seek range.

I would suggest you look at [Playhead](https://github.com/google/shaka-player/blob/master/lib/media/playhead.js)  next and see what data it has to work with.

**Comment by TheModMaker** [comment] 2019-03-22 16:14
We have seen something similar on Chromecast.  It tends to take a while to start playing, especially after hitting the end of the buffer.  Since it takes a few seconds to start playing after a seek, we fall outside the availability window and do another seek.

Try setting the `.streaming.safeSeekOffset` configuration value to 10+ (seconds).  This will make us seek further from the left side of the live edge when we fall outside the range.  You can also try using a smaller segment size and reduce the `minBufferTime`.  This will allow us to download something faster (to resume playing) and allows us to continue playing with less content.

**Closed** 2019-04-01 15:35 UTC
Labels: TV/STB, needs triage, waiting on response
