### ISSUE TITLE
MPD@availabilityStartTime of 0 incorrectly triggers assertion about not having AST

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1147] opened 2017-11-22 09:13 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes

**What version of Shaka Player are you using**:
2.2.6-debug

**Can you reproduce the issue with our latest release version**:
unknown, used demo app

**Can you reproduce the issue with the latest code from `master`**:
unknown, used demo app

**Are you using the demo app or your own custom app**:
demo app

**If custom app, can you reproduce the issue using our demo app**:
N/A

**What browser and OS are you using**:
Chrome 62, Windows 10

**What are the manifest and license server URIs**:
https://media.axprod.net/PublicVideos/DashAstZero/Manifest.mpd

No segments are publically available - manifest only. Should be enough to reproduce.

**What did you do?**
Hit Load to start playback.

**What did you expect to happen?**
Player attempts to play back live presentation, no errors reported.

**What actually happened?**
`Assertion failed: Detected as IPR stream, but does not match our model of IPR!`

This appears to be because `MPD@availabilityStartTime` is "1970-01-01T00:00:00Z" which gets parsed to 0 in *dash_parser.js*. Because of that the `presentationStartTime_` check in the below assertion from *presentation_timeline.js* fails (0 == null).

```
      goog.asserts.assert(this.presentationStartTime_ != null &&
                          this.segmentAvailabilityDuration_ == Infinity,
          'Detected as IPR stream, but does not match our model of IPR!');
```

**Comment by TheModMaker** [comment] 2017-11-22 17:31
Duplicate of #1148

`0 != null`, the problem is that `segmentAvailabilityDuration_` is not infinity.  This is the same problem as your other manifest, your live streams have a duration.  We'll continue the discussion there.

**Closed by TheModMaker** 2017-11-22 17:31 UTC

**Comment by sandersaares** [comment] 2017-11-22 17:58
I confirm your assessment of the facts. Apologies for insufficient investigation on my side!
