### ISSUE TITLE
Unable to play Shaka History live stream

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#1120] opened 2017-11-13 19:26 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**:

**Can you reproduce the issue with our latest release version**: Yes (v2.2.5-debug)

**Can you reproduce the issue with the latest code from `master`**: Yes (v2.2.0-117-g7e7a58d4-uncompiled)

**Are you using the demo app or your own custom app**: Demo App

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**: Linux/Mac, Chrome 62

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
https://storage.googleapis.com/shaka-live-assets/player-source.mpd

**What did you do?**
Select the `Shaka Player History` asset from the demo.

https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-live-assets/player-source.mpd;lang=en-US

**What did you expect to happen?**
To play.

**What actually happened?**
Infinite buffering with `cannot find segment`.  When it starts, the time is not at the live edge.  If I manually seek to the live edge, it still doesn't play.  May be related to #1117.

**Comment by avelad** [comment] 2017-11-13 21:20
I think that it is the same as https://github.com/google/shaka-player/issues/1105

**Comment by joeyparrish** [comment] 2017-11-13 21:23
Closing as a duplicate of #1105

**Closed by joeyparrish** 2017-11-13 21:23 UTC
Labels: duplicate
