### ISSUE TITLE
[CORS] Not able to start playready stream

### ISSUE THREAD

**Issue by pajong** [google/shaka-player#448] opened 2016-07-18 17:48 UTC
Hello,
I am trying to play the following stream in the demo player, but the stream does not play with a source not supported error.
I am using Edge to try to play the stream.

Manifest: http://us-primetime-dash.s3.amazonaws.com/1/y/am/g3jyb/g3jyb_Primetime_Dash_Playlist_DRM.mpd
License server: http://40.118.248.232/License/PlayReady/Get

The following test pages are able to play the stream just fine.
http://playready.azurewebsites.net/Home/TestPlayer
http://bitmovin.com/mpeg-dash-hls-drm-test-player/

Can you please take a look at why the stream is not able to be played on shaka?

Thank you so much!

**Comment by johnluther** [comment] 2016-07-20 21:57
Here is the console output from Edge:

SCRIPT5: Access is denied.

http_plugin.js (38,5)
Wrong error type!
Player error Error: Access is denied.

main.js (147,3)
   "Player error"
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "Error"
      },
      description: "Access is denied.",
      message: "Access is denied.",
      name: "Error",
      number: -2147024891,
      stack: "Error: Access is denied.

   at Anonymous function (https://shaka-player-demo.appspot.com/lib/net/http_plugin.js:38:5)

   at Promise (native code)

   at shaka.net.HttpPlugin (https://shaka-player-demo.appspot.com/lib/net/http_plugin.js:35:3)

   at shaka.net.NetworkingEngine.prototype.send_ (https://shaka-player-demo.appspot.com/lib/net/networking_engine.js:364:3)

   at shaka.net.NetworkingEngine.prototype.request (https://shaka-player-demo.appspot.com/lib/net/networking_engine.js:302:3)

   at shaka.dash.DashParser.prototype.requestManifest_ (https://shaka-player-demo.appspot.com/lib/dash/dash_parser.js:341:3)

   at shaka.dash.DashParser.prototype.start (https://shaka-player-demo.appspot.com/lib/dash/dash_parser.js:303:3)

   at Anonymous function (https://shaka-player-demo.appspot.com/lib/player.js:340:5)"

   }

**Comment by joeyparrish** [comment] 2016-07-21 18:11
I was able to reproduce on Edge [with the nightly build](http://nightly.shaka-player-demo.appspot.com/demo/?asset=http://us-primetime-dash.s3.amazonaws.com/1/y/am/g3jyb/g3jyb_Primetime_Dash_Playlist_DRM.mpd;license=http://40.118.248.232/License/PlayReady/Get;play).  What I found was an error 6007 (LICENSE_REQUEST_FAILED), with the data field set to an error 1002 (HTTP_ERROR).

What this means is that the license request failed due to an HTTP error.  An HTTP error is distinct from error 1001 (BAD_HTTP_STATUS).  A bad HTTP status means the server returned something other than a 2xx status, but an HTTP error means the request failed without a status code being communicated to JavaScript through the XHR.

Error 1002 is typically caused by a CORS problem, and indeed, Edge's debug console shows the error message `SEC7120: Origin http://nightly.shaka-player-demo.appspot.com not found in Access-Control-Allow-Origin header.`

I would advise you to make sure your CORS headers are correct and understood by Edge.

**Comment by joeyparrish** [comment] 2016-07-28 23:53
@pajong, @johnluther, were you able to resolve the CORS error?

**Comment by esboyd** [comment] 2016-07-29 18:55
Thanks for checking in on this @joeyparrish. I am reaching back to the customer to see if they were able to change anything

**Comment by esboyd** [comment] 2016-07-29 20:43
@joeyparrish they added  

"headers": [{"name": "Accept", value": "*/*"  },

But the response header is still not containing the following: 

"headers": [
                        {
                            "name": "Access-Control-Allow-Headers",
                            "value": "ORIGIN, X-REQUESTED-WITH, CONTENT-TYPE, ACCEPT, SOAPACTION, CUSTOMDATA, AUTHORIZATION"
                        },
                        {
                            "name": "Access-Control-Allow-Methods",
                            "value": "GET, POST, OPTIONS, HEAD"
                        },
                        {
                            "name": "Access-Control-Allow-Origin",
                            "value": "http://playready.azurewebsites.net"
                        },
Which is what we see happens in one of the other test players. Reaching out to the owner of the license server to see why those headers are not getting added to the response. 

thanks again!

**Comment by joeyparrish** [comment] 2016-08-11 20:17
@esboyd Any update?  Is there anything else you need from us on this, or can we close the issue?

**Comment by esboyd** [comment] 2016-08-22 13:11
@joeyparrish Sorry for the late reply, still have not been able to get the key server to change their rules, so we can probably close this.

**Comment by joeyparrish** [comment] 2016-08-23 00:29
Okay, well please feel free to reach out again if you need further support.

**Closed by joeyparrish** 2016-08-23 00:29 UTC
Labels: question
