### ISSUE TITLE
shaka crashes on audio track switching - Firefox 

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#517] opened 2016-09-14 11:51 UTC
- Are you using the demo app or your own custom app? **demo app**
- What did you do? **switch audio track**
  - What content did you load?
    - If custom asset, what manifest and license server URIs?

http://qa-nginx-vod.dev.kaltura.com/dash/p/1091/sp/109100/serveFlavor/entryId/0_rd5ko090/v/2/flavorId/0_,zfgyzbls,q6o5z8f3,5na0i0y6,/forceproxy/true/name/a.mp4.urlset/manifest.mpd
- What did you expect to happen?
  **audio track switching**
- What actually happened?
  **shaka crashes**

**Note: in FirefoxNightly it works ok**

**Comment by cpeterso** [comment] 2016-09-14 17:05
@yairans, can you please elaborate on what you mean by "Shaka crashes"? Does the stream stop loading? Do you see a JavaScript exception in Firefox's web console?

Your Disney stream plays correctly for me using the [Shaka demo player](http://shaka-player-demo.appspot.com/demo/) on Firefox 48 and Firefox Nightly 51 (on Windows 10).

**Comment by yairans** [comment] 2016-09-15 07:48
**@cpeterso,**  I can reproduce this one on both mac (FF 48) and windows 10 (FF 47).
When I switch the audio track I see a red line "Shaka Error MEDIA.VIDEO.ERROR(3,)"
and the loading spinner. 
In the console I get the following:

`(audio:4) failed fetch and append: code=3014         streaming_engine.js:1167:7`

`Player error Object { category: 3, code: 3014, data: Array[1], message: "Shaka Error MEDIA.MEDIA_SOURCE_OPER…", stack: "shaka.util.Error@http://shaka-playe…" }   main.js:190:3`

`Media resource mediasource:http://shaka-player-demo.appspot.com/d6cc740e-54f3-8c4c-aa9c-ad439474c2b5 could not be decoded.                demo`

`Player error Object { category: 3, code: 3016, data: Array[2], message: "Shaka Error MEDIA.VIDEO_ERROR (3,)", stack: "shaka.util.Error@http://shaka-playe…" }         main.js:190:3`

`failed to get buffered range for video DOMException [InvalidStateError: "An attempt was made to use an object that is not, or is no longer, usable"
code: 11
nsresult: 0x8053000b
location: http://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:316]`

Thanks,
Yair

**Comment by joeyparrish** [comment] 2016-09-15 17:32
Looks like a decoder error.  @cpeterso, should we move to Firefox bugzilla or continue here?

**Comment by cpeterso** [comment] 2016-09-15 23:07
Good news! I was able to reproduce this exception. (I forgot to switch audio tracks when testing.)

This problem was [Firefox bug 1247138](https://bugzilla.mozilla.org/show_bug.cgi?id=1247138) ("Handle MSE audio configuration change"). It is fixed in Firefox Beta 49, which will be the new stable release on September 20 next week.

@joeyparrish, please feel free to close this GitHub issue (now or when Firefox 49 is released next week), unless you plan to work around this problem in Shaka for people using outdated Firefox versions.

**Comment by joeyparrish** [comment] 2016-09-15 23:18
Thanks, Chris!  I'll mark external bug for now, and close once 49 goes stable.

**Comment by yairans** [comment] 2016-09-18 06:56
@joeyparrish @cpeterso 
Thank you

**Comment by joeyparrish** [comment] 2016-11-14 19:24
Closing now that Firefox 49 is out.

**Closed by joeyparrish** 2016-11-14 19:24 UTC
Labels: bug, external
