### ISSUE TITLE
Incorrect expiration times reported by Tizen5

### ISSUE THREAD

**Issue by tvanlaerhoven** [google/shaka-player#2456] opened 2020-03-15 19:26 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes, and extensively read documentation as well.

**What version of Shaka Player are you using?**

2.5.6c

**Please ask your question**

In our react-native-web application, running as a Tizen smart web app on Samsung smart TVs, we use ShakaPlayer 2.5.6c to play DASH live streams.

The issue is that sometimes the stream does not start. The DRM license is received, segments are being fetched, but somehow the player does not show any frames. The player does not log any errors. Hours later the issue disappears. Also, the issue does not seem to affect all devices.

The live streams originate from a Halo packages that is being used for other clients as well (ExoPlayer, AVplayer & Chromecast ShakaPlayer), without any issue. We use titanium DRM license wrapping.

Below is a detailed timeline of what happens with a failing stream. The app registers player listeners for events abrstatuschanged, adaptation, buffering, drmsessionupdate, emsg, error, expirationupdated, largegap, loading, manifestparsed, onstatechange, onstateidle, streaming, unloading, and variantchanged. Additionally, every 2.5 seconds the playhead, current manifest & buffering info is written. For each segment fetch, the response date header is shown.

We have tried with a wide range of configurations, including different values for buffering parameters, defaultPresentationDelay jumpLargeGaps and videoRobustness. All with the same result.

The timeline below shows that the same segment is fetched multiple times. It looks like the player is retrying to fetch segments, although none fail.

At first it looks like there is a DRM issue, where the player is not able to decode video chunks. When play-out succeeds we see an extra 'expirationupdated: there is a change in the expiration times of an EME session' event right after a 'drmsessionupdate: the CDM has accepted the license response' event, which could support this theory. However, no error is thrown by the player.

What could be the cause of this behavior? Note that the issue appear often, but not always.

```
2020-3-14 11:10:55	loading
2020-3-14 11:10:55	onstatechange					"attach"
2020-3-14 11:10:55	onstatechange					"media-source"
2020-3-14 11:10:55	onstatechange					"manifest-parser"
2020-3-14 11:10:55	onstatechange					"manifest"
2020-3-14 11:10:55	networkEngine manifest response
2020-3-14 11:10:55	manifestparsed
2020-3-14 11:10:55	onstatechange					"drm-engine"
2020-3-14 11:10:55	onstatechange					"load"
2020-3-14 11:10:55	buffering						true
2020-3-14 11:10:55	streaming
2020-3-14 11:10:55	abrstatuschanged
2020-3-14 11:10:55	seekRange						{"start":266177.98933333333,"end":266197.85233330727}
2020-3-14 11:10:55	onstateidle						state: load
2020-3-14 11:10:56	video event: play
2020-3-14 11:10:56	network license request
2020-3-14 11:10:56	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:29 GMT"	audio1/Header.m4s 
2020-3-14 11:10:56	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	audio1/1388208802880.m4s
2020-3-14 11:10:56	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:55 GMT"	video2/Header.m4s
2020-3-14 11:10:56	network license					response received
2020-3-14 11:10:56	drmsessionupdate				the CDM has accepted the license response
2020-3-14 11:10:56	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video2/1388208801440.m4s
2020-3-14 11:10:57	abrstatuschanged
2020-3-14 11:10:57	adaptation						an automatic adaptation causes the active tracks to change
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:43 GMT"	audio1/1388208981440.m4s
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:38 GMT"	video2/1388208081440.m4s
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:34 GMT"	audio1/1388208261440.m4s
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:56 GMT"	video3/Header.m4s
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video3/1388208081440.m4s	MISS
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video3/1388208081440.m4s	HIT
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video3/1388208081440.m4s	HIT
2020-3-14 11:10:57	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:58	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:58	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video3/1388208081440.m4s	HIT
2020-3-14 11:10:58	current status					player.isBuffering(): true; player.isInProgress(): false
2020-3-14 11:10:58	current manifest info			delay: 10s; maxSegmentDuration: 2.25s; seekRange: [2020-3-14 11:10:25 - 2020-3-14 11:10:45]; usingPresentationStartTime: false;
2020-3-14 11:10:58	live presentationStartTime		2020-3-11 09:14:05
2020-3-14 11:10:58	live playhead time				2020-3-14 11:10:34
2020-3-14 11:10:58	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:58	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video3/1388208081440.m4s	HIT
2020-3-14 11:10:58	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:58	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video3/1388208081440.m4s	HIT
2020-3-14 11:10:58	networkEngine manifest response
2020-3-14 11:10:58	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:33 GMT"	audio1/1388208082880.m4s	HIT
2020-3-14 11:10:58	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:34 GMT"	audio1/1388208261440.m4s	HIT
2020-3-14 11:10:59	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video3/1388208081440.m4s	HIT
2020-3-14 11:10:59	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:37 GMT"	audio1/1388208441920.m4s	HIT
2020-3-14 11:10:59	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	video3/1388208261440.m4s	MISS
2020-3-14 11:10:59	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:49 GMT"	video3/1388208441440.m4s	MISS
2020-3-14 11:10:59	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:51 GMT"	video3/1388208621440.m4s	MISS
2020-3-14 11:10:59	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:53 GMT"	video3/1388208801440.m4s	MISS
2020-3-14 11:11:00	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:39 GMT"	audio1/1388208622400.m4s	HIT
2020-3-14 11:11:00	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:41 GMT"	audio1/1388208802880.m4s	HIT
2020-3-14 11:11:00	buffering						false
2020-3-14 11:11:00	current status					player.isBuffering(): false; player.isInProgress(): false
2020-3-14 11:11:00	current manifest info			delay: 10s; maxSegmentDuration: 2.25s; seekRange: [2020-3-14 11:10:28 - 2020-3-14 11:10:48]; usingPresentationStartTime: false; 
2020-3-14 11:11:00	live presentationStartTime		2020-3-11 09:14:05
2020-3-14 11:11:00	live playhead time				2020-3-14 11:10:34
2020-3-14 11:11:00	buffered time					[2020-3-14 11:10:31 to 2020-3-14 11:10:40]
2020-3-14 11:11:01	networkEngine manifest response
2020-3-14 11:11:03	current status					player.isBuffering(): false; player.isInProgress(): false
2020-3-14 11:11:03	current manifest info			delay: 10s; maxSegmentDuration: 2.25s; seekRange: [2020-3-14 11:10:30 - 2020-3-14 11:10:50]; usingPresentationStartTime: false; 
2020-3-14 11:11:03	live presentationStartTime		2020-3-11 09:14:05
2020-3-14 11:11:03	live playhead time				2020-3-14 11:10:34
2020-3-14 11:11:03	buffered time					[2020-3-14 11:10:31 to 2020-3-14 11:10:40]
2020-3-14 11:11:04	networkEngine manifest response
2020-3-14 11:11:05	current status					player.isBuffering(): false; player.isInProgress(): false
2020-3-14 11:11:05	current manifest info			delay: 10s; maxSegmentDuration: 2.25s; seekRange: [2020-3-14 11:10:33 - 2020-3-14 11:10:53]; usingPresentationStartTime: false; 
2020-3-14 11:11:05	live presentationStartTime		2020-3-11 09:14:05
2020-3-14 11:11:05	live playhead time				2020-3-14 11:10:34
2020-3-14 11:11:05	buffered time					[2020-3-14 11:10:31 to 2020-3-14 11:10:40]
2020-3-14 11:11:07	adaptation						an automatic adaptation causes the active tracks to change
2020-3-14 11:11:07	networkEngine segment			"date":"Sat, 14 Mar 2020 10:11:04 GMT"	video3/1388208981440.m4s	MISS
2020-3-14 11:11:07	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:43 GMT"	audio1/1388208981440.m4s	HIT
2020-3-14 11:11:07	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:45 GMT"	audio1/1388209161920.m4s	HIT
2020-3-14 11:11:07	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:29 GMT"	video7/Header.m4s			HIT
2020-3-14 11:11:07	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:47 GMT"	audio1/1388209342400.m4s	HIT
2020-3-14 11:11:07	networkEngine manifest response
2020-3-14 11:11:08	current status					player.isBuffering(): false; player.isInProgress(): false
2020-3-14 11:11:08	current manifest info			delay: 10s; maxSegmentDuration: 2.25s; seekRange: [2020-3-14 11:10:35 - 2020-3-14 11:10:55]; usingPresentationStartTime: false; 
2020-3-14 11:11:08	live presentationStartTime		2020-3-11 09:14:05
2020-3-14 11:11:08	live playhead time				2020-3-14 11:10:39
2020-3-14 11:11:08	buffered time					[2020-3-14 11:10:31 to 2020-3-14 11:10:42]
2020-3-14 11:11:08	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:45 GMT"	video7/1388209161440.m4s	HIT
2020-3-14 11:11:09	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:47 GMT"	video7/1388209341440.m4s	HIT
2020-3-14 11:11:10	current status					player.isBuffering(): false; player.isInProgress(): false
2020-3-14 11:11:10	current manifest info			delay: 10s; maxSegmentDuration: 2.25s; seekRange: [2020-3-14 11:10:38 - 2020-3-14 11:10:58]; usingPresentationStartTime: false; 
2020-3-14 11:11:10	live presentationStartTime		2020-3-11 09:14:05
2020-3-14 11:11:10	live playhead time				2020-3-14 11:10:40
2020-3-14 11:11:10	buffered time					[2020-3-14 11:10:31 to 2020-3-14 11:10:46]
2020-3-14 11:11:11	networkEngine manifest response
2020-3-14 11:11:12	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:49 GMT"	audio1/1388209522880.m4s	HIT
2020-3-14 11:11:12	networkEngine segment			"date":"Sat, 14 Mar 2020 10:10:51 GMT"	audio1/1388209701440.m4s	HIT
2020-3-14 11:11:13	current status					player.isBuffering(): false; player.isInProgress(): false
2020-3-14 11:11:13	current manifest info			delay: 10s; maxSegmentDuration: 2.25s; seekRange: [2020-3-14 11:10:40 - 2020-3-14 11:11:00]; usingPresentationStartTime: false; 
2020-3-14 11:11:13	live presentationStartTime		2020-3-11 09:14:05
2020-3-14 11:11:13	live playhead time				2020-3-14 11:10:45
2020-3-14 11:11:13	buffered time					[2020-3-14 11:10:31 to 2020-3-14 11:10:46]
```

**Comment by TheModMaker** [comment] 2020-03-19 20:37
Can you reproduce on Desktop?  Could you post Shaka Player logs?  You can use a debug or uncompiled build and set log level with `shaka.log.setLevel(shaka.log.Level.V1)`.  With the debug or uncompiled builds, could you also log `player.drmEngine_.activeSessions_.forEach((v, k) => console.log(k))`.

**Comment by tvanlaerhoven** [comment] 2020-03-20 10:40
It is not reproducible on Desktop no. I'll collect extra logging and post it here.

**Comment by tvanlaerhoven** [comment] 2020-03-20 16:25
The app with extra logging was not yet deployed on a Tizen 5 model where we originally saw the issue, but when checking verbose logs on a Chrome browser I already see a lot of "Assertion failed: SegmentReferences are incorrect" errors. On Chrome the stream just plays without other issues though.

It is probably best to look into this first. Could this be an indication for issues in the manifest? Note that on Android's Exoplayer we have no issues with the exact same streams. I also don't see any failed video/audio chunks being fetched. Below a sample of our MPD timeline:

```
<Period id="7462933" start="PT0S">
	...
	<SegmentTemplate timescale="90000" initialization="$RepresentationID$/Header.m4s" media="$RepresentationID$/$Time$.m4s" presentationTimeOffset="1364251342400">
		<SegmentTimeline>
			<S t="1436832201440" d="180000" r="14"/>
		</SegmentTimeline>
	</SegmentTemplate>
	...
</Period>
```

**Comment by TheModMaker** [comment] 2020-03-20 16:52
That log happens when the segment list changes in an incompatible way in a manifest update.  For example, the `presentationTimeOffset` changes, or the segment times don't match the old segments.  This content isn't supported, but may not be the cause of this problem.  If you could post a before and after segment list, I could give more info.

**Comment by tvanlaerhoven** [comment] 2020-03-20 22:34
Weirdly enough I cannot reproduce it again right now. It looks like an intermittent issue, much like the one being reported on the Tizen device.
I will continue to monitor it, and meanwhile deployed a version on a remote Tizen device.
Many thanks already!

**Comment by tvanlaerhoven** [comment] 2020-03-24 18:58
I got the following Level.V1 logging from a Tizen device, where I see a few "Stall detection" messages and a "Session expired":

```
18:21:31.326  onChooseStreams_
18:21:31.327  Found variant with audio and video content, so filtering out audio-only content in all periods.
18:21:31.327  codecs
18:21:31.327  Choosing new streams after period changed
18:21:31.327  init: completed initial Stream setup
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.328  Ignoring duplicate init data.
18:21:31.329  Ignoring duplicate init data.
18:21:31.329  Ignoring duplicate init data.
18:21:31.329  Ignoring duplicate init data.
18:21:31.329  Ignoring duplicate init data.
18:21:31.329  (audio:9)
18:21:31.330  (video:7)
18:21:31.331  (video:7)
18:21:31.331  (all) setting up Period 0
18:21:31.331  (all) Period 0 is being or has been set up
18:21:31.331  (all) Stream 9 is being or has been set up
18:21:31.332  (all) Stream 7 is being or has been set up
18:21:31.331  canSwitch_
18:21:31.331  Calling switch_(), bandwidth=1965 kbps
18:21:31.331  switch_
18:21:31.332  switch: switching to Stream (video:4)
18:21:31.331  (video:4)
18:21:31.331  switch: Stream (audio:9) already active
18:21:31.332  (video:4)
18:21:31.333  Calling switch_(), bandwidth=837 kbps
18:21:31.333  switch_
18:21:31.333  switch: switching to Stream (video:1)
18:21:31.333  (video:1)
18:21:31.333  switch: Stream (audio:9) already active
18:21:31.333  (video:1)
18:21:31.335  (all): seeked: buffered seek: presentationTime=1159580.140666
18:21:31.335  Calling switch_(), bandwidth=928 kbps
18:21:31.335  switch_
18:21:31.336  switch: Stream (video:1) already active
18:21:31.336  switch: Stream (audio:9) already active
18:21:31.336  Session has expired
18:21:31.337  Stall detected at 1159581.404 for 1.001000165939331 seconds. Seeking forward 0.1 seconds.
18:21:31.337  (all): seeked: buffered seek: presentationTime=1159581.504
18:21:31.337  (all): seeked: buffered seek: presentationTime=1159585.025666
18:21:31.338  Stall detected at 1159583.95 for 1.0149998664855957 seconds. Seeking forward 0.1 seconds.
18:21:31.337  (all): seeked: buffered seek: presentationTime=1159584.05
18:21:31.338  Stall detected at 1159583.95 for 1.121000051498413 seconds. Seeking forward 0.1 seconds.
18:21:31.338  (all): seeked: buffered seek: presentationTime=1159584.05
18:21:31.338  (all): seeked: buffered seek: presentationTime=1159588.988666
```

**Comment by tvanlaerhoven** [comment] 2020-03-27 14:34
@TheModMaker any insights? I'll further check the code of lib_media_drm_engine.js for details on the session object.

**Comment by joeyparrish** [comment] 2020-03-30 18:24
I see that you referenced version 2.5.6 of Shaka Player in the original post.  We released v2.5.10 last week which includes some DRM-related fixes for older versions of Tizen.

Could you try updating to v2.5.10 and see if that changes things?  If you see the same issues, would you please try extending the Tizen 2 fix to all versions by editing lib/media/drm_engine.js and replacing `isTizen2()` with `isTizen()`?

I'm sorry we're not able to offer more at this time, but our only Tizen device is running Tizen 3 and is in a test lab that none of us have physical access to right now because of the COVID pandemic.

**Comment by tvanlaerhoven** [comment] 2020-03-30 21:03
Thanks @joeyparrish ; I'll try with both v2.5.10, and a build that does not suppress the duplicate webkitneedkey events for all Tizen versions.

**Comment by tvanlaerhoven** [comment] 2020-04-10 08:34
I tried play-out with both v2.5.10, and a patched version of 2.5.10 where I replaced `isTizen2()` with `isTizen()`.
It seems to have effect, as both players are sometimes are to play when the original 2.5.6 version did not. But still, the fix is not consistent.

In the version where `isTizen2` is replaced with `isTizen` I see it creates a lot of sessions that shortly after expire. The session list is then empty, but there is still one usable keyId. From thereon, the expiration time is reported to be 'Infinity' as there is no session left I guess.

```
	Apr 10, 2020 @ 10:06:03.736	network license request
	Apr 10, 2020 @ 10:06:03.735	network license request
	Apr 10, 2020 @ 10:06:03.736	network license request
	Apr 10, 2020 @ 10:06:03.740	network license request
	Apr 10, 2020 @ 10:06:03.739	network license request
	Apr 10, 2020 @ 10:06:03.739	network license request
	Apr 10, 2020 @ 10:06:03.739	network license request
	Apr 10, 2020 @ 10:06:03.739	network license request
	Apr 10, 2020 @ 10:06:03.736	network license request
	Apr 10, 2020 @ 10:06:03.740	network license request
	Apr 10, 2020 @ 10:06:03.739	network license request
	Apr 10, 2020 @ 10:06:03.739	network license request
	Apr 10, 2020 @ 10:06:03.739	network license request
	Apr 10, 2020 @ 10:06:03.739	network license request
	Apr 10, 2020 @ 10:06:03.736	network license request
        ...
	Apr 10, 2020 @ 10:06:03.740	network license response
	Apr 10, 2020 @ 10:06:03.739	network license response	
	Apr 10, 2020 @ 10:06:03.739	network license response	
	Apr 10, 2020 @ 10:06:03.737	network license response	 
	Apr 10, 2020 @ 10:06:03.740	network license response	
	Apr 10, 2020 @ 10:06:03.739	network license response	
	Apr 10, 2020 @ 10:06:03.739	network license response	 
	Apr 10, 2020 @ 10:06:03.739	network license response
        ...
       Apr 10, 2020 @ 10:06:03.740	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.738	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.740	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.739	expiration time	next expiration time for any EME session: 2020-04-09T00:32:45.000Z
	Apr 10, 2020 @ 10:06:03.739	session ids	["ksid9CFCBA60","ksid08AD0211","ksidC5622DCB","ksid9AB2C478","ksid8D210BDB","ksidDA089F6C","ksid870543EC","ksidC03CE403","ksid2BE9D800","ksid8651AB7A","ksidB67B3B47","ksidDAD6BB4B","ksidE89A1E93","ksidB72150B5","ksidA70F7AC4"]
	Apr 10, 2020 @ 10:06:03.739	keyIds	[]
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.738	verbose	"Updating manifest..."
	Apr 10, 2020 @ 10:06:03.740	expirationupdated	there is a change in the expiration times of an EME session
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.739	drmsessionupdate	the CDM has accepted the license response
	Apr 10, 2020 @ 10:06:03.738	verbose	"Session has expired" "ksid9CFCBA60"
	Apr 10, 2020 @ 10:06:03.740	verbose	"Session has expired" "ksid08AD0211"
	Apr 10, 2020 @ 10:06:03.739	network manifest	{"uri":"https://..."}
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksid9AB2C478"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksidC5622DCB"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksid870543EC"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksid8D210BDB"
	Apr 10, 2020 @ 10:06:03.740	verbose	"Session has expired" "ksidC03CE403"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksidDA089F6C"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksid2BE9D800"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksidB67B3B47"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksid8651AB7A"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksidB72150B5"
	Apr 10, 2020 @ 10:06:03.740	verbose	"Session has expired" "ksidE89A1E93"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksidDAD6BB4B"
	Apr 10, 2020 @ 10:06:03.739	verbose	"Session has expired" "ksidA70F7AC4" 
        ...
        Apr 10, 2020 @ 10:06:03.740	expiration time	next expiration time for any EME session: Infinity
	Apr 10, 2020 @ 10:06:03.740	session ids	[]
	Apr 10, 2020 @ 10:06:03.740	keyIds	[["58c11f2039944d15950b39f38b7e3a23","usable"]]
	...
        Apr 10, 2020 @ 10:06:03.741	expiration time	next expiration time for any EME session: Infinity
	Apr 10, 2020 @ 10:06:03.740	session ids	[]
	Apr 10, 2020 @ 10:06:03.741	keyIds	[["58c11f2039944d15950b39f38b7e3a23","usable"]]
```

**Comment by joeyparrish** [comment] 2020-04-13 17:22
I'm not sure what the issue is, and we don't have access to a Tizen device at the moment.

From your logs, I would guess that the workaround where we have to create duplicate sessions may also be needed on Tizen 5, which is a real shame.  It's clearly a bug in Tizen's implementation of Widevine if that's needed at all, and I would have hoped Samsung could get it right by Tizen 5.

But something else strange is going on in that log, and it's not clear what.  Can you provide any details of your Widevine policy?  Key rotation periods, license durations, etc.  The more info you can provide, the better we may be able to guess at what's wrong.

Sadly, we still can't debug this directly.

**Comment by tvanlaerhoven** [comment] 2020-05-13 08:36
@joeyparrish , some info on our Widevine policy:

- There is no key rotation; the same key is used for both audio+video
- The license valid for max. either 24 or 48 hours (or end of entitlement)

**Comment by el-gringo** [comment] 2020-05-19 15:16
Hi, I've logged the session.expiration in drm_engine and it is 1 hour before actual date.

**Comment by joeyparrish** [comment] 2020-05-19 15:19
If the session expiration is in the past, then the session is expired and unusable.  There's nothing we can do to control this in JavaScript.  If the OS is doing the wrong thing with your license policy (such as misinterpreting the duration), you could try having your license server use a different policy for that OS to work around the bug.

The only other thing I can recommend is that you reach out to Samsung/Tizen for support to get them to fix the bug in their Widevine implementation.

Does this help?

**Comment by el-gringo** [comment] 2020-05-19 16:26
Thank you for your quick response !
We are going to have a partnership with Samsung so we will work with them in order to address this issue. Unfortunately I'm not expecting any answer for TV models already on market.
I'll work with the team to find an other license policy. 

However, patching drm_engine, by adding 1 hour to session.expiration works.

**Comment by joeyparrish** [comment] 2020-05-19 16:36
If that works, then it means the expiration time reported by the browser is not the actual expiration time understood by the CDM.  That's surprising, but perhaps it shouldn't be.  We've seen so many varied issues with Tizen's media and DRM implementations in each version of Tizen.

It's not possible for us to know that adding 1 hour will always be correct on Tizen 5.  For example, is it dependent on time zones?  Or Daylight Savings Time in the US and Summer Time in Europe?  Does it work this way for every policy, or only certain ones?  So I wouldn't feel confident about applying your workaround to all Tizen 5 devices for all applications.

However, expiration time is only one way we decide to close sessions for key rotation.  We also check for the "expired" key status.  Perhaps we could add a config to ignore the expiration time from EME.  You could configure Shaka Player this way on Tizen devices and avoid maintaining a fork.  Does that sound helpful?

**Comment by el-gringo** [comment] 2020-05-19 17:03
Yes I totally agree we cannot arbitrary add one hour. We'll do more investigation and ask Samsung.
We'll let you know if we find a solution. 
Adding an option to ignore expiration will not help that much as it will break our key rotation system.

**Comment by joeyparrish** [comment] 2020-05-19 17:04
How would it break key rotation?  Wouldn't we just close sessions based on the key status of 'expired'?

**Comment by el-gringo** [comment] 2020-05-19 17:18
Oh ok, I'm not a DRM specialist. That could work then.
Issue #2252 is also requesting for a such option.

**Comment by joeyparrish** [comment] 2020-05-19 17:23
Ah, thanks.  I had forgotten about that issue.  Thanks!

**Comment by joeyparrish** [comment] 2020-05-19 17:26
If you're interested to contribute a PR for this, please let us know!

Since we have a plan to solve it through the new option, should we close this as a duplicate of #2252?

**Comment by el-gringo** [comment] 2020-05-19 17:32
Yes you can close it.
We will let you know for a PR.

**Comment by joeyparrish** [comment] 2020-05-19 17:43
Thanks!

**Closed by joeyparrish** 2020-05-19 17:43 UTC
Labels: TV/STB, help wanted, needs triage
