### ISSUE TITLE
Issue with linear/live DASH DRM SSAI stream on Shaka player

### ISSUE THREAD

**Issue by mihirshroff-g** [google/shaka-player#2993] opened 2020-11-17 18:46 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from master?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app

**If custom app, can you reproduce the issue using our demo app?**
This is observed on CTV devices. Web plays content fine.

**What browser and OS are you using?**
WebOS/Tizen

**What issue are you facing?**
We are running into an issue where ads fail to play using Shaka player on multiple platforms. 

These are SSAI inserted ads in a DASH stream. Issue occurs when we are inserting ads in a DRM encrypted DASH stream.

We have capture our observations in the doc here for one of the platforms - LG webOS - [Link](https://docs.google.com/document/d/1N8ORmYAM9zKqwYrQ6s3p5zJ2bpZJPXHwPgDETCclFVg/edit?usp=sharing)

The other platforms where similar issues are observed:

- Samsung Tizen
- Roku
- Xbox

**What did you do?**

Created a demo app on LG/Samsung using Shaka player and tried to play the DRM encoded stream

**What did you expect to happen?**
Stream with ads to play seamlessly

**What actually happened?**
Stream stalls when ad content hits.

Let us know if you require more information to help debug this further. Let us know if you need access to the observations document.

Thanks,
Mihir

**Comment by Acesarye** [comment] 2020-12-24 12:49
Hi, I am also develop a Tizen DRM project, but I cannot play WIDEVINE stream. I have not applied to be a partner in Samsung yet, so I cannot use Drminfo Privileges. Can I bypass this privilege? Or can you provide me with a demo? I am looking forward to your reply.

**Comment by michellezhuogg** [comment] 2021-01-14 18:07
Update: I was not able to reproduce the issue on Tizen with the sample manifest. It should be reproducible on LG, according to @mihirshroff-g, however we don't have a WebOS set up in our lab now.
@mihirshroff-g is finding a sample with the issue on Tizen.

**Comment by joeyparrish** [comment] 2021-02-18 01:12
@mihirshroff-g, can you please try with the latest v3.0.8 release?  We added a workaround for platform issues on Tizen and Xbox that were triggered by SSAI and DRM.  It could be that this is fixed now, or that the same workaround would be effective on WebOS, too.

**Comment by mihirshroff-g** [comment] 2021-02-23 01:49
Thanks @Joey. Will give it a try and update you.

Thanks,
Mihir

Mihir Shroff |  Video Solutions Consultant, gTech |  mihirshroff@google.com
 |  202-657-1879 <(202)657-1879>

**Closed** 2021-03-03 19:06 UTC
Labels: needs triage, waiting on response
