### ISSUE TITLE
Ad blocker breaks demo page (known issue)

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#3388] opened 2021-05-05 17:31 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
didnt check

**Are you using the demo app or your own custom app?**
Demo App is broken - custom App

**If custom app, can you reproduce the issue using our demo app?**
Demo App is broken

**What browser and OS are you using?**
any :)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
irrelevant

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
irrelevant

**What did you do?**
- added the mux.js Lib (5.11.0) to the Page
- Added the Shaka 3.1.0 Lib to the Page
- started a HLS LiveStream on Chrome

**What did you expect to happen?**
HLS LiveStream should play.

**What actually happened?**
- Shaka immediately emits an Error
- I wanted to check on the Demo, but that Page is broken? (is it only me?)
- I wanted to check the Upgrade Guides for 3.1 if I missed something - but there is no Upgrade from 3.0 to 3.1 explained.

**Comment by boredom2** [comment] 2021-05-05 17:33
In case it is not related to muxjs - here is the Manifest: https://sdn-global-live-streaming-packager-cache.3qsdn.com/17612/17612_264_live.m3u8

**Comment by joeyparrish** [comment] 2021-05-05 17:37
> Demo App is broken

How so?  Can you be more specific?  It appears to be working for me.

I added your content URL to the custom content tab, and it's playing for me.  (Und auf Deutsch!  Diese Sendung is total verrückt.  I can't stop watching.  LOL)

https://shaka-player-demo.appspot.com/demo/#audiolang=de;textlang=de;uilang=de;asset=https://sdn-global-live-streaming-packager-cache.3qsdn.com/17612/17612_264_live.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by boredom2** [comment] 2021-05-05 17:44
I know, its a CRAZY Show...
First of all - I cant open the Demo Page anymore, since 3.1.0 was released.
I only see "Cannot read property 'reasonCode' of null" omn a red big Box.

So if its a Configuration Thing - its still strange. It works in 3.0.11, but crashes in 3.1.0 without any change.
But if its working on your Side, it must be something in the Config...

**Comment by joeyparrish** [comment] 2021-05-05 17:47
Please try these explicitly-versioned links:

 - http://v3-0-11-dot-shaka-player-demo.appspot.com/
 - http://v3-1-0-dot-shaka-player-demo.appspot.com/

If you are having an issue with caching (either locally in your browser or in some appspot intermediate server), then these explicit links should ensure you're getting consistent content from a single version.

So if those links both work, I would suggest you try going back to the general link (https://shaka-player-demo.appspot.com/demo/) and clear your browser cache.

Please let us know what happens!

**Comment by boredom2** [comment] 2021-05-05 17:49
I found it - if you have an active AdBlocker, the Page doesnt load anymore :)
Without an AdBlocker, its still working.

**Comment by boredom2** [comment] 2021-05-05 17:50
![Screenshot 2021-05-05 194945](https://user-images.githubusercontent.com/409857/117186394-106db380-addb-11eb-9b1b-13cfc7bd13ca.png)

Reason seems to be "AD_STARTED is undefined :)"

**Comment by joeyparrish** [comment] 2021-05-05 17:50
Ah, that's a known issue.  Some ad blockers appear to block individual source files with "ad" in the filename.  If you load the Shaka Player demo in debug or compiled mode, everything works because it loads Shaka as a bundle.  If you load the Shaka Player demo in uncompiled mode (the default), individual source files get blocked, which breaks everything.

**Comment by joeyparrish** [comment] 2021-05-05 17:52
We have this entry in [the FAQ](https://github.com/google/shaka-player/blob/master/docs/tutorials/faq.md) about it:

> **Q**: The Nightly Demo isn't loading for me!
>
> **A**: Are you looking at the uncompiled build with an AdBlocker enabled? We're rolling out ad support which is triggering some ad blockers to block requests for some of our source files. This only affects the uncompiled build. Switch to the compiled build (add "build=compiled" to the url) or temporarily disable your ad blocker to see the nightly uncompiled mode. Please note that if you want to test our ad logic, you might have to disable the ad blocker in compiled mode as well.

**Comment by joeyparrish** [comment] 2021-05-05 17:53
Anything else we can do to help, or should we close the issue?

**Comment by boredom2** [comment] 2021-05-05 17:54
You can close this Issue - this is 100% on our end - whatever this may be, as it works in 3.0.11 with the same Config. But yes, the Demo Page is working, so I gotta investigate.

**Comment by joeyparrish** [comment] 2021-05-05 18:01
Okay, sounds good.  Thanks for reaching out, and for the link to this insane German shopping show.  😁

**Comment by boredom2** [comment] 2021-05-05 18:01
Just to be sure - there is nothing needed to enable muxjs in 3.1.0? if window.muxjs is supported, it should work? Im just asking as we receive error 4032 in our custom Player with 3.1.0, which hints to "unsupported container"?

**Closed by joeyparrish** 2021-05-05 18:01 UTC
Labels: question

**Comment by joeyparrish** [comment] 2021-05-05 18:05
The only change with respect to mux.js is that we no longer need it for CEA in MP4.  It is still used for TS transmuxing, and the use of it for that has not changed.

**Comment by boredom2** [comment] 2021-05-05 18:07
Yes, I am aware of that Change - I just remembered, that there once was a Ticket for 3.1 ro refactor the Integration of mux.js. But afaik, that was archived and not implemented. Sorry for asking again :)

**Comment by joeyparrish** [comment] 2021-05-05 18:08
No worries!

**Comment by theodab** [comment] 2021-05-05 20:35
Actually, there is kind of a bug here. The demo is meant to show a custom error prompt telling you to turn off your adblocker in this case.

Looking into it, we have a regression from 95ba28b5afdb9ca98b6181e06613807acc40044e. We switched from using `document.createEvent` to make custom events, to just using the `CustomEvent` constructor directly. In the process, we accidentally broke the event that's fired when the UI fails to load; we didn't notice because we're used to not using adblockers when developing. Luckily, fixing this is a one-line change.
