### ISSUE TITLE
Failure to resume playback with Drag seek backwards (multiple seeks in quick succession)

### ISSUE THREAD

**Issue by david-hm-morgan** [google/shaka-player#3384] opened 2021-05-04 13:32 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://v3-0-7-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd;panel=HOME;build=uncompiled

Also on https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd;panel=HOME;build=uncompiled

**What version of Shaka Player are you using?**
v3.0.7-uncompiled
Also on v3.1.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

**What did you do?**

Seek backwards quickly in succession by dragging the seek bar controls to the left gradually.

**What did you expect to happen?**
Wherever I let go on the mouse button, it will resume playback from that point.

**What actually happened?**

Playback frozen (spinner sometimes)
Click on video toggles pause/resume button, but playback still frozen.
Have to seek again in order to recover.

My observations:
1. This seems significantly easier to recreate from v3.0.7 onwards.  However, I can occasionally get it on v3.0.6
2. I had originally added some notes to https://github.com/google/shaka-player/issues/3344 because I first saw this on Tizen, but now I've realised I can recreated this on Chrome too.  I've therefore separated it from Tizen specific concerns. 
That ticket contains some notes and screenshots from a Tizen environment where I saw that the stall detector is not able to recover from this condition.
3. I created a custom UI with a button to seek back 10 seconds and a double click on that can recreate this issue.

**Comment by joeyparrish** [comment] 2021-05-04 21:18
Do you have this issue with our UI control or the browser's native controls?  (Our demo app uses our UI controls by default.)

**Comment by david-hm-morgan** [comment] 2021-05-05 07:43
Hi @joeyparrish I get this with the demo app UI controls... but I can also recreate on Tizen 3 with native controls.
I've captured a video of the issue at https://drive.google.com/file/d/1akPaKSFECvDLi6EBVsQciY13aQ10oh5M/view

**Comment by david-hm-morgan** [comment] 2021-05-11 11:34
> I narrowed in on #3042 introduced in v3.0.7 which I can see in the circumstance where we have a negative overflow it concludes `buffer behind okay` and ends up not `remove`ing anything from the Media Source Engine's buffer.
> I am going to trial dealing with the negative overflow scenario.

I was mistaken, it is not as simple as that... the code change from v3.0.7 would not have changed behaviour of what I was seeing.

**Comment by Wayne-Morgan** [comment] 2021-06-02 10:49
Hi,

It's interesting that this problem occurs only on seeking back in time.

The attached image shows that while seeking backwards, multiple audio segment downloads are started and then cancelled. When we stop seeking, audio segments are loaded from segment number 68, but video from 71 (following on from the last completed video segment download. I hope this helps @joeyparrish .
![image](https://user-images.githubusercontent.com/26894243/120467201-d2db5680-c397-11eb-8535-500195f1647b.png)

**Comment by Wayne-Morgan** [comment] 2021-06-02 11:04
Here's another example showing the end of a much longer "drag" of the seek bar:
![image](https://user-images.githubusercontent.com/26894243/120469483-4ed69e00-c39a-11eb-8a03-a8e52aa34c22.png)

Both these examples were using 3.0.11.

We'd really appreciate any help you can provide, as we're looking forward to introducing the features of 3.1.x, but at the moment we're unable to deploy anything newer than 3.0.6.

**Comment by TheModMaker** [comment] 2021-06-03 21:45
I think this is a duplicate of #3089.  You could work around this by setting `streaming.jumpLargeGaps` to `true`.

**Comment by Wayne-Morgan** [comment] 2021-06-08 11:05
Hi @TheModMaker @joeyparrish,

This is not a duplicate of #3089.

When I see this issue, video stops at the point before the seek (in #3089 there is some video played after the seek). Setting jumpLargeGaps does not fix this problem.

Are you able to re-open this issue please?

Thanks.

**Comment by Wayne-Morgan** [comment] 2021-06-08 14:50
The problem seems to have been introduced in https://github.com/google/shaka-player/commit/ec210cbe1d33f7fd2ca99e6ff728bd7af1aa4abe
It's fairly easy to reproduce from this point forward, but in the previous commit, (https://github.com/google/shaka-player/commit/7944616657eb69e104abca5369294c993fc82307) I was unable to reproduce the problem at all.

**Comment by TheModMaker** [comment] 2021-06-08 16:58
When you see the problem, what is the value of `video.currentTime`, `player.getBufferedInfo()`, and `player.streamingEngine_.mediaStates_.get('video').segmentIterator`?  For the last one, you need to use the debug or uncompiled library and not be using `CastProxy`.  Or if you are using the hosted demo, you can get the player instance with `shakaDemoMain.controls_.localPlayer_`.

**Comment by Wayne-Morgan** [comment] 2021-06-09 07:28
Most of the time I've seen the problem occur with the video buffer, but in my current debug session it's the audio:

With 2 second segments:
* presentationTime: 328.039485
* video buffer: 326.125 - 338.124999
* video segmentIterator.nextPosition: 170
* audio buffer: 336 - 340.010666
* audio segmentIterator.nextPosition: 171

**Comment by Wayne-Morgan** [comment] 2021-06-09 08:16
On this occasion the problem was with the video:
![image](https://user-images.githubusercontent.com/26894243/121318499-3539d700-c903-11eb-8375-678041a4669c.png)

**Comment by Wayne-Morgan** [comment] 2021-06-10 16:19
Hi @joeyparrish @TheModMaker 

I believe I have a solution to this issue.  Please can you assign it to me, and I'll prepare a PR.

Thanks.

**Comment by joeyparrish** [comment] 2021-06-10 17:02
Done.  Thanks!

**Closed** 2021-06-21 22:57 UTC
Labels: bug, priority:P1
