### ISSUE TITLE
Subtitles sometimes disappear in seek actions

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2962] opened 2020-11-04 07:30 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.5

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 86, macOS 10.15.7

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

I will send the stream privately.

**What did you do?**

Load the stream
Enable the spanish subtitle.
Do some seeks on the stream

**What did you expect to happen?**
The spanish subtitle is always shown

**What actually happened?**

The spanish subtitle sometimes disappear

Video of the demo page with the error;
[Subtitles error.zip](https://github.com/google/shaka-player/files/5486131/Subtitles.error.zip)

**Comment by avelad** [comment] 2020-12-22 08:10
With the last changes in master I am no longer able to reproduce the error.

**Comment by joeyparrish** [comment] 2020-12-22 16:57
Excellent!  We'll close this, then, as a duplicate of b/168253400 (an issue from another team at Google on an internal bug tracker, unfortunately).

**Closed** 2020-12-22 16:57 UTC
Labels: duplicate
