### ISSUE TITLE
How to create a Response?

### ISSUE THREAD

**Issue by Fenny** [google/shaka-player#2213] opened 2019-10-23 18:48 UTC
After some hours of reading documentations, I managed to intercept requests like @joeyparrish suggest here [Issue 2205](https://github.com/google/shaka-player/issues/2205#issuecomment-545442163) to create my own octet/stream pulling buffers from a readablestream (_startPiece, _endpiece)

```html
<video src="" autoplay id="video"></video>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.5/shaka-player.compiled.js"></script>
```
```javascript
// Video element
var video     = document.getElementById('video');
// Shaka player
var player    = new shaka.Player(video)
// Bind error handling for debugging
player.addEventListener('error', ErrHandler);
// Error handling function
function ErrHandler(err) {
  console.log(err)
}
// Tunnel function
function Tunnel(uri, request, requestType, progressUpdated) {
  console.log(request)
  // This part is for my buffered stream
  if (uri == 'please-send-range-requests') {
    // ***~~ Magic ~~***
    // How should I return a custom response?
    // ***~~ Magic ~~***
  }
  // without "HttpFetchPlugin.parse()" function I can ignore and forward other requests 
  return shaka.net.HttpFetchPlugin(uri, request, requestType, progressUpdated);
}
// Polyfill because why not
shaka.polyfill.installAll();
// Register custom tunnel function to intercept requests
shaka.net.NetworkingEngine.registerScheme('http', Tunnel);
shaka.net.NetworkingEngine.registerScheme('https', Tunnel);
// Set a custom url to catch with the Tunnel function
player.load('/please-send-range-requests').catch(ErrHandler);
```
In the beginning I had the following error code:
```error
TypeError: shaka.net.HttpFetchPlugin.parse is not a function
```

But I fixed this by removing the ".parse()" method since it kept throwing errors on v2.5.5
```javascript
return shaka.net.HttpFetchPlugin(uri, request, requestType, progressUpdated);
```

The next step is to actually respond to my custom url requests.

1. Could anyone please show me how I can setup a basic response with a body, headers and statuscode ( to support range response 206 )

```javascript
// Service Worker response example
var blob = new Blob([getBuffer(startByte)], { type: 'octet/stream' });
return new Response(blob, {
  status: 206,
  headers: new Headers({
    'Content-Range': `bytes ${startByte}-${size - 1}/${size}`,
    'Content-Length': size - startByte
  })
});
```

2. Do I need to trick shaka player that it should send range requests automatically, if so how?

**Comment by TheModMaker** [comment] 2019-10-23 20:18
The Response created as part of the network plugins is a custom type, not the web standard one.  It is just a "plain" object that contains the [expected fields](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Response).  Only `data` is required, other fields can be missing.  For example:

```js
return {
  uri: uri,
  data: new Uint8Array(buffer),
  headers: {'Content-Range': '', 'Content-Length': ''},
};
```

A range request is just like a normal request that has a `Range` header.  So if you want to create a range request, just add that header.

**Comment by joeyparrish** [comment] 2019-10-23 20:20
> In the beginning I had the following error code:
> 
> ```error
> TypeError: shaka.net.HttpFetchPlugin.parse is not a function
> ```
> 
> But I fixed this by removing the ".parse()" method since it kept throwing errors on v2.5.5
> ```javascript
> return shaka.net.HttpFetchPlugin(uri, request, requestType, progressUpdated);
> ```

You didn't fix it, then.  :-)  What you did was replace the call to the static parse method (which is correct) with the constructor (which does nothing on a class with only static methods).  So it doesn't crash, but neither does it do anything when called.

The problem is that we have a bug in the latest release.  The method is not exported from the compiled build as it should be.  We should have that fixed soon.  You'll need to either build from source or wait for another release to see that fix.  When the fix is merged, you will see the commit referenced here in the issue history.  Until then, you could delegate to the other HTTP plugin, which is correctly exported: `shaka.net.HttpXHRPlugin.parse`.

> Could anyone please show me how I can setup a basic response with a body, headers and statuscode ( to support range response 206 )

It's just an anonymous object with the right fields in it.  Please follow the format in the docs I referenced before: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Response

```js
async function myPlugin(uri, request, requestType, progressUpdated) {
  // ... whatever you need to do to get the blob
  const data = await blob.arrayBuffer();
  const response = {
    uri: uri,
    originalUri: uri,
    data: data,
    headers: {
      // Response headers go here
    },
  };
  // ... the rest of your plugin
}
```

> Do I need to trick shaka player that it should send range requests automatically, if so how?

I'm not sure what you mean by that.  Shaka Player will send range requests if the manifest provides byte ranges for a segment.  This is typically true of DASH VOD content.

You can read the ranges in the range request by examining the request object in the scheme plugin.  There is a `headers` field there, and a range request is just a request with a `range` header..  See the docs for the complete format of the Request object: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Request

**Comment by Fenny** [comment] 2019-10-23 22:10
`I'm not sure what you mean by that. Shaka Player will send range requests if the manifest provides byte ranges for a segment. This is typically true of DASH VOD content.`

What a bummer, I don't think this video is DASH VOD content.

I'm using [WebTorrent](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md) to stream this video from other peers, this library creates the  [video.createReadStream()](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#user-content-stream--filecreatereadstreamopts).

This is the actual hosted file [https://webtorrent.io/torrents/Sintel/Sintel.mp4](https://webtorrent.io/torrents/Sintel/Sintel.mp4)

Here is my current code, I hope it makes sense.
But shaka only sends one HEAD request, not sure how I should respond to trigger the range requests.

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8">
<title></title>
</head>
<body>
<video src="" autoplay id="video"></video>
<script type="text/javascript" src="/shaka-player.compiled.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webtorrent/0.107.16/webtorrent.min.js"></script>
<script type="text/javascript">
// Max chunk size ( this if for later chromecast project )
var segment_size  = 64 * 1000;
// Create torrent client
var client = new WebTorrent()
// Set global scope for the file we are downloading
var file = null;
// Video element
var video  = document.getElementById('video');
// Shaka player
var player = new shaka.Player(video)
// Bind error handling for debugging
player.addEventListener('error', ErrHandler);
// Tunnel function
async function Tunnel(uri, request, requestType, progressUpdated) {
  // Pars uri
  var url = new URL(uri)
  // Not our url, you can pass
  if (!url.host == 'custom-url') {
    return shaka.net.HttpFetchPlugin.parse(uri, request, requestType, progressUpdated);
  }
  // I store the file size in a query parameter, dont mind this
  var fileSize  = parseInt(new URLSearchParams(url.search).get('size'));
  // Create a start byte
  var startByte = 0
  // Check for range header
  if (request.headers['range']) {
    startByte = parseInt(request.headers['range'].match(/bytes=([0-9]*)-/)[1]);
  }
  var buffer = await readFileStream(startByte)
  var response = {
    uri: uri,
    originalUri: uri,
    data: buffer,
    headers: {
      'Accept-Ranges': 'Bytes',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Expose-Headers': 'origin, range',
      'Cache-Control': 'public, max-age=0',
      'Content-Type': 'video/mp4',
      'Content-Range': `bytes ${startByte}-${fileSize - 1}/${startByte}`,
      'Content-Length': fileSize - startByte
    },
  };
  return response
}
// Polyfill because why not
shaka.polyfill.installAll();
// Register custom tunnel function to intercept requests
shaka.net.NetworkingEngine.registerScheme('http', Tunnel);
shaka.net.NetworkingEngine.registerScheme('https', Tunnel);
// Start downloading a torrent
client.add('magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent', {
  announce: [
    'wss://tracker.openwebtorrent.com/',
    'wss://tracker.fastcast.nz/'
  ]
}, (torrent) => {
  // If the torrent is ready to be streamed, find the mp4 file
  media = torrent.files.find(function (file) {
    return file.name.endsWith('.mp4')
  })
  // Lets go
  player.load('/custom-url?size=' + media.length).catch(ErrHandler);
  // To video stream using video-stream, but we dont need this for chromecast project
  // media.appendTo('body')
})
// Get the Uint8Array
function readFileStream(start) {
  return new Promise((res, reject) => {
    var stream = media.createReadStream({
      start: start,
      end: start + segment_size - 1
    });
    stream.once('data', data => {
      res(data.slice(0, segment_size))
    });
    stream.once('error', reject);
  })
}
// Error handling function
function ErrHandler(err) {
  console.log(err)
}
</script>
</body>
</html>

```

**Comment by theodab** [comment] 2019-10-23 23:18
If what you're loading is just an mp4 file, Shaka Player isn't making range requests because it isn't making requests at all. For raw media files like that without manifests, Shaka Player just hands things over to the browser, and the browser is the thing doing all of the requests.

```js
if (!url.host == 'custom-url') {
```
I don't think this line is doing what you think it does. You're comparing `'custom-url'` to `!url.host`, which (as the logical negation of `url.host`) is `true` if url.host is falsy and `false` if url.host is truthy. I think you meant to do `url.host != 'custom-url'` instead.

**Comment by Fenny** [comment] 2019-10-24 01:03
@theodab Thanks for the clarification!

I learned a lot the last couple of days regarding video on the web, and I think shaka-player is not the way to go to eventually cast local content without any extensions.

It is a raw MP4 file with a specific length where you can request the desired chunks by start/end bytes.  If you can create a dynamic synthetic manifest that would do the job, I might continue this quest.

Otherwise I just wait a couple of months until google fixes [Issue 17509737](https://support.google.com/chromecast/thread/17509737?hl=en)

Thanks for all the help though!

**Comment by mstattma** [comment] 2019-10-24 07:11
Maybe this helps: https://github.com/gpac/mp4box.js 

It enables using XHR for streaming plain mp4s into MSE (with some caveats). It should be possible to replace XHR with something else like WebRTC.

**Comment by theodab** [comment] 2019-10-24 17:04
Yeah, it does sound like Shaka Player is probably the incorrect tool for what you are doing, unless you are really interested in our UI layer or something. If you don't have manifests to interpret, and don't have any need for ABR logic, and so on and so forth, we don't have much to offer you.
You could possibly use MediaSource directly; like, say, see [this tutorial](https://developers.google.com/web/fundamentals/media/mse/basics). It's not too much work to get something that just loads raw media buffer segments into a video element.
Either way, good luck getting your project working!

**Closed by theodab** 2019-10-24 17:04 UTC
Labels: question
