### ISSUE TITLE
Firefox bug - MediaKeySystemAccess.createMediaKeys returns a promise that is never resolved

### ISSUE THREAD

**Issue by karlovich** [google/shaka-player#452] opened 2016-07-22 14:41 UTC
Hi shaka player community,

We use shaka player & try to support Firefox 47+, but unfortunately seems FF is not so stable for DASH Widevine streaming.

The problem is in EME API with MediaKeySystemAccess.createMediaKeys.

We even raised a bug at bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1286685

So, the next script (https://bug1286685.bmoattachments.org/attachment.cgi?id=8770732) returns three states on different machines & platforms with FF 47+:
1. There is no result on some windows machines. 
   Promise  returned by "MediaKeySystemAccess.createMediaKeys" don't resolved at all.
2. Win10. Firefox Nightly (50.0a1 2016-07-13) returns:
   Failed to created cdm; InvalidStateError: GetGMPDecryptor failed to return a CDM
3. FF on OSX & on some windows machines returns success result:
   Created cdm.

Full script to test Widevine CDM:

```
function e(id) {
  return document.getElementById(id);
}

function log(msg) {
  var log_pane = e('log');
  log_pane.appendChild(document.createTextNode(msg));
  log_pane.appendChild(document.createElement("br"));
}

var configs = [
  {
    audioCapabilities: [
      {
        contentType: 'audio/mp4; codecs="mp4a.40.2"',
        robustness: '',
      },
      {
        contentType: 'audio/mp4; codecs="mp4a.40.2"',
        robustness: '',
      }
    ],
    distinctiveIdentifier: 'optional',
    initDataTypes: undefined,
    label : "com.widevine.alpha",
    persistentState: 'optional',
    sessionTypes: ['temporary'],
    videoCapabilities: [
      {
        contentType: 'video/mp4; codecs="avc1.42E01F"',
        robustness: '',
      },
      {
        contentType: 'video/mp4; codecs="avc1.42E01E"',
        robustness: '',
      },
      {
        contentType: 'video/mp4; codecs="avc1.42E015"',
        robustness: '',
      }
    ]
  }
];

navigator.requestMediaKeySystemAccess('com.widevine.alpha', configs).then(
  function (access) {
    return access.createMediaKeys();
  }).then(
    function (mediaKeys) {
      log("Created cdm.");
    },
    function (ex) {
      log("Failed to created cdm; " + ex);
    }
  );
```

So, the question is anybody experienced with this issue & how to resolve it?

**Comment by olivbraun** [comment] 2016-07-22 15:24
We have the same issue, and as for now the only workaround we found was to use Flash on Firefox...

**Comment by joeyparrish** [comment] 2016-07-25 18:39
Marked as "external bug".  We'll track [Firefox bug 1286685](https://bugzilla.mozilla.org/show_bug.cgi?id=1286685) for updates.

**Comment by cpearce** [comment] 2016-07-25 22:04
Thanks for reporting this bug @karlovich. I work on EME in Firefox. I've asked some questions in the Firefox bug to help me debug this.

We're committed to fixing this.

@olivbraun Do you mostly see this the first time you try loading a page in Firefox, or consistently? When you see this, if you open Hamburger Menu > Add-on > Plugins, does the "Widevine Content Decryption Module" entry show that the Widevine plugin is installed? 

I'm wondering if the CDM hasn't had enough time to download yet.

**Comment by olivbraun** [comment] 2016-07-26 08:10
I tested both FF 47.0.1 and Nightly, and noticed that Widevine CDM is reinstalled whenever I switch from one version to the other.
When I start the browser and immediately go to the Plugins menu, it says that Widevine CDM will be installed shortly, which is the true after 30s to 1min.

If I wait until the plugin is installed and then run the script above, it works fine and tells me "Created cdm". If I don't wait and run the script while the plugin is not yet installed, I get a message saying that Firefox is currently installing a required component, but then when I refresh the page a few seconds later it works fine.

I'm not able to reproduce the problem I previously had (the script returning a blank page). I wonder if the fact that the CDM was reinstalled when I switched between 47 and Nightly versions helped.

**Comment by cpearce** [comment] 2016-07-26 09:22
@olivbraun:
> I tested both FF 47.0.1 and Nightly, and noticed that Widevine CDM is reinstalled whenever I switch from one version to the other.

I'd guess you have a 64bit Firefox Nightly, and a 32bit Firefox 47.0.1? We reinstall when the arch changes (32 vs 64 bit).

> If I wait until the plugin is installed and then run the script above, it works fine and tells me "Created cdm". If I don't wait and run the script while the plugin is not yet installed, I get a message saying that Firefox is currently installing a required component, but then when I refresh the page a few seconds later it works fine.

I'm also guessing your Nightly has multi-process Firefox enabled. :)

This sounds like [bug 1288976](https://bugzilla.mozilla.org/show_bug.cgi?id=1288976) which should be fixed in tomorrow's Nightly build onwards. Try updating your Nightly tomorrow, and re-testing. You can update your Nightly in Hamburger menu > ? > About Firefox.

**Comment by karlovich** [comment] 2016-07-28 10:02
@cpearce Thanks for the help,

please find answers at [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1286685).

**Comment by cpearce** [comment] 2016-10-03 21:29
@olivbraun do you still have issues with an up to date release version of Firefox (version 49). A lot of the issues here should be fixed now.

The issues @karlovich was having are much harder to solve. We're still looking into those.

**Comment by joeyparrish** [comment] 2016-11-14 19:25
Closing now that Firefox 49 is out.

**Closed by joeyparrish** 2016-11-14 19:25 UTC
Labels: bug, external
