### ISSUE TITLE
Chrome bug - after video buffer is emptied, audio keeps playing

### ISSUE THREAD

**Issue by mnylen** [google/shaka-player#438] opened 2016-07-06 16:20 UTC
Platform: Windows, Android, (maybe others)
Browser: Chrome (51.0.2704.103 on Windows)

To reproduce, go to https://shaka-player-demo.appspot.com/demo/ on desktop Chrome and choose Sintel 4k. Let it buffer some of the video, then switch Chrome's network throttling on to GRPS setting and wait for the buffer to empty.

Expected: video and audio stop at the same time when the buffer is emptied
Actual: video stops, but audio keeps going for a second or two

The issue is not as severe on desktop browsers (though not ideal), but on Android Galaxy A5 and S7 Edge, for example, the audio just keeps on going without ever stopping.

I investigated the issue a bit on S7 and it seems that a buffering event is sent only after a few seconds has passed from the video freezing. However, even after the buffering event has fired, the audio keeps playing.

As a workaround, I tried calling `video.pause()` from the buffering event handler and this finally stops the audio. But it's not ideal, as the buffering event comes late.

Is there any way to stop the playback at the exact moment either the video or audio buffer is emptied?

**Comment by joeyparrish** [comment] 2016-07-06 18:24
The behavior you're describing is in the browser, not in Shaka.  You could [file a bug against Chrome](https://bugs.chromium.org/p/chromium/issues/entry) and add a link to that bug here, if you like, but there's nothing Shaka can do to control this detail of the browser's media pipeline.

As I understand it, Chrome's media pipeline on Android has historically been implemented differently from the pipeline on desktops, so this may explain why audio keeps going on those platforms.  That, at least, sounds like a bug to me.

Not stopping audio and video at exactly the same time may be working as intended for Chrome, but I am only speculating.  Someone from Chrome's media team should be able to tell you more definitively what the intent is.

**Comment by mnylen** [comment] 2016-07-06 18:29
Having spent a few moments going through the codebase, it looks like the delay between buffer running out and buffering event being fired is caused by the delays given to `shaka.media.StreamingEngine.prototype.scheduleUpdate_`

Doesn't look like anything is actively trying to stop video or audio from playing if either one runs out of buffered content. But probably browser itself stops the 

Hmm-m... One ugly hack I could implement on my end would be to just have a very short interval running in the background polling the buffering status and pause the video when it detects there isn't anything buffered. Too bad there doesn't seem to be an exposed api on shaka player that would give info about the buffer status. The `buffered` information given by the video element has proved to not be very trustworthy always... at least not on all platforms, can't remember if it was Android or iOS having problems, or both.

**Comment by mnylen** [comment] 2016-07-06 18:41
https://bugs.chromium.org/p/chromium/issues/detail?id=593271 this might be the Chrome issue.

**Comment by joeyparrish** [comment] 2016-07-06 18:44
Exactly.  The browser has its own logic for when the pipeline stalls and playback is held up waiting for data.  Our 'buffering' event is fired when we first notice that we have too little data, which isn't tied to when the browser stalls.  Trying to detect browser pipeline stalls was difficult to do consistently across browsers.

`video.buffered` as far as I know is the intersection of the `buffered` ranges of each `SourceBuffer`.  But I've seen browser pipelines stall when `currentTime` is less than `buffered.end(0)`, and I've seen stalls when `currentTime` is actually greater than `buffered.end(0)`.  So `buffered` is (counter-intuitively) not the best way to detect pipeline stalls.

**Comment by mnylen** [comment] 2016-07-06 19:10
True, it's not perfect... But might be enough to get around the bigger problem of audio not stopping at all on Android. 

Could Shaka's internal state give better estimate when buffer has run out? Doesn't Shaka know which segments it has downloaded and which time ranges those segments map to?

**Comment by joeyparrish** [comment] 2016-07-06 19:26
As long as tracks are not changing, Shaka (in StreamingEngine) tracks the number of the segment it most recently downloaded.  It does not know every segment it has ever downloaded.

StreamingEngine also has access to the buffered ranges of each SourceBuffer (through MediaSourceEngine), so it can know how much audio is buffered separate from how much video is buffered.

**Comment by mnylen** [comment] 2016-07-07 07:42
Just dropping this here in case someone else stumbles upon this and tries to hack around the problem. Copying this to the demo page's console seems to, at least on desktop, solve the issue. Have to wait until Monday to check the Android situation when I'm back at office with an actual device to test with.

Of course, this probably won't work if you seek the video.. Our use case is simpler as we just play video from start to finish without allowing user to seek.

```
var video = document.querySelector("video");
var pausedByBuffering = false;

setInterval(function() {
  if (video.buffered.length > 0) {
    var buffered = video.buffered.end(video.buffered.length - 1) - video.currentTime;
    var remainingTime = video.duration - video.currentTime;

    if (!video.paused && buffered < 0.5) {
      console.log("video buffer ran out");
      pausedByBuffering = true;
      video.pause();
    } else if (pausedByBuffering && buffered >= Math.min(remainingTime, 5)) {
      console.log("video has buffered enough to continue...", Math.min(remainingTime, 5));
      pausedByBuffering = false;
      video.play();
    }
  }
}, 17); // ~60fps
```

**Comment by patrickkunka** [comment] 2016-07-07 13:14
Thanks so much for that snippet @mnylen - Have been struggling to find a solution to this exact same issue.

**Comment by joeyparrish** [comment] 2016-11-15 00:30
The [Chrome bug report](http://crbug.com/593271) attached to this issue states that the situation has been improved significantly in Chrome 51.  Although that issue is still open, I believe it's fair to close this one now.  Please let us know if there's anything else we can do here to assist, and please feel free to follow up with Chrome if you feel there is additional work needed there.

**Closed by joeyparrish** 2016-11-15 00:30 UTC
Labels: bug, external
