### ISSUE TITLE
Question: Which errors will terminate playback

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#598] opened 2016-11-18 20:03 UTC
Is there a way to distinguish which errors are critical and which will allow for playback to continue? It would be useful to be able to distinguish between these cases.

**Comment by joeyparrish** [comment] 2016-11-29 20:58
Closing as a duplicate of #564.  Thanks, Sanborn, for pointing that out.

**Closed by joeyparrish** 2016-11-29 20:58 UTC
Labels: duplicate
