### ISSUE TITLE
Error 4012 and then 5005 on Dash manifest

### ISSUE THREAD

**Issue by lelikg** [google/shaka-player#940] opened 2017-07-23 19:33 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes

**What version of Shaka Player are you using**:
latest master

**Can you reproduce the issue with our latest release version**:
yes

**Can you reproduce the issue with the latest code from `master`**:
yes

**Are you using the demo app or your own custom app**:
custom app

**If custom app, can you reproduce the issue using our demo app**:
haven't tried

**What browser and OS are you using**:
chrome macos

**What are the manifest and license server URIs**:
http://vod.panda-os.com/1718/dash/sport1-stream1-1.mpd

*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
tried to play this url in shaka player

**What did you expect to happen?**
the video would play

**What actually happened?**
got error 4012 and then error 5005

**Comment by joeyparrish** [comment] 2017-07-23 20:08
In the MPD you referenced, the video track's bandwidth is 0, and the audio track's bandwidth is 125000.  The content is broken because 0 is not a valid value.  See detailed analysis in https://github.com/google/shaka-player/issues/938#issuecomment-317278180 if you are interested.

That said, it plays in v2.0.9, and in #938 I agreed implement a work-around.  Since your content only has one audio+video combination, we should still be able to play it.

I'm going to mark this as a duplicate of #938, and will close them both with the same work-around.  Thanks!

**Comment by lelikg** [comment] 2017-07-23 20:30
@joeyparrish thanks for the quick reply.
So according to #938 the manifest should play audio bandwidth is 125000, however it never plays for me.
It does play in bitdash and dashif and akamai players.
I am using v2.1.5 because of an error in PlayReady that 2.1.5 fixes.
Can you please elaborate how I can implement the workaround?

**Comment by joeyparrish** [comment] 2017-07-23 22:06
@lelikg, no, I'm sorry for the confusion.  According to #938, the manifest is broken because the video bandwidth is 0, which is invalid.  A bandwidth of 0 produces nonsensical values according to formulas in the spec.

I will attempt to make a change in Shaka Player that will allow such content to play in spite of it being out of spec.  I will use the manifest link you provided to validate that change.

What encoder/packager are you using to produce that stream?  I'd like to report the bandwidth="0" issue to them, so that they have an opportunity to fix it on their end, as well.

**Comment by lelikg** [comment] 2017-07-24 07:15
@joeyparrish I'm using nginx rtmp module https://github.com/arut/nginx-rtmp-module

**Comment by joeyparrish** [comment] 2017-07-24 09:13
I filed arut/nginx-rtmp-module#1079.  Thanks!

**Comment by joeyparrish** [comment] 2017-07-24 09:15
@lelikg, I am now getting a 404 error on your manifest.  Can you please make it available to me again for testing purposes?  I want to make sure that my workaround is correct for your content.

If you don't want to leave it up publicly, you can send a new URI to <shaka-player-issues@google.com> instead.  Thanks!

**Comment by joeyparrish** [comment] 2017-07-25 08:24
I saw that the manifest was back up, and I was able to verify that my work-around works with your content.  Thanks!

**Closed** 2017-07-25 08:26 UTC
Labels: bad content, duplicate, enhancement

**Comment by lelikg** [comment] 2017-07-25 08:31
@joeyparrish thanks for all your help
I used lua to modify the bandwidth="0" to bandwidth="600000" as a temporary workaround, and it works.

**Comment by joeyparrish** [comment] 2017-07-25 08:39
The fix has been pushed to `master`, so you can try the player workaround now as well.

**Comment by lelikg** [comment] 2017-07-25 08:40
@joeyparrish will test and let you know! Thanks!

**Comment by joeyparrish** [comment] 2017-07-25 13:08
The work-around has been cherry-picked for v2.1.6.
