### ISSUE TITLE
Fairplay broken in v3.2 (dup)

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3678] opened 2021-10-04 15:57 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
I am trying to play the content on Mac Safari (HLS Fairplay) but it doesn't play the video.

I have perfectly configured the DRM license URL and apply Fairplay cert in the player configuration but it still doesn't work.

First approach: I manually fetched the server cert and converted it in Uint8Array and passed it in `drm.advanced.com\\.apple\\.fps\\.1_0.serverCertificate` but it doesn't play the content

The second approach I pass my cert URL directly to `serverCertificateUri` in drm.advanced but it still doesn't work correctly.

Can you please suggest to me a better approach for playing FairPlay content as these both are confusing?

**Comment by avelad** [comment] 2021-10-04 16:29
Duplicate of https://github.com/google/shaka-player/issues/3530

**Closed as completed** 2021-10-08 18:38 UTC
Labels: type: bug, status: duplicate, status: archived
