### ISSUE TITLE
SHAKA and Offline Events

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#937] opened 2017-07-20 23:20 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

yes

**What version of Shaka Player are you using**:

2.1.5

**Can you reproduce the issue with our latest release version**:

yes

**Can you reproduce the issue with the latest code from `master`**:

yes

**Are you using the demo app or your own custom app**:

both

**If custom app, can you reproduce the issue using our demo app**:

yes

**What browser and OS are you using**:

windows, android, macOS

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

any

**What did you do?**

see below.

**What did you expect to happen?**

see below.

**What actually happened?**

We added some basic "offline" Behaviour into our Players - at least to that Point, that it shouldnt just crash, when going offline, but instead showing a Message, pause Contents and wait until Network comes back.
This works actually quite nice - but sadly, SHAKA does not like this :)
When Network turns off, we try with pause() to pause the Player - mostly, an Error from SHAKA is already triggered, but we were able to ignore this.
Nevertheless, problematic is the Return of the Internet. Afer being sure, Internet is back, we seek -5 Seconds and start Playback again (that works also), but once the Parts are reached, that were previously not being available because of being Offline (I think), SHAKA stops and nothing happens.
So, summing it up - is there any way to purge the internal Cache or force SHAKA to reload Segments or make SHAKA not cache/download/try anything when !navigator.onLine ?

Thanks a lot!
Christoph

**Comment by joeyparrish** [comment] 2017-07-25 08:56
Hi Christoph,

First, let me explain what Shaka is doing.

Shaka continues to buffer up to the `bufferingGoal` setting even when paused.  It doesn't check `navigator.onLine`, either.  We also don't cache anything, so if we fail to fetch a segment, there is no reason that failure should "stick".  We should be able to fetch those same segments once the network is back.

We don't check `navigator.onLine` in `StreamingEngine` because the same streaming logic is used for content that has been stored in a database for offline playback.  If we didn't stream during `navigator.onLine == false`, offline playback from the database would not be possible.

I can reproduce your issue with VOD content, but not with live:

https://shaka-player-demo.appspot.com/demo/#asset=//vm2.dashif.org/livesim/utc_head/testpic_2s/Manifest.mpd;lang=en-US

It looks like this was introduced in PR #842, which was meant to address issues #830 and #762.  In #830, the complaint was that we kept retrying on VOD even after a failure.  So it sounds like you want exactly the opposite behavior.

#762 was reopened with a discussion about adding a [method to ask the player to retry streaming after a failure](https://github.com/google/shaka-player/issues/762#issuecomment-311593973), but I'm not sure if that's the best way to go or not.

Let me consider the best way to allow each application to choose the desired behavior, and I'll let you know what we come up with.  Thanks!

**Comment by boredom2** [comment] 2017-07-25 13:42
Thanks for these Insights - and yes, I understand, that there are potentially completely different desired Behaviours, no doubt about that. Ill stay tuned :)

**Comment by joeyparrish** [comment] 2017-08-09 19:45
@boredom2, I'm closing this issue and merging it into #960, in which I've proposed a more general solution.  Please provide feedback there.  Thanks!

**Closed by joeyparrish** 2017-08-09 19:45 UTC
Labels: needs triage
