### ISSUE TITLE
Bitmap Subtitle is displaying middle of the screen 

### ISSUE THREAD

**Issue by kumarashu123** [google/shaka-player#2477] opened 2020-03-31 03:06 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes, able to reproduce issue in demo app

**What browser and OS are you using?**
Chrome and Mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

Play a content which has bitmap based subtitle

**What did you expect to happen?**
Subtile should not display middle of the screen

**What actually happened?**

Subtile is displaying middle of the screen. After investigation I found 
Below is sample for subtitle segment
`<layout>
	<region tts:extent="100.00% 20.67%" tts:origin="0% 78%" xml:id="region0"/>
	<region tts:extent="100.00% 6.76%" tts:origin="0% 86%" xml:id="region1"/>
</layout>`

In /lib/text/ttml_text_parser.js

parseCueRegion_ function
percentage = TtmlTextParser.percentValues_.exec(extent);

shaka.text.TtmlTextParser.percentValues_ =
    /^(\d{1,2}(?:\.\d+)?|100)% (\d{1,2}(?:\.\d+)?|100)%$/;

**percentValues_ regex there is no support for decimal point for 100**

![image](https://user-images.githubusercontent.com/10974291/77982720-9db61d00-732a-11ea-8de0-eda747530276.png)

**Comment by joeyparrish** [comment] 2020-03-31 17:46
> What are the manifest and license server URIs?

You skipped this question.  Without a sample, we will be unable to reproduce your issue or work on a fix.

**Comment by kumarashu123** [comment] 2020-04-02 11:18
@joeyparrish Thanks for quick reply.
I will share manifest url soon.

**Comment by kumarashu123** [comment] 2020-04-03 04:30
@joeyparrish Do you have an email where i can send the manifest url "

**Comment by michellezhuogg** [comment] 2020-04-03 04:35
Hello @kumarashu123 , you can send it to shaka-player-issues@google.com .

**Comment by kumarashu123** [comment] 2020-04-07 10:45
Hi @joeyparrish,
I will be mailing you the manifest URL.
  
Summarizing the issue,

This is the <layout> we are getting in the manifest:
	
<layout> <region tts:extent="**100.00%** 20.67%" tts:origin="0% 78%" xml:id="region0"/> <region tts:extent="**100.00%** 6.76%" tts:origin="0% 86%" xml:id="region1"/> </layout>

And in ttml_text_parser.js, we parse this <layout> with the following regex:
shaka.text.TtmlTextParser.percentValues_ = /^(\d{1,2}(?:.\d+)?|**100**)% (\d{1,2}(?:.\d+)?|**100**)%$/;

As you can see above, **this regex works fine for "100%", but not for "100.00%"**, as given in the <layout> example above.

Proposed fix: 
/^(\d{1,2}(?:.\d+)?|**100(?:.0+)?**)% (\d{1,2}(?:.\d+)?|**100(?:.0+)?**)%$/

**Comment by joeyparrish** [comment] 2020-04-07 15:43
@kumarashu123, since you already have a fix, I've gone ahead and marked this as a bug and added the "help wanted" label.  Please send a PR with your fix.  Thanks so much!

**Comment by kumarashu123** [comment] 2020-04-08 13:15
@joeyparrish I have sent the manifest URL to shaka-player-issues@google.com.

**Closed** 2020-04-13 16:43 UTC
Labels: bug, help wanted
