### ISSUE TITLE
ignoreTextStreamFailures not respected on some situations, at least for HLS

### ISSUE THREAD

**Issue by CHaNGeTe** [google/shaka-player#2229] opened 2019-11-07 16:18 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.5/2.5.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome on MacOS Mojave

**What are the manifest and license server URIs?**
The stream has expiration token, so it is difficult to share.
I can share it on 1:1 conversation.

The VTT files are the ones returning 502, bad gateway

**What did you do?**
Load the stream, with VTT files on the manifest, but that are returning 502 (Bad gateway) on the server.
Player config `streaming.ignoreTextStreamFailures = true`
and `manifest.hls.ignoreTextStreamFailures = true`

**What did you expect to happen?**
Ignore the HTTP errors and proceed with the playback.

**What actually happened?**
The stream stopped loading, with critical error, ignoring the `manifest.hls.ignoreTextStreamFailures` settings
![Screenshot 2019-11-07 at 17 07 57](https://user-images.githubusercontent.com/1237997/68406285-d984f600-0181-11ea-90e3-47164cef0eee.png)

**Comment by ismena** [comment] 2019-11-07 18:04
Hi @CHaNGeTe 
Please send the manifest url to shaka-player-issues@google.com, we'll take a look!

(I'm taking the manifest text out of the issue for readability since we need the stream to debug anyway. I have it in my inbox if we end up needing it.)

**Comment by CHaNGeTe** [comment] 2019-11-08 10:11
Thanks @ismena, sended an email to shaka-player-issues@google.com

**Comment by CHaNGeTe** [comment] 2019-11-08 11:27
I don't know if it is related, but I have a suspicion:
I think if subtitle tracks are placed on top of the manifest, it is trying to `getStartTime_` on them (the vtt files).
And as the request is failing, it is elevating the error as CRITICAL.

**Comment by ismena** [comment] 2019-11-08 18:47
Thanks for the email!
Is there any way at all you could make it a bit easier for us to get the manifest? Whitelist our IPs or zip the streams and send them to us?

In the meantime, let me try to hack one of my local streams to get text failures and test your idea about `getStartTime_()` :)

**Comment by ismena** [comment] 2019-11-08 19:08
Okay, I can get a repro on the demo page, but not in the [current master](https://nightly-dot-shaka-player-demo.appspot.com/demo/). I think you might be right about the `getStartTime`(which is pretty awesome, btw, we don't often see this level of awareness when people file bugs :)), in which case it is a duplicate of #2065.

@TheModMaker was this not cheery-picked into a releases? How come it's not working on the main appspot demo?

**Comment by joeyparrish** [comment] 2019-11-08 19:21
We recently optimized the HLS parser such that we don't need to get the start time of text streams any more.  That change was deemed too risky to cherry-pick, since it wasn't strictly a bug fix, and it introduced a big behavior change in the HLS parser.

**Comment by joeyparrish** [comment] 2019-11-08 19:22
But the change will be in v2.6.  I suggest we mark this as a duplicate of #1563.

**Comment by ismena** [comment] 2019-11-08 19:27
@joeyparrish Sounds great. Let me wait a bit for @CHaNGeTe to confirm that everything works on the nightly.

**Comment by CHaNGeTe** [comment] 2019-11-08 21:02
Seems it is working for me on https://nightly-dot-shaka-player-demo.appspot.com/demo/
when subtitles disabled, if I enabled them it fails.
But enabling manifest.hls.ignoreTextStreamFailures works as expected.

So seems this nightly is working like a charm.
I agree both 
https://github.com/google/shaka-player/issues/2065
https://github.com/google/shaka-player/issues/1563
seem to be related.

Thanks for your time! 
Not to put pressure but to estimate it, is there any ETA for this nightly to become an actual release?

Thanks in advance @ismena and @joeyparrish

**Comment by joeyparrish** [comment] 2019-11-08 21:57
I'm working every day to finish #1339.  That's the last thing blocking v2.6.

**Comment by CHaNGeTe** [comment] 2019-11-09 07:15
> Okay, I can get a repro on the demo page, but not in the current master. I think you might be right about the getStartTime(which is pretty awesome, btw, we don't often see this level of awareness when people file bugs :))

Thanks for the feedback @ismena 
Indeed I was trying to make a PR for it, but I still feel a bit uncomfortable with shaka ecosystem.

Quick question, those nightly builds are coming from `master` branch directly? I understood that, but seeing this makes my doubt:
https://github.com/google/shaka-player/blob/master/package.json#L4
I would expect to see 2.5.6 there.

> That change was deemed too risky to cherry-pick, since it wasn't strictly a bug fix, and it introduced a big behavior change in the HLS parser.

@joeyparrish don't know if you agree, but IMHO this situation has changed, as the behaviour reported on this issue, https://github.com/google/shaka-player/issues/2065, and https://github.com/google/shaka-player/issues/1563 has 'bug nature' IMO, specially when the config `manifest.hls.ignoreTextStreamFailures` and `streaming.ignoreTextStreamFailures` has reached the (non-nightly)releases and it is not being fully honoured by hls_parser.

BTW, anything I can help with on https://github.com/google/shaka-player/issues/1339 ?

**Comment by ismena** [comment] 2019-11-18 23:54
Okay, I think we can resolve this as a duplicate of #1563 since the behavior is fixed in the nightly.
Let me tag @joeyparrish  again, so he has a chance to reconsider getting this into a minor release (it doesn't look like a risky change to me, but I might be wrong. Is there something tricky about it that I'm not seeing, Joey?).

@CHaNGeTe nightly's coming directly from master yes, so it has all the 2.5.6 stuff and more.

**Closed by ismena** 2019-11-18 23:54 UTC
Labels: needs triage
