### ISSUE TITLE
[v2.01] Video stuck at first frame in firefox v52 and safari v9.1.3

### ISSUE THREAD

**Issue by izar89** [google/shaka-player#625] opened 2016-12-08 15:24 UTC
- Shaka Player V2.01
- Demo: [http://stijnheylen.com/shakaTest/](http://stijnheylen.com/shakaTest/)
- Manifest: [http://stijnheylen.com/shakaTest/video/animated-font/animated-font.mpd](http://stijnheylen.com/shakaTest/video/animated-font/animated-font.mpd)

When doing `videoEl.start();` the video get stuck at first frame in both firefox v52 and safari v9.1.3 (Macbook pro El Capitan). In chrome v 55.0.2883.75 the video works fine.

The rest of the code is just loading the Shaka Player:
```
shaka.polyfill.installAll();
if (shaka.Player.isBrowserSupported()) {
	var player = new shaka.Player(videoEl);
	player.addEventListener('error', onPlayerError);
	player.load(src).then(onLoad).catch(onError);
}
```
- When trying the same code with Shaka Player V2.00 the video plays in both firefox and chrome but get stuck at the first frame in safari.
- When trying the same source and manifest with the demo app (local) with Shaka Player Master I get the following warning in firefox: `No Period ID given for Period with start time 0,  Assigning a default` (I did remove the autostart attribute, with autostart it's working? Without the autostart it also works randomly sometimes? Either It works or the first frame shows with the buffer spinner spinning). The demo I provided never works for me.

Thanks :)

**Comment by cpeterso** [comment] 2016-12-08 19:08
I can reproduce this stuck video with Firefox 50 and Firefox Nightly 53 on Windows 10. The [same video test](http://stijnheylen.com/shakaTest/) plays correctly in Chrome and Edge (after clicking the "play/pause" button).

**Comment by izar89** [comment] 2016-12-11 15:34
I don't know if this is related but you can force start the video after it gets stuck when you set the video.currentTime to something higher then 0. When you do that the currentTime starts counting down for a few seconds before counting up?
```
loaded
0 / 49 (video.currentTime / video.duration) <--- stuck
------------------ video.currentTime = 16.078125 <--- force start
16.076124999999998 / 49
16.075124999999996 / 49
16.074124999999995 / 49
16.073124999999994 / 49
16.072124999999993 / 49
16.07112499999999 / 49
16.07012499999999 / 49
16.06912499999999 / 49
16.068124999999988 / 49
16.068124999999988 / 49
16.067124999999987 / 49
...
```

**Comment by ckelsey** [comment] 2016-12-13 19:08
Hi,
I'm having a similar issue. I'm using v2.0.1 of the player and am having trouble playing dash videos if Firefox 50 and up. The same video played correctly in Firefox 49. To transcode the videos, I'm using FFmpeg and Shaka-packager. In FFmpeg, if I change the profile from high or main to baseline, then try and play in Firefox, it plays as expected. However, changing the profile setting is not a desirable option.

To make sure it's not my code that is causing issues, I've tested on the Shaka Player demo with the following files:

Profile set to baseline:
https://d1g1aamoxberjq.cloudfront.net/dash/sintel-1.mpd

Profile set to high (errors):
https://d1g1aamoxberjq.cloudfront.net/dash/sintel-2.mpd
The error it gives is "The last segment should not end before the end of the Period." However, it also says that in Chrome and still plays.

Another interesting thing to note, if you click play on the manifest that errors then seek ahead, the video will actually play. It will throw undefined errors, but plays which what makes me suspect it has something to do with the initialization.

I've also tested using Dash-if's player in Firefox 50 and both files play as expected:
http://mediapm.edgesuite.net/dash/public/nightly/samples/dash-if-reference-player/index.html

Thanks for any insight you may have.

**Comment by cpeterso** [comment] 2016-12-13 19:37
@ckelsey, I am unable to play either of your .mpd manifests in the Shaka or DASH-IF demo players in Firefox, Chrome, or Edge on Windows 10. Shaka reports "Shaka Error NETWORK.HTTP_ERROR (https://d1g1aamoxberjq.cloudfront.net/dash/sintel-1-audio.mp4)"

**Comment by izar89** [comment] 2016-12-14 09:34
@ckelsey, I also get the Shaka network error. When trying _https://d1g1aamoxberjq.cloudfront.net/dash/sintel-1.mpd_ with the _http://mediapm.edgesuite.net/dash/public/nightly/samples/dash-if-reference-player/index.html_ I get `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by ckelsey** [comment] 2016-12-14 20:14
@izar89  and @cpeterso, my apologies, I just updated my comment with the correct links.

**Comment by cpeterso** [comment] 2016-12-14 23:29
@ckelsey, your manifests play correctly for me with both the Shaka and DASH-IF players in Firefox 50 and 53 (Nightly) and Chrome on macOS 10.12.

**Comment by ckelsey** [comment] 2016-12-14 23:38
Am I missing something? I see that it gets initialized as there is a duration, but it does not play on the Shaka demo.

Just to make sure:
Browser: Firefox 50.1.0
Player: http://shaka-player-demo.appspot.com/demo/
Manifest: https://s3-us-west-2.amazonaws.com/cklsymedia/dash/sintel-2.mpd

This is what I see
<img width="1195" alt="shaka_player_demo" src="https://cloud.githubusercontent.com/assets/676171/21205862/16d9fa0a-c224-11e6-94a7-766f920a0217.png">

**Comment by cpeterso** [comment] 2016-12-15 05:55
Interesting. I can reproduce the video stall and error in Firefox and Safari now. The video plays in Chrome and Edge, though Edge logs a console error similar to Firefox and Safari: ``

In Firefox 50 and 53 (Nightly) on macOS 10.12, I see:

The last segment should not end before the end of the Period. Object { position: 73, startTime: 885.7083333333334, endTime: 888, getUris: shaka.media.Mp4SegmentIndexParser/<(), startByte: 414991746, endByte: 415018384 }

In Safari, I see:

```
The last segment should not end before the end of the Period.
SegmentReference
endByte: 415018384
endTime: 888
getUris: function()
position: 73
startByte: 414991746
startTime: 885.7083333333334
```

**Comment by izar89** [comment] 2016-12-15 13:35
Ik got the same results on mac in Firefox and Safari as @cpeterso. Same error messages. Chrome works fine.

**Comment by ckelsey** [comment] 2016-12-15 16:28
@izar89, When I do get info on the files I see Dimensions:1586 × 676, but ffprobe gives me 1280x676. I think maybe the discrepancy comes from how mac interprets the pixel dimensions.

I'm interested in why you don't get the same error as I do, but have the same symptoms. My shaka packager command is exactly the same, minus file names.

@cpeterso Do you know if there's anything actionable with the error messages?

**Comment by joeyparrish** [comment] 2016-12-15 17:47
The message "The last segment should not end before the end of the Period" is only a warning, and it seems to be confusing things more than helping.  We will consider removing it.  For now, please disregard that message.

**Comment by joeyparrish** [comment] 2016-12-15 17:48
In Firefox, the latest release build fails to start playback:  http://shaka-player-demo.appspot.com/demo/?asset=https://s3-us-west-2.amazonaws.com/cklsymedia/dash/sintel-2.mpd;play

The latest nightly build from `master` works fine, though:  http://nightly.shaka-player-demo.appspot.com/demo/?asset=https://s3-us-west-2.amazonaws.com/cklsymedia/dash/sintel-2.mpd;play

So it appears that this is a duplicate of a bug we've already fixed in `master`.  We will be releasing v2.0.2 with the fix soon.

**Comment by joeyparrish** [comment] 2016-12-15 17:50
Confirmed, duplicate of #579.  Sorry for the confusion!

**Comment by izar89** [comment] 2016-12-15 19:18
@joeyparrish Just tested the nightly build with the following links:
1) http://nightly.shaka-player-demo.appspot.com/demo/?asset=https://s3-us-west-2.amazonaws.com/cklsymedia/dash/sintel-2.mpd;play
2) http://nightly.shaka-player-demo.appspot.com/demo/?asset=http://stijnheylen.com/shakaTest/video/animated-font/animated-font.mpd;play

- The first link works for me in Firefox(dev v52.0a2) but fails to start in safari(v9.1.3) (manifest and segments are loaded).
- The second link (manifest on my server) sometimes works in Firefox (fails to start when dev tools are closed?) and also fails to start in safari.
- Cleared cache, tried safe mode. Force starting it with the playback bar works. Still playback issue? Could this be a server issue?

**Comment by joeyparrish** [comment] 2016-12-15 19:39
Both links are working for me on:
 * Chrome 55 on Linux
 * Firefox 50 on Linux (no issues with dev tools being open or closed)
 * Safari 10

Neither link works for me on Safari 9.  In both cases, the first timestamp is about 83ms, rather than 0, and the video is in a paused state, even though the Player is no longer in a buffering state.

So Safari 9 apparently has a bug in its MSE implementation or media stack somewhere that has already been fixed in Safari 10.  You can work around Safari 9's issue by setting `video.currentTime` to 0.1 or 0.2.  But since seeking to the first timestamp (83ms) does not work around Safari's bug, there's really no good way for the player to automate such a workaround.

So Safari 9 is buggy, and we can't do anything about it.  Safari 10 seems to work fine.

As for Firefox, I can't reproduce your dev tools issue, so I don't think there's anything further the Shaka Player team can do to help you with that.  If the dev tools issue persists, I recommend moving that support discussion to [Mozilla's bug tracker](bugzilla.mozilla.org).

Thanks!

**Closed by joeyparrish** 2016-12-15 19:39 UTC
Labels: duplicate

**Comment by izar89** [comment] 2016-12-15 19:49
Ok, thanks for the info!
