### ISSUE TITLE
iOS Safari - Player is stuck in buffering state

### ISSUE THREAD

**Issue by thecuriousdev** [google/shaka-player#2323] opened 2020-01-04 04:41 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app, (reproducible in the custom app as well)

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
iOS 13.2 - Safari Browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

NA, Using the Demo App

**What did you do?**

Just try to play any stream.

**What did you expect to happen?**
If unable to autoplay, we should hide the spinner.

**What actually happened?**
the UI is showing the spinner infinitely (Failed to autoplay the video)

**Comment by alexandercerutti** [comment] 2020-01-15 22:33
I might have encountered the same issue, but with 2.5.6. I experienced this only on iPhone iOS 13 Safari (I'm explicating this, because for example iPhone's Safari does not support EMEs, but iPad's Safari does, so there might be some differences more than this). I've experienced this with our custom apps and no Shaka UI.

What I found is that once `.load` is fired, it does not receive the events and, so, does not resolve nor reject the promise. The result is that the stream does not start.

I should do more tests. I have a branch that has been stopped for this reason and on which I applied an empty commit explaining the reason we stopped the development on that branch.
In particular, we were trying to fully bring HLS and Dash support everywhere through Shaka, instead of having our implementation for Safari.

**Comment by joeyparrish** [comment] 2020-01-15 23:48
We recently merged a PR to fix a similar issue.  Can you try again with the latest in the `master` or `v2.5.x` branches?

**Comment by joeyparrish** [comment] 2020-01-27 23:47
I'm unable to reproduce this today on iOS 12.  Can anyone reproduce it still on iOS 13 with the [latest release](https://v2-5-8-dot-shaka-player-demo.appspot.com/) or the [nightly build](https://nightly-dot-shaka-player-demo.appspot.com/demo/)?

**Comment by TheModMaker** [comment] 2020-02-10 19:45
Closing due to inactivity. If this is still an issue for you or if you have further questions, you can ask us to reopen or have the bot reopen it by including `@shaka-bot reopen` in a comment.

**Closed by TheModMaker** 2020-02-10 19:45 UTC
Labels: UI, unable to reproduce

**Comment by alexandercerutti** [comment] 2020-02-10 19:48
Sorry, I hadn't enough time to reproduce it at work... Anyway, in my case, it wasn't a UI problem.
