### ISSUE TITLE
shaka build source_map using the absolute paths.

### ISSUE THREAD

**Issue by asdftu** [google/shaka-player#413] opened 2016-06-12 10:42 UTC
following is a clip in the file of "shaka-player.compiled.debug.map",  

`"sources":["d:/venus/shaka-player/third_party/closure/goog/base.js","d:/venus/shaka-player/lib/polyfill/patchedmediakeys_v01b.js","d:/venus/shaka-player/lib/abr/ewma.js","d:/venus/shaka-player/lib/abr/ewma_bandwidth_estimator.js","d:/venus/shaka-player/lib/abr/simple_abr_manager.js","d:/venus/shaka-player/lib/media/presentation_timeline.js","d:/venus/shaka-player/lib/media/segment_reference.js","d:/venus/shaka-player/lib/media/time_ranges_utils.js","d:/venus/shaka-player/lib/polyfill/all.js","d:/venus/shaka-player/lib/polyfill/fullscreen.js","d:/venus/shaka-player/lib/polyfill/patchedmediakeys_nop.js","d:/venus/shaka-player/lib/polyfill/promise.js","d:/venus/shaka-player/lib/polyfill/videoplaybackquality.js","d:/venus/shaka-player/lib/util/array_utils.js","d:/venus/shaka-player/lib/util/config_utils.js","d:/venus/shaka-player/lib/util/error.js","d:/venus/shaka-player/lib/util/cancelable_chain.js","d:/venus/shaka-player/lib/util/data_view_reader.js","d:/venus/shaka-player/lib/util/pssh.js","d:/venus/shaka-player/lib/util/ebml_parser.js","d:/venus/shaka-player/lib/util/fake_event.js","d:/venus/shaka-player/lib/util/functional.js","d:/venus/shaka-player/lib/media/segment_index.js","d:/venus/shaka-player/lib/media/text_engine.js","d:/venus/shaka-player/lib/util/language_utils.js","d:/venus/shaka-player/lib/util/map_utils.js","d:/venus/shaka-player/lib/util/multi_map.js","d:/venus/shaka-player/lib/util/event_manager.js","d:/venus/shaka-player/lib/media/playhead.js","d:/venus/shaka-player/lib/util/fake_event_target.js","d:/venus/shaka-player/lib/util/public_promise.js","d:/venus/shaka-player/lib/media/media_source_engine.js","d:/venus/shaka-player/lib/media/streaming_engine.js","d:/venus/shaka-player/lib/offline/db_engine.js","d:/venus/shaka-player/lib/offline/storage.js","d:/venus/shaka-player/lib/util/string_utils.js","d:/venus/shaka-player/lib/util/text_parser.js","d:/venus/shaka-player/lib/media/vtt_text_parser.js","d:/venus/shaka-player/lib/util/uint8array_utils.js","d:/venus/shaka-player/lib/media/drm_engine.js","d:/venus/shaka-player/lib/polyfill/patchedmediakeys_20140218.js","d:/venus/shaka-player/lib/polyfill/mediakeys.js","d:/venus/shaka-player/lib/util/stream_utils.js","d:/venus/shaka-player/lib/util/xml_utils.js","d:/venus/shaka-player/lib/dash/content_protection.js","d:/venus/shaka-player/third_party/closure/goog/uri/utils.js","d:/venus/shaka-player/third_party/closure/goog/uri/uri.js","d:/venus/shaka-player/lib/dash/mpd_utils.js","d:/venus/shaka-player/lib/dash/segment_base.js","d:/venus/shaka-player/lib/media/mp4_segment_index_parser.js","d:/venus/shaka-player/lib/media/webm_segment_index_parser.js","d:/venus/shaka-player/lib/dash/segment_list.js","d:/venus/shaka-player/lib/dash/segment_template.js","d:/venus/shaka-player/lib/net/networking_engine.js","d:/venus/shaka-player/lib/media/manifest_parser.js","d:/venus/shaka-player/lib/dash/dash_parser.js","d:/venus/shaka-player/lib/net/data_uri_plugin.js","d:/venus/shaka-player/lib/net/http_plugin.js","d:/venus/shaka-player/lib/offline/download_manager.js","d:/venus/shaka-player/lib/offline/offline_manifest_parser.js","d:/venus/shaka-player/lib/offline/offline_scheme.js","d:/venus/shaka-player/lib/player.js"],`

you see that the paths are all the absolute paths.
**is there any way to change to use the relative path?**

the reason i want to use the relative path is that when i debugged in **chrome** using source map 
i got the following error

`Source map http://localhost:8000/shaka-player.compiled.debug.map points to the files missing from the workspace: [http://localhost:8000/d:/venus/shaka-player/third_party/closure/goog/base.js, http://localhost:8000/d:/venus/shaka-player/lib/polyfill/patchedmediakeys_v01b.js, http://localhost:8000/d:/venus/shaka-player/lib/abr/ewma.js, …]` 

if map file uses the relative path, the issue will gone.

**Comment by TheModMaker** [comment] 2016-06-13 17:42
What version are you using and on what platform?  Have you tried with a clean version on `master`? This is a duplicate of #323 and should have been fixed in 58ac690.

**Comment by asdftu** [comment] 2016-06-15 03:16
i am sure that i am using an clean version of` master`.

my platform is :
OS: windows 10
Python 2.7

**Comment by TheModMaker** [comment] 2016-06-15 04:31
I have verified that this happens on Windows, will investigate further.

**Closed** 2016-06-15 17:58 UTC
Labels: bug
