### ISSUE TITLE
Fairplay content not playing on 3.2.0 but works on 3.1.2

### ISSUE THREAD

**Issue by bmaniar** [google/shaka-player#3598] opened 2021-08-25 10:27 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari Version 14.1.1 

**What are the manifest and license server URIs?**
Sent in email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
{
   "drm":{
      "servers":{
         "com.widevine.alpha":"licenseUrl",
         "com.microsoft.playready":"licenseUrl",
         "com.apple.fps.1_0":"licenseUrl"
      },
      "advanced":{
         "com.apple.fps.1_0":{
            "serverCertificate":"fairPlayCertData"
         }
      }
   }
}
```

License Wrapping
```
inUseInstance.getNetworkingEngine().registerRequestFilter((type, request) => {
    if (type != net.NetworkingEngine.RequestType.LICENSE) {
        return
    }
    const originalPayload = new Uint8Array(request.body)
    const base64Payload = util.Uint8ArrayUtils.toBase64(originalPayload)
    const params = JSON.stringify({
        spc: encodeURIComponent(base64Payload),
        assetId: window.location.hostname
    })
    request.headers['Content-Type'] = 'application/json'
    request.responseType = 'arraybuffer'
    request.body = params
})
``` 

**What did you do?**
Tried to play Fairplay protected content on the safari browser

**What did you expect to happen?**
It should play the video properly

**What actually happened?**
We are getting error code 6010 which indicate ENCRYPTED_CONTENT_WITHOUT_DRM_INFO

Content properly plays with the same configuration on version 3.1.2.

**Comment by avelad** [comment] 2021-08-25 10:32
Duplicate of https://github.com/google/shaka-player/issues/3530

**Comment by TheModMaker** [comment] 2021-09-20 17:41
Closing as a duplicate.

**Closed by TheModMaker** 2021-09-20 17:41 UTC
Labels: needs triage
