### ISSUE TITLE
Memory leak after bundling latest version with Webpack

### ISSUE THREAD

**Issue by Yuvalke** [google/shaka-player#3092] opened 2021-01-12 19:42 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
3.0.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
No, I build shaka locally and it doesn't happen.

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No, it's related to Webpack but with Shaka after bundling with Webpack mode=production on a standalone page I can reproduce the issue.

**What browser and OS are you using?**
Chrome latest

**What are the manifest and license server URIs?**
I'm using live with a segment template same as mentioned here: https://github.com/google/shaka-player/issues/3038 

**What did you do?**
Install Shaka from NPM and bundle it with Webpack mode production cause memory leak same as it happens here: https://github.com/google/shaka-player/issues/3038, it seems like it caused by `minimize` option on Webpack bundle but I tried to test with your master, I pulled the master and execute `python build/all.py --force` then used the generated dist and it worked well and still working from the current master today.

**What did you expect to happen?**
Expect Webpack bundle won't cause a memory leak(There is a difference between the local build and the dist from the tag since I don't see the issue when I bundling locally from the same commit).

**What actually happened?**
Same as mentioned here: https://github.com/google/shaka-player/issues/3038.

**Comment by joeyparrish** [comment] 2021-01-13 00:35
That's interesting, but I'm not sure what we could do about it.  If webpack is corrupting the code in some way that creates a memory leak at runtime, that would seem to be a bug in webpack.  Have you filed an issue with them?

I have never used webpack (sad, I know; it's super common and I should know more).  But here are some ideas you could try to work around the issue:

1. If webpack is configured to minimize the code, you could try giving it our "debug" build instead of the "production" build.  (The difference is mainly in minimizing and renaming, but "debug" builds also have logging available.)  For example, instead of `shaka-player.ui.js`, try `shaka-player.ui.debug.js`
2. Try feeding webpack all of the sources instead of compiling them through the Closure compiler.  The resulting binary will expose namespaces we don't support as part of our stable, exported API, but this may also have some effect on webpack's output.

If either of these helps, that may be valuable information for the webpack folks to help them find and fix whatever issue is in webpack.

Does this help?

**Comment by MilosRasic** [comment] 2021-01-13 01:09
@Yuvalke If it's not happening without minification, then the problem is caused by the minifier, not by webpack itself. It should be terser for newer versions and uglify-js for older versions. It might be good to check in production mode with `minimize: false` just to make sure it's not another loader or plugin causing the issue.

You could also use the `minimizer` config field to instantiate the plugin manually and play around with minifier options, see if flipping one of them might remove the problem.

**Comment by Yuvalke** [comment] 2021-01-13 08:39
Hi @joeyparrish, thanks I'll try it.
actually, I tried to compare the dist from tag and dist that was generated by a script from tag 3.0.7(and works with Webpack - minimized), there is a difference between before I involved Webpack.
Do you know what could cause this difference? Do you create the tag dist in another way? 
Thanks

**Comment by Yuvalke** [comment] 2021-01-13 08:46
Hi @MilosRasic thanks, I probably didn't mention it clear enough I saw that it's working when I'm using `minimize: false` I also take shaka with Webpack without plugins, and I saw that the issue come up from this config.
I also found a config on Webpack that makes it works but it changes the bundle completely and before I'll make this change I want to understand why this issue happens only for tag and doesn't for the local build from shaka repo.

**Comment by Yuvalke** [comment] 2021-01-14 14:49
Hi @joeyparrish I saw that the tag released from branch v3.0.x and not from the master branch as I thought so I compared those two and I find out a change from the master branch(part from LL support but it seems like it shouldn't influence the player behivour) that makes 3.0.7 to work with Webpack(Treser)(Tried to compare the two minified but I didn't find anything yet).
I took the `merge` method from `segmentIndex` and replace it with the same method from the master branch and it works!!
What do you think about adding this change to the next release and resolve the issue for Webpack users?

**Comment by joeyparrish** [comment] 2021-01-25 17:51
Fixed in v3.0.x by PR #3098

**Closed by joeyparrish** 2021-01-25 17:51 UTC
Labels: bug, external
