### ISSUE TITLE
Modify DASH manifest BaseURL through Shaka interface

### ISSUE THREAD

**Issue by Towli** [google/shaka-player#1280] opened 2018-02-07 16:18 UTC
Wondering if there's a way to dynamically modify the <BaseURL> element of a dash manifest file through Shaka's API?

**Comment by theodab** [comment] 2018-02-07 18:26
When you say "dynamically modify" the element, do you mean modify it before parsing, or modify it while playing?

If you mean the former, a response filter could be used. These filters are called after the download is complete but before it is passed to the manifest parser, so you could use that to modify the manifest as you wish.

If you mean the latter, you could still use a response filter and make the mpd's type attribute be "dynamic", so that the manifest parser will periodically re-download the manifest. That way you can use the filter to change it during runtime. You could also use a custom scheme plugin that forwards to the normal http/s plugin the first time and returns a cached result after that, so that you don't need to actually download the manifest multiple times. Whether this will work as intended depends on what kind of changes you intend to make, though; for instance, if you want to change the timescale during runtime or something weird like that, I doubt that would work properly.

**Comment by joeyparrish** [comment] 2018-02-07 18:45
If you want to modify `<BaseURL>` specifically, you only need a request filter to change the URIs of segment requests.  No need to modify the manifest at all.

Does this help?

**Comment by gwevans** [comment] 2018-02-21 19:30
@joeyparrish I have a question for you about using request filters. I'm looking to dynamically update the manfiestUri for live streaming. I'm pretty new to http streaming so there are probably some gaps in my understanding.

```
manifestUri = www.someurl1.com;
var player = new shaka.Player(video);
player.load(manifestUri).then(function() {
    console.log('The video has now been loaded!');
  }).catch(onError);
```

Then every 10 seconds my manifestUri changes to something else. How would I go about setting up a request filter to change the URI? I'm doing this in react, so I plan to have a ```componentWillReceiveProps()``` function where the manifestUri will be updated. Is this where requestFilter comes in or am I completely missing the point?

**Comment by joeyparrish** [comment] 2018-02-21 19:35
Here's an example:

```js
player.getNetworkingEngine().registerRequestFilter(function(type, request) {
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST) {
    return;  // ignore non-manifest requests
  }

  // Look for one URI and change it to something else.
  if (request.uris[0] == 'foo') {
    request.uris[0] = 'bar';
  }
});
```

If you want more detail, I recommend reading the tutorial on license server authentication: https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html

It goes into detail about various things you may want to do in changing requests.  Although it is focused on authentication and `LICENSE` requests, the concepts can be applied universally.  It also discusses asynchronous filters, which would allow you to asynchronously compute changes if needed.

Does this help?

**Comment by gwevans** [comment] 2018-02-21 19:44
@joeyparrish Thanks for the reply, and yes it does help. I had just stumbled onto that tutorial after I made the comment.

So the request.uris[0] will seamlessly transition to the new uri without re-rendering the entire player? I don't have an environment to play around with shaka at the moment or else I would give this a go.

**Comment by joeyparrish** [comment] 2018-02-21 19:47
Correct.  You are essentially changing the URI of the request before we make it.

The DASH parser is creating the request structure based on the original URI of the manifest (given to player.load()), plus any redirects at the HTTP level (HTTP 302) or DASH level (Location element).  Your filter gets to inspect and/or edit any part of that before it goes out on the actual network.

**Comment by gwevans** [comment] 2018-02-21 20:20
Ok that makes sense. I get that the requestFilter is like an event listener on the requests going out.

But how would I manually force registerRequestFilter to execute when I have a new manifestUri? I assume it's not by ```player.load(newManifestUri)```, right?

**Comment by joeyparrish** [comment] 2018-02-21 21:22
You don't manually force it to execute at all.  It will be executed on every single network request that occurs after you register it.  The registration persists, even when you make subsequent `load()` calls.  To remove a filter, you would use `unregisterRequestFilter()` or `clearAllRequestFilters()`.

If you want to change the URIs of manifest requests (requests to get the initial manifest or to update it in the case of live streams), you can look for type == `RequestType.MANIFEST`.  If you want to change the URIs of segments, you can look for type == `RequestType.SEGMENT`.

I think I might have gotten confused looking at the history this morning, so I showed you an example of changing manifest URIs instead of segment URIs.  Looking at the history again, I think you segment URIs might be what you really want to modify.  Is that correct?

**Comment by gwevans** [comment] 2018-02-21 21:46
@joeyparrish I'm pretty sure I want to modify the manifest URIs, but I'll describe my problem in more detail just to be clear, you might know more than I.

I am playing a live stream with constantly changing source urls. Typically (from what I understand) a live stream will have one url, but will constantly grab new chunks from the server via the same url. But I can't be using chunks via the same url, I need new manifest urls every 10-15 seconds. So I believe I'm just playing 10-15 second videos after each other.

So in my code I need to determine when the manifestUri changes and then feed it to the shakaPlayer. I am pretty much manually changing the manifest Uri on the fly. There will only be 1 segment per manifest, so type should never equal ```RequestType.SEGMENT``` in my case.

I have the shaka player set up now, and I'm struggling to see the purpose of the registerRequestFilter if I am forcing the manifestUri to change every 10 seconds. It seems like just doing player.load(newManifestUri) does the trick, but I don't want to just load a brand new video, I want to keep the previously loaded video accessible in the player (similar to how segments work).

**Comment by joeyparrish** [comment] 2018-02-26 18:49
If you want to change the manifest URI every 10 seconds, here are your options as I see them:

1. Call `load(newManifestUri)`, which will treat the new URI like a completely different, unrelated piece of content.  This is probably not what you want.
2. Put a `<Location>` element in the manifest which contains the URI to use for the next manifest update, and a `minimumUpdatePeriod` attribute of "PT10S" (10 seconds in XML duration format).  Every 10 seconds, Shaka will update the manifest from the location in the most recent manifest's `<Location>` element.  This requires cooperation server-side and control of the manifest contents, and only works for DASH.
3. Use a request filter to modify the manifest URI before the request is made.  This will work without complete manifest control and will also work for HLS.  In DASH, though, you still need a `minimumUpdatePeriod` attribute of "PT10S" for Shaka to update the manifest at that interval.

Does this help?

**Comment by gwevans** [comment] 2018-02-26 19:01
@joeyparrish Thanks again for the response.

I definitely do not want #1, HLS is required (so no #2), looks like I will have to push forward with #3.

However, I still don't quite understand how a request filter will achieve the desired result. I'm not sure if you're familiar with React or not, but I have a react component that is fetching the manifestUri, which is in turn feeding it to the video player.

Once the manifestUri changes, I have to feed it to the video player. To feed the new manifestUri to shaka-player, I would do player.load(newManifestUri), which would then execute the requestFilter where the requestType is MANIFEST, right?

But once I change that uris[0] to the new manifest (which I currently don't know how to get scope of inside the requestFilter), it will just load a new video and not have any record of the previous piece of content, right?

I must be missing something of how the requestFilter works.

**Comment by joeyparrish** [comment] 2018-02-26 21:06
No, I'm sorry, I'm not familiar with React.

I have a few more clarifying questions:

When you have manifestUri1, and later you want to load manifestUri2, how are these pieces of content related?  Is one an extension of the other (more segments listed)?

I would expect that for live streaming, the updated version would be an extension of the previous one, but it is an important distinction for me to give you the right advice.

**Comment by gwevans** [comment] 2018-02-26 21:46
@joeyparrish 
I guess React isn't really important in this case, just the fact that I have something giving the video updated manifestUris.

I am told that they are completely separate manifests. manifestUri2 is not just manifestUri with extra segments appended, they are entirely separate segments.

**Comment by joeyparrish** [comment] 2018-02-26 22:02
In the case that your manifests are unrelated, you just want to call `player.load()` with the new manifest.  The player will unload what was already playing and load the new thing.  This is **not** how live streaming works, for the record.

If that solves your problem, you can disregard the rest of the advice here, which was based on the misapprehension that you wanted to change the manifest URI during an update of a typical live stream manifest.

**Comment by gwevans** [comment] 2018-02-26 22:07
@joeyparrish 
I have just clarified with someone and I was mistaken. manifestUri2 is merely an extension of manifestUri1.

**Comment by joeyparrish** [comment] 2018-02-26 23:22
Okay, then here's how this work for a live stream.

`player.load(manifestUri)` triggers an initial manifest request.  After that, on a timer, the manifest parser will request updates to the manifest.  This is where your request filter comes in.

Every request gets filtered through all request filters.  Your filter can modify any request it wants before the request hits the network.  So you can change the manifest URI before each update it fetched.

There are two ways to do this:

1. Your react component gets new URIs on its own schedule, however it does that.  It then caches the most recent URI.  When you filter fires, it sets `request.uris[0] = mostRecentCachedUriFromReact`.
2. When your filter fires, it starts an asynchronous process to get the URI it should use for the manifest.  Your filter returns a Promise, which you later resolve after you have modified the request with a fresh URI.

Because your filter is called on all requests, you should look for `MANIFEST` requests specifically:
```js
player.getNetworkingEngine().registerRequestFilter(function(type, request) {
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST) {
    return;  // ignore non-manifest requests
  }

  if (mostRecentCachedUriFromReact) {
    request.uris[0] = mostRecentCachedUriFromReact;
  }
});
```

Or, the async version where you stop the request, calculate/fetch a manifest URI, then modify the request and continue:
```js
player.getNetworkingEngine().registerRequestFilter(function(type, request) {
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST) {
    return;  // ignore non-manifest requests
  }

  return goFigureOutTheNewManifestUri.then(function(newUri) {
    request.uris[0] = newUri;
  });
});
```

To answer your questions from earlier:
> To feed the new manifestUri to shaka-player, I would do player.load(newManifestUri), which would then execute the requestFilter where the requestType is MANIFEST, right?

No.  `load()` tears down everything the player was already doing (if anything), and sets up playback for a new piece of content.  The request filter is triggered for every request, period.  At least one of those will be a `MANIFEST` type request, assuming you register the filter *before* the player requests the manifest.  It suffices to register the filter before calling `load()`.  It is also worth noting that calling `load()` a second time will not wipe out any existing filters.  Filters persist across multiple calls to `load()`.

> But once I change that uris[0] to the new manifest (which I currently don't know how to get scope of inside the requestFilter), it will just load a new video and not have any record of the previous piece of content, right?

No, it's the opposite.  That would be true of calling `load()` again, but not a request filter.  A request filter is just giving your application a chance to inspect and/or edit a request before it actually happens.  It doesn't affect anything but that manifest request.

Does this help?

**Comment by gwevans** [comment] 2018-02-27 00:09
@joeyparrish 
I'm definitely coming off as slow, I apologize. I greatly appreciate the write up here, but I think most of our discussion could have been simplified if I were more clear about what I was confused about.

I was under the impression that the only times the RequestType will equal MANIFEST is when the user manually alters the manifestUri. I get that RequestType equals SEGMENT every time it's time to load a new segment, but I don't understand when Request will actually equal MANIFEST.

I had pretty much the same code as below set up with my own player, but I never saw the RequestType equal MANIFEST unless i manually did a player.load() with a new manifestUri. My react component fetches the new manifestUri on its own, but then I somehow need to get inside of the requestFilter to set the request.uris[0] = newManifest. I can't call player.load() without tearing everything down, so I don't know how to get inside the requestFilter to set the request. Does my question make sense?

```
player.getNetworkingEngine().registerRequestFilter(function(type, request) {
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST) {
    return;  // ignore non-manifest requests
  }

  if (mostRecentCachedUriFromReact) {
    request.uris[0] = mostRecentCachedUriFromReact;
  }
});
```

**Comment by joeyparrish** [comment] 2018-02-27 17:19
> I was under the impression that the only times the RequestType will equal MANIFEST is when the user manually alters the manifestUri. I get that RequestType equals SEGMENT every time it's time to load a new segment, but I don't understand when Request will actually equal MANIFEST.

That is not true.  Live manifests have to be periodically updated, which means we will make subsequent `MANIFEST` requests.  For VOD, we would only request the manifest once.  In fact, there is no API for the user to manually alter the manifest URI, because this is not typically required.  We are still unclear on why you would want to do this in the first place.

> I had pretty much the same code as below set up with my own player, but I never saw the RequestType equal MANIFEST unless i manually did a player.load() with a new manifestUri.

Did you register the filter before the first call to `load()`?  If you register the filter after calling `load()`, it would be too late to intercept the initial manifest request.

Is the content live or VOD?  (Check `player.isLive()` or send us a sample URI to test.)  VOD content does not need to update the manifest.  If your content looks like VOD, but you're trying to hack it so that it "updates" and acts more like live, then you should stop what you are doing and build a proper live, HLS event, or DASH IPR stream instead.

> My react component fetches the new manifestUri on its own, but then I somehow need to get inside of the requestFilter to set the request.uris[0] = newManifest. I can't call player.load() without tearing everything down, so I don't know how to get inside the requestFilter to set the request.

Here's an example using a timer to compute a new URI.  The timer has no direct interaction with the request filter, but they both reference a common variable.  You can use a global, or attach something to window, or attach something to a namespace both pieces of code know about.  It doesn't technically matter where you store it.

```js
// These could easily live anywhere else that both our
// manifest computation and request filter can access.
let nextManifestUri;
let counter = 0;

function computeNextManifestUri() {
  counter++;
  nextManifestUri = '/foo/manifest/' + counter + '.mpd';
}

// Compute the first URI.
computeNextManifestUri();
// Load the content.
player.load(nextManifestUri);
// Update the manifest URI every 10 s.
setTimer(computeNextManifestUri, 10000);
// Manifest requests always go to the most recently computed URI.
player.getNetworkingEngine().registerRequestFilter(function(type, request) {
  if (type == shaka.net.NetworkingEngine.RequestType.MANIFEST) {
    request.uris[0] = nextManifestUri;
  }
});
```

**Comment by gwevans** [comment] 2018-02-27 17:44
Ok this clears a lot up for me. I was testing with a link I found online that was claiming to be a live stream, but it seems like it was a VOD then, I'm not sure. I haven't tested any players with the actual live manifests that my services team are providing because they're not ready yet, but I am just being told what is required of me on the front end.

To get the new manifestUri I need to make an server call so instead of having my react component feed the shaka player a new manifest, maybe I'll just use the async version you mentioned above. Every time a new chunk is appended to the manifest, the manifestUri changes, so I'll follow the code below and hopefully that will work for me.

```
player.getNetworkingEngine().registerRequestFilter(function(type, request) {
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST) {
    return;  // ignore non-manifest requests
  }

  return getManifestServiceCall.then(function(newUri) {
    request.uris[0] = newUri;
  });
});
```

So conceptually, supposed the initial manifestUri has only 1 segment in it. When it gets to the end of the segment it will trigger the requestFilter if I'm not mistaken, but will the RequestType be MANIFEST or SEGMENT? I don't have anything to test with at the moment or else I'd try it.

**Comment by joeyparrish** [comment] 2018-02-27 19:29
> So conceptually, supposed the initial manifestUri has only 1 segment in it. When it gets to the end of the segment it will trigger the requestFilter if I'm not mistaken, but will the RequestType be MANIFEST or SEGMENT?

No, the manifest request has nothing to do with the number of segments in the manifest or the playback position.  It's based on a timer.  In DASH, this interval is controlled by the `minimumUpdatePeriod` attribute.  In HLS, it's based on the minimum of the `EXT-X-TARGETDURATION` tags.

So if your live manifest has 1 segment in it, that would be a bad time to start playback.  In DASH, playback should always be offset from the live edge by the amount of the `suggestedPresentationDelay` attribute.  In HLS, playback should always be offset from the live edge by 3 segments.  These features of DASH and HLS are meant to keep playback from running off the edge if there is some delay on the server side or in fetching an update.

**Comment by gwevans** [comment] 2018-02-27 19:57
@joeyparrish 

Awesome, thanks for the explanation. This has been hugely helpful and I appreciate you taking the time to explain these concepts to me. Cheers.

**Comment by joeyparrish** [comment] 2018-02-27 20:29
Happy to help.  I'm going to go ahead and close the issue now.  If you need more help, just let us know and we can open it again.

**Closed by joeyparrish** 2018-02-27 20:29 UTC
Labels: question
